<a href="https://colab.research.google.com/github/GUNAPILLCO/neural_profit/blob/main/stage_06_model_training/seq2one/stage_06_04_mlp_seq2one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Stage_07_01 -  SEQ2ONE TUNING - Modelo MLP - Target: `delta_60`**

En esta sección iniciamos el proceso de **tuning del modelo MLP bajo el enfoque many-to-one (SEQ2ONE)**, utilizando como variable objetivo el **`delta_60`**, es decir, la variación en puntos del MNQ en los próximos 60 minutos.

El enfoque SEQ2ONE consiste en utilizar una ventana histórica de tamaño \( L \) minutos como entrada y predecir un único valor futuro correspondiente al horizonte seleccionado. En este caso:

$$
X \in \mathbb{R}^{(L \times F)} \quad \longrightarrow \quad y \in \mathbb{R}
$$

donde:

- $L$ = window size  
- $F$ = número de features (36)
- $y$ = `delta_60`  

---

**Motivación**

De acuerdo con el workflow de investigación y modelado presentado en el libro *Machine Learning for Algorithmic Trading*, el diseño y tuning del modelo corresponde a la etapa de:

> **Design, tune, and evaluate ML models to generate trading signals**

En esta fase, el objetivo no es todavía el backtesting completo, sino encontrar una configuración que:

- Generalice correctamente (early stopping sobre VALID)  
- Maximice capacidad predictiva (R², RMSE, MAE)  
- Mantenga estabilidad direccional (DA)  

---

**Objetivo del tuning**

El propósito del tuning será:

1. Evaluar distintos tamaños de ventana $L$.  
2. Ajustar hiperparámetros del MLP:
   - `hidden_dim`
   - `dropout`
   - `learning_rate`
   - `weight_decay`
3. Seleccionar la mejor configuración usando exclusivamente el conjunto **VALID**.  
4. Reservar el conjunto **TEST** para evaluación final no sesgada.  

Este procedimiento evita leakage y respeta el principio de generalización fuera de muestra, fundamental en modelado financiero.

---

**Contexto técnico**

El MLP:

- Recibe ventanas aplanadas en formato 2D.  
- No modela memoria temporal explícita (a diferencia de LSTM/GRU).  
- Aprende relaciones no lineales entre patrones recientes del mercado y el `delta_60`.  

Por lo tanto, el tamaño de ventana seleccionado determinará indirectamente cuánta información temporal puede capturar el modelo.

---

En las siguientes secciones se definirá el espacio de búsqueda y se ejecutará el proceso de tuning controlado sobre TRAIN/VALID.

# **BLOQUE DE EJECUCIÓN COMPLETO**

## **1. Imports + paths**

In [1]:
# Permite anotaciones modernas en Python < 3.11.
from __future__ import annotations

import os
import json
import time
import random
from pathlib import Path
import numpy as np

import numpy as np
from typing import Any, Dict, List, Iterable, Tuple
# Si usa sklearn en algún modelo/baseline
# from sklearn.linear_model import Ridge

# Dataclass: contenedor simple e inmutable para configuración.
from dataclasses import dataclass
# Joblib para cargar scalers .pkl (sklearn).
import joblib

from pathlib import Path
import sys
import importlib

## **2. Acceso a drive**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

# --------------------------------------------------
# Ruta base en Google Drive
# --------------------------------------------------
# Ajuste si su estructura cambia
DRIVE_DIR =   Path(os.environ.get("DRIVE_DIR", "/content/drive/MyDrive/neural_profit/"))

Mounted at /content/drive

## **3. Rutas de ventanas seq2one y scalers**

In [3]:
from pathlib import Path
import os

WINDOWS_SEQ2ONE_DIR = Path(
    os.environ.get("WINDOWS_SEQ2ONE_DIR", "data/windows/seq2one/")
)

SCALERS_DIR = Path(
    os.environ.get("SCALERS_DIR", "data/scaled/")
)

window_sizes = [30, 60, 90, 120, 180]
targets = ['delta_60', 'delta_90', 'ret_60', 'ret_90']
splits = ['train', 'valid', 'test']

In [4]:
windows_paths = {}

for w in window_sizes:
    windows_paths[w] = {}

    for t in targets:
        windows_paths[w][t] = {}

        for s in splits:
            path = (
                DRIVE_DIR
                / WINDOWS_SEQ2ONE_DIR
                / f"L{w}"
                / f"windows_{t}_{s}.npz"
            )

            windows_paths[w][t][s] = path

#display(windows_paths)

#Como llamarlo:
#path_train_L60_delta = windows_paths[60]['delta_90']['train']
#print(path_train_L60_delta)

In [5]:
scalers_paths = {}
for t in targets:
  scalers_paths[t] = {}
  path = (
                DRIVE_DIR
                / SCALERS_DIR
                / f"scaler_{t}.pkl"
            )

  scalers_paths[t] = path

display(scalers_paths)

{'delta_60': PosixPath('/content/drive/MyDrive/neural_profit/data/scaled/scaler_delta_60.pkl'),
 'delta_90': PosixPath('/content/drive/MyDrive/neural_profit/data/scaled/scaler_delta_90.pkl'),
 'ret_60': PosixPath('/content/drive/MyDrive/neural_profit/data/scaled/scaler_ret_60.pkl'),
 'ret_90': PosixPath('/content/drive/MyDrive/neural_profit/data/scaled/scaler_ret_90.pkl')}

## **4. Reproducibilidad**

In [6]:
def set_seeds(seed: int = 42) -> None:
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

set_seeds(42)

## **5. Importar métricas comunes desde .py**

In [7]:
# 1) Define el root del proyecto (DEBE existir en esta misma celda)
DRIVE_DIR =   Path(os.environ.get("DRIVE_DIR", "/content/drive/MyDrive/neural_profit/"))

# 2) Agrega el root al PYTHONPATH (antes de importar)
if str(DRIVE_DIR) not in sys.path:
    sys.path.insert(0, str(DRIVE_DIR))  # insert(0) para priorizarlo

# 3) Asegura que metrics sea paquete Python
(DRIVE_DIR / "metrics" / "__init__.py").touch(exist_ok=True)

# 4) Invalida cachés de import (importante en Colab)
importlib.invalidate_caches()

# 5) Diagnóstico (le muestra qué ve Python)
#print("DRIVE_DIR:", DRIVE_DIR)
#print("sys.path[0]:", sys.path[0])
#print("metrics exists:", (DRIVE_DIR / "metrics").exists())
#print("metrics __init__:", (DRIVE_DIR / "metrics" / "__init__.py").exists())

# 6) Imports reales
from metrics.seq2one_metrics import compute_seq2one_metrics
#from metrics.opportunity_filter_metrics import compute_opportunity_filter_metrics

print("OK - imports metrics.*")

OK - imports metrics.*

In [8]:
print(compute_seq2one_metrics.__doc__)

    Calcula métricas simples y comparables para modelos seq2one.

    Parámetros
    ----------
    y_true : np.ndarray
        Valores reales con shape (n_samples,), (n_samples, 1)
        (opcional) (n_samples, seq_len) si allow_seq_inputs_take_last=True.
    y_pred : np.ndarray
        Valores predichos con shape (n_samples,), (n_samples, 1)
        (opcional) (n_samples, seq_len) si allow_seq_inputs_take_last=True.
    compute_r2 : bool
        Si True, calcula R² sobre el vector completo.
    da_ignore_zeros : bool
        Si True, ignora casos donde el signo sea 0 en y_true o y_pred al calcular DA.
    allow_seq_inputs_take_last : bool
        Si True, permite inputs 2D (n_samples, seq_len) y toma el último paso [:, -1].
        Útil si algún modelo devuelve secuencia pero usted lo evalúa como many-to-one.

    Retorna
    -------
    metrics : dict
        Diccionario con métricas globales.

## **6. Carga de data windows**

In [9]:
def load_npz_windows(path: Path) -> Tuple[np.ndarray, np.ndarray]:
    """
    Carga ventanas X e y desde un archivo .npz estándar.
    """

    if not path.exists():
        raise FileNotFoundError(f"No se encontró el archivo: {path}")

    # Usar contexto para cerrar correctamente el archivo
    with np.load(path) as data:

        if "X" not in data:
            raise KeyError(f"NPZ inválido (falta clave 'X'): {path}")
        X = data["X"]

        if "y" in data:
            y = data["y"]
        elif "Y" in data:
            y = data["Y"]
        else:
            raise KeyError(f"NPZ inválido (falta clave 'y'/'Y'): {path}")

        # Opcional pero recomendable: copiar a memoria
        X = X.copy()
        y = y.copy()

    return X, y

In [10]:
# --------------------------------------------------
# Función común: carga scaler .pkl (sklearn)
# --------------------------------------------------
def load_scaler(path: Path) -> Any:
    """
    Carga un scaler serializado con joblib (ej. StandardScaler/MinMaxScaler).
    """
    # Verifica existencia del archivo.
    if not path.exists():
        raise FileNotFoundError(f"No se encontró el scaler: {path}")

    # Carga el objeto scaler.
    scaler = joblib.load(path)

    # Devuelve scaler (tipo genérico).
    return scaler

In [11]:
from typing import Any, Dict, Mapping
from pathlib import Path

# --------------------------------------------------
# Carga completa: ventanas + scaler por window_size y target
# --------------------------------------------------
def load_windows_and_scaler(
    *,
    window_size: int,
    target: str,
    windows_paths: Mapping[int, Mapping[str, Mapping[str, Path]]],
    scalers_path: Mapping[str, Path],
) -> Dict[str, Any]:
    """
    Carga X/y (train/valid/test) y el scaler correspondiente
    a un (window_size, target).

    windows_paths[L][target][split] -> Path
    scalers_path[target] -> Path
    """

    # --------------------------
    # 1) Validaciones
    # --------------------------
    if window_size not in windows_paths:
        raise KeyError(f"window_size={window_size} no existe en windows_paths")

    if target not in windows_paths[window_size]:
        raise KeyError(f"target='{target}' no existe en windows_paths[{window_size}]")

    if target not in scalers_path:
        raise KeyError(f"target='{target}' no existe en scalers_path")

    # --------------------------
    # 2) Paths
    # --------------------------
    train_path = windows_paths[window_size][target]["train"]
    valid_path = windows_paths[window_size][target]["valid"]
    test_path  = windows_paths[window_size][target]["test"]
    scaler_path = scalers_paths[target]

    # --------------------------
    # 3) Carga
    # --------------------------
    X_train, y_train = load_npz_windows(train_path)
    X_valid, y_valid = load_npz_windows(valid_path)
    X_test,  y_test  = load_npz_windows(test_path)

    scaler = load_scaler(scaler_path)

    # --------------------------
    # 4) Inferir horizonte
    # --------------------------
    horizon = int(target.split("_")[-1])

    # --------------------------
    # 5) Retorno
    # --------------------------
    return {
        "window_size": window_size,
        "target": target,
        "horizon": horizon,
        "paths": {
            "train": str(train_path),
            "valid": str(valid_path),
            "test": str(test_path),
            "scaler": str(scaler_path),
        },
        "scaler": scaler,
        "train": {"X": X_train, "y": y_train},
        "valid": {"X": X_valid, "y": y_valid},
        "test":  {"X": X_test,  "y": y_test},
    }

In [12]:
import numpy as np

def maybe_flatten_X(X: np.ndarray, *, flatten: bool) -> np.ndarray:
    """
    Si flatten=True y X es 3D (N,L,F) -> (N, L*F)
    Si flatten=False -> retorna X tal cual.
    """
    if not flatten:
        return X
    if X.ndim == 3:
        N, L, F = X.shape
        return X.reshape(N, L * F)
    if X.ndim == 2:
        return X
    raise ValueError(f"X debe ser 2D o 3D, recibí shape={X.shape}")

In [13]:
def create_bundles(window_size, targets: list, windows_paths=windows_paths, scalers_paths=scalers_paths, *, flatten_X=False):

    bundles = []
    for t in targets:
        b = load_windows_and_scaler(
            window_size=window_size,
            target=t,
            windows_paths=windows_paths,
            scalers_path=scalers_paths,
        )
        if flatten_X:
            b["train"]["X"] = maybe_flatten_X(b["train"]["X"], flatten=True)
            b["valid"]["X"] = maybe_flatten_X(b["valid"]["X"], flatten=True)
            b["test"]["X"]  = maybe_flatten_X(b["test"]["X"],  flatten=True)
        bundles.append(b)

    # prints (opcional)
    for b in bundles:
        print(f"H{b['horizon']} Train:", b["train"]["X"].shape, b["train"]["y"].shape)
        print(f"H{b['horizon']} Valid:", b["valid"]["X"].shape, b["valid"]["y"].shape)
        print(f"H{b['horizon']} Test :", b["test"]["X"].shape,  b["test"]["y"].shape)
        print(f"Scaler H{b['horizon']}:", type(b["scaler"]).__name__)

    return tuple(bundles)

In [14]:
#bundle_delta_60, bundle_delta_90 = create_bundles(window_size = 30, targets = ['delta_60', 'delta_90'], windows_paths = windows_paths, scalers_paths = scalers_paths, flatten_X = False)
#bundle_ret_60, bundle_ret_90 = create_bundles(window_size = 30, targets = ['ret_60', 'ret_90'], windows_paths = windows_paths, scalers_paths = scalers_paths)
'''
def run_mlp(window_size: int, *, alpha: float = 1.0, verbose: bool = True):

    size = window_size

    if verbose:
        print("\n" + "=" * 80)
        print(f"RIDGE | SEQ2ONE | WINDOW_SIZE=L{size} | alpha={alpha}")
        print("=" * 80)

    targets = ["delta_60", "delta_90", "ret_60", "ret_90"]
    rows = []

    for target in targets:
        if verbose:
            print(f"\n[BUILD] L{size} | target = '{target}'")


        # crear SOLO 1 bundle (y aplanar X para Ridge)
        (bundle,) = create_bundles(
            window_size=size,
            targets=[target],            # <- SOLO UNO
            windows_paths=windows_paths,
            scalers_paths=scalers_paths,
            flatten_X=True,              # <- MLP necesita 2D
        )
'''

'\ndef run_mlp(window_size: int, *, alpha: float = 1.0, verbose: bool = True):\n\n    size = window_size\n\n    if verbose:\n        print("\n" + "=" * 80)\n        print(f"RIDGE | SEQ2ONE | WINDOW_SIZE=L{size} | alpha={alpha}")\n        print("=" * 80)\n\n    targets = ["delta_60", "delta_90", "ret_60", "ret_90"]\n    rows = []\n\n    for target in targets:\n        if verbose:\n            print(f"\n[BUILD] L{size} | target = \'{target}\'")\n\n\n        # crear SOLO 1 bundle (y aplanar X para Ridge)\n        (bundle,) = create_bundles(\n            window_size=size,\n            targets=[target],            # <- SOLO UNO\n            windows_paths=windows_paths,\n            scalers_paths=scalers_paths,\n            flatten_X=True,              # <- MLP necesita 2D\n        )\n'

NOTA IMPORTANTE: COMO ACCEDER A LAS VENTANAS

Para el horizonte: `h`

  - Train
    - `X`: `bundle_h["train"]["X"]`
    - `y`: `bundle_h["train"]["y"]`

  - Valid
    - `X`: `bundle_h["valid"]["X"]`
    - `y`:`bundle_h["valid"]["y"]`

  - Test
    - `X`: `bundle_h["test"]["X"]`
    - `y`: `bundle_h["test"]["y"]`

  - Scaler
    - `bundle_h["scaler"]`

## **7. Sanity Check**

In [15]:
from __future__ import annotations

from typing import Any, Dict, Optional, Tuple
import numpy as np


# ============================================================
# 1) Utilidades internas (inferencias y normalización)
# ============================================================

def _as_float_array(a: Any, *, name: str) -> np.ndarray:
    """Convierte a np.ndarray float64 y valida finitud."""
    arr = np.asarray(a, dtype=np.float64)
    if arr.size == 0:
        raise ValueError(f"{name} está vacío. shape={arr.shape}")
    if not np.isfinite(arr).all():
        raise ValueError(f"{name} contiene NaN/inf. Limpie antes de continuar. shape={arr.shape}")
    return arr


def _normalize_y_seq2one(y: np.ndarray, *, name: str = "y") -> np.ndarray:
    """
    Normaliza y para seq2one a shape (n_samples,).
    Acepta: (n,), (n,1). Rechaza shapes incompatibles.
    """
    if y.ndim == 1:
        return y
    if y.ndim == 2 and y.shape[1] == 1:
        return y.squeeze(1)
    raise ValueError(f"{name} shape inválido para seq2one. Se esperaba (n,) o (n,1). Recibido {y.shape}")


def _infer_seq_len_and_n_features(X: np.ndarray) -> Tuple[int, Optional[int], str]:
    """
    Infiera (seq_len, n_features, mode) desde X.
    mode:
      - "3d": X=(n, seq_len, n_features)
      - "2d": X=(n, d_flat)  -> n_features=None
    """
    if X.ndim == 3:
        return int(X.shape[1]), int(X.shape[2]), "3d"
    if X.ndim == 2:
        return int(X.shape[1]), None, "2d"
    raise ValueError(f"X.ndim inválido. Se esperaba 2D o 3D. Recibido X.shape={X.shape}")

In [16]:
# ============================================================
# 2) Sanity check principal (seq2one)
# ============================================================

def sanity_check_seq2one(
    X: Any,
    y: Any,
    split_name: str,
    *,
    expected_seq_len: Optional[int] = None,
    expected_n_features: Optional[int] = None,
    expected_flat_dim: Optional[int] = None,
    allow_seq_inputs_take_last: bool = False,
    verbose: bool = True,
) -> Dict[str, Any]:
    """
    Sanity check para datasets seq2one.

    Soporta:
      - X 3D: (n, seq_len, n_features)
      - X 2D: (n, d_flat)  [ventana aplanada]

    y soporta:
      - y 1D: (n,)
      - y 2D: (n,1)

    Parámetros
    ----------
    expected_seq_len:
        Para X 3D: valida seq_len.
        Para X 2D: si expected_flat_dim no está, puede usarse como "d_flat" esperado.
    expected_n_features:
        Solo aplica a X 3D.
    expected_flat_dim:
        Solo aplica a X 2D (d_flat esperado). Ej: 60*20=1200.
    allow_seq_inputs_take_last:
        Si y viniera como (n, seq_len) (caso raro), permite tomar y[:, -1].
        Por defecto False (recomendado).
    """
    X = _as_float_array(X, name=f"X[{split_name}]")
    y = _as_float_array(y, name=f"y[{split_name}]")

    # Normalizar y
    if y.ndim == 2 and y.shape[1] != 1 and allow_seq_inputs_take_last:
        # caso tolerante: y=(n,seq_len) -> tomar último
        y = y[:, -1]
    y = _normalize_y_seq2one(y, name=f"y[{split_name}]")

    # Inferir modo y dimensiones de X
    seq_len, n_features, mode = _infer_seq_len_and_n_features(X)
    n_samples = int(X.shape[0])

    # Validaciones básicas n_samples
    if y.shape[0] != n_samples:
        raise ValueError(
            f"Mismatch n_samples en {split_name}: X tiene n={n_samples}, y tiene n={y.shape[0]}"
        )

    # Validación de shapes según modo
    if mode == "3d":
        # expected_seq_len / expected_n_features
        if expected_seq_len is not None and seq_len != int(expected_seq_len):
            raise ValueError(
                f"{split_name}: seq_len esperado={expected_seq_len}, recibido={seq_len}. X.shape={X.shape}"
            )
        if expected_n_features is not None and n_features != int(expected_n_features):
            raise ValueError(
                f"{split_name}: n_features esperado={expected_n_features}, recibido={n_features}. X.shape={X.shape}"
            )

    elif mode == "2d":
        d_flat = int(X.shape[1])

        # Si expected_flat_dim está, valida contra eso
        if expected_flat_dim is not None and d_flat != int(expected_flat_dim):
            raise ValueError(
                f"{split_name}: d_flat esperado={expected_flat_dim}, recibido={d_flat}. X.shape={X.shape}"
            )

        # Si no hay expected_flat_dim pero sí expected_seq_len, úselo como d_flat esperado
        if expected_flat_dim is None and expected_seq_len is not None and d_flat != int(expected_seq_len):
            raise ValueError(
                f"{split_name}: d_flat esperado={expected_seq_len}, recibido={d_flat}. X.shape={X.shape}"
            )

        # expected_n_features no aplica en 2D
        if expected_n_features is not None:
            raise ValueError(
                f"{split_name}: expected_n_features no aplica para X 2D. "
                f"Use expected_flat_dim (ej: 1200) o pase X en 3D."
            )

    # Validación extra: varianza de y (para detectar targets constantes)
    y_std = float(np.std(y))
    if verbose:
        info = {
            "split": split_name,
            "X_shape": tuple(X.shape),
            "y_shape": tuple(y.shape),
            "mode": mode,
            "seq_len": seq_len if mode == "3d" else None,
            "n_features": n_features if mode == "3d" else None,
            "flat_dim": int(X.shape[1]) if mode == "2d" else None,
            "y_mean": float(np.mean(y)),
            "y_std": y_std,
            "y_min": float(np.min(y)),
            "y_max": float(np.max(y)),
        }
        print(
            f"[sanity_check_seq2one] {split_name} | X={info['X_shape']} | y={info['y_shape']} | "
            f"mode={mode} | y_std={y_std:.6f}"
        )

    return {
        "split": split_name,
        "X_shape": tuple(X.shape),
        "y_shape": tuple(y.shape),
        "mode": mode,
        "seq_len": seq_len if mode == "3d" else None,
        "n_features": n_features if mode == "3d" else None,
        "flat_dim": int(X.shape[1]) if mode == "2d" else None,
        "y_mean": float(np.mean(y)),
        "y_std": float(np.std(y)),
        "y_min": float(np.min(y)),
        "y_max": float(np.max(y)),
    }

In [17]:
# ============================================================
# 3) Sanity checks por bundle (train/valid/test)
# ============================================================

def run_sanity_checks_for_bundle_seq2one(
    bundle: Dict[str, Any],
    *,
    tag: str,
    expected_seq_len: Optional[int] = None,
    expected_n_features: Optional[int] = None,
    expected_flat_dim: Optional[int] = None,
    verbose: bool = True,
) -> Dict[str, Any]:
    """
    Ejecuta sanity checks para un bundle con estructura:

    {
      "horizon": 60,
      "train": {"X":..., "y":...},
      "valid": {"X":..., "y":...},
      "test":  {"X":..., "y":...},
    }

    Detecta automáticamente si X es 2D o 3D, y usa TRAIN como referencia
    si no se pasan expected_*.
    """
    X_tr = bundle["train"]["X"]
    y_tr = bundle["train"]["y"]
    X_va = bundle["valid"]["X"]
    y_va = bundle["valid"]["y"]
    X_te = bundle["test"]["X"]
    y_te = bundle["test"]["y"]

    X_tr_arr = np.asarray(X_tr)
    seq_len_tr, n_feat_tr, mode_tr = _infer_seq_len_and_n_features(X_tr_arr)

    # Setear esperados desde TRAIN si no se dieron
    if mode_tr == "3d":
        if expected_seq_len is None:
            expected_seq_len = seq_len_tr
        if expected_n_features is None:
            expected_n_features = n_feat_tr
        # En 3D no hace falta expected_flat_dim
        expected_flat_dim = None
    else:
        d_flat_tr = int(X_tr_arr.shape[1])
        if expected_flat_dim is None:
            expected_flat_dim = d_flat_tr
        # Para evitar confusión, no usamos expected_seq_len/n_features en 2D
        expected_seq_len = expected_seq_len  # puede quedar None
        expected_n_features = None

    # Ejecutar checks
    out_tr = sanity_check_seq2one(
        X_tr, y_tr, f"train_{tag}",
        expected_seq_len=expected_seq_len,
        expected_n_features=expected_n_features,
        expected_flat_dim=expected_flat_dim,
        verbose=verbose,
    )
    out_va = sanity_check_seq2one(
        X_va, y_va, f"valid_{tag}",
        expected_seq_len=expected_seq_len,
        expected_n_features=expected_n_features,
        expected_flat_dim=expected_flat_dim,
        verbose=verbose,
    )
    out_te = sanity_check_seq2one(
        X_te, y_te, f"test_{tag}",
        expected_seq_len=expected_seq_len,
        expected_n_features=expected_n_features,
        expected_flat_dim=expected_flat_dim,
        verbose=verbose,
    )

    h = bundle.get("horizon", "NA")
    if verbose:
        print(f"OK {tag} (h={h})")

    return {"train": out_tr, "valid": out_va, "test": out_te, "horizon": h}


def run_sanity_checks_all_horizons_seq2one(
    bundle_60: Dict[str, Any],
    bundle_90: Dict[str, Any],
    *,
    verbose: bool = True,
) -> Dict[str, Any]:
    """Corre sanity checks para ambos horizontes (ej: 60 y 90)."""
    out_60 = run_sanity_checks_for_bundle_seq2one(bundle_60, tag="h60", verbose=verbose)
    out_90 = run_sanity_checks_for_bundle_seq2one(bundle_90, tag="h90", verbose=verbose)
    return {"h60": out_60, "h90": out_90}

In [18]:
#summary_delta = run_sanity_checks_all_horizons_seq2one(bundle_delta_60, bundle_delta_90)
#summary_ret = run_sanity_checks_all_horizons_seq2one(bundle_ret_60, bundle_ret_90)

## **8. Gestión de dataset de métricas**

In [19]:
def load_seq2one_metrics_if_exists(
    *,
    name: str,
    base_dir: str = "/content/drive/MyDrive/neural_profit/metrics/seq2one_metrics",
) -> pd.DataFrame:
    path = Path(base_dir) / f"seq2one_{name}_metrics.parquet"
    if path.exists():
        return pd.read_parquet(path)
    return pd.DataFrame()

In [20]:
from pathlib import Path
import pandas as pd

def save_seq2one_metrics(
    df_metrics: pd.DataFrame,
    *,
    name: str,
    base_dir: str = "/content/drive/MyDrive/neural_profit/metrics/seq2one_metrics",
) -> Path:
    """
    Guarda un DataFrame de métricas seq2one en formato Parquet.

    Parámetros
    ----------
    df_metrics : pd.DataFrame
        DataFrame con métricas (una fila por modelo/horizonte/split).
    name : str
        Nombre identificador del archivo (ej: 'naive_valid', 'ridge_valid').
        No incluir extensión.
    base_dir : str
        Directorio base donde se almacenan todas las métricas seq2one.

    Retorna
    -------
    out_path : Path
        Ruta completa del archivo guardado.
    """
    out_dir = Path(base_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    out_path = out_dir / f"seq2one_{name}_metrics.parquet"
    df_metrics.to_parquet(out_path, index=False)

    print(f"[OK] Métricas guardadas en: {out_path}")
    return out_path

## **9. Métricas ML**

In [21]:
import pandas as pd

def metrics_to_df(
    metrics: dict,
    *,
    model: str,
    split: str,
    horizon: int,
    window_size: int,
    target: str,
) -> pd.DataFrame:
    """
    Convierte un dict de métricas seq2one en una fila de DataFrame.
    """

    return pd.DataFrame([{
        "model": model,
        "split": split,
        "window_size": window_size,
        "target": target,
        "horizon_min": horizon,
        "MAE": metrics["MAE"],
        "RMSE": metrics["RMSE"],
        "R2": metrics.get("R2"),
        "DA": metrics.get("DA"),
    }])

In [22]:
def get_metrics_torch(bundle, model, *, device) -> tuple[dict, dict]:
  # -------- VALID --------
  X_valid = bundle["valid"]["X"]
  y_valid = bundle["valid"]["y"]
  y_pred_valid = predict_mlp(model, X_valid, device=device)
  metrics_valid = compute_seq2one_metrics(y_valid, y_pred_valid, compute_r2=True)

  # -------- TEST --------
  X_test = bundle["test"]["X"]
  y_test = bundle["test"]["y"]
  y_pred_test = predict_mlp(model, X_test, device=device)
  metrics_test  = compute_seq2one_metrics(y_test, y_pred_test,  compute_r2=True)

  return metrics_valid, metrics_test

# **DEFINICIÓN DE MODELO**

## **11. Definición del modelo — placeholder**

### **11.1. Baseline MLP Configuration (SEQ2ONE – delta_60)**

**Hiperparámetros baseline**


| Hiperparámetro   | Valor   |
|------------------|---------|
| in_dim           | 1200    |
| hidden_dim       | 128     |
| dropout          | 0.0     |
| learning_rate    | 1e-3    |
| weight_decay     | 1e-4    |
| max_epochs       | 30      |
| patience         | 5       |
| optimizer        | Adam    |
| loss_function    | MSE     |

In [23]:
import pandas as pd
def load_seq2one_metrics_if_exists(
    *,
    name: str,
    base_dir: str = "/content/drive/MyDrive/neural_profit/metrics/seq2one_metrics",
) -> pd.DataFrame:
    path = Path(base_dir) / f"seq2one_{name}_metrics.parquet"
    if path.exists():
        return pd.read_parquet(path)
    return pd.DataFrame()

df_mlp_all_sizes = load_seq2one_metrics_if_exists(name="mlp")
df_mlp_delta_60 = df_mlp_all_sizes[df_mlp_all_sizes["target"] == "delta_60"].copy()

In [24]:
df_mlp_delta_60

,model,split,window_size,target,horizon_min,MAE,RMSE,R2,DA,w_decay
0,mlp,test,30,delta_60,60,50.232999,77.094085,0.264331,0.651685,0.0001
1,mlp,valid,30,delta_60,60,32.880210,46.714091,0.273345,0.661028,0.0001
8,mlp,test,60,delta_60,60,38.923520,63.419347,0.496504,0.738393,0.0001
9,mlp,valid,60,delta_60,60,24.081825,37.120464,0.550355,0.758303,0.0001
16,mlp,test,90,delta_60,60,40.382358,64.906080,0.481965,0.729042,0.0001
17,mlp,valid,90,delta_60,60,25.324535,38.475513,0.528487,0.741210,0.0001
24,mlp,test,120,delta_60,60,39.748844,63.426119,0.518663,0.741398,0.0001
25,mlp,valid,120,delta_60,60,24.769221,37.699327,0.556814,0.754523,0.0001
32,mlp,test,180,delta_60,60,38.112160,60.078973,0.570888,0.783965,0.0001
33,mlp,valid,180,delta_60,60,23.693735,35.268546,0.635576,0.785406,0.0001

### **11.2. Imports (PyTorch) + semillas**

In [25]:
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

In [26]:
def set_seed(seed: int = 42) -> None:
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

### **11.2. Dataset/DataLoader desde bundle**

In [27]:
#DATASET/DATALOADER DESDE BUNDLE

def make_loaders_from_bundle(
    bundle,
    *,
    batch_size: int = 4096,
    num_workers: int = 0,
) -> dict:
    """
    Convierte bundle {train/valid/test} a DataLoaders PyTorch.
    Espera X: (n, 1200) y y: (n,)
    """
    loaders = {}

    for split in ["train", "valid", "test"]:
        X = np.asarray(bundle[split]["X"], dtype=np.float32)
        y = np.asarray(bundle[split]["y"], dtype=np.float32).reshape(-1, 1)  # (n,1)

        ds = TensorDataset(torch.from_numpy(X), torch.from_numpy(y))
        shuffle = (split == "train")

        loaders[split] = DataLoader(
            ds,
            batch_size=batch_size,
            shuffle=shuffle,
            num_workers=num_workers,
            pin_memory=torch.cuda.is_available(),
            drop_last=False,
        )

    return loaders

In [28]:
#loaders_60 = make_loaders_from_bundle(bundle_60, batch_size=16384)
#loaders_90 = make_loaders_from_bundle(bundle_90, batch_size=16384)

### **11.3. Definición del modelo MLP (simple y controlado)**

In [29]:
#DEFINICIÓN DEL MODELO MLP
class MLPSeq2One(nn.Module):
    def __init__(self, in_dim: int = 1200, hidden_dim: int = 128, dropout: float = 0.0):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 1),
        )

    def forward(self, x):
        return self.net(x)

### **11.4. Entrenamiento con early stopping (VALID)**

In [30]:
#ENTRENAMIENTO CON EARLY STOPPING (VALID)
@torch.no_grad()
def evaluate_mse(model: nn.Module, loader: DataLoader, device: torch.device) -> float:
    model.eval()
    mse_sum = 0.0
    n = 0
    for xb, yb in loader:
        xb = xb.to(device)
        yb = yb.to(device)
        pred = model(xb)
        mse_sum += torch.sum((pred - yb) ** 2).item()
        n += yb.numel()
    return mse_sum / max(n, 1)

import time
import torch
import torch.nn as nn

def _ts():
    return time.strftime("%H:%M:%S")

def train_mlp(
    loaders: dict,
    *,
    in_dim: int = 1200,
    hidden_dim: int = 128,
    dropout: float = 0.0,
    lr: float = 1e-3,
    weight_decay: float = 1e-4,
    max_epochs: int = 30,
    patience: int = 5,
    device: torch.device,
    verbose: bool = True,
    log_every: int = 0,  # 0 => no log por batch; si pones 50, log cada 50 batches
):
    """
    Entrena un MLP seq2one usando TRAIN y early stopping en VALID (por MSE).
    Logs: inicio/fin, train_loss, valid_mse, mejoras, early-stopping.
    """
    if verbose:
        print(f"[{_ts()}] [TRAIN] START | in_dim={in_dim} hidden_dim={hidden_dim} dropout={dropout} "
              f"lr={lr} wd={weight_decay} max_epochs={max_epochs} patience={patience} "
              f"device={device.type}")

    t_global = time.perf_counter()

    model = MLPSeq2One(in_dim=in_dim, hidden_dim=hidden_dim, dropout=dropout).to(device)
    opt = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    loss_fn = nn.MSELoss()

    best_state = None
    best_valid = float("inf")
    bad_epochs = 0

    for epoch in range(1, max_epochs + 1):
        t_epoch = time.perf_counter()

        # -------------------------
        # TRAIN EPOCH
        # -------------------------
        model.train()
        train_loss_sum = 0.0
        train_n = 0

        for b, (xb, yb) in enumerate(loaders["train"], start=1):
            xb = xb.to(device, non_blocking=True)
            yb = yb.to(device, non_blocking=True)

            opt.zero_grad(set_to_none=True)
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()

            # acumular loss para log por época
            bs = yb.numel()
            train_loss_sum += loss.item() * bs
            train_n += bs

            if verbose and log_every and (b % log_every == 0):
                train_loss_avg_so_far = train_loss_sum / max(train_n, 1)
                print(f"[{_ts()}]   epoch={epoch:02d} batch={b:04d} | train_loss_avg={train_loss_avg_so_far:.6f}")

        train_loss_avg = train_loss_sum / max(train_n, 1)

        # -------------------------
        # VALIDATION
        # -------------------------
        #if verbose:
        #    print(f"[{_ts()}]   [VALID] Calculando valid_mse ...")
        t0 = time.perf_counter()

        valid_mse = evaluate_mse(model, loaders["valid"], device)

        dt_valid = time.perf_counter() - t0
        dt_epoch = time.perf_counter() - t_epoch

        # -------------------------
        # EARLY STOPPING LOGIC
        # -------------------------
        improved = valid_mse < (best_valid - 1e-9)
        if improved:
            best_valid = valid_mse
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            bad_epochs = 0
        else:
            bad_epochs += 1

        if verbose:
            flag = "BEST" if improved else f"no_improve({bad_epochs}/{patience})"
            print(
                f"[{_ts()}] epoch={epoch:02d} | train_loss={train_loss_avg:.6f} | "
                f"valid_mse={valid_mse:.6f} | {flag} | dt_valid={dt_valid:.2f}s | dt_epoch={dt_epoch:.2f}s"
            )

        if bad_epochs >= patience:
            if verbose:
                print(f"[{_ts()}] [TRAIN] EARLY STOPPING | patience={patience} | best_valid_mse={best_valid:.6f}")
            break

    if best_state is not None:
        if verbose:
            print(f"[{_ts()}] [TRAIN] Cargando best_state (best_valid_mse={best_valid:.6f}) ...")
        model.load_state_dict(best_state)

    if verbose:
        dt_all = time.perf_counter() - t_global
        print(f"[{_ts()}] [TRAIN] END | best_valid_mse={best_valid:.6f} | dt_total={dt_all:.2f}s")

    return model

### **11.5. Predicciones MLP**

In [31]:
#predicciones MLP

import numpy as np
import torch

@torch.no_grad()
def predict_mlp(model, X: np.ndarray, *, device: torch.device, batch_size: int = 32768) -> np.ndarray:
    """
    Predice con un modelo MLP PyTorch en batches.
    Retorna shape (n_samples,)
    """
    model.eval()

    X = np.asarray(X, dtype=np.float32)
    n = X.shape[0]
    preds = []

    for i in range(0, n, batch_size):
        xb = torch.from_numpy(X[i:i+batch_size]).to(device)
        yb = model(xb).squeeze(-1)          # (batch,)
        preds.append(yb.detach().cpu().numpy())

    return np.concatenate(preds, axis=0)

## **12. Ejecución completa**

In [32]:
#RUN MLP

import pandas as pd
import gc
import time

def _ts():
    return time.strftime("%H:%M:%S")

def run_mlp(window_size: int, *, weight_decay: float = 1e-4, verbose: bool = True):

    size = window_size
    n_features = 36

    if verbose:
        print("\n" + "=" * 80)
        print(f"[{_ts()}] MLP | SEQ2ONE | WINDOW_SIZE=L{size} | in_dim={size*n_features} | weight_decay={weight_decay}")
        print("=" * 80)

    targets = ["delta_60", "delta_90", "ret_60", "ret_90"]
    rows = []

    t_global = time.perf_counter()

    for i, target in enumerate(targets, start=1):
        t_target = time.perf_counter()

        if verbose:
            print(f"\n[{_ts()}] [{i}/{len(targets)}] START target='{target}' | L{size}")

        # -------------------------
        # BUILD BUNDLE
        # -------------------------
        if verbose:
            print(f"[{_ts()}]   [BUILD] Creando bundle (flatten_X=True) ...")
        t0 = time.perf_counter()

        (bundle,) = create_bundles(
            window_size=size,
            targets=[target],
            windows_paths=windows_paths,
            scalers_paths=scalers_paths,
            flatten_X=True,  # MLP necesita 2D
        )

        if verbose:
            dt = time.perf_counter() - t0
            # (opcional) si existe el shape, lo mostramos
            try:
                xshape = bundle["train"]["X"].shape
                yshape = bundle["train"]["y"].shape
                print(f"[{_ts()}]   [BUILD] OK | train X={xshape} y={yshape} | dt={dt:.2f}s")
            except Exception:
                print(f"[{_ts()}]   [BUILD] OK | dt={dt:.2f}s")

        # -------------------------
        # LOADERS
        # -------------------------
        if verbose:
            print(f"[{_ts()}]   [LOADERS] Creando DataLoaders ...")
        t0 = time.perf_counter()

        loaders = make_loaders_from_bundle(
            bundle,
            batch_size=16384
        )

        if verbose:
            dt = time.perf_counter() - t0
            # si los loaders exponen dataset length, lo imprimimos
            try:
                ntr = len(loaders["train"].dataset)
                nva = len(loaders["valid"].dataset)
                nte = len(loaders["test"].dataset)
                print(f"[{_ts()}]   [LOADERS] OK | n(train/valid/test)=({ntr}/{nva}/{nte}) | dt={dt:.2f}s")
            except Exception:
                print(f"[{_ts()}]   [LOADERS] OK | dt={dt:.2f}s")

        # -------------------------
        # TRAIN
        # -------------------------
        if verbose:
            print(f"[{_ts()}]   [TRAIN] Iniciando entrenamiento ...")
        t0 = time.perf_counter()

        model = train_mlp(
            loaders,
            in_dim=size * n_features,
            hidden_dim=128,
            dropout=0.0,
            lr=1e-3,
            weight_decay=weight_decay,
            max_epochs=30,
            patience=5,
            device=device
        )

        if verbose:
            dt = time.perf_counter() - t0
            print(f"[{_ts()}]   [TRAIN] FIN entrenamiento | dt={dt:.2f}s")

        # liberar TRAIN (opcional)
        if verbose:
            print(f"[{_ts()}]   [MEM] Liberando bundle['train'] y gc.collect() ...")
        del bundle["train"]
        gc.collect()

        # -------------------------
        # PRED + METRICS
        # -------------------------
        if verbose:
            print(f"[{_ts()}]   [PRED] Iniciando predicciones + cálculo de métricas (valid/test) ...")
        t0 = time.perf_counter()

        metrics_valid, metrics_test = get_metrics_torch(bundle, model, device=device)

        if verbose:
            dt = time.perf_counter() - t0
            print(f"[{_ts()}]   [METRICS] OK (valid/test) | dt={dt:.2f}s")

        # -------------------------
        # DF APPEND
        # -------------------------
        if verbose:
            print(f"[{_ts()}]   [DF] Agregando filas a la tabla de métricas ...")
        t0 = time.perf_counter()

        rows.append(metrics_to_df(
            metrics_valid,
            model="mlp",
            split="valid",
            horizon=bundle["horizon"],
            window_size=bundle["window_size"],
            target=bundle["target"],
        ))

        rows.append(metrics_to_df(
            metrics_test,
            model="mlp",
            split="test",
            horizon=bundle["horizon"],
            window_size=bundle["window_size"],
            target=bundle["target"],
        ))

        if verbose:
            dt = time.perf_counter() - t0
            print(f"[{_ts()}]   [DF] OK | dt={dt:.2f}s")

        # -------------------------
        # CLEANUP
        # -------------------------
        if verbose:
            print(f"[{_ts()}]   [CLEAN] Liberando objetos (bundle/model/metrics/loaders) ...")
        del bundle, model, metrics_valid, metrics_test, loaders
        gc.collect()

        if verbose:
            dt_target = time.perf_counter() - t_target
            print(f"[{_ts()}] [{i}/{len(targets)}] DONE target='{target}' | dt_total={dt_target:.2f}s")

    # -------------------------
    # FINAL DF
    # -------------------------
    if verbose:
        print(f"\n[{_ts()}] [FINAL] Concatenando resultados ...")
    t0 = time.perf_counter()

    df_mlp_metrics = (
        pd.concat(rows, ignore_index=True)
          .sort_values(["window_size", "target", "split", "horizon_min", "model"])
          .reset_index(drop=True)
    )

    if verbose:
        dt = time.perf_counter() - t0
        dt_all = time.perf_counter() - t_global
        print(f"[{_ts()}] [FINAL] OK | rows={len(df_mlp_metrics)} | dt_concat={dt:.2f}s | dt_total={dt_all:.2f}s")
        print(df_mlp_metrics[["window_size", "target", "split", "horizon_min", "model"]]
              .drop_duplicates()
              .to_string(index=False))

    return df_mlp_metrics

In [33]:
#RUN MLP INCREMENTAL

def run_mlp_incremental(
    window_sizes: list[int],
    *,
    dropout: float = 0.0,
    lr: float = 1e-3,
    weight_decay: float = 1e-4,
    name: str = "mlp",  # -> seq2one_ridge_metrics.parquet
    base_dir: str = "/content/drive/MyDrive/neural_profit/metrics/seq2one_metrics",
    verbose: bool = True,
) -> pd.DataFrame:

    # 1) Cargar si existe
    df_all = load_seq2one_metrics_if_exists(name=name, base_dir=base_dir)

    # 2) Asegurar columna w_decay
    if df_all.empty:
        df_all = pd.DataFrame(columns=[
            "model","split","window_size","target","horizon_min","MAE","RMSE","R2","DA","w_decay"
        ])
    if "w_decay" not in df_all.columns:
        df_all["w_decay"] = pd.NA

    key_cols = ["model","w_decay","window_size","target","split","horizon_min"]

    # 3) Normalizar tipos (evita falsos mismatches)
    if len(df_all):
        df_all["window_size"] = pd.to_numeric(df_all["window_size"], errors="coerce").astype("Int64")
        df_all["horizon_min"] = pd.to_numeric(df_all["horizon_min"], errors="coerce").astype("Int64")

    # 4) Loop por window_size
    for ws in window_sizes:

        # Si ya existen todas las filas esperadas para este ws, saltar
        # Esperadas: 4 targets x 2 splits (valid/test) = 8 filas para mlp (siempre)
        # (Esto asume que tu run_mlp devuelve valid+test para los 4 targets)
        df_ws = df_all[(df_all["model"] == "mlp") & (df_all["w_decay"] == weight_decay) & (df_all["window_size"] == ws)]
        if len(df_ws) >= 8:
            if verbose:
                print(f"[SKIP] L{ws}: ya hay {len(df_ws)} filas (mlp w_decay={weight_decay}).")
            continue

        if verbose:
            print("\n" + "="*90)
            print(f"[RUN] MLP incremental | L{ws} |in_dim={ws*36}| dropout={dropout} | lr={lr} | w_decay={weight_decay}")  ###################
            print("="*90)

        # 5) Entrenar y obtener métricas para ESTE ws
        df_new = run_mlp(ws, weight_decay=weight_decay, verbose=verbose).copy() #####################
        df_new["w_decay"] = weight_decay  # agregar

        # 6) Filtrar filas ya existentes (anti-duplicados)
        # Creamos un "key" para comparar rápido
        existing_keys = set(tuple(x) for x in df_all[key_cols].dropna().values)
        mask_keep = [tuple(row) not in existing_keys for row in df_new[key_cols].values]
        df_new = df_new.loc[mask_keep].copy()

        if df_new.empty:
            if verbose:
                print(f"[INFO] L{ws}: no había filas nuevas para agregar.")
            continue

        # 7) Merge + dedupe por seguridad
        df_all = pd.concat([df_all, df_new], ignore_index=True)
        df_all = df_all.drop_duplicates(subset=key_cols, keep="last").reset_index(drop=True)

        # 8) Guardar checkpoint con TU función
        save_seq2one_metrics(df_all, name=name, base_dir=base_dir)

        if verbose:
            print(f"[OK] Checkpoint guardado. Total rows={len(df_all)}")

    return df_all

In [34]:
#df_mlp_all_sizes = load_seq2one_metrics_if_exists(name="mlp", base_dir="/content/drive/MyDrive/neural_profit/metrics/seq2one_metrics")

In [35]:
#MLP_ALL_TRAIN = '''
df_mlp_all_sizes = run_mlp_incremental(
    window_sizes=[30, 60, 90, 120, 180],
    name="mlp",   # genera seq2one_ridge_metrics.parquet
    verbose=True,
)
#'''

[SKIP] L30: ya hay 8 filas (mlp w_decay=0.0001).
[SKIP] L60: ya hay 8 filas (mlp w_decay=0.0001).
[SKIP] L90: ya hay 8 filas (mlp w_decay=0.0001).
[SKIP] L120: ya hay 8 filas (mlp w_decay=0.0001).
[SKIP] L180: ya hay 8 filas (mlp w_decay=0.0001).

## **13. Tuning de Arquitectura (capacidad del modelo)**

Afecta el bias–variance trade-off estructural.

Parámetros relevantes:
- hidden_dim
- n_layers (si agregas más capas)
- dropout
- Activación (ReLU, GELU, etc.)

Esto controla qué tan complejo puede ser el mapeo no lineal entre la ventana y delta_60.

### **13.1. Funciones para tuning de arquitectura**

In [36]:
import torch
import torch.nn as nn

# ============================================================
# MLP configurable para tuning de arquitectura (SEQ2ONE)
# ============================================================
class MLPSeq2One(nn.Module):
    """
    MLP SEQ2ONE configurable.
    - in_dim: dimensión de entrada (L * F si está aplanado)
    - hidden_dims: lista con el tamaño de cada capa oculta (profundidad + anchura)
    - dropout: dropout aplicado entre capas (0.0 desactiva)
    - activation: "relu" o "gelu"
    """
    def __init__(
        self,
        *,
        in_dim: int = 1200,
        hidden_dims: list[int] = [128],
        dropout: float = 0.0,
        activation: str = "relu",
    ):
        super().__init__()

        if not hidden_dims or any(h <= 0 for h in hidden_dims):
            raise ValueError(f"hidden_dims inválido: {hidden_dims}")

        if activation.lower() == "relu":
            Act = nn.ReLU
        elif activation.lower() == "gelu":
            Act = nn.GELU
        else:
            raise ValueError(f"activation no soportada: {activation} (use 'relu' o 'gelu')")

        layers: list[nn.Module] = []
        prev = in_dim

        for h in hidden_dims:
            layers.append(nn.Linear(prev, h))
            layers.append(Act())
            if dropout and dropout > 0.0:
                layers.append(nn.Dropout(dropout))
            prev = h

        layers.append(nn.Linear(prev, 1))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)

In [37]:
import time
import torch
import torch.nn as nn
from torch.utils.data import DataLoader

# ============================================================
# EVAL: MSE (VALID) para early stopping
# ============================================================
@torch.no_grad()
def evaluate_mse(model: nn.Module, loader: DataLoader, device: torch.device) -> float:
    model.eval()
    mse_sum = 0.0
    n = 0
    for xb, yb in loader:
        xb = xb.to(device, non_blocking=True)
        yb = yb.to(device, non_blocking=True)
        pred = model(xb)
        mse_sum += torch.sum((pred - yb) ** 2).item()
        n += yb.numel()
    return mse_sum / max(n, 1)


def _ts():
    return time.strftime("%H:%M:%S")


# ============================================================
# TRAIN: MLP seq2one + early stopping en VALID (por MSE)
# ============================================================
def train_mlp(
    loaders: dict,
    *,
    # ---- arquitectura ----
    in_dim: int = 1200,
    hidden_dims: list[int] | None = None,   # ej: [256] o [256,128]
    dropout: float = 0.0,
    activation: str = "relu",               # "relu" o "gelu"

    # ---- entrenamiento ----
    lr: float = 1e-3,
    weight_decay: float = 1e-4,
    max_epochs: int = 30,
    patience: int = 5,
    device: torch.device,
    verbose: bool = True,
    log_every: int = 0,  # 0 => no log por batch; si pones 50, log cada 50 batches
):
    """
    Entrena un MLP seq2one usando TRAIN y early stopping en VALID (por MSE).
    Logs: inicio/fin, train_loss, valid_mse, mejoras, early-stopping.

    Nota:
    - hidden_dims controla profundidad/anchura. Si None, usa [128] por compatibilidad.
    """
    if hidden_dims is None:
        hidden_dims = [128]  # baseline equivalente a hidden_dim=128

    if verbose:
        print(
            f"[{_ts()}] [TRAIN] START | in_dim={in_dim} hidden_dims={hidden_dims} "
            f"dropout={dropout} activation={activation} lr={lr} wd={weight_decay} "
            f"max_epochs={max_epochs} patience={patience} device={device.type}"
        )

    t_global = time.perf_counter()

    # ---- modelo (arquitectura tuneable) ----
    model = MLPSeq2One(
        in_dim=in_dim,
        hidden_dims=hidden_dims,
        dropout=dropout,
        activation=activation,
    ).to(device)

    opt = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    loss_fn = nn.MSELoss()

    best_state = None
    best_valid = float("inf")
    bad_epochs = 0

    for epoch in range(1, max_epochs + 1):
        t_epoch = time.perf_counter()

        # -------------------------
        # TRAIN EPOCH
        # -------------------------
        model.train()
        train_loss_sum = 0.0
        train_n = 0

        for b, (xb, yb) in enumerate(loaders["train"], start=1):
            xb = xb.to(device, non_blocking=True)
            yb = yb.to(device, non_blocking=True)

            opt.zero_grad(set_to_none=True)
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()

            bs = yb.numel()
            train_loss_sum += loss.item() * bs
            train_n += bs

            if verbose and log_every and (b % log_every == 0):
                train_loss_avg_so_far = train_loss_sum / max(train_n, 1)
                print(f"[{_ts()}]   epoch={epoch:02d} batch={b:04d} | train_loss_avg={train_loss_avg_so_far:.6f}")

        train_loss_avg = train_loss_sum / max(train_n, 1)

        # -------------------------
        # VALIDATION (MSE)
        # -------------------------
        t0 = time.perf_counter()
        valid_mse = evaluate_mse(model, loaders["valid"], device)
        dt_valid = time.perf_counter() - t0
        dt_epoch = time.perf_counter() - t_epoch

        # -------------------------
        # EARLY STOPPING
        # -------------------------
        improved = valid_mse < (best_valid - 1e-9)
        if improved:
            best_valid = valid_mse
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            bad_epochs = 0
        else:
            bad_epochs += 1

        if verbose:
            flag = "BEST" if improved else f"no_improve({bad_epochs}/{patience})"
            print(
                f"[{_ts()}] epoch={epoch:02d} | train_loss={train_loss_avg:.6f} | "
                f"valid_mse={valid_mse:.6f} | {flag} | dt_valid={dt_valid:.2f}s | dt_epoch={dt_epoch:.2f}s"
            )

        if bad_epochs >= patience:
            if verbose:
                print(f"[{_ts()}] [TRAIN] EARLY STOPPING | patience={patience} | best_valid_mse={best_valid:.6f}")
            break

    if best_state is not None:
        if verbose:
            print(f"[{_ts()}] [TRAIN] Cargando best_state (best_valid_mse={best_valid:.6f}) ...")
        model.load_state_dict(best_state)

    if verbose:
        dt_all = time.perf_counter() - t_global
        print(f"[{_ts()}] [TRAIN] END | best_valid_mse={best_valid:.6f} | dt_total={dt_all:.2f}s")

    return model

In [38]:
#cfg = {"hidden_dims": [256, 128], "dropout": 0.1, "activation": "relu"}
#model = train_mlp(loaders, device=device, in_dim=1200, **cfg)

In [39]:
import numpy as np
import torch

@torch.no_grad()
def predict_mlp(
    model,
    X: np.ndarray,
    *,
    device: torch.device,
    batch_size: int = 32768
) -> np.ndarray:
    """
    Predice con un modelo MLP PyTorch en batches.
    Retorna shape (n_samples,)
    """
    model.eval()

    X = np.asarray(X, dtype=np.float32)
    n = X.shape[0]
    preds = []

    for i in range(0, n, batch_size):
        xb_np = np.ascontiguousarray(X[i : i + batch_size])
        xb = torch.from_numpy(xb_np).to(device, non_blocking=True)

        yb = model(xb).squeeze(-1)  # (batch,)
        preds.append(yb.detach().cpu().numpy())

    return np.concatenate(preds, axis=0)

In [40]:
# ============================================================
# RUN MLP (solo delta_60 + arquitectura tuneable)
# ============================================================
import pandas as pd
import gc
import time

def _ts():
    return time.strftime("%H:%M:%S")


def run_mlp_delta_60(
    window_size: int,
    *,
    hidden_dims: list[int] = [128],
    dropout: float = 0.0,
    activation: str = "relu",
    lr: float = 1e-3,
    weight_decay: float = 1e-4,
    batch_size: int = 16384,
    verbose: bool = True,
) -> pd.DataFrame:

    size = window_size
    n_features = 36
    target = "delta_60"

    if verbose:
        print("\n" + "=" * 90)
        print(
            f"[{_ts()}] MLP | SEQ2ONE | target={target} | L{size} | in_dim={size*n_features} | "
            f"hidden_dims={hidden_dims} | dropout={dropout} | act={activation} | "
            f"lr={lr} | w_decay={weight_decay}"
        )
        print("=" * 90)

    rows = []
    t_global = time.perf_counter()

    # -------------------------
    # BUILD BUNDLE
    # -------------------------
    if verbose:
        print(f"[{_ts()}]   [BUILD] Creando bundle (flatten_X=True) ...")
    t0 = time.perf_counter()

    (bundle,) = create_bundles(
        window_size=size,
        targets=[target],
        windows_paths=windows_paths,
        scalers_paths=scalers_paths,
        flatten_X=True,  # MLP necesita 2D
    )

    if verbose:
        dt = time.perf_counter() - t0
        try:
            xshape = bundle["train"]["X"].shape
            yshape = bundle["train"]["y"].shape
            print(f"[{_ts()}]   [BUILD] OK | train X={xshape} y={yshape} | dt={dt:.2f}s")
        except Exception:
            print(f"[{_ts()}]   [BUILD] OK | dt={dt:.2f}s")

    # -------------------------
    # LOADERS
    # -------------------------
    if verbose:
        print(f"[{_ts()}]   [LOADERS] Creando DataLoaders ...")
    t0 = time.perf_counter()

    loaders = make_loaders_from_bundle(
        bundle,
        batch_size=batch_size,
    )

    if verbose:
        dt = time.perf_counter() - t0
        try:
            ntr = len(loaders["train"].dataset)
            nva = len(loaders["valid"].dataset)
            nte = len(loaders["test"].dataset)
            print(f"[{_ts()}]   [LOADERS] OK | n(train/valid/test)=({ntr}/{nva}/{nte}) | dt={dt:.2f}s")
        except Exception:
            print(f"[{_ts()}]   [LOADERS] OK | dt={dt:.2f}s")

    # -------------------------
    # TRAIN
    # -------------------------
    if verbose:
        print(f"[{_ts()}]   [TRAIN] Iniciando entrenamiento ...")
    t0 = time.perf_counter()

    model = train_mlp(
        loaders,
        in_dim=size * n_features,
        hidden_dims=hidden_dims,
        dropout=dropout,
        activation=activation,
        lr=lr,
        weight_decay=weight_decay,
        max_epochs=30,
        patience=5,
        device=device,
        verbose=verbose,
    )

    if verbose:
        dt = time.perf_counter() - t0
        print(f"[{_ts()}]   [TRAIN] FIN entrenamiento | dt={dt:.2f}s")

    # liberar TRAIN (opcional)
    if verbose:
        print(f"[{_ts()}]   [MEM] Liberando bundle['train'] y gc.collect() ...")
    del bundle["train"]
    gc.collect()

    # -------------------------
    # PRED + METRICS
    # -------------------------
    if verbose:
        print(f"[{_ts()}]   [PRED] Predicciones + métricas (valid/test) ...")
    t0 = time.perf_counter()

    metrics_valid, metrics_test = get_metrics_torch(bundle, model, device=device)

    if verbose:
        dt = time.perf_counter() - t0
        print(f"[{_ts()}]   [METRICS] OK (valid/test) | dt={dt:.2f}s")

    # -------------------------
    # DF APPEND
    # -------------------------
    rows.append(metrics_to_df(
        metrics_valid,
        model="mlp",
        split="valid",
        horizon=bundle["horizon"],
        window_size=bundle["window_size"],
        target=bundle["target"],
    ))

    rows.append(metrics_to_df(
        metrics_test,
        model="mlp",
        split="test",
        horizon=bundle["horizon"],
        window_size=bundle["window_size"],
        target=bundle["target"],
    ))

    df_mlp_metrics = (
        pd.concat(rows, ignore_index=True)
          .sort_values(["window_size", "target", "split", "horizon_min", "model"])
          .reset_index(drop=True)
    )

    # ---- agregar columnas de arquitectura + entrenamiento para tracking ----
    df_mlp_metrics["hidden_dims"] = str(hidden_dims)
    df_mlp_metrics["dropout"] = dropout
    df_mlp_metrics["activation"] = activation
    df_mlp_metrics["lr"] = lr
    df_mlp_metrics["w_decay"] = weight_decay

    if verbose:
        dt_all = time.perf_counter() - t_global
        print(f"[{_ts()}] [DONE] rows={len(df_mlp_metrics)} | dt_total={dt_all:.2f}s")

    # cleanup
    del bundle, model, metrics_valid, metrics_test, loaders
    gc.collect()

    return df_mlp_metrics

In [41]:
# ============================================================
# RUN MLP INCREMENTAL (solo delta_60 + arquitectura tuneable)
# ============================================================
import pandas as pd

def run_mlp_incremental_delta_60(
    window_sizes: list[int],
    *,
    hidden_dims: list[int] = [128],
    dropout: float = 0.0,
    activation: str = "relu",
    lr: float = 1e-3,
    weight_decay: float = 1e-4,
    name: str = "mlp_arch_tuning_delta_60",
    base_dir: str = "/content/drive/MyDrive/neural_profit/metrics/seq2one_metrics",
    verbose: bool = True,
) -> pd.DataFrame:

    # 1) Cargar si existe
    df_all = load_seq2one_metrics_if_exists(name=name, base_dir=base_dir)

    # 2) Esquema mínimo esperado (ahora guardamos arquitectura)
    base_cols = [
        "model","split","window_size","target","horizon_min","MAE","RMSE","R2","DA",
        "hidden_dims","dropout","activation","lr","w_decay"
    ]
    if df_all.empty:
        df_all = pd.DataFrame(columns=base_cols)
    else:
        for c in base_cols:
            if c not in df_all.columns:
                df_all[c] = pd.NA

    # 3) Normalizar tipos
    if len(df_all):
        df_all["window_size"] = pd.to_numeric(df_all["window_size"], errors="coerce").astype("Int64")
        df_all["horizon_min"] = pd.to_numeric(df_all["horizon_min"], errors="coerce").astype("Int64")

    # 4) Keys únicas por config + ws + split/horizon
    hidden_dims_str = str(hidden_dims)
    key_cols = ["model","window_size","target","split","horizon_min","hidden_dims","dropout","activation","lr","w_decay"]

    # 5) Loop por window_size
    for ws in window_sizes:

        df_ws = df_all[
            (df_all["model"] == "mlp") &
            (df_all["window_size"] == ws) &
            (df_all["target"] == "delta_60") &
            (df_all["hidden_dims"] == hidden_dims_str) &
            (df_all["dropout"] == dropout) &
            (df_all["activation"] == activation) &
            (df_all["lr"] == lr) &
            (df_all["w_decay"] == weight_decay)
        ]

        # Esperadas: delta_60 x 2 splits (valid/test) = 2 filas
        if len(df_ws) >= 2:
            if verbose:
                print(f"[SKIP] L{ws}: ya hay {len(df_ws)} filas para esta config (delta_60).")
            continue

        if verbose:
            print("\n" + "="*100)
            print(
                f"[RUN] MLP incremental | target=delta_60 | L{ws} | in_dim={ws*36} | "
                f"hidden_dims={hidden_dims} | dropout={dropout} | act={activation} | "
                f"lr={lr} | w_decay={weight_decay}"
            )
            print("="*100)

        # Entrenar/evaluar para ESTE ws (solo delta_60)
        df_new = run_mlp_delta_60(
            ws,
            hidden_dims=hidden_dims,
            dropout=dropout,
            activation=activation,
            lr=lr,
            weight_decay=weight_decay,
            verbose=verbose,
        ).copy()

        # Anti-duplicados por key
        existing_keys = set(tuple(x) for x in df_all[key_cols].dropna().values)
        mask_keep = [tuple(row) not in existing_keys for row in df_new[key_cols].values]
        df_new = df_new.loc[mask_keep].copy()

        if df_new.empty:
            if verbose:
                print(f"[INFO] L{ws}: no había filas nuevas para agregar.")
            continue

        # Merge + dedupe
        df_all = pd.concat([df_all, df_new], ignore_index=True)
        df_all = df_all.drop_duplicates(subset=key_cols, keep="last").reset_index(drop=True)

        # Guardar checkpoint
        save_seq2one_metrics(df_all, name=name, base_dir=base_dir)

        if verbose:
            print(f"[OK] Checkpoint guardado. Total rows={len(df_all)}")

    return df_all

### **13.2. Ejecución de tuning**

In [42]:
# ============================================================
# ARCH_GRID: solo arquitectura (tuning controlado)
# ============================================================
ARCH_GRID = [
    # 1 capa (baseline y variantes)
    {"hidden_dims": [64],  "dropout": 0.0, "activation": "relu"},
    {"hidden_dims": [128], "dropout": 0.0, "activation": "relu"},  # baseline
    {"hidden_dims": [256], "dropout": 0.0, "activation": "relu"},
    {"hidden_dims": [512], "dropout": 0.0, "activation": "relu"},

    # 1 capa + dropout
    {"hidden_dims": [128], "dropout": 0.1, "activation": "relu"},
    {"hidden_dims": [256], "dropout": 0.1, "activation": "relu"},
    {"hidden_dims": [256], "dropout": 0.2, "activation": "relu"},

    # 2 capas
    {"hidden_dims": [128, 64],   "dropout": 0.0, "activation": "relu"},
    {"hidden_dims": [256, 128],  "dropout": 0.0, "activation": "relu"},
    {"hidden_dims": [256, 128],  "dropout": 0.1, "activation": "relu"},

    # (opcional) activación alternativa
    {"hidden_dims": [256], "dropout": 0.1, "activation": "gelu"},
]

In [43]:
# ============================================================
# TUNING RUNNER: recorre ARCH_GRID y ejecuta incremental por config
# ============================================================
import time
import pandas as pd

def _ts():
    return time.strftime("%H:%M:%S")


def run_mlp_arch_tuning_delta_60(
    window_sizes: list[int],
    *,
    arch_grid: list[dict],
    lr: float = 1e-3,                 # fijo en tuning de arquitectura
    weight_decay: float = 1e-4,       # fijo en tuning de arquitectura
    base_name: str = "mlp_arch_tuning_delta_60",
    base_dir: str = "/content/drive/MyDrive/neural_profit/metrics/seq2one_metrics",
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Recorre un grid de arquitecturas y ejecuta:
      run_mlp_incremental_delta_60(window_sizes, hidden_dims, dropout, activation, lr, weight_decay)

    Guarda checkpoints incrementales por config (name único por arquitectura).
    Retorna el último df_all cargado/guardado (del último config).
    """
    last_df = pd.DataFrame()

    for k, cfg in enumerate(arch_grid, start=1):
        hidden_dims = cfg["hidden_dims"]
        dropout = float(cfg.get("dropout", 0.0))
        activation = cfg.get("activation", "relu")

        # name único por arquitectura (para no mezclar resultados)
        arch_tag = f"hd={'-'.join(map(str, hidden_dims))}_do={dropout}_act={activation}"
        name = f"{base_name}__{arch_tag}"

        if verbose:
            print("\n" + "=" * 110)
            print(f"[{_ts()}] [{k}/{len(arch_grid)}] ARCH TUNING | {arch_tag} | lr={lr} | w_decay={weight_decay}")
            print("=" * 110)

        last_df = run_mlp_incremental_delta_60(
            window_sizes,
            hidden_dims=hidden_dims,
            dropout=dropout,
            activation=activation,
            lr=lr,
            weight_decay=weight_decay,
            name=name,
            base_dir=base_dir,
            verbose=verbose,
        )

    return last_df

In [44]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda

In [46]:
import pandas as pd

def run_mlp_incremental_delta_60_onefile(
    window_sizes: list[int],
    arch_grid: list[dict],
    *,
    lr: float = 1e-3,
    weight_decay: float = 1e-4,
    name: str = "mlp_arch_tuning_delta_60_all",  # <-- UN SOLO DATASET
    base_dir: str = "/content/drive/MyDrive/neural_profit/metrics/seq2one_metrics",
    verbose: bool = True,
) -> pd.DataFrame:

    # 1) Cargar si existe
    df_all = load_seq2one_metrics_if_exists(name=name, base_dir=base_dir)

    # 2) Esquema esperado (incluye arquitectura)
    cols = [
        "model","split","window_size","target","horizon_min","MAE","RMSE","R2","DA",
        "hidden_dims","dropout","activation","lr","w_decay"
    ]
    if df_all.empty:
        df_all = pd.DataFrame(columns=cols)
    else:
        for c in cols:
            if c not in df_all.columns:
                df_all[c] = pd.NA

    # 3) Normalizar tipos
    if len(df_all):
        df_all["window_size"] = pd.to_numeric(df_all["window_size"], errors="coerce").astype("Int64")
        df_all["horizon_min"] = pd.to_numeric(df_all["horizon_min"], errors="coerce").astype("Int64")

    # 4) Key única por corrida (incluye hiperparams)
    key_cols = ["model","window_size","target","split","horizon_min","hidden_dims","dropout","activation","lr","w_decay"]

    # 5) Loop por arquitectura y window_size
    for k, cfg in enumerate(arch_grid, start=1):
        hidden_dims = cfg["hidden_dims"]
        dropout = float(cfg.get("dropout", 0.0))
        activation = cfg.get("activation", "relu")
        hidden_dims_str = str(hidden_dims)

        if verbose:
            print("\n" + "=" * 110)
            print(f"[{_ts()}] [{k}/{len(arch_grid)}] ARCH | hidden_dims={hidden_dims} | dropout={dropout} | act={activation}")
            print("=" * 110)

        for ws in window_sizes:

            # Esperadas: delta_60 x 2 splits (valid/test) = 2 filas
            df_ws = df_all[
                (df_all["model"] == "mlp") &
                (df_all["target"] == "delta_60") &
                (df_all["window_size"] == ws) &
                (df_all["hidden_dims"] == hidden_dims_str) &
                (df_all["dropout"] == dropout) &
                (df_all["activation"] == activation) &
                (df_all["lr"] == lr) &
                (df_all["w_decay"] == weight_decay)
            ]

            if len(df_ws) >= 2:
                if verbose:
                    print(f"[SKIP] L{ws}: ya existen valid+test para esta config.")
                continue

            if verbose:
                print("\n" + "-" * 90)
                print(f"[RUN] target=delta_60 | L{ws} | in_dim={ws*36} | hidden_dims={hidden_dims} | dropout={dropout} | act={activation}")
                print("-" * 90)

            # Entrenar/evaluar ESTE ws con ESTA arquitectura
            df_new = run_mlp_delta_60(
                ws,
                hidden_dims=hidden_dims,
                dropout=dropout,
                activation=activation,
                lr=lr,
                weight_decay=weight_decay,
                verbose=verbose,
            ).copy()

            # Anti-duplicados por key
            existing_keys = set(tuple(x) for x in df_all[key_cols].dropna().values)
            mask_keep = [tuple(row) not in existing_keys for row in df_new[key_cols].values]
            df_new = df_new.loc[mask_keep].copy()

            if df_new.empty:
                if verbose:
                    print(f"[INFO] L{ws}: no hubo filas nuevas para agregar.")
                continue

            # Merge + dedupe
            df_all = pd.concat([df_all, df_new], ignore_index=True)
            df_all = df_all.drop_duplicates(subset=key_cols, keep="last").reset_index(drop=True)

            # Guardar SIEMPRE al mismo archivo
            save_seq2one_metrics(df_all, name=name, base_dir=base_dir)

            if verbose:
                print(f"[OK] Guardado incremental (1 archivo). Total rows={len(df_all)}")

    return df_all

In [47]:
window_sizes = [60, 180]

df_all = run_mlp_incremental_delta_60_onefile(
    window_sizes,
    ARCH_GRID,
    lr=1e-3,
    weight_decay=1e-4,
    name="mlp_arch_tuning_delta_60_all",
    base_dir="/content/drive/MyDrive/neural_profit/metrics/seq2one_metrics",
    verbose=True,
)

==============================================================================================================
[15:38:53] [1/11] ARCH | hidden_dims=[64] | dropout=0.0 | act=relu
==============================================================================================================

------------------------------------------------------------------------------------------
[RUN] target=delta_60 | L60 | in_dim=2160 | hidden_dims=[64] | dropout=0.0 | act=relu
------------------------------------------------------------------------------------------

==========================================================================================
[15:38:53] MLP | SEQ2ONE | target=delta_60 | L60 | in_dim=2160 | hidden_dims=[64] | dropout=0.0 | act=relu | lr=0.001 | w_decay=0.0001
==========================================================================================
[15:38:53]   [BUILD] Creando bundle (flatten_X=True) ...
H60 Train: (330144, 2160) (330144,)
H60 Valid: (70590, 2160) (70590,)
H60 Test : (70952, 2160) (70952,)
Scaler H60: StandardScaler
[15:39:03]   [BUILD] OK | train X=(330144, 2160) y=(330144,) | dt=9.48s
[15:39:03]   [LOADERS] Creando DataLoaders ...
[15:39:03]   [LOADERS] OK | n(train/valid/test)=(330144/70590/70952) | dt=0.00s
[15:39:03]   [TRAIN] Iniciando entrenamiento ...
[15:39:03] [TRAIN] START | in_dim=2160 hidden_dims=[64] dropout=0.0 activation=relu lr=0.001 wd=0.0001 max_epochs=30 patience=5 device=cuda
[15:39:09] epoch=01 | train_loss=3063.329338 | valid_mse=2443.758493 | BEST | dt_valid=1.16s | dt_epoch=6.51s
[15:39:16] epoch=02 | train_loss=2532.070100 | valid_mse=2166.597138 | BEST | dt_valid=1.16s | dt_epoch=6.56s
[15:39:22] epoch=03 | train_loss=2335.568585 | valid_mse=2024.511347 | BEST | dt_valid=1.18s | dt_epoch=6.57s
[15:39:29] epoch=04 | train_loss=2256.814212 | valid_mse=1977.687293 | BEST | dt_valid=1.18s | dt_epoch=6.61s
[15:39:35] epoch=05 | train_loss=2196.123615 | valid_mse=1902.236237 | BEST | dt_valid=1.15s | dt_epoch=6.50s
[15:39:42] epoch=06 | train_loss=2144.034105 | valid_mse=1871.175152 | BEST | dt_valid=1.18s | dt_epoch=6.60s
[15:39:48] epoch=07 | train_loss=2101.938833 | valid_mse=1830.347018 | BEST | dt_valid=1.18s | dt_epoch=6.58s
[15:39:55] epoch=08 | train_loss=2065.580692 | valid_mse=1795.544383 | BEST | dt_valid=1.18s | dt_epoch=6.69s
[15:40:02] epoch=09 | train_loss=2032.377254 | valid_mse=1766.684120 | BEST | dt_valid=1.04s | dt_epoch=6.65s
[15:40:08] epoch=10 | train_loss=2001.686189 | valid_mse=1744.233093 | BEST | dt_valid=1.17s | dt_epoch=6.63s
[15:40:15] epoch=11 | train_loss=1972.702478 | valid_mse=1716.423148 | BEST | dt_valid=1.20s | dt_epoch=6.66s
[15:40:22] epoch=12 | train_loss=1944.792012 | valid_mse=1696.419266 | BEST | dt_valid=1.20s | dt_epoch=6.68s
[15:40:28] epoch=13 | train_loss=1917.301147 | valid_mse=1678.832441 | BEST | dt_valid=1.19s | dt_epoch=6.63s
[15:40:35] epoch=14 | train_loss=1890.846831 | valid_mse=1665.305794 | BEST | dt_valid=1.18s | dt_epoch=6.58s
[15:40:42] epoch=15 | train_loss=1868.904288 | valid_mse=1637.307069 | BEST | dt_valid=1.20s | dt_epoch=6.66s
[15:40:48] epoch=16 | train_loss=1843.737073 | valid_mse=1613.960377 | BEST | dt_valid=1.18s | dt_epoch=6.60s
[15:40:55] epoch=17 | train_loss=1822.386416 | valid_mse=1597.961298 | BEST | dt_valid=1.17s | dt_epoch=6.64s
[15:41:02] epoch=18 | train_loss=1801.966151 | valid_mse=1587.406049 | BEST | dt_valid=1.18s | dt_epoch=6.66s
[15:41:08] epoch=19 | train_loss=1783.464876 | valid_mse=1559.876101 | BEST | dt_valid=1.19s | dt_epoch=6.60s
[15:41:15] epoch=20 | train_loss=1765.744788 | valid_mse=1544.070222 | BEST | dt_valid=1.18s | dt_epoch=6.60s
[15:41:21] epoch=21 | train_loss=1748.157157 | valid_mse=1532.479091 | BEST | dt_valid=1.18s | dt_epoch=6.66s
[15:41:28] epoch=22 | train_loss=1732.498580 | valid_mse=1537.038136 | no_improve(1/5) | dt_valid=1.19s | dt_epoch=6.59s
[15:41:34] epoch=23 | train_loss=1718.243156 | valid_mse=1516.388624 | BEST | dt_valid=1.01s | dt_epoch=6.47s
[15:41:41] epoch=24 | train_loss=1703.052769 | valid_mse=1503.415512 | BEST | dt_valid=1.20s | dt_epoch=6.58s
[15:41:48] epoch=25 | train_loss=1688.774167 | valid_mse=1505.027228 | no_improve(1/5) | dt_valid=1.18s | dt_epoch=6.63s
[15:41:54] epoch=26 | train_loss=1676.044703 | valid_mse=1485.760108 | BEST | dt_valid=1.17s | dt_epoch=6.56s
[15:42:01] epoch=27 | train_loss=1662.425143 | valid_mse=1472.225372 | BEST | dt_valid=1.18s | dt_epoch=6.61s
[15:42:07] epoch=28 | train_loss=1649.776939 | valid_mse=1467.561510 | BEST | dt_valid=1.20s | dt_epoch=6.62s
[15:42:14] epoch=29 | train_loss=1638.810815 | valid_mse=1451.236733 | BEST | dt_valid=1.18s | dt_epoch=6.62s
[15:42:21] epoch=30 | train_loss=1629.324365 | valid_mse=1443.650772 | BEST | dt_valid=1.19s | dt_epoch=6.63s
[15:42:21] [TRAIN] Cargando best_state (best_valid_mse=1443.650772) ...
[15:42:21] [TRAIN] END | best_valid_mse=1443.650772 | dt_total=198.19s
[15:42:21]   [TRAIN] FIN entrenamiento | dt=198.19s
[15:42:21]   [MEM] Liberando bundle['train'] y gc.collect() ...
[15:42:21]   [PRED] Predicciones + métricas (valid/test) ...
[15:42:21]   [METRICS] OK (valid/test) | dt=0.27s
[15:42:21] [DONE] rows=2 | dt_total=208.11s
[OK] Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics/seq2one_metrics/seq2one_mlp_arch_tuning_delta_60_all_metrics.parquet
[OK] Guardado incremental (1 archivo). Total rows=2

------------------------------------------------------------------------------------------
[RUN] target=delta_60 | L180 | in_dim=6480 | hidden_dims=[64] | dropout=0.0 | act=relu
------------------------------------------------------------------------------------------

==========================================================================================
[15:42:21] MLP | SEQ2ONE | target=delta_60 | L180 | in_dim=6480 | hidden_dims=[64] | dropout=0.0 | act=relu | lr=0.001 | w_decay=0.0001
==========================================================================================
[15:42:21]   [BUILD] Creando bundle (flatten_X=True) ...

/tmp/ipython-input-723513373.py:95: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all = pd.concat([df_all, df_new], ignore_index=True)

H60 Train: (220704, 6480) (220704,)
H60 Valid: (47190, 6480) (47190,)
H60 Test : (47432, 6480) (47432,)
Scaler H60: StandardScaler
[15:42:40]   [BUILD] OK | train X=(220704, 6480) y=(220704,) | dt=18.36s
[15:42:40]   [LOADERS] Creando DataLoaders ...
[15:42:40]   [LOADERS] OK | n(train/valid/test)=(220704/47190/47432) | dt=0.00s
[15:42:40]   [TRAIN] Iniciando entrenamiento ...
[15:42:40] [TRAIN] START | in_dim=6480 hidden_dims=[64] dropout=0.0 activation=relu lr=0.001 wd=0.0001 max_epochs=30 patience=5 device=cuda
[15:42:47] epoch=01 | train_loss=3521.184638 | valid_mse=2801.498623 | BEST | dt_valid=1.27s | dt_epoch=7.36s
[15:42:54] epoch=02 | train_loss=2847.599943 | valid_mse=2281.132359 | BEST | dt_valid=1.27s | dt_epoch=7.37s
[15:43:02] epoch=03 | train_loss=2515.380330 | valid_mse=2132.272897 | BEST | dt_valid=1.28s | dt_epoch=7.51s
[15:43:09] epoch=04 | train_loss=2323.981159 | valid_mse=2020.758084 | BEST | dt_valid=1.46s | dt_epoch=7.50s
[15:43:17] epoch=05 | train_loss=2211.010310 | valid_mse=1934.294978 | BEST | dt_valid=1.27s | dt_epoch=7.35s
[15:43:24] epoch=06 | train_loss=2130.487100 | valid_mse=1871.510701 | BEST | dt_valid=1.28s | dt_epoch=7.55s
[15:43:32] epoch=07 | train_loss=2068.640689 | valid_mse=1816.653528 | BEST | dt_valid=1.44s | dt_epoch=7.51s
[15:43:39] epoch=08 | train_loss=2015.473632 | valid_mse=1769.758296 | BEST | dt_valid=1.26s | dt_epoch=7.30s
[15:43:47] epoch=09 | train_loss=1969.340059 | valid_mse=1734.250477 | BEST | dt_valid=1.27s | dt_epoch=7.49s
[15:43:54] epoch=10 | train_loss=1931.029217 | valid_mse=1710.227167 | BEST | dt_valid=1.28s | dt_epoch=7.37s
[15:44:02] epoch=11 | train_loss=1892.679150 | valid_mse=1695.319178 | BEST | dt_valid=1.26s | dt_epoch=7.48s
[15:44:09] epoch=12 | train_loss=1858.250013 | valid_mse=1652.450604 | BEST | dt_valid=1.43s | dt_epoch=7.39s
[15:44:16] epoch=13 | train_loss=1824.301923 | valid_mse=1622.603391 | BEST | dt_valid=1.27s | dt_epoch=7.34s
[15:44:24] epoch=14 | train_loss=1794.726741 | valid_mse=1603.620725 | BEST | dt_valid=1.27s | dt_epoch=7.53s
[15:44:31] epoch=15 | train_loss=1762.454902 | valid_mse=1581.017673 | BEST | dt_valid=1.29s | dt_epoch=7.37s
[15:44:39] epoch=16 | train_loss=1733.742744 | valid_mse=1561.766624 | BEST | dt_valid=1.30s | dt_epoch=7.64s
[15:44:46] epoch=17 | train_loss=1704.768008 | valid_mse=1539.614537 | BEST | dt_valid=1.46s | dt_epoch=7.55s
[15:44:54] epoch=18 | train_loss=1677.134156 | valid_mse=1519.250752 | BEST | dt_valid=1.29s | dt_epoch=7.45s
[15:45:01] epoch=19 | train_loss=1650.057758 | valid_mse=1506.966306 | BEST | dt_valid=1.30s | dt_epoch=7.67s
[15:45:09] epoch=20 | train_loss=1621.807276 | valid_mse=1490.125599 | BEST | dt_valid=1.28s | dt_epoch=7.35s
[15:45:16] epoch=21 | train_loss=1595.778603 | valid_mse=1462.552914 | BEST | dt_valid=1.29s | dt_epoch=7.60s
[15:45:24] epoch=22 | train_loss=1571.455325 | valid_mse=1446.012799 | BEST | dt_valid=1.48s | dt_epoch=7.57s
[15:45:31] epoch=23 | train_loss=1548.725329 | valid_mse=1443.188260 | BEST | dt_valid=1.30s | dt_epoch=7.45s
[15:45:39] epoch=24 | train_loss=1530.998616 | valid_mse=1443.565247 | no_improve(1/5) | dt_valid=1.29s | dt_epoch=7.63s
[15:45:46] epoch=25 | train_loss=1511.263880 | valid_mse=1406.750201 | BEST | dt_valid=1.29s | dt_epoch=7.41s
[15:45:54] epoch=26 | train_loss=1491.967537 | valid_mse=1398.366349 | BEST | dt_valid=1.29s | dt_epoch=7.59s
[15:46:02] epoch=27 | train_loss=1471.366520 | valid_mse=1372.860903 | BEST | dt_valid=1.45s | dt_epoch=7.59s
[15:46:09] epoch=28 | train_loss=1453.889228 | valid_mse=1356.322356 | BEST | dt_valid=1.29s | dt_epoch=7.41s
[15:46:17] epoch=29 | train_loss=1436.975944 | valid_mse=1352.460479 | BEST | dt_valid=1.30s | dt_epoch=7.63s
[15:46:24] epoch=30 | train_loss=1422.757051 | valid_mse=1337.045624 | BEST | dt_valid=1.29s | dt_epoch=7.42s
[15:46:24] [TRAIN] Cargando best_state (best_valid_mse=1337.045624) ...
[15:46:24] [TRAIN] END | best_valid_mse=1337.045624 | dt_total=224.40s
[15:46:24]   [TRAIN] FIN entrenamiento | dt=224.40s
[15:46:24]   [MEM] Liberando bundle['train'] y gc.collect() ...
[15:46:24]   [PRED] Predicciones + métricas (valid/test) ...
[15:46:25]   [METRICS] OK (valid/test) | dt=0.54s
[15:46:25] [DONE] rows=2 | dt_total=243.47s
[OK] Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics/seq2one_metrics/seq2one_mlp_arch_tuning_delta_60_all_metrics.parquet
[OK] Guardado incremental (1 archivo). Total rows=4

==============================================================================================================
[15:46:25] [2/11] ARCH | hidden_dims=[128] | dropout=0.0 | act=relu
==============================================================================================================

------------------------------------------------------------------------------------------
[RUN] target=delta_60 | L60 | in_dim=2160 | hidden_dims=[128] | dropout=0.0 | act=relu
------------------------------------------------------------------------------------------

==========================================================================================
[15:46:25] MLP | SEQ2ONE | target=delta_60 | L60 | in_dim=2160 | hidden_dims=[128] | dropout=0.0 | act=relu | lr=0.001 | w_decay=0.0001
==========================================================================================
[15:46:25]   [BUILD] Creando bundle (flatten_X=True) ...
H60 Train: (330144, 2160) (330144,)
H60 Valid: (70590, 2160) (70590,)
H60 Test : (70952, 2160) (70952,)
Scaler H60: StandardScaler
[15:46:34]   [BUILD] OK | train X=(330144, 2160) y=(330144,) | dt=9.34s
[15:46:34]   [LOADERS] Creando DataLoaders ...
[15:46:34]   [LOADERS] OK | n(train/valid/test)=(330144/70590/70952) | dt=0.00s
[15:46:34]   [TRAIN] Iniciando entrenamiento ...
[15:46:34] [TRAIN] START | in_dim=2160 hidden_dims=[128] dropout=0.0 activation=relu lr=0.001 wd=0.0001 max_epochs=30 patience=5 device=cuda
[15:46:41] epoch=01 | train_loss=3011.031781 | valid_mse=2319.266723 | BEST | dt_valid=1.03s | dt_epoch=6.51s
[15:46:48] epoch=02 | train_loss=2447.799220 | valid_mse=2082.921660 | BEST | dt_valid=1.21s | dt_epoch=6.73s
[15:46:54] epoch=03 | train_loss=2279.572404 | valid_mse=1964.739708 | BEST | dt_valid=1.19s | dt_epoch=6.69s
[15:47:01] epoch=04 | train_loss=2194.667958 | valid_mse=1883.013940 | BEST | dt_valid=1.20s | dt_epoch=6.73s
[15:47:08] epoch=05 | train_loss=2128.752908 | valid_mse=1823.142796 | BEST | dt_valid=1.19s | dt_epoch=6.67s
[15:47:14] epoch=06 | train_loss=2076.925345 | valid_mse=1786.164273 | BEST | dt_valid=1.20s | dt_epoch=6.71s
[15:47:21] epoch=07 | train_loss=2032.058526 | valid_mse=1749.104916 | BEST | dt_valid=1.19s | dt_epoch=6.67s
[15:47:28] epoch=08 | train_loss=1991.167551 | valid_mse=1724.024564 | BEST | dt_valid=1.21s | dt_epoch=6.69s
[15:47:34] epoch=09 | train_loss=1952.798308 | valid_mse=1699.501771 | BEST | dt_valid=1.19s | dt_epoch=6.63s
[15:47:41] epoch=10 | train_loss=1915.338230 | valid_mse=1679.373254 | BEST | dt_valid=1.20s | dt_epoch=6.68s
[15:47:48] epoch=11 | train_loss=1882.069277 | valid_mse=1641.050432 | BEST | dt_valid=1.02s | dt_epoch=6.45s
[15:47:54] epoch=12 | train_loss=1851.254852 | valid_mse=1616.103357 | BEST | dt_valid=1.19s | dt_epoch=6.83s
[15:48:01] epoch=13 | train_loss=1820.232404 | valid_mse=1583.128828 | BEST | dt_valid=1.19s | dt_epoch=6.66s
[15:48:08] epoch=14 | train_loss=1793.233637 | valid_mse=1558.591798 | BEST | dt_valid=1.02s | dt_epoch=6.52s
[15:48:14] epoch=15 | train_loss=1769.038423 | valid_mse=1542.062148 | BEST | dt_valid=1.21s | dt_epoch=6.72s
[15:48:21] epoch=16 | train_loss=1745.572453 | valid_mse=1522.565576 | BEST | dt_valid=1.20s | dt_epoch=6.71s
[15:48:28] epoch=17 | train_loss=1724.524268 | valid_mse=1503.593583 | BEST | dt_valid=1.20s | dt_epoch=6.68s
[15:48:34] epoch=18 | train_loss=1705.558544 | valid_mse=1481.511177 | BEST | dt_valid=1.19s | dt_epoch=6.64s
[15:48:41] epoch=19 | train_loss=1687.942083 | valid_mse=1465.520003 | BEST | dt_valid=1.19s | dt_epoch=6.67s
[15:48:48] epoch=20 | train_loss=1668.481627 | valid_mse=1449.680875 | BEST | dt_valid=1.18s | dt_epoch=6.66s
[15:48:54] epoch=21 | train_loss=1651.181002 | valid_mse=1441.564613 | BEST | dt_valid=1.19s | dt_epoch=6.66s
[15:49:01] epoch=22 | train_loss=1636.171992 | valid_mse=1425.604207 | BEST | dt_valid=1.20s | dt_epoch=6.67s
[15:49:08] epoch=23 | train_loss=1620.873578 | valid_mse=1434.111064 | no_improve(1/5) | dt_valid=1.20s | dt_epoch=6.69s
[15:49:14] epoch=24 | train_loss=1607.861959 | valid_mse=1417.476526 | BEST | dt_valid=1.05s | dt_epoch=6.55s
[15:49:21] epoch=25 | train_loss=1595.364874 | valid_mse=1414.279289 | BEST | dt_valid=1.18s | dt_epoch=6.81s
[15:49:28] epoch=26 | train_loss=1583.593317 | valid_mse=1398.156524 | BEST | dt_valid=1.21s | dt_epoch=6.64s
[15:49:34] epoch=27 | train_loss=1574.254713 | valid_mse=1390.933135 | BEST | dt_valid=1.01s | dt_epoch=6.48s
[15:49:41] epoch=28 | train_loss=1562.084808 | valid_mse=1391.786641 | no_improve(1/5) | dt_valid=1.21s | dt_epoch=6.66s
[15:49:47] epoch=29 | train_loss=1552.246400 | valid_mse=1386.773226 | BEST | dt_valid=1.19s | dt_epoch=6.67s
[15:49:54] epoch=30 | train_loss=1544.507171 | valid_mse=1406.225995 | no_improve(1/5) | dt_valid=1.19s | dt_epoch=6.68s
[15:49:54] [TRAIN] Cargando best_state (best_valid_mse=1386.773226) ...
[15:49:54] [TRAIN] END | best_valid_mse=1386.773226 | dt_total=199.78s
[15:49:54]   [TRAIN] FIN entrenamiento | dt=199.78s
[15:49:54]   [MEM] Liberando bundle['train'] y gc.collect() ...
[15:49:54]   [PRED] Predicciones + métricas (valid/test) ...
[15:49:55]   [METRICS] OK (valid/test) | dt=0.27s
[15:49:55] [DONE] rows=2 | dt_total=209.55s
[OK] Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics/seq2one_metrics/seq2one_mlp_arch_tuning_delta_60_all_metrics.parquet
[OK] Guardado incremental (1 archivo). Total rows=6

------------------------------------------------------------------------------------------
[RUN] target=delta_60 | L180 | in_dim=6480 | hidden_dims=[128] | dropout=0.0 | act=relu
------------------------------------------------------------------------------------------

==========================================================================================
[15:49:55] MLP | SEQ2ONE | target=delta_60 | L180 | in_dim=6480 | hidden_dims=[128] | dropout=0.0 | act=relu | lr=0.001 | w_decay=0.0001
==========================================================================================
[15:49:55]   [BUILD] Creando bundle (flatten_X=True) ...
H60 Train: (220704, 6480) (220704,)
H60 Valid: (47190, 6480) (47190,)
H60 Test : (47432, 6480) (47432,)
Scaler H60: StandardScaler
[15:50:13]   [BUILD] OK | train X=(220704, 6480) y=(220704,) | dt=18.29s
[15:50:13]   [LOADERS] Creando DataLoaders ...
[15:50:13]   [LOADERS] OK | n(train/valid/test)=(220704/47190/47432) | dt=0.00s
[15:50:13]   [TRAIN] Iniciando entrenamiento ...
[15:50:13] [TRAIN] START | in_dim=6480 hidden_dims=[128] dropout=0.0 activation=relu lr=0.001 wd=0.0001 max_epochs=30 patience=5 device=cuda
[15:50:20] epoch=01 | train_loss=3380.773060 | valid_mse=2576.071202 | BEST | dt_valid=1.27s | dt_epoch=7.40s
[15:50:28] epoch=02 | train_loss=2703.743735 | valid_mse=2146.945709 | BEST | dt_valid=1.26s | dt_epoch=7.43s
[15:50:35] epoch=03 | train_loss=2380.801237 | valid_mse=2050.525154 | BEST | dt_valid=1.28s | dt_epoch=7.57s
[15:50:43] epoch=04 | train_loss=2208.600499 | valid_mse=1885.489299 | BEST | dt_valid=1.30s | dt_epoch=7.35s
[15:50:50] epoch=05 | train_loss=2092.651076 | valid_mse=1789.165628 | BEST | dt_valid=1.28s | dt_epoch=7.58s
[15:50:58] epoch=06 | train_loss=2005.335606 | valid_mse=1717.766815 | BEST | dt_valid=1.42s | dt_epoch=7.50s
[15:51:05] epoch=07 | train_loss=1934.943824 | valid_mse=1663.679212 | BEST | dt_valid=1.28s | dt_epoch=7.30s
[15:51:13] epoch=08 | train_loss=1878.038681 | valid_mse=1636.920576 | BEST | dt_valid=1.28s | dt_epoch=7.59s
[15:51:20] epoch=09 | train_loss=1824.336162 | valid_mse=1598.900021 | BEST | dt_valid=1.26s | dt_epoch=7.39s
[15:51:28] epoch=10 | train_loss=1775.781828 | valid_mse=1563.077093 | BEST | dt_valid=1.27s | dt_epoch=7.44s
[15:51:35] epoch=11 | train_loss=1724.854180 | valid_mse=1530.963128 | BEST | dt_valid=1.42s | dt_epoch=7.54s
[15:51:42] epoch=12 | train_loss=1681.464274 | valid_mse=1503.165501 | BEST | dt_valid=1.30s | dt_epoch=7.31s
[15:51:50] epoch=13 | train_loss=1643.084002 | valid_mse=1482.992922 | BEST | dt_valid=1.29s | dt_epoch=7.60s
[15:51:57] epoch=14 | train_loss=1606.796683 | valid_mse=1456.502734 | BEST | dt_valid=1.28s | dt_epoch=7.43s
[15:52:05] epoch=15 | train_loss=1572.022847 | valid_mse=1424.080441 | BEST | dt_valid=1.28s | dt_epoch=7.55s
[15:52:13] epoch=16 | train_loss=1539.071788 | valid_mse=1404.119432 | BEST | dt_valid=1.44s | dt_epoch=7.58s
[15:52:20] epoch=17 | train_loss=1509.296725 | valid_mse=1389.069400 | BEST | dt_valid=1.28s | dt_epoch=7.41s
[15:52:28] epoch=18 | train_loss=1483.472427 | valid_mse=1365.850180 | BEST | dt_valid=1.28s | dt_epoch=7.53s
[15:52:35] epoch=19 | train_loss=1457.690271 | valid_mse=1357.450328 | BEST | dt_valid=1.28s | dt_epoch=7.42s
[15:52:42] epoch=20 | train_loss=1435.578922 | valid_mse=1336.067811 | BEST | dt_valid=1.26s | dt_epoch=7.43s
[15:52:50] epoch=21 | train_loss=1414.021391 | valid_mse=1327.053147 | BEST | dt_valid=1.44s | dt_epoch=7.56s
[15:52:57] epoch=22 | train_loss=1395.235946 | valid_mse=1318.815936 | BEST | dt_valid=1.29s | dt_epoch=7.41s
[15:53:05] epoch=23 | train_loss=1377.437089 | valid_mse=1303.327463 | BEST | dt_valid=1.26s | dt_epoch=7.48s
[15:53:12] epoch=24 | train_loss=1365.125425 | valid_mse=1294.441577 | BEST | dt_valid=1.29s | dt_epoch=7.36s
[15:53:20] epoch=25 | train_loss=1342.765865 | valid_mse=1280.860140 | BEST | dt_valid=1.28s | dt_epoch=7.54s
[15:53:27] epoch=26 | train_loss=1329.942795 | valid_mse=1276.120301 | BEST | dt_valid=1.44s | dt_epoch=7.56s
[15:53:35] epoch=27 | train_loss=1317.893995 | valid_mse=1275.349184 | BEST | dt_valid=1.25s | dt_epoch=7.36s
[15:53:42] epoch=28 | train_loss=1303.032037 | valid_mse=1260.795508 | BEST | dt_valid=1.26s | dt_epoch=7.45s
[15:53:50] epoch=29 | train_loss=1290.770429 | valid_mse=1259.955838 | BEST | dt_valid=1.28s | dt_epoch=7.39s
[15:53:57] epoch=30 | train_loss=1276.332771 | valid_mse=1245.661962 | BEST | dt_valid=1.28s | dt_epoch=7.54s
[15:53:57] [TRAIN] Cargando best_state (best_valid_mse=1245.661962) ...
[15:53:57] [TRAIN] END | best_valid_mse=1245.661962 | dt_total=224.03s
[15:53:57]   [TRAIN] FIN entrenamiento | dt=224.03s
[15:53:57]   [MEM] Liberando bundle['train'] y gc.collect() ...
[15:53:57]   [PRED] Predicciones + métricas (valid/test) ...
[15:53:58]   [METRICS] OK (valid/test) | dt=0.54s
[15:53:58] [DONE] rows=2 | dt_total=243.02s
[OK] Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics/seq2one_metrics/seq2one_mlp_arch_tuning_delta_60_all_metrics.parquet
[OK] Guardado incremental (1 archivo). Total rows=8

==============================================================================================================
[15:53:58] [3/11] ARCH | hidden_dims=[256] | dropout=0.0 | act=relu
==============================================================================================================

------------------------------------------------------------------------------------------
[RUN] target=delta_60 | L60 | in_dim=2160 | hidden_dims=[256] | dropout=0.0 | act=relu
------------------------------------------------------------------------------------------

==========================================================================================
[15:53:58] MLP | SEQ2ONE | target=delta_60 | L60 | in_dim=2160 | hidden_dims=[256] | dropout=0.0 | act=relu | lr=0.001 | w_decay=0.0001
==========================================================================================
[15:53:58]   [BUILD] Creando bundle (flatten_X=True) ...
H60 Train: (330144, 2160) (330144,)
H60 Valid: (70590, 2160) (70590,)
H60 Test : (70952, 2160) (70952,)
Scaler H60: StandardScaler
[15:54:07]   [BUILD] OK | train X=(330144, 2160) y=(330144,) | dt=9.38s
[15:54:07]   [LOADERS] Creando DataLoaders ...
[15:54:07]   [LOADERS] OK | n(train/valid/test)=(330144/70590/70952) | dt=0.00s
[15:54:07]   [TRAIN] Iniciando entrenamiento ...
[15:54:07] [TRAIN] START | in_dim=2160 hidden_dims=[256] dropout=0.0 activation=relu lr=0.001 wd=0.0001 max_epochs=30 patience=5 device=cuda
[15:54:14] epoch=01 | train_loss=2909.902845 | valid_mse=2193.496473 | BEST | dt_valid=1.02s | dt_epoch=6.54s
[15:54:21] epoch=02 | train_loss=2350.288140 | valid_mse=1966.209888 | BEST | dt_valid=1.19s | dt_epoch=6.67s
[15:54:27] epoch=03 | train_loss=2206.898969 | valid_mse=1876.645587 | BEST | dt_valid=1.18s | dt_epoch=6.66s
[15:54:34] epoch=04 | train_loss=2116.169181 | valid_mse=1801.400963 | BEST | dt_valid=1.18s | dt_epoch=6.62s
[15:54:41] epoch=05 | train_loss=2048.573155 | valid_mse=1752.314322 | BEST | dt_valid=1.19s | dt_epoch=6.68s
[15:54:47] epoch=06 | train_loss=1992.207910 | valid_mse=1711.386032 | BEST | dt_valid=1.20s | dt_epoch=6.66s
[15:54:54] epoch=07 | train_loss=1946.233328 | valid_mse=1684.630061 | BEST | dt_valid=1.17s | dt_epoch=6.63s
[15:55:00] epoch=08 | train_loss=1902.692467 | valid_mse=1644.068622 | BEST | dt_valid=1.18s | dt_epoch=6.65s
[15:55:07] epoch=09 | train_loss=1859.312824 | valid_mse=1610.249030 | BEST | dt_valid=1.19s | dt_epoch=6.68s
[15:55:14] epoch=10 | train_loss=1820.586102 | valid_mse=1585.667049 | BEST | dt_valid=1.19s | dt_epoch=6.69s
[15:55:20] epoch=11 | train_loss=1784.793272 | valid_mse=1560.552543 | BEST | dt_valid=1.03s | dt_epoch=6.50s
[15:55:27] epoch=12 | train_loss=1753.225247 | valid_mse=1523.653818 | BEST | dt_valid=1.17s | dt_epoch=6.84s
[15:55:34] epoch=13 | train_loss=1721.868312 | valid_mse=1507.322142 | BEST | dt_valid=1.18s | dt_epoch=6.61s
[15:55:40] epoch=14 | train_loss=1697.857790 | valid_mse=1489.414945 | BEST | dt_valid=1.01s | dt_epoch=6.51s
[15:55:47] epoch=15 | train_loss=1674.583418 | valid_mse=1465.681074 | BEST | dt_valid=1.20s | dt_epoch=6.64s
[15:55:54] epoch=16 | train_loss=1651.674643 | valid_mse=1448.983794 | BEST | dt_valid=1.18s | dt_epoch=6.66s
[15:56:00] epoch=17 | train_loss=1632.064422 | valid_mse=1434.109746 | BEST | dt_valid=1.17s | dt_epoch=6.62s
[15:56:07] epoch=18 | train_loss=1613.989518 | valid_mse=1422.852217 | BEST | dt_valid=1.18s | dt_epoch=6.62s
[15:56:14] epoch=19 | train_loss=1597.294205 | valid_mse=1402.093186 | BEST | dt_valid=1.20s | dt_epoch=6.67s
[15:56:20] epoch=20 | train_loss=1580.443449 | valid_mse=1410.579643 | no_improve(1/5) | dt_valid=1.18s | dt_epoch=6.67s
[15:56:27] epoch=21 | train_loss=1568.410701 | valid_mse=1391.195538 | BEST | dt_valid=1.18s | dt_epoch=6.63s
[15:56:33] epoch=22 | train_loss=1551.257928 | valid_mse=1390.573877 | BEST | dt_valid=1.17s | dt_epoch=6.60s
[15:56:40] epoch=23 | train_loss=1539.471017 | valid_mse=1378.078396 | BEST | dt_valid=1.17s | dt_epoch=6.62s
[15:56:46] epoch=24 | train_loss=1529.157099 | valid_mse=1365.781796 | BEST | dt_valid=1.01s | dt_epoch=6.42s
[15:56:53] epoch=25 | train_loss=1516.321392 | valid_mse=1364.937002 | BEST | dt_valid=1.19s | dt_epoch=6.86s
[15:57:00] epoch=26 | train_loss=1505.036596 | valid_mse=1361.019266 | BEST | dt_valid=1.19s | dt_epoch=6.67s
[15:57:06] epoch=27 | train_loss=1494.833755 | valid_mse=1355.456169 | BEST | dt_valid=1.02s | dt_epoch=6.49s
[15:57:13] epoch=28 | train_loss=1485.011545 | valid_mse=1371.396855 | no_improve(1/5) | dt_valid=1.19s | dt_epoch=6.62s
[15:57:20] epoch=29 | train_loss=1483.090874 | valid_mse=1357.154370 | no_improve(2/5) | dt_valid=1.18s | dt_epoch=6.66s
[15:57:26] epoch=30 | train_loss=1466.118732 | valid_mse=1342.806077 | BEST | dt_valid=1.21s | dt_epoch=6.68s
[15:57:26] [TRAIN] Cargando best_state (best_valid_mse=1342.806077) ...
[15:57:26] [TRAIN] END | best_valid_mse=1342.806077 | dt_total=199.13s
[15:57:26]   [TRAIN] FIN entrenamiento | dt=199.13s
[15:57:26]   [MEM] Liberando bundle['train'] y gc.collect() ...

### **13.3. Análisis de resultados**

In [49]:
df_mlp_delta_60

,model,split,window_size,target,horizon_min,MAE,RMSE,R2,DA,w_decay
0,mlp,test,30,delta_60,60,50.232999,77.094085,0.264331,0.651685,0.0001
1,mlp,valid,30,delta_60,60,32.880210,46.714091,0.273345,0.661028,0.0001
8,mlp,test,60,delta_60,60,38.923520,63.419347,0.496504,0.738393,0.0001
9,mlp,valid,60,delta_60,60,24.081825,37.120464,0.550355,0.758303,0.0001
16,mlp,test,90,delta_60,60,40.382358,64.906080,0.481965,0.729042,0.0001
17,mlp,valid,90,delta_60,60,25.324535,38.475513,0.528487,0.741210,0.0001
24,mlp,test,120,delta_60,60,39.748844,63.426119,0.518663,0.741398,0.0001
25,mlp,valid,120,delta_60,60,24.769221,37.699327,0.556814,0.754523,0.0001
32,mlp,test,180,delta_60,60,38.112160,60.078973,0.570888,0.783965,0.0001
33,mlp,valid,180,delta_60,60,23.693735,35.268546,0.635576,0.785406,0.0001

In [51]:
df_mlp_delta_60_valid = df_mlp_delta_60[df_mlp_delta_60["split"] == "valid"].copy()
df_mlp_delta_60_valid

,model,split,window_size,target,horizon_min,MAE,RMSE,R2,DA,w_decay
1,mlp,valid,30,delta_60,60,32.880210,46.714091,0.273345,0.661028,0.0001
9,mlp,valid,60,delta_60,60,24.081825,37.120464,0.550355,0.758303,0.0001
17,mlp,valid,90,delta_60,60,25.324535,38.475513,0.528487,0.741210,0.0001
25,mlp,valid,120,delta_60,60,24.769221,37.699327,0.556814,0.754523,0.0001
33,mlp,valid,180,delta_60,60,23.693735,35.268546,0.635576,0.785406,0.0001

In [48]:
df_mlp_tuning_arch_delta_60 = df_all.copy()
df_mlp_tuning_arch_delta_60

,model,split,window_size,target,horizon_min,MAE,RMSE,R2,DA,hidden_dims,dropout,activation,lr,w_decay
0,mlp,test,60,delta_60,60,40.068522,64.459744,0.479849,0.734468,[64],0.0,relu,0.001,0.0001
1,mlp,valid,60,delta_60,60,24.927824,37.995405,0.528908,0.751019,[64],0.0,relu,0.001,0.0001
2,mlp,test,180,delta_60,60,40.178311,62.111102,0.541368,0.775434,[64],0.0,relu,0.001,0.0001
3,mlp,valid,180,delta_60,60,25.115257,36.565634,0.608278,0.777230,[64],0.0,relu,0.001,0.0001
4,mlp,test,60,delta_60,60,38.833490,63.446381,0.496075,0.746188,[128],0.0,relu,0.001,0.0001
5,mlp,valid,60,delta_60,60,24.209347,37.239405,0.547468,0.757337,[128],0.0,relu,0.001,0.0001
6,mlp,test,180,delta_60,60,38.316973,59.955042,0.572657,0.783479,[128],0.0,relu,0.001,0.0001
7,mlp,valid,180,delta_60,60,23.858791,35.293936,0.635051,0.786341,[128],0.0,relu,0.001,0.0001
8,mlp,test,60,delta_60,60,37.773079,62.546829,0.510263,0.752019,[256],0.0,relu,0.001,0.0001
9,mlp,valid,60,delta_60,60,23.512603,36.644319,0.561816,0.766311,[256],0.0,relu,0.001,0.0001
10,mlp,test,180,delta_60,60,37.475574,59.351822,0.581213,0.782297,[256],0.0,relu,0.001,0.0001
11,mlp,valid,180,delta_60,60,23.066683,34.578408,0.649699,0.791799,[256],0.0,relu,0.001,0.0001
12,mlp,test,60,delta_60,60,38.659862,63.227579,0.499545,0.742163,[512],0.0,relu,0.001,0.0001
13,mlp,valid,60,delta_60,60,23.648664,36.740375,0.559516,0.764764,[512],0.0,relu,0.001,0.0001
14,mlp,test,180,delta_60,60,38.206245,59.290018,0.582084,0.775138,[512],0.0,relu,0.001,0.0001
15,mlp,valid,180,delta_60,60,23.369585,34.678097,0.647676,0.790461,[512],0.0,relu,0.001,0.0001
16,mlp,test,60,delta_60,60,38.543919,63.874819,0.489246,0.738577,[128],0.1,relu,0.001,0.0001
17,mlp,valid,60,delta_60,60,23.807150,36.866043,0.556497,0.759439,[128],0.1,relu,0.001,0.0001
18,mlp,test,180,delta_60,60,36.966631,58.563898,0.592258,0.791693,[128],0.1,relu,0.001,0.0001
19,mlp,valid,180,delta_60,60,23.068531,34.573680,0.649794,0.790843,[128],0.1,relu,0.001,0.0001
20,mlp,test,60,delta_60,60,37.345821,63.024484,0.502755,0.752612,[256],0.1,relu,0.001,0.0001
21,mlp,valid,60,delta_60,60,23.200309,36.356479,0.568673,0.766865,[256],0.1,relu,0.001,0.0001
22,mlp,test,180,delta_60,60,36.755217,58.366176,0.595007,0.792981,[256],0.1,relu,0.001,0.0001
23,mlp,valid,180,delta_60,60,22.857940,34.080816,0.659708,0.795239,[256],0.1,relu,0.001,0.0001
24,mlp,test,60,delta_60,60,37.599722,64.007494,0.487122,0.748136,[256],0.2,relu,0.001,0.0001
25,mlp,valid,60,delta_60,60,23.118319,36.337468,0.569124,0.770230,[256],0.2,relu,0.001,0.0001
26,mlp,test,180,delta_60,60,36.232697,58.411394,0.594379,0.793382,[256],0.2,relu,0.001,0.0001
27,mlp,valid,180,delta_60,60,22.505675,33.985249,0.661614,0.796768,[256],0.2,relu,0.001,0.0001
28,mlp,test,60,delta_60,60,39.293993,63.177576,0.500336,0.729187,"[128, 64]",0.0,relu,0.001,0.0001
29,mlp,valid,60,delta_60,60,24.017458,37.209055,0.548206,0.755662,"[128, 64]",0.0,relu,0.001,0.0001
30,mlp,test,180,delta_60,60,37.608104,58.758935,0.589538,0.781515,"[128, 64]",0.0,relu,0.001,0.0001
31,mlp,valid,180,delta_60,60,23.428267,34.230294,0.656716,0.786192,"[128, 64]",0.0,relu,0.001,0.0001
32,mlp,test,60,delta_60,60,40.466921,63.177927,0.500330,0.718921,"[256, 128]",0.0,relu,0.001,0.0001
33,mlp,valid,60,delta_60,60,24.267621,36.952139,0.554423,0.755236,"[256, 128]",0.0,relu,0.001,0.0001
34,mlp,test,180,delta_60,60,39.738684,61.649894,0.548154,0.765467,"[256, 128]",0.0,relu,0.001,0.0001
35,mlp,valid,180,delta_60,60,23.742190,35.161462,0.637786,0.782667,"[256, 128]",0.0,relu,0.001,0.0001
36,mlp,test,60,delta_60,60,37.882964,62.892805,0.504830,0.740921,"[256, 128]",0.1,relu,0.001,0.0001
37,mlp,valid,60,delta_60,60,23.616035,36.749744,0.559291,0.760561,"[256, 128]",0.1,relu,0.001,0.0001
38,mlp,test,180,delta_60,60,37.673212,60.304956,0.567654,0.786604,"[256, 128]",0.1,relu,0.001,0.0001
39,mlp,valid,180,delta_60,60,23.206209,34.627546,0.648702,0.788167,"[256, 128]",0.1,relu,0.001,0.0001
40,mlp,test,60,delta_60,60,37.282289,62.676989,0.508223,0.753671,[256],0.1,gelu,0.001,0.0001
41,mlp,valid,60,delta_60,60,23.080716,36.363161,0.568514,0.768981,[256],0.1,gelu,0.001,0.0001
42,mlp,test,180,delta_60,60,38.395328,59.833466,0.574388,0.774779,[256],0.1,gelu,0.001,0.0001
43,mlp,valid,180,delta_60,60,23.188783,34.735729,0.646504,0.788740,[256],0.1,gelu,0.001,0.0001

In [52]:
df_mlp_tuning_arch_delta_60_valid  = df_mlp_tuning_arch_delta_60 [df_mlp_tuning_arch_delta_60 ["split"] == "valid"].copy()
df_mlp_tuning_arch_delta_60_valid

,model,split,window_size,target,horizon_min,MAE,RMSE,R2,DA,hidden_dims,dropout,activation,lr,w_decay
1,mlp,valid,60,delta_60,60,24.927824,37.995405,0.528908,0.751019,[64],0.0,relu,0.001,0.0001
3,mlp,valid,180,delta_60,60,25.115257,36.565634,0.608278,0.777230,[64],0.0,relu,0.001,0.0001
5,mlp,valid,60,delta_60,60,24.209347,37.239405,0.547468,0.757337,[128],0.0,relu,0.001,0.0001
7,mlp,valid,180,delta_60,60,23.858791,35.293936,0.635051,0.786341,[128],0.0,relu,0.001,0.0001
9,mlp,valid,60,delta_60,60,23.512603,36.644319,0.561816,0.766311,[256],0.0,relu,0.001,0.0001
11,mlp,valid,180,delta_60,60,23.066683,34.578408,0.649699,0.791799,[256],0.0,relu,0.001,0.0001
13,mlp,valid,60,delta_60,60,23.648664,36.740375,0.559516,0.764764,[512],0.0,relu,0.001,0.0001
15,mlp,valid,180,delta_60,60,23.369585,34.678097,0.647676,0.790461,[512],0.0,relu,0.001,0.0001
17,mlp,valid,60,delta_60,60,23.807150,36.866043,0.556497,0.759439,[128],0.1,relu,0.001,0.0001
19,mlp,valid,180,delta_60,60,23.068531,34.573680,0.649794,0.790843,[128],0.1,relu,0.001,0.0001
21,mlp,valid,60,delta_60,60,23.200309,36.356479,0.568673,0.766865,[256],0.1,relu,0.001,0.0001
23,mlp,valid,180,delta_60,60,22.857940,34.080816,0.659708,0.795239,[256],0.1,relu,0.001,0.0001
25,mlp,valid,60,delta_60,60,23.118319,36.337468,0.569124,0.770230,[256],0.2,relu,0.001,0.0001
27,mlp,valid,180,delta_60,60,22.505675,33.985249,0.661614,0.796768,[256],0.2,relu,0.001,0.0001
29,mlp,valid,60,delta_60,60,24.017458,37.209055,0.548206,0.755662,"[128, 64]",0.0,relu,0.001,0.0001
31,mlp,valid,180,delta_60,60,23.428267,34.230294,0.656716,0.786192,"[128, 64]",0.0,relu,0.001,0.0001
33,mlp,valid,60,delta_60,60,24.267621,36.952139,0.554423,0.755236,"[256, 128]",0.0,relu,0.001,0.0001
35,mlp,valid,180,delta_60,60,23.742190,35.161462,0.637786,0.782667,"[256, 128]",0.0,relu,0.001,0.0001
37,mlp,valid,60,delta_60,60,23.616035,36.749744,0.559291,0.760561,"[256, 128]",0.1,relu,0.001,0.0001
39,mlp,valid,180,delta_60,60,23.206209,34.627546,0.648702,0.788167,"[256, 128]",0.1,relu,0.001,0.0001
41,mlp,valid,60,delta_60,60,23.080716,36.363161,0.568514,0.768981,[256],0.1,gelu,0.001,0.0001
43,mlp,valid,180,delta_60,60,23.188783,34.735729,0.646504,0.788740,[256],0.1,gelu,0.001,0.0001

In [54]:
metrics = ["MAE", "RMSE", "R2", "DA"]

summary_valid = pd.DataFrame({
    "min": df_mlp_tuning_arch_delta_60_valid[metrics].min(),
    "max": df_mlp_tuning_arch_delta_60_valid[metrics].max(),
    "dif": df_mlp_tuning_arch_delta_60_valid[metrics].max() - df_mlp_tuning_arch_delta_60_valid[metrics].min(),
})

summary_valid

            min        max       dif
MAE   22.505675  25.115257  2.609582
RMSE  33.985249  37.995405  4.010157
R2     0.528908   0.661614  0.132706
DA     0.751019   0.796768  0.045749

In [56]:
df_mlp_tuning_arch_delta_60_test  = df_mlp_tuning_arch_delta_60 [df_mlp_tuning_arch_delta_60 ["split"] == "test"].copy()
df_mlp_tuning_arch_delta_60_test

,model,split,window_size,target,horizon_min,MAE,RMSE,R2,DA,hidden_dims,dropout,activation,lr,w_decay
0,mlp,test,60,delta_60,60,40.068522,64.459744,0.479849,0.734468,[64],0.0,relu,0.001,0.0001
2,mlp,test,180,delta_60,60,40.178311,62.111102,0.541368,0.775434,[64],0.0,relu,0.001,0.0001
4,mlp,test,60,delta_60,60,38.833490,63.446381,0.496075,0.746188,[128],0.0,relu,0.001,0.0001
6,mlp,test,180,delta_60,60,38.316973,59.955042,0.572657,0.783479,[128],0.0,relu,0.001,0.0001
8,mlp,test,60,delta_60,60,37.773079,62.546829,0.510263,0.752019,[256],0.0,relu,0.001,0.0001
10,mlp,test,180,delta_60,60,37.475574,59.351822,0.581213,0.782297,[256],0.0,relu,0.001,0.0001
12,mlp,test,60,delta_60,60,38.659862,63.227579,0.499545,0.742163,[512],0.0,relu,0.001,0.0001
14,mlp,test,180,delta_60,60,38.206245,59.290018,0.582084,0.775138,[512],0.0,relu,0.001,0.0001
16,mlp,test,60,delta_60,60,38.543919,63.874819,0.489246,0.738577,[128],0.1,relu,0.001,0.0001
18,mlp,test,180,delta_60,60,36.966631,58.563898,0.592258,0.791693,[128],0.1,relu,0.001,0.0001
20,mlp,test,60,delta_60,60,37.345821,63.024484,0.502755,0.752612,[256],0.1,relu,0.001,0.0001
22,mlp,test,180,delta_60,60,36.755217,58.366176,0.595007,0.792981,[256],0.1,relu,0.001,0.0001
24,mlp,test,60,delta_60,60,37.599722,64.007494,0.487122,0.748136,[256],0.2,relu,0.001,0.0001
26,mlp,test,180,delta_60,60,36.232697,58.411394,0.594379,0.793382,[256],0.2,relu,0.001,0.0001
28,mlp,test,60,delta_60,60,39.293993,63.177576,0.500336,0.729187,"[128, 64]",0.0,relu,0.001,0.0001
30,mlp,test,180,delta_60,60,37.608104,58.758935,0.589538,0.781515,"[128, 64]",0.0,relu,0.001,0.0001
32,mlp,test,60,delta_60,60,40.466921,63.177927,0.500330,0.718921,"[256, 128]",0.0,relu,0.001,0.0001
34,mlp,test,180,delta_60,60,39.738684,61.649894,0.548154,0.765467,"[256, 128]",0.0,relu,0.001,0.0001
36,mlp,test,60,delta_60,60,37.882964,62.892805,0.504830,0.740921,"[256, 128]",0.1,relu,0.001,0.0001
38,mlp,test,180,delta_60,60,37.673212,60.304956,0.567654,0.786604,"[256, 128]",0.1,relu,0.001,0.0001
40,mlp,test,60,delta_60,60,37.282289,62.676989,0.508223,0.753671,[256],0.1,gelu,0.001,0.0001
42,mlp,test,180,delta_60,60,38.395328,59.833466,0.574388,0.774779,[256],0.1,gelu,0.001,0.0001

In [57]:
summary_test = pd.DataFrame({
    "min": df_mlp_tuning_arch_delta_60_test[metrics].min(),
    "max": df_mlp_tuning_arch_delta_60_test[metrics].max(),
    "dif": df_mlp_tuning_arch_delta_60_test[metrics].max() - df_mlp_tuning_arch_delta_60_test[metrics].min(),
})

summary_test

            min        max       dif
MAE   36.232697  40.466921  4.234224
RMSE  58.366176  64.459744  6.093568
R2     0.479849   0.595007  0.115157
DA     0.718921   0.793382  0.074461

### **13.4. Conclusiones – Selección y congelamiento de arquitectura (MLP SEQ2ONE – delta_60)**


1. Evaluación exclusivamente en VALID  
   La selección de arquitectura se realizó únicamente utilizando métricas del split de validación, manteniendo el conjunto TEST completamente fuera del proceso de decisión.

2. Sensibilidad limitada a la arquitectura  
   Las diferencias entre configuraciones no son estructuralmente grandes.  
   - Rango total de MAE ≈ 2.61 puntos.  
   - Entre las mejores configuraciones (top 3), la diferencia es < 0.6 puntos.  
   Esto indica que el problema no es altamente sensible a incrementos agresivos de capacidad.

3. Ventana óptima  
   La ventana L=180 domina consistentemente a L=60 en todas las métricas (MAE, RMSE, R² y DA).  
   Se confirma que un contexto largo mejora la capacidad predictiva para delta_60.

4. Tamaño de capa oculta  
   - hidden_dims=[256] muestra desempeño consistentemente superior.
   - Incrementar a 512 no aporta mejoras.
   - Arquitecturas de dos capas no superan de forma clara a una sola capa de 256.

5. Efecto del dropout  
   - Dropout moderado (0.1–0.2) mejora ligeramente la generalización.
   - La mejor métrica de validación (MAE y RMSE mínimos, R² máximo, DA máximo) se obtiene con:
     
     hidden_dims = [256]  
     dropout = 0.2  
     activation = relu  

6. Decisión final de arquitectura (congelada)

   - window_size = 180  
   - hidden_dims = [256]  
   - dropout = 0.2  
   - activation = relu  
   - lr = 1e-3 (provisional)  
   - weight_decay = 1e-4 (provisional)

A partir de este punto, la arquitectura se considera fija.  
La siguiente etapa será el tuning de hiperparámetros de entrenamiento (learning rate y regularización), manteniendo constante la estructura del modelo.

## **14. Tuning de Aprendizaje**

### **14.1. Funciones**

In [70]:
import torch
import torch.nn as nn

class MLPSeq2One(nn.Module):
    """
    MLP SEQ2ONE (arquitectura congelada para delta_60).
    """
    def __init__(
        self,
        *,
        in_dim: int,
        hidden_dims: list[int] = [256],
        dropout: float = 0.2,
        activation: str = "relu",
    ):
        super().__init__()

        if activation.lower() == "relu":
            Act = nn.ReLU
        elif activation.lower() == "gelu":
            Act = nn.GELU
        else:
            raise ValueError(f"activation no soportada: {activation}")

        layers: list[nn.Module] = []
        prev = in_dim

        for h in hidden_dims:
            layers.append(nn.Linear(prev, h))
            layers.append(Act())
            if dropout and dropout > 0.0:
                layers.append(nn.Dropout(dropout))
            prev = h

        layers.append(nn.Linear(prev, 1))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)

In [71]:
HP_GRID_SMALL = [
    {"lr": 5e-4, "weight_decay": 1e-5},
    {"lr": 5e-4, "weight_decay": 1e-4},
    {"lr": 1e-3, "weight_decay": 1e-5},
    {"lr": 1e-3, "weight_decay": 1e-4},   # baseline
    {"lr": 2e-3, "weight_decay": 1e-4},
]
HP_GRID_SMALL

[{'lr': 0.0005, 'weight_decay': 1e-05},
 {'lr': 0.0005, 'weight_decay': 0.0001},
 {'lr': 0.001, 'weight_decay': 1e-05},
 {'lr': 0.001, 'weight_decay': 0.0001},
 {'lr': 0.002, 'weight_decay': 0.0001}]

1) Congelar arquitectura en train_mlp

In [72]:
# ============================================================
# Arquitectura congelada (delta_60, SEQ2ONE)
# ============================================================
FROZEN_ARCH = dict(
    hidden_dims=[256],
    dropout=0.2,
    activation="relu",
)

2) Runner para una corrida (L=180, delta_60) variando lr/wd

In [73]:
def run_mlp_lrwd_delta_60(
    *,
    window_size: int = 180,
    lr: float,
    weight_decay: float,
    verbose: bool = True,
) -> pd.DataFrame:
    return run_mlp_delta_60(
        window_size,
        hidden_dims=FROZEN_ARCH["hidden_dims"],
        dropout=FROZEN_ARCH["dropout"],
        activation=FROZEN_ARCH["activation"],
        lr=lr,
        weight_decay=weight_decay,
        verbose=verbose,
    )

3) Incremental “onefile” para guardar todo en un solo dataset

In [74]:
import pandas as pd
import time

def _ts():
    return time.strftime("%H:%M:%S")


def run_mlp_hp_tuning_delta_60_onefile(
    hp_grid: list[dict],
    *,
    window_size: int = 180,
    name: str = "mlp_learning_tuning_delta_60_L180",

    base_dir: str = "/content/drive/MyDrive/neural_profit/metrics/seq2one_metrics",
    verbose: bool = True,
) -> pd.DataFrame:

    # 1) Cargar si existe
    df_all = load_seq2one_metrics_if_exists(name=name, base_dir=base_dir)

    # 2) Columnas esperadas (incluye hp y arch para trazabilidad)
    cols = [
        "model","split","window_size","target","horizon_min","MAE","RMSE","R2","DA",
        "hidden_dims","dropout","activation","lr","w_decay"
    ]
    if df_all.empty:
        df_all = pd.DataFrame(columns=cols)
    else:
        for c in cols:
            if c not in df_all.columns:
                df_all[c] = pd.NA

    # 3) Normalizar tipos
    if len(df_all):
        df_all["window_size"] = pd.to_numeric(df_all["window_size"], errors="coerce").astype("Int64")
        df_all["horizon_min"] = pd.to_numeric(df_all["horizon_min"], errors="coerce").astype("Int64")

    # 4) Key única por corrida
    key_cols = ["model","window_size","target","split","horizon_min","hidden_dims","dropout","activation","lr","w_decay"]

    # 5) Loop hiperparámetros
    for i, hp in enumerate(hp_grid, start=1):
        lr = float(hp["lr"])
        wd = float(hp["weight_decay"])

        # ¿ya existen valid+test para esta config?
        hidden_dims_str = str(FROZEN_ARCH["hidden_dims"])
        df_cfg = df_all[
            (df_all["model"] == "mlp") &
            (df_all["target"] == "delta_60") &
            (df_all["window_size"] == window_size) &
            (df_all["hidden_dims"] == hidden_dims_str) &
            (df_all["dropout"] == FROZEN_ARCH["dropout"]) &
            (df_all["activation"] == FROZEN_ARCH["activation"]) &
            (df_all["lr"] == lr) &
            (df_all["w_decay"] == wd)
        ]

        if len(df_cfg) >= 2:
            if verbose:
                print(f"[SKIP] [{i}/{len(hp_grid)}] lr={lr} wd={wd}: ya existe valid+test.")
            continue

        if verbose:
            print("\n" + "=" * 110)
            print(f"[{_ts()}] [RUN {i}/{len(hp_grid)}] HP TUNING | L{window_size} | lr={lr} | w_decay={wd} | arch={FROZEN_ARCH}")
            print("=" * 110)

        df_new = run_mlp_lrwd_delta_60(
            window_size=window_size,
            lr=lr,
            weight_decay=wd,
            verbose=verbose,
        ).copy()

        # Anti-duplicados por key
        existing_keys = set(tuple(x) for x in df_all[key_cols].dropna().values)
        mask_keep = [tuple(row) not in existing_keys for row in df_new[key_cols].values]
        df_new = df_new.loc[mask_keep].copy()

        if df_new.empty:
            if verbose:
                print(f"[INFO] lr={lr} wd={wd}: no hubo filas nuevas.")
            continue

        df_all = pd.concat([df_all, df_new], ignore_index=True)
        df_all = df_all.drop_duplicates(subset=key_cols, keep="last").reset_index(drop=True)

        save_seq2one_metrics(df_all, name=name, base_dir=base_dir)

        if verbose:
            print(f"[OK] Guardado incremental. Total rows={len(df_all)}")

    return df_all

### **14.2. Ejecución con tu HP_GRID_SMALL**

In [75]:
df_hp = run_mlp_hp_tuning_delta_60_onefile(
    HP_GRID_SMALL,
    window_size=180,
    name="mlp_learning_tuning_delta_60_L180",
    base_dir="/content/drive/MyDrive/neural_profit/metrics/seq2one_metrics",
    verbose=True,
)

==============================================================================================================
[17:30:09] [RUN 1/5] HP TUNING | L180 | lr=0.0005 | w_decay=1e-05 | arch={'hidden_dims': [256], 'dropout': 0.2, 'activation': 'relu'}
==============================================================================================================

==========================================================================================
[17:30:09] MLP | SEQ2ONE | target=delta_60 | L180 | in_dim=6480 | hidden_dims=[256] | dropout=0.2 | act=relu | lr=0.0005 | w_decay=1e-05
==========================================================================================
[17:30:09]   [BUILD] Creando bundle (flatten_X=True) ...
H60 Train: (220704, 6480) (220704,)
H60 Valid: (47190, 6480) (47190,)
H60 Test : (47432, 6480) (47432,)
Scaler H60: StandardScaler
[17:30:28]   [BUILD] OK | train X=(220704, 6480) y=(220704,) | dt=18.27s
[17:30:28]   [LOADERS] Creando DataLoaders ...
[17:30:28]   [LOADERS] OK | n(train/valid/test)=(220704/47190/47432) | dt=0.00s
[17:30:28]   [TRAIN] Iniciando entrenamiento ...
[17:30:28] [TRAIN] START | in_dim=6480 hidden_dims=[256] dropout=0.2 activation=relu lr=0.0005 wd=1e-05 max_epochs=30 patience=5 device=cuda
[17:30:35] epoch=01 | train_loss=3501.621376 | valid_mse=2841.600890 | BEST | dt_valid=1.29s | dt_epoch=7.36s
[17:30:43] epoch=02 | train_loss=2899.512774 | valid_mse=2332.777114 | BEST | dt_valid=1.28s | dt_epoch=7.64s
[17:30:50] epoch=03 | train_loss=2576.445175 | valid_mse=2142.902395 | BEST | dt_valid=1.27s | dt_epoch=7.57s
[17:30:58] epoch=04 | train_loss=2365.119801 | valid_mse=2011.138165 | BEST | dt_valid=1.47s | dt_epoch=7.56s
[17:31:05] epoch=05 | train_loss=2232.418105 | valid_mse=1895.157491 | BEST | dt_valid=1.30s | dt_epoch=7.49s
[17:31:13] epoch=06 | train_loss=2134.293203 | valid_mse=1810.654122 | BEST | dt_valid=1.28s | dt_epoch=7.48s
[17:31:20] epoch=07 | train_loss=2063.055606 | valid_mse=1740.970968 | BEST | dt_valid=1.28s | dt_epoch=7.53s
[17:31:28] epoch=08 | train_loss=2004.773075 | valid_mse=1695.001483 | BEST | dt_valid=1.27s | dt_epoch=7.53s
[17:31:35] epoch=09 | train_loss=1955.235568 | valid_mse=1655.578343 | BEST | dt_valid=1.29s | dt_epoch=7.52s
[17:31:43] epoch=10 | train_loss=1911.517887 | valid_mse=1622.440644 | BEST | dt_valid=1.29s | dt_epoch=7.47s
[17:31:50] epoch=11 | train_loss=1869.300726 | valid_mse=1594.962534 | BEST | dt_valid=1.26s | dt_epoch=7.62s
[17:31:58] epoch=12 | train_loss=1828.207039 | valid_mse=1573.806527 | BEST | dt_valid=1.27s | dt_epoch=7.49s
[17:32:05] epoch=13 | train_loss=1792.826278 | valid_mse=1555.021700 | BEST | dt_valid=1.27s | dt_epoch=7.55s
[17:32:13] epoch=14 | train_loss=1758.767175 | valid_mse=1542.687391 | BEST | dt_valid=1.46s | dt_epoch=7.57s
[17:32:20] epoch=15 | train_loss=1724.412888 | valid_mse=1500.168298 | BEST | dt_valid=1.27s | dt_epoch=7.33s
[17:32:28] epoch=16 | train_loss=1693.556411 | valid_mse=1481.514177 | BEST | dt_valid=1.45s | dt_epoch=7.61s
[17:32:35] epoch=17 | train_loss=1663.734359 | valid_mse=1464.515088 | BEST | dt_valid=1.27s | dt_epoch=7.36s
[17:32:43] epoch=18 | train_loss=1637.689836 | valid_mse=1436.639712 | BEST | dt_valid=1.29s | dt_epoch=7.64s
[17:32:51] epoch=19 | train_loss=1610.539833 | valid_mse=1421.286226 | BEST | dt_valid=1.43s | dt_epoch=7.64s
[17:32:58] epoch=20 | train_loss=1586.608665 | valid_mse=1398.297436 | BEST | dt_valid=1.27s | dt_epoch=7.34s
[17:33:06] epoch=21 | train_loss=1561.869493 | valid_mse=1385.067218 | BEST | dt_valid=1.45s | dt_epoch=7.66s
[17:33:13] epoch=22 | train_loss=1541.798935 | valid_mse=1364.581352 | BEST | dt_valid=1.31s | dt_epoch=7.52s
[17:33:21] epoch=23 | train_loss=1517.445469 | valid_mse=1352.791227 | BEST | dt_valid=1.28s | dt_epoch=7.60s
[17:33:28] epoch=24 | train_loss=1496.142847 | valid_mse=1335.005531 | BEST | dt_valid=1.46s | dt_epoch=7.65s
[17:33:36] epoch=25 | train_loss=1476.842959 | valid_mse=1320.639330 | BEST | dt_valid=1.30s | dt_epoch=7.47s
[17:33:44] epoch=26 | train_loss=1460.002423 | valid_mse=1315.500106 | BEST | dt_valid=1.45s | dt_epoch=7.62s
[17:33:51] epoch=27 | train_loss=1441.381603 | valid_mse=1290.527654 | BEST | dt_valid=1.27s | dt_epoch=7.45s
[17:33:58] epoch=28 | train_loss=1426.859297 | valid_mse=1283.676584 | BEST | dt_valid=1.27s | dt_epoch=7.49s
[17:34:06] epoch=29 | train_loss=1406.272475 | valid_mse=1270.042382 | BEST | dt_valid=1.44s | dt_epoch=7.54s
[17:34:13] epoch=30 | train_loss=1391.297538 | valid_mse=1273.046641 | no_improve(1/5) | dt_valid=1.30s | dt_epoch=7.40s
[17:34:13] [TRAIN] Cargando best_state (best_valid_mse=1270.042382) ...
[17:34:13] [TRAIN] END | best_valid_mse=1270.042382 | dt_total=225.76s
[17:34:13]   [TRAIN] FIN entrenamiento | dt=225.76s
[17:34:13]   [MEM] Liberando bundle['train'] y gc.collect() ...
[17:34:14]   [PRED] Predicciones + métricas (valid/test) ...
[17:34:14]   [METRICS] OK (valid/test) | dt=0.55s
[17:34:14] [DONE] rows=2 | dt_total=244.74s
[OK] Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics/seq2one_metrics/seq2one_mlp_learning_tuning_delta_60_L180_metrics.parquet
[OK] Guardado incremental. Total rows=2

==============================================================================================================
[17:34:14] [RUN 2/5] HP TUNING | L180 | lr=0.0005 | w_decay=0.0001 | arch={'hidden_dims': [256], 'dropout': 0.2, 'activation': 'relu'}
==============================================================================================================

==========================================================================================
[17:34:14] MLP | SEQ2ONE | target=delta_60 | L180 | in_dim=6480 | hidden_dims=[256] | dropout=0.2 | act=relu | lr=0.0005 | w_decay=0.0001
==========================================================================================
[17:34:14]   [BUILD] Creando bundle (flatten_X=True) ...

/tmp/ipython-input-2990061145.py:86: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all = pd.concat([df_all, df_new], ignore_index=True)

H60 Train: (220704, 6480) (220704,)
H60 Valid: (47190, 6480) (47190,)
H60 Test : (47432, 6480) (47432,)
Scaler H60: StandardScaler
[17:34:33]   [BUILD] OK | train X=(220704, 6480) y=(220704,) | dt=18.39s
[17:34:33]   [LOADERS] Creando DataLoaders ...
[17:34:33]   [LOADERS] OK | n(train/valid/test)=(220704/47190/47432) | dt=0.00s
[17:34:33]   [TRAIN] Iniciando entrenamiento ...
[17:34:33] [TRAIN] START | in_dim=6480 hidden_dims=[256] dropout=0.2 activation=relu lr=0.0005 wd=0.0001 max_epochs=30 patience=5 device=cuda
[17:34:40] epoch=01 | train_loss=3489.284654 | valid_mse=2826.119941 | BEST | dt_valid=1.29s | dt_epoch=7.48s
[17:34:48] epoch=02 | train_loss=2865.674952 | valid_mse=2296.862556 | BEST | dt_valid=1.27s | dt_epoch=7.54s
[17:34:55] epoch=03 | train_loss=2544.836942 | valid_mse=2135.147023 | BEST | dt_valid=1.30s | dt_epoch=7.52s
[17:35:03] epoch=04 | train_loss=2345.105408 | valid_mse=2009.037338 | BEST | dt_valid=1.30s | dt_epoch=7.54s
[17:35:10] epoch=05 | train_loss=2214.016341 | valid_mse=1888.747574 | BEST | dt_valid=1.27s | dt_epoch=7.56s
[17:35:18] epoch=06 | train_loss=2122.060257 | valid_mse=1801.327951 | BEST | dt_valid=1.29s | dt_epoch=7.61s
[17:35:26] epoch=07 | train_loss=2055.050248 | valid_mse=1737.486205 | BEST | dt_valid=1.30s | dt_epoch=7.60s
[17:35:33] epoch=08 | train_loss=1999.599378 | valid_mse=1697.556686 | BEST | dt_valid=1.29s | dt_epoch=7.47s
[17:35:41] epoch=09 | train_loss=1952.945423 | valid_mse=1668.115999 | BEST | dt_valid=1.30s | dt_epoch=7.63s
[17:35:48] epoch=10 | train_loss=1909.153465 | valid_mse=1632.354990 | BEST | dt_valid=1.27s | dt_epoch=7.36s
[17:35:56] epoch=11 | train_loss=1866.938448 | valid_mse=1607.367239 | BEST | dt_valid=1.26s | dt_epoch=7.55s
[17:36:03] epoch=12 | train_loss=1830.383299 | valid_mse=1584.214240 | BEST | dt_valid=1.28s | dt_epoch=7.51s
[17:36:11] epoch=13 | train_loss=1793.875664 | valid_mse=1556.209917 | BEST | dt_valid=1.29s | dt_epoch=7.48s
[17:36:18] epoch=14 | train_loss=1757.775485 | valid_mse=1535.812926 | BEST | dt_valid=1.27s | dt_epoch=7.60s
[17:36:26] epoch=15 | train_loss=1724.294366 | valid_mse=1523.707735 | BEST | dt_valid=1.27s | dt_epoch=7.34s
[17:36:33] epoch=16 | train_loss=1695.534918 | valid_mse=1485.090061 | BEST | dt_valid=1.28s | dt_epoch=7.60s
[17:36:41] epoch=17 | train_loss=1663.230589 | valid_mse=1460.333545 | BEST | dt_valid=1.28s | dt_epoch=7.51s
[17:36:48] epoch=18 | train_loss=1638.925433 | valid_mse=1437.600339 | BEST | dt_valid=1.30s | dt_epoch=7.49s
[17:36:56] epoch=19 | train_loss=1611.878834 | valid_mse=1440.561093 | no_improve(1/5) | dt_valid=1.29s | dt_epoch=7.57s
[17:37:03] epoch=20 | train_loss=1592.315232 | valid_mse=1447.968892 | no_improve(2/5) | dt_valid=1.26s | dt_epoch=7.36s
[17:37:11] epoch=21 | train_loss=1569.799670 | valid_mse=1396.310574 | BEST | dt_valid=1.27s | dt_epoch=7.60s
[17:37:18] epoch=22 | train_loss=1548.185163 | valid_mse=1369.310553 | BEST | dt_valid=1.29s | dt_epoch=7.52s
[17:37:26] epoch=23 | train_loss=1526.202050 | valid_mse=1362.587752 | BEST | dt_valid=1.29s | dt_epoch=7.48s
[17:37:33] epoch=24 | train_loss=1505.022184 | valid_mse=1343.615808 | BEST | dt_valid=1.27s | dt_epoch=7.62s
[17:37:41] epoch=25 | train_loss=1485.632368 | valid_mse=1333.527442 | BEST | dt_valid=1.27s | dt_epoch=7.37s
[17:37:48] epoch=26 | train_loss=1471.520365 | valid_mse=1326.322505 | BEST | dt_valid=1.26s | dt_epoch=7.59s
[17:37:56] epoch=27 | train_loss=1454.263432 | valid_mse=1321.435431 | BEST | dt_valid=1.29s | dt_epoch=7.53s
[17:38:03] epoch=28 | train_loss=1441.961334 | valid_mse=1293.698538 | BEST | dt_valid=1.30s | dt_epoch=7.45s
[17:38:11] epoch=29 | train_loss=1422.972571 | valid_mse=1283.258508 | BEST | dt_valid=1.30s | dt_epoch=7.65s
[17:38:18] epoch=30 | train_loss=1405.821382 | valid_mse=1276.499046 | BEST | dt_valid=1.27s | dt_epoch=7.44s
[17:38:18] [TRAIN] Cargando best_state (best_valid_mse=1276.499046) ...
[17:38:18] [TRAIN] END | best_valid_mse=1276.499046 | dt_total=225.66s
[17:38:18]   [TRAIN] FIN entrenamiento | dt=225.66s
[17:38:18]   [MEM] Liberando bundle['train'] y gc.collect() ...
[17:38:19]   [PRED] Predicciones + métricas (valid/test) ...
[17:38:19]   [METRICS] OK (valid/test) | dt=0.55s
[17:38:19] [DONE] rows=2 | dt_total=244.76s
[OK] Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics/seq2one_metrics/seq2one_mlp_learning_tuning_delta_60_L180_metrics.parquet
[OK] Guardado incremental. Total rows=4

==============================================================================================================
[17:38:19] [RUN 3/5] HP TUNING | L180 | lr=0.001 | w_decay=1e-05 | arch={'hidden_dims': [256], 'dropout': 0.2, 'activation': 'relu'}
==============================================================================================================

==========================================================================================
[17:38:19] MLP | SEQ2ONE | target=delta_60 | L180 | in_dim=6480 | hidden_dims=[256] | dropout=0.2 | act=relu | lr=0.001 | w_decay=1e-05
==========================================================================================
[17:38:19]   [BUILD] Creando bundle (flatten_X=True) ...
H60 Train: (220704, 6480) (220704,)
H60 Valid: (47190, 6480) (47190,)
H60 Test : (47432, 6480) (47432,)
Scaler H60: StandardScaler
[17:38:38]   [BUILD] OK | train X=(220704, 6480) y=(220704,) | dt=18.43s
[17:38:38]   [LOADERS] Creando DataLoaders ...
[17:38:38]   [LOADERS] OK | n(train/valid/test)=(220704/47190/47432) | dt=0.00s
[17:38:38]   [TRAIN] Iniciando entrenamiento ...
[17:38:38] [TRAIN] START | in_dim=6480 hidden_dims=[256] dropout=0.2 activation=relu lr=0.001 wd=1e-05 max_epochs=30 patience=5 device=cuda
[17:38:45] epoch=01 | train_loss=3269.073697 | valid_mse=2354.753761 | BEST | dt_valid=1.30s | dt_epoch=7.41s
[17:38:53] epoch=02 | train_loss=2566.157047 | valid_mse=2093.707311 | BEST | dt_valid=1.26s | dt_epoch=7.52s
[17:39:00] epoch=03 | train_loss=2261.661311 | valid_mse=1861.311380 | BEST | dt_valid=1.45s | dt_epoch=7.60s
[17:39:08] epoch=04 | train_loss=2098.997352 | valid_mse=1721.746217 | BEST | dt_valid=1.28s | dt_epoch=7.45s
[17:39:15] epoch=05 | train_loss=1995.783776 | valid_mse=1653.525535 | BEST | dt_valid=1.30s | dt_epoch=7.65s
[17:39:23] epoch=06 | train_loss=1911.918401 | valid_mse=1592.339309 | BEST | dt_valid=1.46s | dt_epoch=7.66s
[17:39:30] epoch=07 | train_loss=1832.056315 | valid_mse=1542.989468 | BEST | dt_valid=1.30s | dt_epoch=7.45s
[17:39:38] epoch=08 | train_loss=1764.996441 | valid_mse=1496.618606 | BEST | dt_valid=1.29s | dt_epoch=7.66s
[17:39:46] epoch=09 | train_loss=1700.610691 | valid_mse=1477.105912 | BEST | dt_valid=1.29s | dt_epoch=7.39s
[17:39:53] epoch=10 | train_loss=1647.164513 | valid_mse=1452.096016 | BEST | dt_valid=1.27s | dt_epoch=7.59s
[17:40:01] epoch=11 | train_loss=1605.989784 | valid_mse=1404.003708 | BEST | dt_valid=1.45s | dt_epoch=7.58s
[17:40:08] epoch=12 | train_loss=1561.396460 | valid_mse=1355.427951 | BEST | dt_valid=1.26s | dt_epoch=7.44s
[17:40:16] epoch=13 | train_loss=1521.632634 | valid_mse=1344.911591 | BEST | dt_valid=1.29s | dt_epoch=7.63s
[17:40:23] epoch=14 | train_loss=1491.652652 | valid_mse=1317.498877 | BEST | dt_valid=1.27s | dt_epoch=7.41s
[17:40:31] epoch=15 | train_loss=1457.592044 | valid_mse=1317.868277 | no_improve(1/5) | dt_valid=1.26s | dt_epoch=7.48s
[17:40:38] epoch=16 | train_loss=1430.561976 | valid_mse=1275.863658 | BEST | dt_valid=1.45s | dt_epoch=7.62s
[17:40:46] epoch=17 | train_loss=1403.673718 | valid_mse=1267.394575 | BEST | dt_valid=1.28s | dt_epoch=7.39s
[17:40:53] epoch=18 | train_loss=1376.521205 | valid_mse=1262.952363 | BEST | dt_valid=1.29s | dt_epoch=7.68s
[17:41:01] epoch=19 | train_loss=1352.381364 | valid_mse=1235.917588 | BEST | dt_valid=1.30s | dt_epoch=7.50s
[17:41:08] epoch=20 | train_loss=1329.634425 | valid_mse=1246.106124 | no_improve(1/5) | dt_valid=1.27s | dt_epoch=7.59s
[17:41:16] epoch=21 | train_loss=1315.488381 | valid_mse=1228.651218 | BEST | dt_valid=1.44s | dt_epoch=7.61s
[17:41:24] epoch=22 | train_loss=1294.997129 | valid_mse=1221.178915 | BEST | dt_valid=1.29s | dt_epoch=7.47s
[17:41:31] epoch=23 | train_loss=1271.508666 | valid_mse=1200.883047 | BEST | dt_valid=1.30s | dt_epoch=7.69s
[17:41:39] epoch=24 | train_loss=1255.660713 | valid_mse=1216.401017 | no_improve(1/5) | dt_valid=1.31s | dt_epoch=7.53s
[17:41:46] epoch=25 | train_loss=1233.644882 | valid_mse=1181.802988 | BEST | dt_valid=1.30s | dt_epoch=7.69s
[17:41:54] epoch=26 | train_loss=1219.237495 | valid_mse=1180.402246 | BEST | dt_valid=1.42s | dt_epoch=7.55s
[17:42:01] epoch=27 | train_loss=1196.875149 | valid_mse=1230.692541 | no_improve(1/5) | dt_valid=1.30s | dt_epoch=7.42s
[17:42:09] epoch=28 | train_loss=1181.356300 | valid_mse=1162.756559 | BEST | dt_valid=1.29s | dt_epoch=7.66s
[17:42:17] epoch=29 | train_loss=1164.343906 | valid_mse=1166.729413 | no_improve(1/5) | dt_valid=1.29s | dt_epoch=7.48s
[17:42:24] epoch=30 | train_loss=1160.101806 | valid_mse=1146.781352 | BEST | dt_valid=1.29s | dt_epoch=7.54s
[17:42:24] [TRAIN] Cargando best_state (best_valid_mse=1146.781352) ...
[17:42:24] [TRAIN] END | best_valid_mse=1146.781352 | dt_total=226.39s
[17:42:24]   [TRAIN] FIN entrenamiento | dt=226.39s
[17:42:24]   [MEM] Liberando bundle['train'] y gc.collect() ...
[17:42:24]   [PRED] Predicciones + métricas (valid/test) ...
[17:42:25]   [METRICS] OK (valid/test) | dt=0.55s
[17:42:25] [DONE] rows=2 | dt_total=245.54s
[OK] Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics/seq2one_metrics/seq2one_mlp_learning_tuning_delta_60_L180_metrics.parquet
[OK] Guardado incremental. Total rows=6

==============================================================================================================
[17:42:25] [RUN 4/5] HP TUNING | L180 | lr=0.001 | w_decay=0.0001 | arch={'hidden_dims': [256], 'dropout': 0.2, 'activation': 'relu'}
==============================================================================================================

==========================================================================================
[17:42:25] MLP | SEQ2ONE | target=delta_60 | L180 | in_dim=6480 | hidden_dims=[256] | dropout=0.2 | act=relu | lr=0.001 | w_decay=0.0001
==========================================================================================
[17:42:25]   [BUILD] Creando bundle (flatten_X=True) ...
H60 Train: (220704, 6480) (220704,)
H60 Valid: (47190, 6480) (47190,)
H60 Test : (47432, 6480) (47432,)
Scaler H60: StandardScaler
[17:42:43]   [BUILD] OK | train X=(220704, 6480) y=(220704,) | dt=18.22s
[17:42:43]   [LOADERS] Creando DataLoaders ...
[17:42:43]   [LOADERS] OK | n(train/valid/test)=(220704/47190/47432) | dt=0.00s
[17:42:43]   [TRAIN] Iniciando entrenamiento ...
[17:42:43] [TRAIN] START | in_dim=6480 hidden_dims=[256] dropout=0.2 activation=relu lr=0.001 wd=0.0001 max_epochs=30 patience=5 device=cuda
[17:42:51] epoch=01 | train_loss=3256.000805 | valid_mse=2359.435643 | BEST | dt_valid=1.30s | dt_epoch=7.46s
[17:42:58] epoch=02 | train_loss=2565.517570 | valid_mse=2084.727993 | BEST | dt_valid=1.29s | dt_epoch=7.63s
[17:43:06] epoch=03 | train_loss=2266.424983 | valid_mse=1853.557194 | BEST | dt_valid=1.43s | dt_epoch=7.53s
[17:43:13] epoch=04 | train_loss=2112.385430 | valid_mse=1740.348209 | BEST | dt_valid=1.28s | dt_epoch=7.34s
[17:43:21] epoch=05 | train_loss=2007.359853 | valid_mse=1659.030303 | BEST | dt_valid=1.29s | dt_epoch=7.66s
[17:43:29] epoch=06 | train_loss=1922.308165 | valid_mse=1607.475016 | BEST | dt_valid=1.46s | dt_epoch=7.64s
[17:43:36] epoch=07 | train_loss=1842.386124 | valid_mse=1558.600466 | BEST | dt_valid=1.31s | dt_epoch=7.50s
[17:43:44] epoch=08 | train_loss=1770.227449 | valid_mse=1505.696609 | BEST | dt_valid=1.29s | dt_epoch=7.70s
[17:43:51] epoch=09 | train_loss=1705.383927 | valid_mse=1471.686353 | BEST | dt_valid=1.31s | dt_epoch=7.53s
[17:43:59] epoch=10 | train_loss=1649.505567 | valid_mse=1431.401589 | BEST | dt_valid=1.30s | dt_epoch=7.67s
[17:44:07] epoch=11 | train_loss=1596.876490 | valid_mse=1417.654842 | BEST | dt_valid=1.46s | dt_epoch=7.60s
[17:44:14] epoch=12 | train_loss=1560.856300 | valid_mse=1373.319814 | BEST | dt_valid=1.28s | dt_epoch=7.45s
[17:44:22] epoch=13 | train_loss=1518.684240 | valid_mse=1381.677199 | no_improve(1/5) | dt_valid=1.28s | dt_epoch=7.62s
[17:44:29] epoch=14 | train_loss=1489.726950 | valid_mse=1332.541704 | BEST | dt_valid=1.30s | dt_epoch=7.44s
[17:44:37] epoch=15 | train_loss=1456.179146 | valid_mse=1316.720576 | BEST | dt_valid=1.29s | dt_epoch=7.64s
[17:44:44] epoch=16 | train_loss=1430.859671 | valid_mse=1379.129477 | no_improve(1/5) | dt_valid=1.43s | dt_epoch=7.62s
[17:44:52] epoch=17 | train_loss=1405.970300 | valid_mse=1282.558000 | BEST | dt_valid=1.31s | dt_epoch=7.41s
[17:44:59] epoch=18 | train_loss=1380.574448 | valid_mse=1286.427887 | no_improve(1/5) | dt_valid=1.30s | dt_epoch=7.69s
[17:45:07] epoch=19 | train_loss=1355.369639 | valid_mse=1273.387582 | BEST | dt_valid=1.27s | dt_epoch=7.46s
[17:45:14] epoch=20 | train_loss=1329.974739 | valid_mse=1253.225471 | BEST | dt_valid=1.27s | dt_epoch=7.53s
[17:45:22] epoch=21 | train_loss=1314.618039 | valid_mse=1233.956940 | BEST | dt_valid=1.43s | dt_epoch=7.58s
[17:45:29] epoch=22 | train_loss=1293.720441 | valid_mse=1228.673787 | BEST | dt_valid=1.30s | dt_epoch=7.40s
[17:45:37] epoch=23 | train_loss=1271.713249 | valid_mse=1272.333397 | no_improve(1/5) | dt_valid=1.29s | dt_epoch=7.66s
[17:45:45] epoch=24 | train_loss=1261.792984 | valid_mse=1225.119474 | BEST | dt_valid=1.30s | dt_epoch=7.50s
[17:45:52] epoch=25 | train_loss=1240.041854 | valid_mse=1218.029773 | BEST | dt_valid=1.30s | dt_epoch=7.69s
[17:46:00] epoch=26 | train_loss=1222.439915 | valid_mse=1185.118924 | BEST | dt_valid=1.46s | dt_epoch=7.69s
[17:46:07] epoch=27 | train_loss=1202.927400 | valid_mse=1220.761644 | no_improve(1/5) | dt_valid=1.31s | dt_epoch=7.54s
[17:46:15] epoch=28 | train_loss=1186.324281 | valid_mse=1181.026340 | BEST | dt_valid=1.27s | dt_epoch=7.57s
[17:46:22] epoch=29 | train_loss=1172.887920 | valid_mse=1157.099343 | BEST | dt_valid=1.27s | dt_epoch=7.39s
[17:46:30] epoch=30 | train_loss=1156.766277 | valid_mse=1171.777177 | no_improve(1/5) | dt_valid=1.31s | dt_epoch=7.69s
[17:46:30] [TRAIN] Cargando best_state (best_valid_mse=1157.099343) ...
[17:46:30] [TRAIN] END | best_valid_mse=1157.099343 | dt_total=226.90s
[17:46:30]   [TRAIN] FIN entrenamiento | dt=226.90s
[17:46:30]   [MEM] Liberando bundle['train'] y gc.collect() ...
[17:46:30]   [PRED] Predicciones + métricas (valid/test) ...
[17:46:31]   [METRICS] OK (valid/test) | dt=0.56s
[17:46:31] [DONE] rows=2 | dt_total=245.84s
[OK] Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics/seq2one_metrics/seq2one_mlp_learning_tuning_delta_60_L180_metrics.parquet
[OK] Guardado incremental. Total rows=8

==============================================================================================================
[17:46:31] [RUN 5/5] HP TUNING | L180 | lr=0.002 | w_decay=0.0001 | arch={'hidden_dims': [256], 'dropout': 0.2, 'activation': 'relu'}
==============================================================================================================

==========================================================================================
[17:46:31] MLP | SEQ2ONE | target=delta_60 | L180 | in_dim=6480 | hidden_dims=[256] | dropout=0.2 | act=relu | lr=0.002 | w_decay=0.0001
==========================================================================================
[17:46:31]   [BUILD] Creando bundle (flatten_X=True) ...
H60 Train: (220704, 6480) (220704,)
H60 Valid: (47190, 6480) (47190,)
H60 Test : (47432, 6480) (47432,)
Scaler H60: StandardScaler
[17:46:50]   [BUILD] OK | train X=(220704, 6480) y=(220704,) | dt=18.46s
[17:46:50]   [LOADERS] Creando DataLoaders ...
[17:46:50]   [LOADERS] OK | n(train/valid/test)=(220704/47190/47432) | dt=0.00s
[17:46:50]   [TRAIN] Iniciando entrenamiento ...
[17:46:50] [TRAIN] START | in_dim=6480 hidden_dims=[256] dropout=0.2 activation=relu lr=0.002 wd=0.0001 max_epochs=30 patience=5 device=cuda
[17:46:57] epoch=01 | train_loss=3064.898040 | valid_mse=2067.925662 | BEST | dt_valid=1.29s | dt_epoch=7.49s
[17:47:05] epoch=02 | train_loss=2304.226267 | valid_mse=1821.786862 | BEST | dt_valid=1.27s | dt_epoch=7.63s
[17:47:12] epoch=03 | train_loss=2066.182833 | valid_mse=1700.936851 | BEST | dt_valid=1.43s | dt_epoch=7.54s
[17:47:20] epoch=04 | train_loss=1923.297541 | valid_mse=1572.595889 | BEST | dt_valid=1.28s | dt_epoch=7.37s
[17:47:27] epoch=05 | train_loss=1801.732044 | valid_mse=1501.551218 | BEST | dt_valid=1.30s | dt_epoch=7.67s
[17:47:35] epoch=06 | train_loss=1710.695044 | valid_mse=1447.792308 | BEST | dt_valid=1.46s | dt_epoch=7.69s
[17:47:42] epoch=07 | train_loss=1627.136201 | valid_mse=1422.144649 | BEST | dt_valid=1.28s | dt_epoch=7.37s
[17:47:50] epoch=08 | train_loss=1554.695173 | valid_mse=1367.217588 | BEST | dt_valid=1.29s | dt_epoch=7.67s
[17:47:57] epoch=09 | train_loss=1490.532914 | valid_mse=1371.836978 | no_improve(1/5) | dt_valid=1.29s | dt_epoch=7.50s
[17:48:05] epoch=10 | train_loss=1441.037254 | valid_mse=1331.881733 | BEST | dt_valid=1.30s | dt_epoch=7.62s
[17:48:13] epoch=11 | train_loss=1392.489356 | valid_mse=1317.224497 | BEST | dt_valid=1.46s | dt_epoch=7.74s
[17:48:20] epoch=12 | train_loss=1348.672280 | valid_mse=1329.571096 | no_improve(1/5) | dt_valid=1.31s | dt_epoch=7.53s
[17:48:28] epoch=13 | train_loss=1312.910671 | valid_mse=1290.204259 | BEST | dt_valid=1.28s | dt_epoch=7.65s
[17:48:35] epoch=14 | train_loss=1273.356233 | valid_mse=1278.167366 | BEST | dt_valid=1.30s | dt_epoch=7.41s
[17:48:43] epoch=15 | train_loss=1240.012614 | valid_mse=1297.908752 | no_improve(1/5) | dt_valid=1.28s | dt_epoch=7.61s
[17:48:51] epoch=16 | train_loss=1206.096185 | valid_mse=1283.278173 | no_improve(2/5) | dt_valid=1.47s | dt_epoch=7.69s
[17:48:58] epoch=17 | train_loss=1180.535505 | valid_mse=1401.516063 | no_improve(3/5) | dt_valid=1.31s | dt_epoch=7.54s
[17:49:06] epoch=18 | train_loss=1166.772871 | valid_mse=1300.083662 | no_improve(4/5) | dt_valid=1.27s | dt_epoch=7.62s
[17:49:13] epoch=19 | train_loss=1137.425974 | valid_mse=1271.634668 | BEST | dt_valid=1.29s | dt_epoch=7.54s
[17:49:21] epoch=20 | train_loss=1104.232774 | valid_mse=1276.823840 | no_improve(1/5) | dt_valid=1.28s | dt_epoch=7.70s
[17:49:29] epoch=21 | train_loss=1077.044798 | valid_mse=1228.734096 | BEST | dt_valid=1.45s | dt_epoch=7.63s
[17:49:36] epoch=22 | train_loss=1053.113677 | valid_mse=1321.118097 | no_improve(1/5) | dt_valid=1.30s | dt_epoch=7.48s
[17:49:44] epoch=23 | train_loss=1034.536439 | valid_mse=1263.320259 | no_improve(2/5) | dt_valid=1.27s | dt_epoch=7.59s
[17:49:51] epoch=24 | train_loss=1012.470661 | valid_mse=1251.317567 | no_improve(3/5) | dt_valid=1.27s | dt_epoch=7.41s
[17:49:59] epoch=25 | train_loss=990.345373 | valid_mse=1257.285675 | no_improve(4/5) | dt_valid=1.30s | dt_epoch=7.55s
[17:50:06] epoch=26 | train_loss=977.324667 | valid_mse=1317.212842 | no_improve(5/5) | dt_valid=1.45s | dt_epoch=7.67s
[17:50:06] [TRAIN] EARLY STOPPING | patience=5 | best_valid_mse=1228.734096
[17:50:06] [TRAIN] Cargando best_state (best_valid_mse=1228.734096) ...
[17:50:06] [TRAIN] END | best_valid_mse=1228.734096 | dt_total=196.94s
[17:50:06]   [TRAIN] FIN entrenamiento | dt=196.94s
[17:50:06]   [MEM] Liberando bundle['train'] y gc.collect() ...
[17:50:07]   [PRED] Predicciones + métricas (valid/test) ...
[17:50:07]   [METRICS] OK (valid/test) | dt=0.55s
[17:50:07] [DONE] rows=2 | dt_total=216.11s
[OK] Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics/seq2one_metrics/seq2one_mlp_learning_tuning_delta_60_L180_metrics.parquet
[OK] Guardado incremental. Total rows=10

In [76]:
df_hp

,model,split,window_size,target,horizon_min,MAE,RMSE,R2,DA,hidden_dims,dropout,activation,lr,w_decay
0,mlp,test,180,delta_60,60,38.083891,60.026711,0.571634,0.784830,[256],0.2,relu,0.0005,0.00001
1,mlp,valid,180,delta_60,60,24.080995,35.637654,0.627908,0.783325,[256],0.2,relu,0.0005,0.00001
2,mlp,test,180,delta_60,60,38.270353,60.490109,0.564995,0.786203,[256],0.2,relu,0.0005,0.00010
3,mlp,valid,180,delta_60,60,24.023231,35.728128,0.626017,0.784366,[256],0.2,relu,0.0005,0.00010
4,mlp,test,180,delta_60,60,36.319312,57.737049,0.603690,0.792094,[256],0.2,relu,0.0010,0.00001
5,mlp,valid,180,delta_60,60,22.961283,33.864160,0.664021,0.788762,[256],0.2,relu,0.0010,0.00001
6,mlp,test,180,delta_60,60,36.682615,58.471111,0.593549,0.790954,[256],0.2,relu,0.0010,0.00010
7,mlp,valid,180,delta_60,60,22.605512,34.016163,0.660998,0.796279,[256],0.2,relu,0.0010,0.00010
8,mlp,test,180,delta_60,60,40.108800,61.694373,0.547502,0.759977,[256],0.2,relu,0.0020,0.00010
9,mlp,valid,180,delta_60,60,23.635401,35.053303,0.640011,0.781669,[256],0.2,relu,0.0020,0.00010

### **14.3. Resultados**

In [77]:
df_hp_valid = df_hp[df_hp["split"] == "valid"].copy()
df_hp_valid

,model,split,window_size,target,horizon_min,MAE,RMSE,R2,DA,hidden_dims,dropout,activation,lr,w_decay
1,mlp,valid,180,delta_60,60,24.080995,35.637654,0.627908,0.783325,[256],0.2,relu,0.0005,0.00001
3,mlp,valid,180,delta_60,60,24.023231,35.728128,0.626017,0.784366,[256],0.2,relu,0.0005,0.00010
5,mlp,valid,180,delta_60,60,22.961283,33.864160,0.664021,0.788762,[256],0.2,relu,0.0010,0.00001
7,mlp,valid,180,delta_60,60,22.605512,34.016163,0.660998,0.796279,[256],0.2,relu,0.0010,0.00010
9,mlp,valid,180,delta_60,60,23.635401,35.053303,0.640011,0.781669,[256],0.2,relu,0.0020,0.00010

## Tuning de Hiperparámetros de Aprendizaje  
### MLP SEQ2ONE – delta_60 (Selección en VALID)

En esta etapa se mantuvo fija la arquitectura previamente seleccionada:

- window_size = 180  
- hidden_dims = [256]  
- dropout = 0.2  
- activation = relu  

Se variaron únicamente los hiperparámetros de aprendizaje:

- learning rate (lr)  
- weight decay (regularización L2)  

La selección se realizó exclusivamente utilizando el conjunto **VALID**.

---

## 1. Comparación de configuraciones (VALID)

| lr     | w_decay | MAE     | RMSE    | R²      | DA      |
|--------|---------|---------|---------|---------|---------|
| 5e-4   | 1e-5    | 24.0810 | 35.6377 | 0.6279  | 0.7833  |
| 5e-4   | 1e-4    | 24.0232 | 35.7281 | 0.6260  | 0.7844  |
| 1e-3   | 1e-5    | 22.9613 | **33.8642** | **0.6640** | 0.7888  |
| 1e-3   | 1e-4    | **22.6055** | 34.0162 | 0.6610  | **0.7963** |
| 2e-3   | 1e-4    | 23.6354 | 35.0533 | 0.6400  | 0.7817  |

---

## 2. Interpretación técnica

### 2.1 Learning rate

- lr = 5e-4 → desempeño inferior (MAE elevado).
- lr = 1e-3 → mejor desempeño global.
- lr = 2e-3 → degradación del rendimiento.

**Conclusión:**  
El rango óptimo de aprendizaje se encuentra en torno a **1e-3**.

---

### 2.2 Weight decay

Para lr = 1e-3:

- w_decay = 1e-5 → mejor RMSE y mejor R².
- w_decay = 1e-4 → mejor MAE y mejor Directional Accuracy.

Diferencia en MAE:

22.9613 vs 22.6055
↓
Mejora ≈ 0.36 puntos


Aunque la diferencia es moderada, es consistente.

---

## 3. Criterio de selección

Dado que la métrica primaria del proyecto es **MAE (error absoluto en puntos)**, la configuración seleccionada es:

lr = 1e-3
weight_decay = 1e-4


Porque:

- Presenta el MAE más bajo en VALID.
- Obtiene la mayor Directional Accuracy.
- Mantiene un R² prácticamente equivalente al máximo observado.

---

## 4. Configuración final congelada

### Arquitectura
- window_size = 180  
- hidden_dims = [256]  
- dropout = 0.2  
- activation = relu  

### Hiperparámetros de entrenamiento
- learning_rate = 1e-3  
- weight_decay = 1e-4  

A partir de este punto, tanto arquitectura como hiperparámetros quedan congelados.

---

## 5. Observación relevante

El baseline original (`lr=1e-3`, `weight_decay=1e-4`) resultó prácticamente óptimo tras el tuning.

Esto sugiere:

- Estabilidad del proceso de entrenamiento.
- Baja sensibilidad extrema a ajustes finos.
- Robustez estructural del modelo seleccionado.

---

## Próximo paso

Evaluación final en TEST con la configuración completamente congelada y comparación frente a modelos alternativos previamente entrenados.