<a href="https://colab.research.google.com/github/GUNAPILLCO/neural_profit/blob/main/stage_08_model_tuning/stage_08_03_gru.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Stage_08_03 - Tuning - GRU**

**GRU**

- Tuneo grueso

  * `hidden_size` → capacidad del modelo

    * `[64, 128, 256]`
  * `num_layers`

    * `[1, 2]`
  * `learning_rate`

    * `[1e-4, 5e-4, 1e-3]`

- Tuneo fino

  * `dropout` → `[0.0, 0.1, 0.2, 0.3]`
  * `batch_size` → `[1024, 2048, 4096]`
  * `grad_clip_norm` → `[0.5, 1.0, 2.0]`
  * thresholds de probabilidad

# **SETUP COMÚN DEL PIPELINE DE ENTRENAMIENTO**

## **1. Imports**

In [1]:
# Permite anotaciones modernas en Python < 3.11
from __future__ import annotations

# ================================
# Standard library
# ================================
import os
import sys
import json
import time
import random
import importlib
import warnings
import logging
from pathlib import Path
from dataclasses import dataclass
from typing import Any, Dict, List, Iterable, Tuple

# ================================
# Third-party
# ================================
import numpy as np
import joblib

# ================================
# Configuración global
# ================================

# ---- Warnings (controlado, no agresivo)
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

# ---- Logging limpio para notebooks
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
logger.propagate = False  # evita duplicación con el root logger

# limpiar handlers si se re-ejecuta la celda
if logger.handlers:
    logger.handlers.clear()

handler = logging.StreamHandler()
formatter = logging.Formatter("%(asctime)s | %(levelname)s | %(message)s")
handler.setFormatter(formatter)
logger.addHandler(handler)

logger.info("Environment initialized")

2026-04-23 16:22:36,738 | INFO | Environment initialized

## **2. Acceso a drive**

In [2]:
# ================================
# Entorno (Google Drive / local)
# ================================

from pathlib import Path
import os

# Detectar si estamos en Colab
IN_COLAB = "google.colab" in sys.modules

if IN_COLAB:
    from google.colab import drive
    drive.mount("/content/drive", force_remount=False)

    DEFAULT_DRIVE_DIR = "/content/drive/MyDrive/neural_profit/"
else:
    # fallback local (puedes ajustarlo si quieres)
    DEFAULT_DRIVE_DIR = "./neural_profit/"

# Ruta base del proyecto
DRIVE_DIR = Path(os.environ.get("DRIVE_DIR", DEFAULT_DRIVE_DIR))

# Validación básica
if not DRIVE_DIR.exists():
    logger.warning(f"DRIVE_DIR no existe: {DRIVE_DIR}")
else:
    logger.info(f"DRIVE_DIR: {DRIVE_DIR}")

Mounted at /content/drive

2026-04-23 16:23:10,356 | INFO | DRIVE_DIR: /content/drive/MyDrive/neural_profit

## **3. Rutas de ventanas `seq2one` y `scaler`**

In [3]:
# ================================
# Configuración de paths
# ================================

WINDOWS_SEQ2ONE_DIR = DRIVE_DIR / os.environ.get(
    "WINDOWS_SEQ2ONE_DIR",
    "data/07_windows/seq2one/"
)

SCALERS_DIR = DRIVE_DIR / os.environ.get(
    "SCALERS_DIR",
    "data/06_scaled/"
)

# Validación básica
for p in [WINDOWS_SEQ2ONE_DIR, SCALERS_DIR]:
    if not p.exists():
        logger.warning(f"Path no existe: {p}")
    else:
        logger.info(f"Path OK: {p}")

# ================================
# Configuración del experimento
# ================================

# Targets T2 (clasificación)
TARGETS = [
  "t2_p40_h30",
  "t2_p40_h60",
  "t2_p50_h30",
]

# Tamaños de ventana
WINDOW_SIZES = [30]

# Splits
SPLITS = ["train", "valid", "test"]

# Features finales (consistencia global)
FEATURES_T2 = [
        "ema_60",
        "roc_60",
        "roc_30",
        "stoch_k_30",
        "mom_5",
        "atr_norm_10",
        "macd"
]

logger.info("Configuración de experimento cargada")
logger.info(f"Targets: {TARGETS}")
logger.info(f"Window sizes: {WINDOW_SIZES}")

2026-04-23 16:23:11,643 | INFO | Path OK: /content/drive/MyDrive/neural_profit/data/07_windows/seq2one
2026-04-23 16:23:11,644 | INFO | Path OK: /content/drive/MyDrive/neural_profit/data/06_scaled
2026-04-23 16:23:11,644 | INFO | Configuración de experimento cargada
2026-04-23 16:23:11,645 | INFO | Targets: ['t2_p40_h30', 't2_p40_h60', 't2_p50_h30']
2026-04-23 16:23:11,646 | INFO | Window sizes: [30]

In [4]:
# ================================
# Construcción y validación de paths (windows + scaler compartido)
# ================================

def build_windows_paths(window_sizes, targets, splits, base_dir):
    """
    windows_paths[w][t][s] -> Path
    """
    windows_paths = {}

    for w in window_sizes:
        windows_paths[w] = {}
        for t in targets:
            windows_paths[w][t] = {}
            for s in splits:
                windows_paths[w][t][s] = (
                    base_dir
                    / f"L{w}"
                    / f"windows_{t}_{s}.npz"
                )

    return windows_paths


def build_shared_scaler_path(base_dir, scaler_name="scaler_t2.pkl"):
    """
    Retorna el path del scaler compartido para T2.
    """
    return base_dir / scaler_name


# ================================
# Construcción
# ================================

WINDOWS_PATHS = build_windows_paths(
    window_sizes=WINDOW_SIZES,
    targets=TARGETS,
    splits=SPLITS,
    base_dir=WINDOWS_SEQ2ONE_DIR,
)

SCALER_T2_PATH = build_shared_scaler_path(
    base_dir=SCALERS_DIR,
    scaler_name="scaler_mnq_t2.pkl",
)

logger.info("Paths construidos (windows + scaler compartido T2)")

# ================================
# Validación
# ================================

missing_windows = []
existing_windows = []

for w in WINDOW_SIZES:
    for t in TARGETS:
        for s in SPLITS:
            p = WINDOWS_PATHS[w][t][s]
            if p.exists():
                existing_windows.append(p)
            else:
                missing_windows.append(p)

scaler_exists = SCALER_T2_PATH.exists()

# -------------------------------
# Logs
# -------------------------------
logger.info(f"Windows OK      : {len(existing_windows)}")
logger.info(f"Windows missing : {len(missing_windows)}")

if scaler_exists:
    logger.info(f"Scaler T2 OK    : {SCALER_T2_PATH}")
else:
    logger.warning(f"Scaler T2 missing: {SCALER_T2_PATH}")

if missing_windows:
    logger.warning("Archivos de ventanas faltantes:")
    for p in missing_windows[:10]:
        logger.warning(f"Missing window: {p}")

if not missing_windows and scaler_exists:
    logger.info("Todos los archivos existen correctamente")

# ================================
# Ejemplo de uso
# ================================

# window
# WINDOWS_PATHS[30]["t2_p40_h30"]["train"]

# scaler compartido
# SCALER_T2_PATH

2026-04-23 16:23:11,655 | INFO | Paths construidos (windows + scaler compartido T2)
2026-04-23 16:23:12,528 | INFO | Windows OK      : 9
2026-04-23 16:23:12,529 | INFO | Windows missing : 0
2026-04-23 16:23:12,530 | INFO | Scaler T2 OK    : /content/drive/MyDrive/neural_profit/data/06_scaled/scaler_mnq_t2.pkl
2026-04-23 16:23:12,530 | INFO | Todos los archivos existen correctamente

## **4. Carga de ventanas X/y**

### **4.1. Cargar ventanas (*.npz)**

In [5]:
from pathlib import Path
from typing import Tuple
import numpy as np


def load_npz_windows(path: Path) -> Tuple[np.ndarray, np.ndarray]:
    """
    Carga ventanas X e y desde un archivo .npz estándar (T2 seq2one).

    Espera:
    - 'X': (n_samples, seq_len, n_features)
    - 'y' o 'Y': (n_samples,) o (n_samples, 1) o (n_samples, seq_len, 1)

    Retorna
    -------
    X : np.ndarray  -> (n_samples, seq_len, n_features)
    y : np.ndarray  -> (n_samples,)
    """

    # --------------------------------------------------
    # 1. Validación
    # --------------------------------------------------
    if not path.exists():
        raise FileNotFoundError(f"No se encontró el archivo: {path}")

    # --------------------------------------------------
    # 2. Carga
    # --------------------------------------------------
    with np.load(path) as data:

        if "X" not in data:
            raise KeyError(f"NPZ inválido (falta clave 'X'): {path}")

        X = data["X"]

        if "y" in data:
            y = data["y"]
        elif "Y" in data:
            y = data["Y"]
        else:
            raise KeyError(f"NPZ inválido (falta clave 'y'/'Y'): {path}")

        # copiar a memoria
        X = X.copy()
        y = y.copy()

    # --------------------------------------------------
    # 3. Ajuste de shape de y (CRÍTICO)
    # --------------------------------------------------
    # Caso (n_samples, 1)
    if y.ndim == 2 and y.shape[1] == 1:
        y = y.reshape(-1)

    # Caso (n_samples, seq_len, 1) -> tomar último valor
    elif y.ndim == 3:
        y = y[:, -1, 0]

    # Caso (n_samples, seq_len) -> tomar último valor
    elif y.ndim == 2 and y.shape[1] > 1:
        y = y[:, -1]

    # Validación final
    if y.ndim != 1:
        raise ValueError(f"y no es 1D después de procesamiento: shape={y.shape}")

    # --------------------------------------------------
    # 4. Logs útiles
    # --------------------------------------------------
    logger.info(f"Loaded: {path.name}")
    logger.info(f"X shape: {X.shape} | y shape: {y.shape}")

    return X, y

### **4.2. Cargar escalador (*.pkl)**

In [6]:
# --------------------------------------------------
# Función común: carga scaler compartido (T2)
# --------------------------------------------------
def load_scaler(path: Path) -> Any:
    """
    Carga un scaler serializado con joblib.

    Parámetros
    ----------
    path : Path
        Ruta al archivo scaler (.pkl)

    Retorna
    -------
    scaler : Any
        Objeto scaler (ej. StandardScaler, MinMaxScaler)
    """

    # --------------------------------------------------
    # 1. Validación de existencia
    # --------------------------------------------------
    if not path.exists():
        raise FileNotFoundError(f"No se encontró el scaler: {path}")

    # --------------------------------------------------
    # 2. Carga
    # --------------------------------------------------
    scaler = joblib.load(path)

    # --------------------------------------------------
    # 3. Validación básica (opcional pero útil)
    # --------------------------------------------------
    if not hasattr(scaler, "transform"):
        raise TypeError(f"El objeto cargado no es un scaler válido: {type(scaler)}")

    # --------------------------------------------------
    # 4. Logging
    # --------------------------------------------------
    logger.info(f"Scaler cargado: {path.name}")

    return scaler

### **4.3. Función de carga**

In [7]:
from typing import Any, Dict, Mapping
from pathlib import Path


# --------------------------------------------------
# Carga completa: ventanas + scaler compartido T2
# --------------------------------------------------
def load_windows_and_scaler(
    *,
    window_size: int,
    target: str,
    windows_paths: Mapping[int, Mapping[str, Mapping[str, Path]]],
    scaler_path: Path,
) -> Dict[str, Any]:
    """
    Carga X/y (train/valid/test) y el scaler compartido T2
    para un par (window_size, target).

    Parámetros
    ----------
    window_size : int
        Tamaño de ventana.
    target : str
        Target T2, por ejemplo:
        - 't2_p40_h30'
        - 't2_p40_h60'
        - 't2_p50_h30'
    windows_paths : mapping
        Estructura:
        windows_paths[window_size][target][split] -> Path
    scaler_path : Path
        Ruta al scaler compartido T2.

    Retorna
    -------
    bundle : dict
        Diccionario con:
        - metadata
        - paths
        - scaler
        - train/valid/test con X e y
    """

    # --------------------------
    # 1) Validaciones
    # --------------------------
    if window_size not in windows_paths:
        raise KeyError(f"window_size={window_size} no existe en windows_paths")

    if target not in windows_paths[window_size]:
        raise KeyError(f"target='{target}' no existe en windows_paths[{window_size}]")

    for split in ["train", "valid", "test"]:
        if split not in windows_paths[window_size][target]:
            raise KeyError(
                f"split='{split}' no existe en windows_paths[{window_size}]['{target}']"
            )

    if not scaler_path.exists():
        raise FileNotFoundError(f"No se encontró el scaler compartido: {scaler_path}")

    # --------------------------
    # 2) Paths
    # --------------------------
    train_path = windows_paths[window_size][target]["train"]
    valid_path = windows_paths[window_size][target]["valid"]
    test_path  = windows_paths[window_size][target]["test"]

    # --------------------------
    # 3) Carga de ventanas
    # --------------------------
    X_train, y_train = load_npz_windows(train_path)
    X_valid, y_valid = load_npz_windows(valid_path)
    X_test, y_test   = load_npz_windows(test_path)

    # --------------------------
    # 4) Carga de scaler
    # --------------------------
    scaler = load_scaler(scaler_path)

    # --------------------------
    # 5) Inferir horizonte
    # --------------------------
    try:
        horizon_str = target.split("_")[-1]   # ej: "h30"
        horizon = int(horizon_str.replace("h", ""))
    except Exception:
        horizon = None

    # --------------------------
    # 6) Logging
    # --------------------------
    logger.info(
        f"Bundle cargado | target={target} | window_size={window_size} | "
        f"train={X_train.shape} | valid={X_valid.shape} | test={X_test.shape}"
    )

    # --------------------------
    # 7) Retorno
    # --------------------------
    return {
        "window_size": window_size,
        "target": target,
        "horizon": horizon,
        "paths": {
            "train": str(train_path),
            "valid": str(valid_path),
            "test": str(test_path),
            "scaler": str(scaler_path),
        },
        "scaler": scaler,
        "train": {
            "X": X_train,
            "y": y_train,
        },
        "valid": {
            "X": X_valid,
            "y": y_valid,
        },
        "test": {
            "X": X_test,
            "y": y_test,
        },
    }

### **4.4. Creación de bundles T2**

In [8]:
def create_bundles(
    window_size: int,
    targets: list[str] = TARGETS,
    windows_paths=WINDOWS_PATHS,
    scaler_path=SCALER_T2_PATH,
):
    """
    Crea un bundle por target para un window_size dado.

    Retorna
    -------
    bundles : dict
        bundles[target] -> bundle dict
    """

    bundles = {}

    # --------------------------
    # Construcción
    # --------------------------
    for target in targets:
        bundles[target] = load_windows_and_scaler(
            window_size=window_size,
            target=target,
            windows_paths=windows_paths,
            scaler_path=scaler_path,
        )

    # --------------------------
    # Verificación rápida
    # --------------------------
    print(f"\n{'=' * 70}")
    print(f"WINDOW_SIZE: {window_size}")
    print(f"{'=' * 70}")

    for target in targets:
        b = bundles[target]

        print(f"\nTARGET: {target}")
        print("Train :", b["train"]["X"].shape, b["train"]["y"].shape)
        print("Valid :", b["valid"]["X"].shape, b["valid"]["y"].shape)
        print("Test  :", b["test"]["X"].shape,  b["test"]["y"].shape)
        print("Scaler:", type(b["scaler"]).__name__)

    return bundles

In [9]:
bundles_L30 = create_bundles(window_size=30)

2026-04-23 16:23:13,966 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:23:13,967 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:23:14,628 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:23:14,629 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:23:15,536 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:23:15,536 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:23:17,659 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:23:17,659 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:23:20,784 | INFO | Loaded: windows_t2_p40_h60_train.npz
2026-04-23 16:23:20,785 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:23:21,753 | INFO | Loaded: windows_t2_p40_h60_valid.npz
2026-04-23 16:23:21,754 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:23:22,565 | INFO | Loaded: windows_t2_p40_h60_test.npz
2026-04-23 16:23:22,565 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:23:22,569 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:23:22,569 | INFO | Bundle cargado | target=t2_p40_h60 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:23:24,422 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:23:24,423 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:23:25,326 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:23:25,327 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:23:26,785 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:23:26,786 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:23:26,789 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:23:26,790 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p40_h60
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

Como acceder a las ventanas X e y:

```python
bundle_p40_h30 = bundles_L30["t2_p40_h30"]

X_train = bundle_p40_h30["train"]["X"]
y_train = bundle_p40_h30["train"]["y"]

X_valid = bundle_p40_h30["valid"]["X"]
y_valid = bundle_p40_h30["valid"]["y"]

X_test = bundle_p40_h30["test"]["X"]
y_test = bundle_p40_h30["test"]["y"]

scaler = bundle_p40_h30["scaler"]

print("Target :", bundle_p40_h30["target"])
print("Horizon:", bundle_p40_h30["horizon"])
print("Train  :", X_train.shape, y_train.shape)
print("Valid  :", X_valid.shape, y_valid.shape)
print("Test   :", X_test.shape, y_test.shape)
print("Scaler :", type(scaler).__name__)
```

In [10]:
bundles_L30

{'t2_p40_h30': {'window_size': 30,
  'target': 't2_p40_h30',
  'horizon': 30,
  'paths': {'train': '/content/drive/MyDrive/neural_profit/data/07_windows/seq2one/L30/windows_t2_p40_h30_train.npz',
   'valid': '/content/drive/MyDrive/neural_profit/data/07_windows/seq2one/L30/windows_t2_p40_h30_valid.npz',
   'test': '/content/drive/MyDrive/neural_profit/data/07_windows/seq2one/L30/windows_t2_p40_h30_test.npz',
   'scaler': '/content/drive/MyDrive/neural_profit/data/06_scaled/scaler_mnq_t2.pkl'},
  'scaler': StandardScaler(),
  'train': {'X': array([[[-0.11680385, -0.06583842, -0.2238865 , ..., -0.04129868,
            -1.507039  , -0.02778307],
           [ 0.0909589 ,  0.05818945, -0.07248875, ...,  0.3872164 ,
            -1.3723946 ,  0.08631181],
           [-0.18229802, -0.13053213, -0.21077001, ..., -0.1151728 ,
            -1.2194692 ,  0.02307655],
           ...,
           [ 0.40151003,  0.28442496,  0.59289074, ...,  0.47497907,
            -1.0690751 , -0.19294474],
           [ 0.48057374,  0.33290818,  0.69842666, ...,  0.5486468 ,
            -1.096222  , -0.05818947],
           [ 0.35272706,  0.27904537,  0.5598997 , ...,  0.5193024 ,
            -1.0535853 , -0.03214845]],

          [[ 0.0909589 ,  0.05818945, -0.07248875, ...,  0.3872164 ,
            -1.3723946 ,  0.08631181],
           [-0.18229802, -0.13053213, -0.21077001, ..., -0.1151728 ,
            -1.2194692 ,  0.02307655],
           [-0.06536855, -0.10894598, -0.0264139 , ...,  0.15079567,
            -1.185231  ,  0.03934627],
           ...,
           [ 0.48057374,  0.33290818,  0.69842666, ...,  0.5486468 ,
            -1.096222  , -0.05818947],
           [ 0.35272706,  0.27904537,  0.5598997 , ...,  0.5193024 ,
            -1.0535853 , -0.03214845],
           [ 0.5169626 ,  0.40302435,  0.7048929 , ...,  0.6814119 ,
            -1.0416261 ,  0.06614138]],

          [[-0.18229802, -0.13053213, -0.21077001, ..., -0.1151728 ,
            -1.2194692 ,  0.02307655],
           [-0.06536855, -0.10894598, -0.0264139 , ...,  0.15079567,
            -1.185231  ,  0.03934627],
           [ 0.29877228,  0.09588703,  0.19092916, ...,  0.5939512 ,
            -1.021974  ,  0.22790259],
           ...,
           [ 0.35272706,  0.27904537,  0.5598997 , ...,  0.5193024 ,
            -1.0535853 , -0.03214845],
           [ 0.5169626 ,  0.40302435,  0.7048929 , ...,  0.6814119 ,
            -1.0416261 ,  0.06614138],
           [ 0.26721224,  0.27369905,  0.39498132, ...,  0.01772826,
            -0.97849196,  0.00327425]],

          ...,

          [[-0.5089691 , -0.5938694 , -0.8091699 , ..., -0.13298607,
            -0.9649065 ,  0.42550054],
           [-0.37185302, -0.53930634, -0.6919696 , ..., -0.0046208 ,
            -0.97516584,  0.58679634],
           [-0.18540893, -0.4276997 , -0.60310847, ...,  0.2520691 ,
            -0.93760353,  0.86246175],
           ...,
           [ 0.21873358, -0.20961736,  0.37126327, ...,  0.30876938,
            -1.2857738 ,  0.21861549],
           [ 0.20196198, -0.26148045,  0.3935713 , ...,  0.30165097,
            -1.3082111 ,  0.2967786 ],
           [ 0.19919315, -0.2537004 ,  0.6071964 , ...,  0.3301561 ,
            -1.308665  ,  0.32644603]],

          [[-0.37185302, -0.53930634, -0.6919696 , ..., -0.0046208 ,
            -0.97516584,  0.58679634],
           [-0.18540893, -0.4276997 , -0.60310847, ...,  0.2520691 ,
            -0.93760353,  0.86246175],
           [-0.153053  , -0.36288396, -0.47968507, ...,  0.35906896,
            -0.9676904 ,  1.0425373 ],
           ...,
           [ 0.20196198, -0.26148045,  0.3935713 , ...,  0.30165097,
            -1.3082111 ,  0.2967786 ],
           [ 0.19919315, -0.2537004 ,  0.6071964 , ...,  0.3301561 ,
            -1.308665  ,  0.32644603],
           [ 0.16064383, -0.29519528,  0.4382164 , ...,  0.35157496,
            -1.3287635 ,  0.28683305]],

          [[-0.18540893, -0.4276997 , -0.60310847, ...,  0.2520691 ,
            -0.93760353,  0.86246175],
           [-0.153053  , -0.36288396, -0.47968507, ...,  0.35906896,
            -0.9676904 ,  1.0425373 ],
           [-0.18005393, -0.34736055, -0.55567527, ...,  0.78052276,
            -1.0044805 ,  1.0914437 ],
           ...,
           [ 0.19919315, -0.2537004 ,  0.6071964 , ...,  0.3301561 ,
            -1.308665  ,  0.32644603],
           [ 0.16064383, -0.29519528,  0.4382164 , ...,  0.35157496,
            -1.3287635 ,  0.28683305],
           [ 0.15026338, -0.27187246,  0.3490162 , ...,  0.159165  ,
            -1.3592631 ,  0.2326271 ]]], dtype=float32),
   'y': array([-1, -1, -1, ...,  0,  0,  0], dtype=int8)},
  'valid': {'X': array([[[-0.01797212, -0.24633172,  0.14247243, ..., -0.11870122,
            -1.4548776 , -0.35338983],
           [ 0.2827738 ,  0.70315224,  0.46411356, ...,  0.2734014 ,
            -1.3050504 , -0.09317604],
           [ 0.22348776,  0.7399675 ,  0.4003854 , ...,  0.18072149,
            -1.2462628 ,  0.01512693],
           ...,
           [ 0.18818419,  0.28970504,  0.27580673, ..., -0.33193523,
            -1.1241578 , -0.5910114 ],
           [ 0.11411569,  0.30020246,  0.24403623, ..., -0.4599904 ,
            -1.1428092 , -0.75425917],
           [ 0.13665295,  0.36801454,  0.30768037, ..., -0.34619758,
            -1.1796142 , -0.8088358 ]],

          [[ 0.2827738 ,  0.70315224,  0.46411356, ...,  0.2734014 ,
            -1.3050504 , -0.09317604],
           [ 0.22348776,  0.7399675 ,  0.4003854 , ...,  0.18072149,
            -1.2462628 ,  0.01512693],
           [ 0.22899517,  0.43101314,  0.40036815, ...,  0.23776756,
            -1.2157528 ,  0.08647836],
           ...,
           [ 0.11411569,  0.30020246,  0.24403623, ..., -0.4599904 ,
            -1.1428092 , -0.75425917],
           [ 0.13665295,  0.36801454,  0.30768037, ..., -0.34619758,
            -1.1796142 , -0.8088358 ],
           [-0.08371288,  0.2795107 ,  0.1868808 , ..., -0.64511627,
            -1.1181315 , -1.037442  ]],

          [[ 0.22348776,  0.7399675 ,  0.4003854 , ...,  0.18072149,
            -1.2462628 ,  0.01512693],
           [ 0.22899517,  0.43101314,  0.40036815, ...,  0.23776756,
            -1.2157528 ,  0.08647836],
           [-0.14724576,  0.3765885 ,  0.17119715, ..., -0.24705712,
            -1.0634754 , -0.2578135 ],
           ...,
           [ 0.13665295,  0.36801454,  0.30768037, ..., -0.34619758,
            -1.1796142 , -0.8088358 ],
           [-0.08371288,  0.2795107 ,  0.1868808 , ..., -0.64511627,
            -1.1181315 , -1.037442  ],
           [-0.08607977,  0.36566493, -0.02935827, ..., -0.54559517,
            -1.075667  , -1.1459628 ]],

          ...,

          [[-0.7747873 , -0.75870997, -0.26651144, ...,  0.0080273 ,
            -0.25995776, -1.7303042 ],
           [-0.6837994 , -0.70840716, -0.27232748, ...,  0.4302407 ,
            -0.34129897, -1.3003138 ],
           [-0.9064192 , -0.82598984, -0.47485787, ...,  0.05421926,
            -0.34884164, -1.2012448 ],
           ...,
           [ 1.0858637 ,  0.8712395 ,  1.5864046 , ...,  0.6048454 ,
            -0.34754562,  1.7194406 ],
           [ 1.1157135 ,  0.95316535,  1.5771952 , ...,  0.4012554 ,
            -0.34113368,  1.472635  ],
           [ 0.9956538 ,  0.95824516,  1.3231384 , ...,  0.06033191,
            -0.38693458,  1.0980405 ]],

          [[-0.6837994 , -0.70840716, -0.27232748, ...,  0.4302407 ,
            -0.34129897, -1.3003138 ],
           [-0.9064192 , -0.82598984, -0.47485787, ...,  0.05421926,
            -0.34884164, -1.2012448 ],
           [-0.9851026 , -0.8429714 , -0.5336105 , ..., -0.24259308,
            -0.30812123, -1.161224  ],
           ...,
           [ 1.1157135 ,  0.95316535,  1.5771952 , ...,  0.4012554 ,
            -0.34113368,  1.472635  ],
           [ 0.9956538 ,  0.95824516,  1.3231384 , ...,  0.06033191,
            -0.38693458,  1.0980405 ],
           [ 0.91678774,  0.9245494 ,  1.3854185 , ..., -0.04451444,
            -0.44651634,  0.70160484]],

          [[-0.9064192 , -0.82598984, -0.47485787, ...,  0.05421926,
            -0.34884164, -1.2012448 ],
           [-0.9851026 , -0.8429714 , -0.5336105 , ..., -0.24259308,
            -0.30812123, -1.161224  ],
           [-0.41084066, -0.55029976, -0.4186467 , ...,  0.18594785,
            -0.1651649 , -0.44004887],
           ...,
           [ 0.9956538 ,  0.95824516,  1.3231384 , ...,  0.06033191,
            -0.38693458,  1.0980405 ],
           [ 0.91678774,  0.9245494 ,  1.3854185 , ..., -0.04451444,
            -0.44651634,  0.70160484],
           [ 0.8281175 ,  0.84741765,  1.2969568 , ..., -0.42433786,
            -0.5023491 ,  0.29693204]]], dtype=float32),
   'y': array([1, 1, 1, ..., 1, 1, 0], dtype=int8)},
  'test': {'X': array([[[-0.3518573 , -0.22331987, -0.42215154, ..., -0.21469618,
            -1.1491929 ,  0.35514992],
           [-0.85998815, -0.4837476 , -0.56553304, ..., -0.9350084 ,
            -0.90137845, -0.2984129 ],
           [-0.04977896, -0.16831307, -0.0314985 , ...,  0.25013593,
            -0.5738777 ,  0.18791221],
           ...,
           [ 0.30481556, -0.14437935,  0.24585441, ...,  1.1549219 ,
             0.03481962,  0.67033845],
           [ 0.42192152, -0.02508554,  0.29250872, ...,  1.0822464 ,
            -0.03409563,  1.0455434 ],
           [ 0.45688668,  0.0512996 ,  0.47672513, ...,  1.1739886 ,
            -0.10929676,  1.278799  ]],

          [[-0.85998815, -0.4837476 , -0.56553304, ..., -0.9350084 ,
            -0.90137845, -0.2984129 ],
           [-0.04977896, -0.16831307, -0.0314985 , ...,  0.25013593,
            -0.5738777 ,  0.18791221],
           [-0.31240875, -0.33777052, -0.25614282, ..., -0.26704338,
            -0.5025666 ,  0.20174503],
           ...,
           [ 0.42192152, -0.02508554,  0.29250872, ...,  1.0822464 ,
            -0.03409563,  1.0455434 ],
           [ 0.45688668,  0.0512996 ,  0.47672513, ...,  1.1739886 ,
            -0.10929676,  1.278799  ],
           [ 0.41241843,  0.00832834,  0.42116165, ...,  0.8262985 ,
            -0.15384822,  1.3210764 ]],

          [[-0.04977896, -0.16831307, -0.0314985 , ...,  0.25013593,
            -0.5738777 ,  0.18791221],
           [-0.31240875, -0.33777052, -0.25614282, ..., -0.26704338,
            -0.5025666 ,  0.20174503],
           [-0.17097744, -0.18984532, -0.16278334, ...,  0.27645496,
            -0.45601413,  0.3570339 ],
           ...,
           [ 0.45688668,  0.0512996 ,  0.47672513, ...,  1.1739886 ,
            -0.10929676,  1.278799  ],
           [ 0.41241843,  0.00832834,  0.42116165, ...,  0.8262985 ,
            -0.15384822,  1.3210764 ],
           [ 0.2087319 ,  0.08241834,  0.6558675 , ...,  0.06674679,
            -0.13626383,  1.0601416 ]],

          ...,

          [[ 0.08711008, -0.07077762,  0.18922526, ..., -0.26533416,
            -0.04259495,  0.70301336],
           [ 0.11742187, -0.11526359,  0.1281977 , ..., -0.11905547,
            -0.07287768,  0.6782663 ],
           [ 0.34643042, -0.08852473,  0.33069858, ...,  0.38830507,
            -0.13687235,  0.9777634 ],
           ...,
           [ 0.08398844, -0.10806419,  0.21731   , ..., -0.15305226,
            -0.66461414, -1.2906679 ],
           [ 0.07753816, -0.02447833,  0.29573965, ..., -0.06535777,
            -0.7274043 , -1.2071035 ],
           [ 0.01298816,  0.09304444,  0.23260511, ..., -0.34789032,
            -0.73123205, -1.1974655 ]],

          [[ 0.11742187, -0.11526359,  0.1281977 , ..., -0.11905547,
            -0.07287768,  0.6782663 ],
           [ 0.34643042, -0.08852473,  0.33069858, ...,  0.38830507,
            -0.13687235,  0.9777634 ],
           [ 0.54332584,  0.18918473,  0.50711393, ...,  0.9008885 ,
            -0.16732372,  1.425977  ],
           ...,
           [ 0.07753816, -0.02447833,  0.29573965, ..., -0.06535777,
            -0.7274043 , -1.2071035 ],
           [ 0.01298816,  0.09304444,  0.23260511, ..., -0.34789032,
            -0.73123205, -1.1974655 ],
           [ 0.03648783,  0.3285003 ,  0.19991577, ..., -0.06536379,
            -0.74176717, -1.1039711 ]],

          [[ 0.34643042, -0.08852473,  0.33069858, ...,  0.38830507,
            -0.13687235,  0.9777634 ],
           [ 0.54332584,  0.18918473,  0.50711393, ...,  0.9008885 ,
            -0.16732372,  1.425977  ],
           [ 0.5371427 ,  0.2587178 ,  0.5267365 , ...,  0.87641156,
            -0.2900976 ,  1.6481007 ],
           ...,
           [ 0.01298816,  0.09304444,  0.23260511, ..., -0.34789032,
            -0.73123205, -1.1974655 ],
           [ 0.03648783,  0.3285003 ,  0.19991577, ..., -0.06536379,
            -0.74176717, -1.1039711 ],
           [ 0.12366477,  0.31055117,  0.23905112, ...,  0.19787344,
            -0.7768869 , -0.86433077]]], dtype=float32),
   'y': array([1, 1, 1, ..., 1, 1, 1], dtype=int8)}},
 't2_p40_h60': {'window_size': 30,
  'target': 't2_p40_h60',
  'horizon': 60,
  'paths': {'train': '/content/drive/MyDrive/neural_profit/data/07_windows/seq2one/L30/windows_t2_p40_h60_train.npz',
   'valid': '/content/drive/MyDrive/neural_profit/data/07_windows/seq2one/L30/windows_t2_p40_h60_valid.npz',
   'test': '/content/drive/MyDrive/neural_profit/data/07_windows/seq2one/L30/windows_t2_p40_h60_test.npz',
   'scaler': '/content/drive/MyDrive/neural_profit/data/06_scaled/scaler_mnq_t2.pkl'},
  'scaler': StandardScaler(),
  'train': {'X': array([[[-0.11680385, -0.06583842, -0.2238865 , ..., -0.04129868,
            -1.507039  , -0.02778307],
           [ 0.0909589 ,  0.05818945, -0.07248875, ...,  0.3872164 ,
            -1.3723946 ,  0.08631181],
           [-0.18229802, -0.13053213, -0.21077001, ..., -0.1151728 ,
            -1.2194692 ,  0.02307655],
           ...,
           [ 0.40151003,  0.28442496,  0.59289074, ...,  0.47497907,
            -1.0690751 , -0.19294474],
           [ 0.48057374,  0.33290818,  0.69842666, ...,  0.5486468 ,
            -1.096222  , -0.05818947],
           [ 0.35272706,  0.27904537,  0.5598997 , ...,  0.5193024 ,
            -1.0535853 , -0.03214845]],

          [[ 0.0909589 ,  0.05818945, -0.07248875, ...,  0.3872164 ,
            -1.3723946 ,  0.08631181],
           [-0.18229802, -0.13053213, -0.21077001, ..., -0.1151728 ,
            -1.2194692 ,  0.02307655],
           [-0.06536855, -0.10894598, -0.0264139 , ...,  0.15079567,
            -1.185231  ,  0.03934627],
           ...,
           [ 0.48057374,  0.33290818,  0.69842666, ...,  0.5486468 ,
            -1.096222  , -0.05818947],
           [ 0.35272706,  0.27904537,  0.5598997 , ...,  0.5193024 ,
            -1.0535853 , -0.03214845],
           [ 0.5169626 ,  0.40302435,  0.7048929 , ...,  0.6814119 ,
            -1.0416261 ,  0.06614138]],

          [[-0.18229802, -0.13053213, -0.21077001, ..., -0.1151728 ,
            -1.2194692 ,  0.02307655],
           [-0.06536855, -0.10894598, -0.0264139 , ...,  0.15079567,
            -1.185231  ,  0.03934627],
           [ 0.29877228,  0.09588703,  0.19092916, ...,  0.5939512 ,
            -1.021974  ,  0.22790259],
           ...,
           [ 0.35272706,  0.27904537,  0.5598997 , ...,  0.5193024 ,
            -1.0535853 , -0.03214845],
           [ 0.5169626 ,  0.40302435,  0.7048929 , ...,  0.6814119 ,
            -1.0416261 ,  0.06614138],
           [ 0.26721224,  0.27369905,  0.39498132, ...,  0.01772826,
            -0.97849196,  0.00327425]],

          ...,

          [[-0.5089691 , -0.5938694 , -0.8091699 , ..., -0.13298607,
            -0.9649065 ,  0.42550054],
           [-0.37185302, -0.53930634, -0.6919696 , ..., -0.0046208 ,
            -0.97516584,  0.58679634],
           [-0.18540893, -0.4276997 , -0.60310847, ...,  0.2520691 ,
            -0.93760353,  0.86246175],
           ...,
           [ 0.21873358, -0.20961736,  0.37126327, ...,  0.30876938,
            -1.2857738 ,  0.21861549],
           [ 0.20196198, -0.26148045,  0.3935713 , ...,  0.30165097,
            -1.3082111 ,  0.2967786 ],
           [ 0.19919315, -0.2537004 ,  0.6071964 , ...,  0.3301561 ,
            -1.308665  ,  0.32644603]],

          [[-0.37185302, -0.53930634, -0.6919696 , ..., -0.0046208 ,
            -0.97516584,  0.58679634],
           [-0.18540893, -0.4276997 , -0.60310847, ...,  0.2520691 ,
            -0.93760353,  0.86246175],
           [-0.153053  , -0.36288396, -0.47968507, ...,  0.35906896,
            -0.9676904 ,  1.0425373 ],
           ...,
           [ 0.20196198, -0.26148045,  0.3935713 , ...,  0.30165097,
            -1.3082111 ,  0.2967786 ],
           [ 0.19919315, -0.2537004 ,  0.6071964 , ...,  0.3301561 ,
            -1.308665  ,  0.32644603],
           [ 0.16064383, -0.29519528,  0.4382164 , ...,  0.35157496,
            -1.3287635 ,  0.28683305]],

          [[-0.18540893, -0.4276997 , -0.60310847, ...,  0.2520691 ,
            -0.93760353,  0.86246175],
           [-0.153053  , -0.36288396, -0.47968507, ...,  0.35906896,
            -0.9676904 ,  1.0425373 ],
           [-0.18005393, -0.34736055, -0.55567527, ...,  0.78052276,
            -1.0044805 ,  1.0914437 ],
           ...,
           [ 0.19919315, -0.2537004 ,  0.6071964 , ...,  0.3301561 ,
            -1.308665  ,  0.32644603],
           [ 0.16064383, -0.29519528,  0.4382164 , ...,  0.35157496,
            -1.3287635 ,  0.28683305],
           [ 0.15026338, -0.27187246,  0.3490162 , ...,  0.159165  ,
            -1.3592631 ,  0.2326271 ]]], dtype=float32),
   'y': array([0, 0, 0, ..., 0, 0, 0], dtype=int8)},
  'valid': {'X': array([[[-0.01797212, -0.24633172,  0.14247243, ..., -0.11870122,
            -1.4548776 , -0.35338983],
           [ 0.2827738 ,  0.70315224,  0.46411356, ...,  0.2734014 ,
            -1.3050504 , -0.09317604],
           [ 0.22348776,  0.7399675 ,  0.4003854 , ...,  0.18072149,
            -1.2462628 ,  0.01512693],
           ...,
           [ 0.18818419,  0.28970504,  0.27580673, ..., -0.33193523,
            -1.1241578 , -0.5910114 ],
           [ 0.11411569,  0.30020246,  0.24403623, ..., -0.4599904 ,
            -1.1428092 , -0.75425917],
           [ 0.13665295,  0.36801454,  0.30768037, ..., -0.34619758,
            -1.1796142 , -0.8088358 ]],

          [[ 0.2827738 ,  0.70315224,  0.46411356, ...,  0.2734014 ,
            -1.3050504 , -0.09317604],
           [ 0.22348776,  0.7399675 ,  0.4003854 , ...,  0.18072149,
            -1.2462628 ,  0.01512693],
           [ 0.22899517,  0.43101314,  0.40036815, ...,  0.23776756,
            -1.2157528 ,  0.08647836],
           ...,
           [ 0.11411569,  0.30020246,  0.24403623, ..., -0.4599904 ,
            -1.1428092 , -0.75425917],
           [ 0.13665295,  0.36801454,  0.30768037, ..., -0.34619758,
            -1.1796142 , -0.8088358 ],
           [-0.08371288,  0.2795107 ,  0.1868808 , ..., -0.64511627,
            -1.1181315 , -1.037442  ]],

          [[ 0.22348776,  0.7399675 ,  0.4003854 , ...,  0.18072149,
            -1.2462628 ,  0.01512693],
           [ 0.22899517,  0.43101314,  0.40036815, ...,  0.23776756,
            -1.2157528 ,  0.08647836],
           [-0.14724576,  0.3765885 ,  0.17119715, ..., -0.24705712,
            -1.0634754 , -0.2578135 ],
           ...,
           [ 0.13665295,  0.36801454,  0.30768037, ..., -0.34619758,
            -1.1796142 , -0.8088358 ],
           [-0.08371288,  0.2795107 ,  0.1868808 , ..., -0.64511627,
            -1.1181315 , -1.037442  ],
           [-0.08607977,  0.36566493, -0.02935827, ..., -0.54559517,
            -1.075667  , -1.1459628 ]],

          ...,

          [[-0.7747873 , -0.75870997, -0.26651144, ...,  0.0080273 ,
            -0.25995776, -1.7303042 ],
           [-0.6837994 , -0.70840716, -0.27232748, ...,  0.4302407 ,
            -0.34129897, -1.3003138 ],
           [-0.9064192 , -0.82598984, -0.47485787, ...,  0.05421926,
            -0.34884164, -1.2012448 ],
           ...,
           [ 1.0858637 ,  0.8712395 ,  1.5864046 , ...,  0.6048454 ,
            -0.34754562,  1.7194406 ],
           [ 1.1157135 ,  0.95316535,  1.5771952 , ...,  0.4012554 ,

### **4.5. Preparación de inputs según el tipo de modelo**

In [11]:
# ============================================================
# Preparación de inputs según el tipo de modelo
# ============================================================

def flatten_seq2one_X(X: np.ndarray) -> np.ndarray:
    """
    Aplana ventanas seq2one para modelos tabulares.

    Convierte:
        (n_samples, seq_len, n_features)
    a:
        (n_samples, seq_len * n_features)
    """
    X = np.asarray(X)

    if X.ndim != 3:
        raise ValueError(
            f"Se esperaba X 3D con shape (n, seq_len, n_features). "
            f"Recibido X.shape={X.shape}"
        )

    n_samples = X.shape[0]
    return X.reshape(n_samples, -1)


def prepare_X_for_model(
    X: np.ndarray,
    *,
    input_mode: str,
) -> np.ndarray:
    """
    Prepara X según el tipo de modelo.

    Parámetros
    ----------
    X : np.ndarray
        Array de entrada.
    input_mode : str
        - '2d_flat' : aplana ventanas 3D a 2D
        - '3d'      : deja X como está

    Retorna
    -------
    np.ndarray
        X transformado para el modelo correspondiente.
    """
    X = np.asarray(X)

    if input_mode == "3d":
        if X.ndim != 3:
            raise ValueError(
                f"Se esperaba X 3D para input_mode='3d'. "
                f"Recibido X.shape={X.shape}"
            )
        return X

    if input_mode == "2d_flat":
        return flatten_seq2one_X(X)

    raise ValueError(
        f"input_mode no soportado: {input_mode}. "
        f"Use '2d_flat' o '3d'."
    )

**Cómo se usa después**

Para Logistic Regression:

```python
X_train_model = prepare_X_for_model(bundle["train"]["X"], input_mode="2d_flat")
X_valid_model = prepare_X_for_model(bundle["valid"]["X"], input_mode="2d_flat")
```

Para LSTM / GRU / Transformer:

```python
X_train_model = prepare_X_for_model(bundle["train"]["X"], input_mode="3d")
X_valid_model = prepare_X_for_model(bundle["valid"]["X"], input_mode="3d")
```

## **5. Sanity Check**

Estos sanity checks sirven para verificar, antes de entrenar, que los datos cargados tengan la estructura correcta y no vengan con errores silenciosos.

En concreto, comprueban que:

- X tenga el formato esperado: 3D (n, seq_len, n_features) o 2D (n, d_flat)
- y tenga forma válida para clasificación seq2one
- X e y tengan la misma cantidad de muestras
- no haya NaN ni inf
- las dimensiones sean consistentes entre train, valid y test
- exista más de una clase en y

Nos conviene tenerlos, porque ayudan a detectar errores de shape o de datos antes de llegar al entrenamiento.

In [12]:
from __future__ import annotations

from typing import Any, Optional, Tuple, Dict, Mapping
import numpy as np


# ============================================================
# SANITY CHECKS PARA DATASETS SEQ2ONE (T2)
# ============================================================

def _as_numpy_array(a: Any, *, name: str) -> np.ndarray:
    """
    Convierte una entrada a np.ndarray y valida que no esté vacía
    ni contenga NaN/inf.
    """
    arr = np.asarray(a)

    if arr.size == 0:
        raise ValueError(f"{name} está vacío. shape={arr.shape}")

    if not np.isfinite(arr).all():
        raise ValueError(
            f"{name} contiene NaN/inf. Limpie antes de continuar. shape={arr.shape}"
        )

    return arr


def _normalize_y_seq2one(
    y: np.ndarray,
    *,
    name: str = "y",
    allow_seq_inputs_take_last: bool = False,
) -> np.ndarray:
    """
    Normaliza y para seq2one a shape (n_samples,).

    Acepta:
    - (n,)
    - (n, 1)
    - (n, seq_len)       si allow_seq_inputs_take_last=True
    - (n, seq_len, 1)    si allow_seq_inputs_take_last=True
    """
    if y.ndim == 1:
        return y

    if y.ndim == 2 and y.shape[1] == 1:
        return y.squeeze(1)

    if allow_seq_inputs_take_last:
        if y.ndim == 2 and y.shape[1] > 1:
            return y[:, -1]

        if y.ndim == 3 and y.shape[2] == 1:
            return y[:, -1, 0]

    raise ValueError(
        f"{name} shape inválido para seq2one. "
        f"Se esperaba (n,) o (n,1)"
        f"{' o secuencial si allow_seq_inputs_take_last=True' if allow_seq_inputs_take_last else ''}. "
        f"Recibido {y.shape}"
    )


def _infer_seq_len_and_n_features(X: np.ndarray) -> Tuple[int, Optional[int], str]:
    """
    Infiere (seq_len, n_features, mode) desde X.

    mode:
    - '3d': X = (n, seq_len, n_features)
    - '2d': X = (n, d_flat)  -> n_features=None
    """
    if X.ndim == 3:
        return int(X.shape[1]), int(X.shape[2]), "3d"

    if X.ndim == 2:
        return int(X.shape[1]), None, "2d"

    raise ValueError(
        f"X.ndim inválido. Se esperaba 2D o 3D. Recibido X.shape={X.shape}"
    )


def sanity_check_seq2one(
    X: Any,
    y: Any,
    split_name: str,
    *,
    expected_seq_len: Optional[int] = None,
    expected_n_features: Optional[int] = None,
    expected_flat_dim: Optional[int] = None,
    allow_seq_inputs_take_last: bool = False,
    verbose: bool = True,
) -> Dict[str, Any]:
    """
    Sanity check para datasets seq2one de clasificación.

    Soporta:
      - X 3D: (n, seq_len, n_features)
      - X 2D: (n, d_flat)  [ventana aplanada]

    y soporta:
      - y 1D: (n,)
      - y 2D: (n,1)
      - y secuencial, opcionalmente, tomando el último valor

    Parámetros
    ----------
    expected_seq_len:
        Para X 3D: valida seq_len.
        Para X 2D: no aplica directamente.
    expected_n_features:
        Solo aplica a X 3D.
    expected_flat_dim:
        Solo aplica a X 2D.
    allow_seq_inputs_take_last:
        Si y viene como secuencia, toma el último valor.
    """
    X = _as_numpy_array(X, name=f"X[{split_name}]")
    y = _as_numpy_array(y, name=f"y[{split_name}]")

    y = _normalize_y_seq2one(
        y,
        name=f"y[{split_name}]",
        allow_seq_inputs_take_last=allow_seq_inputs_take_last,
    )

    seq_len, n_features, mode = _infer_seq_len_and_n_features(X)
    n_samples = int(X.shape[0])

    if y.shape[0] != n_samples:
        raise ValueError(
            f"Mismatch n_samples en {split_name}: "
            f"X tiene n={n_samples}, y tiene n={y.shape[0]}"
        )

    if mode == "3d":
        if expected_seq_len is not None and seq_len != int(expected_seq_len):
            raise ValueError(
                f"{split_name}: seq_len esperado={expected_seq_len}, "
                f"recibido={seq_len}. X.shape={X.shape}"
            )

        if expected_n_features is not None and n_features != int(expected_n_features):
            raise ValueError(
                f"{split_name}: n_features esperado={expected_n_features}, "
                f"recibido={n_features}. X.shape={X.shape}"
            )

    elif mode == "2d":
        d_flat = int(X.shape[1])

        if expected_flat_dim is not None and d_flat != int(expected_flat_dim):
            raise ValueError(
                f"{split_name}: d_flat esperado={expected_flat_dim}, "
                f"recibido={d_flat}. X.shape={X.shape}"
            )

        if expected_n_features is not None:
            raise ValueError(
                f"{split_name}: expected_n_features no aplica para X 2D. "
                f"Use expected_flat_dim o pase X en 3D."
            )

    classes, counts = np.unique(y, return_counts=True)
    class_distribution = {
        str(cls): int(cnt) for cls, cnt in zip(classes, counts)
    }

    if len(classes) < 2:
        raise ValueError(
            f"{split_name}: y contiene menos de 2 clases únicas. "
            f"classes={classes.tolist()}"
        )

    info = {
        "split": split_name,
        "X_shape": tuple(X.shape),
        "y_shape": tuple(y.shape),
        "mode": mode,
        "seq_len": seq_len if mode == "3d" else None,
        "n_features": n_features if mode == "3d" else None,
        "flat_dim": int(X.shape[1]) if mode == "2d" else None,
        "n_classes": int(len(classes)),
        "classes": classes.tolist(),
        "class_distribution": class_distribution,
    }

    if verbose:
        print(
            f"[sanity_check_seq2one] {split_name} | "
            f"X={info['X_shape']} | y={info['y_shape']} | "
            f"mode={mode} | n_classes={info['n_classes']} | "
            f"classes={info['classes']}"
        )

    return info


def run_sanity_checks_for_bundle_seq2one(
    bundle: Dict[str, Any],
    *,
    tag: str,
    expected_seq_len: Optional[int] = None,
    expected_n_features: Optional[int] = None,
    expected_flat_dim: Optional[int] = None,
    allow_seq_inputs_take_last: bool = False,
    verbose: bool = True,
) -> Dict[str, Any]:
    """
    Ejecuta sanity checks para un bundle con estructura:

    {
      "target": "t2_p40_h30",
      "horizon": 30,
      "train": {"X":..., "y":...},
      "valid": {"X":..., "y":...},
      "test":  {"X":..., "y":...},
    }

    Si no se pasan expected_*, usa TRAIN como referencia.
    """
    X_tr = bundle["train"]["X"]
    y_tr = bundle["train"]["y"]
    X_va = bundle["valid"]["X"]
    y_va = bundle["valid"]["y"]
    X_te = bundle["test"]["X"]
    y_te = bundle["test"]["y"]

    X_tr_arr = np.asarray(X_tr)
    seq_len_tr, n_feat_tr, mode_tr = _infer_seq_len_and_n_features(X_tr_arr)

    if mode_tr == "3d":
        if expected_seq_len is None:
            expected_seq_len = seq_len_tr
        if expected_n_features is None:
            expected_n_features = n_feat_tr
        expected_flat_dim = None
    else:
        d_flat_tr = int(X_tr_arr.shape[1])
        if expected_flat_dim is None:
            expected_flat_dim = d_flat_tr
        expected_n_features = None

    out_tr = sanity_check_seq2one(
        X_tr,
        y_tr,
        f"train_{tag}",
        expected_seq_len=expected_seq_len,
        expected_n_features=expected_n_features,
        expected_flat_dim=expected_flat_dim,
        allow_seq_inputs_take_last=allow_seq_inputs_take_last,
        verbose=verbose,
    )

    out_va = sanity_check_seq2one(
        X_va,
        y_va,
        f"valid_{tag}",
        expected_seq_len=expected_seq_len,
        expected_n_features=expected_n_features,
        expected_flat_dim=expected_flat_dim,
        allow_seq_inputs_take_last=allow_seq_inputs_take_last,
        verbose=verbose,
    )

    out_te = sanity_check_seq2one(
        X_te,
        y_te,
        f"test_{tag}",
        expected_seq_len=expected_seq_len,
        expected_n_features=expected_n_features,
        expected_flat_dim=expected_flat_dim,
        allow_seq_inputs_take_last=allow_seq_inputs_take_last,
        verbose=verbose,
    )

    target = bundle.get("target", "NA")
    horizon = bundle.get("horizon", "NA")

    if verbose:
        print(f"OK {tag} | target={target} | horizon={horizon}")

    return {
        "target": target,
        "horizon": horizon,
        "train": out_tr,
        "valid": out_va,
        "test": out_te,
    }


def run_sanity_checks_all_bundles_seq2one(
    bundles: Mapping[str, Dict[str, Any]],
    *,
    verbose: bool = True,
) -> Dict[str, Any]:
    """
    Corre sanity checks para todos los bundles de un diccionario:

    bundles[target] -> bundle
    """
    results = {}

    for target, bundle in bundles.items():
        results[target] = run_sanity_checks_for_bundle_seq2one(
            bundle,
            tag=target,
            verbose=verbose,
        )

    return results

In [13]:
sanity_results = run_sanity_checks_all_bundles_seq2one(
    bundles_L30,
    verbose=True,
)

[sanity_check_seq2one] train_t2_p40_h30 | X=(32147, 30, 7) | y=(32147,) | mode=3d | n_classes=3 | classes=[-1, 0, 1]
[sanity_check_seq2one] valid_t2_p40_h30 | X=(6882, 30, 7) | y=(6882,) | mode=3d | n_classes=3 | classes=[-1, 0, 1]
[sanity_check_seq2one] test_t2_p40_h30 | X=(6913, 30, 7) | y=(6913,) | mode=3d | n_classes=3 | classes=[-1, 0, 1]
OK t2_p40_h30 | target=t2_p40_h30 | horizon=30
[sanity_check_seq2one] train_t2_p40_h60 | X=(32147, 30, 7) | y=(32147,) | mode=3d | n_classes=3 | classes=[-1, 0, 1]
[sanity_check_seq2one] valid_t2_p40_h60 | X=(6882, 30, 7) | y=(6882,) | mode=3d | n_classes=3 | classes=[-1, 0, 1]
[sanity_check_seq2one] test_t2_p40_h60 | X=(6913, 30, 7) | y=(6913,) | mode=3d | n_classes=3 | classes=[-1, 0, 1]
OK t2_p40_h60 | target=t2_p40_h60 | horizon=60
[sanity_check_seq2one] train_t2_p50_h30 | X=(32147, 30, 7) | y=(32147,) | mode=3d | n_classes=3 | classes=[-1, 0, 1]
[sanity_check_seq2one] valid_t2_p50_h30 | X=(6882, 30, 7) | y=(6882,) | mode=3d | n_classes=3 | classes=[-1, 0, 1]
[sanity_check_seq2one] test_t2_p50_h30 | X=(6913, 30, 7) | y=(6913,) | mode=3d | n_classes=3 | classes=[-1, 0, 1]
OK t2_p50_h30 | target=t2_p50_h30 | horizon=30

## **6. Módulo de métricas T2**

In [14]:
# ================================
# Setup para importar módulos del proyecto
# ================================

import sys
import importlib

if str(DRIVE_DIR) not in sys.path:
    sys.path.insert(0, str(DRIVE_DIR))

# asegurar que metrics es paquete
(DRIVE_DIR / "metrics" / "__init__.py").touch(exist_ok=True)

importlib.invalidate_caches()

# ================================
# Imports de métricas
# ================================

from metrics.classification_metrics import (
    compute_classification_metrics,
    metrics_to_flat_dict,
    print_classification_report_block,
)

from metrics.classification_probabilities import (
    compute_probabilistic_outputs,
    apply_decision_rule,
)

print("Módulos importados correctamente")

Módulos importados correctamente

In [15]:
# ================================
# Utilidades: outputs -> DataFrame
# ================================

from __future__ import annotations

import pandas as pd
from typing import Any


def classification_metrics_to_df(
    metrics: dict,
    *,
    model: str,
    split: str,
    window_size: int,
    target: str,
    horizon: int | None = None,
) -> pd.DataFrame:
    """
    Convierte el output de compute_classification_metrics(...)
    en una fila de DataFrame.

    Usa metrics_to_flat_dict(...) para aplanar la salida
    del módulo classification_metrics y luego agrega metadata
    del experimento.
    """
    flat_metrics = metrics_to_flat_dict(metrics)

    row = {
        "model": model,
        "split": split,
        "window_size": window_size,
        "target": target,
        "horizon": horizon,
        **flat_metrics,
    }

    return pd.DataFrame([row])


def _flatten_dict(
    d: dict[str, Any],
    *,
    parent_key: str = "",
    sep: str = "_",
) -> dict[str, Any]:
    """
    Aplana un diccionario arbitrario de forma recursiva.

    Ejemplo:
    {"a": {"b": 1}} -> {"a_b": 1}
    """
    items: dict[str, Any] = {}

    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else str(k)

        if isinstance(v, dict):
            items.update(_flatten_dict(v, parent_key=new_key, sep=sep))
        else:
            items[new_key] = v

    return items


def probabilities_metrics_to_df(
    prob_metrics: dict,
    *,
    model: str,
    split: str,
    window_size: int,
    target: str,
    horizon: int | None = None,
) -> pd.DataFrame:
    """
    Convierte el output del módulo classification_probabilities
    en una fila de DataFrame.

    Como la estructura puede variar según la implementación,
    se aplana recursivamente el diccionario y luego se agrega
    metadata del experimento.
    """
    flat_prob_metrics = _flatten_dict(prob_metrics)

    row = {
        "model": model,
        "split": split,
        "window_size": window_size,
        "target": target,
        "horizon": horizon,
        **flat_prob_metrics,
    }

    return pd.DataFrame([row])


logger.info("Utilidades de exportación a DataFrame cargadas")

2026-04-23 16:23:30,530 | INFO | Utilidades de exportación a DataFrame cargadas

## **7. Persistencia de métricas (tracking de experimentos)**

In [16]:
# ================================
# Persistencia de métricas de clasificación
# ================================

from pathlib import Path
import pandas as pd


def load_classification_metrics_if_exists(
    *,
    model_name: str,
    split: str = "valid",
    base_dir: Path = DRIVE_DIR / "metrics_tuning" / "classification_metrics",
) -> pd.DataFrame:
    """
    Carga métricas de clasificación si el archivo existe.

    El nombre del archivo incluye modelo y split para evitar
    mezclar resultados de distintos experimentos.
    """
    path = base_dir / f"classification_metrics_{model_name}_{split}.parquet"

    if path.exists():
        logger.info(f"Cargando métricas desde: {path}")
        return pd.read_parquet(path)

    logger.info(
        f"No existen métricas previas para model={model_name} | split={split}"
    )
    return pd.DataFrame()


def save_classification_metrics(
    df_metrics: pd.DataFrame,
    *,
    model_name: str,
    split: str = "valid",
    base_dir: Path = DRIVE_DIR / "metrics_tuning" / "classification_metrics",
) -> Path:
    """
    Guarda un DataFrame de métricas de clasificación en formato Parquet.
    """
    base_dir.mkdir(parents=True, exist_ok=True)

    out_path = base_dir / f"classification_metrics_{model_name}_{split}.parquet"
    df_metrics.to_parquet(out_path, index=False)

    logger.info(f"Métricas guardadas en: {out_path}")

    return out_path


# ================================
# Persistencia de probabilidades / decisión
# ================================

def load_classification_probabilities_if_exists(
    *,
    model_name: str,
    split: str = "valid",
    base_dir: Path = DRIVE_DIR / "metrics_tuning" / "classification_probabilities",
) -> pd.DataFrame:
    """
    Carga resultados probabilísticos si el archivo existe.

    El nombre del archivo incluye modelo y split para evitar
    mezclar resultados de distintos experimentos.
    """
    path = base_dir / f"classification_probabilities_{model_name}_{split}.parquet"

    if path.exists():
        logger.info(f"Cargando probabilidades desde: {path}")
        return pd.read_parquet(path)

    logger.info(
        f"No existen probabilidades previas para model={model_name} | split={split}"
    )
    return pd.DataFrame()


def save_classification_probabilities(
    df_probabilities: pd.DataFrame,
    *,
    model_name: str,
    split: str = "valid",
    base_dir: Path = DRIVE_DIR / "metrics_tuning" / "classification_probabilities",
) -> Path:
    """
    Guarda un DataFrame de probabilidades / decisión en formato Parquet.
    """
    base_dir.mkdir(parents=True, exist_ok=True)

    out_path = base_dir / f"classification_probabilities_{model_name}_{split}.parquet"
    df_probabilities.to_parquet(out_path, index=False)

    logger.info(f"Probabilidades guardadas en: {out_path}")

    return out_path

Ejemplo de uso con logistic regression:

```python
df_metrics_all = load_classification_metrics_if_exists(
    model_name="logistic_regression",
    split="valid",
)

df_probabilities_all = load_classification_probabilities_if_exists(
    model_name="logistic_regression",
    split="valid",
)
```

Guardar:
```python
save_classification_metrics(
    df_metrics_all,
    model_name="logistic_regression",
    split="valid",
)

save_classification_probabilities(
    df_probabilities_all,
    model_name="logistic_regression",
    split="valid",
)
```

## **8. Gestión de dispositivo y memoria**

In [17]:
# ================================
# Device y limpieza de memoria
# ================================

def get_torch_device():
    """
    Retorna el device para modelos PyTorch.
    """
    import torch

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger.info(f"Using device: {device}")
    return device


def clear_torch_memory() -> None:
    """
    Limpia memoria Python y, si existe CUDA, libera caché GPU.
    Útil entre entrenamientos de modelos PyTorch.
    """
    import gc

    gc.collect()

    try:
        import torch
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    except ImportError:
        pass

## **9. Reproducibilidad**

In [18]:
# ================================
# Reproducibilidad
# ================================

def set_seeds(seed: int = 42) -> None:
    """
    Fija semillas para reproducibilidad en:
    - Python
    - NumPy
    - PyTorch (si está disponible)
    """

    import random
    import numpy as np
    import os

    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

    # ---- PyTorch (si está instalado)
    try:
        import torch

        torch.manual_seed(seed)
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

        # determinismo (más lento pero reproducible)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

    except ImportError:
        pass  # no hay PyTorch, ignorar

    logger.info(f"Seeds fijadas en {seed}")


# Aplicación
SEED = 42
set_seeds(SEED)

2026-04-23 16:23:35,009 | INFO | Seeds fijadas en 42

# **10. Entrenamiento de modelo**

## **10.1. Función unitaria por bundle**

In [19]:
import copy
import numpy as np
import torch
import torch.nn as nn


class GRUClassifier(nn.Module):
    def __init__(
        self,
        n_features: int,
        hidden_size: int = 64,
        num_layers: int = 1,
        dropout: float = 0.0,
        num_classes: int = 3,
    ):
        super().__init__()

        gru_dropout = dropout if num_layers > 1 else 0.0

        self.gru = nn.GRU(
            input_size=n_features,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=gru_dropout,
        )

        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        out, _ = self.gru(x)          # (batch, seq_len, hidden_size)
        last_out = out[:, -1, :]      # many-to-one
        last_out = self.dropout(last_out)
        logits = self.fc(last_out)    # (batch, num_classes)
        return logits


def run_gru_for_bundle_seq2one(
    bundle,
    *,
    hidden_size: int = 64,
    num_layers: int = 1,
    dropout: float = 0.0,
    learning_rate: float = 1e-3,
    weight_decay: float = 0.0,
    batch_size: int = 64,
    eval_batch_size: int = 64,
    epochs: int = 20,
    patience: int = 5,
    random_state: int = 42,
    device: str | None = None,
    deterministic: bool = True,
    class_weight=None,
    num_workers: int = 0,
    optimizer_name: str = "adam",
    grad_clip_norm: float | None = None,
    verbose: bool = False,
):
    """
    Ejecuta GRU para un bundle seq2one.
    Evalúa SOLO sobre VALID.

    - Usa TRAIN para fit
    - Usa VALID para early stopping
    - Predice SOLO en VALID
    - Soporta labels arbitrarias (ej. [-1, 0, 1]) mediante codificación interna
    """

    # =========================
    # 1. SEEDS Y DEVICE
    # =========================
    torch.manual_seed(random_state)
    np.random.seed(random_state)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(random_state)

    if deterministic:
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"

    use_pin_memory = device == "cuda"

    # =========================
    # 2. EXTRAER DATA
    # =========================
    X_train = bundle["train"]["X"]
    y_train = bundle["train"]["y"]

    X_valid = bundle["valid"]["X"]
    y_valid = bundle["valid"]["y"]

    target = bundle.get("target")
    horizon = bundle.get("horizon")
    window_size = bundle.get("window_size")

    # =========================
    # 3. VALIDAR SHAPES
    # =========================
    if X_train.ndim != 3 or X_valid.ndim != 3:
        raise ValueError(
            "GRU requiere tensores 3D: (n_samples, seq_len, n_features). "
            f"Recibido train={X_train.shape}, valid={X_valid.shape}"
        )

    seq_len_train, n_features_train = X_train.shape[1], X_train.shape[2]
    seq_len_valid, n_features_valid = X_valid.shape[1], X_valid.shape[2]

    if not (
        seq_len_train == seq_len_valid
        and n_features_train == n_features_valid
    ):
        raise ValueError(
            "Inconsistencia entre shapes de train/valid. "
            f"train={X_train.shape}, valid={X_valid.shape}"
        )

    n_features = n_features_train

    # =========================
    # 4. CODIFICAR LABELS
    # =========================
    classes_ = np.sort(np.unique(y_train))

    unknown_valid = set(np.unique(y_valid)) - set(classes_)
    if unknown_valid:
        raise ValueError(
            f"VALID contiene clases no vistas en TRAIN: {sorted(unknown_valid)}"
        )

    class_to_idx = {cls: idx for idx, cls in enumerate(classes_)}
    idx_to_class = {idx: cls for cls, idx in class_to_idx.items()}

    y_train_enc = np.array([class_to_idx[y] for y in y_train], dtype=np.int64)
    y_valid_enc = np.array([class_to_idx[y] for y in y_valid], dtype=np.int64)

    num_classes = len(classes_)

    # Validación opcional útil para este proyecto
    if not np.array_equal(classes_, [-1, 0, 1]):
        raise ValueError(f"Clases inesperadas en TRAIN: {classes_}")

    # =========================
    # 5. CLASS WEIGHTS
    # =========================
    criterion_weight = None
    weights_by_idx = None

    if class_weight is None:
        criterion_weight = None

    elif class_weight == "balanced":
        counts = np.bincount(y_train_enc, minlength=num_classes)
        total = counts.sum()

        weights_by_idx = {
            idx: total / (num_classes * count)
            for idx, count in enumerate(counts)
        }

        criterion_weight = torch.tensor(
            [weights_by_idx[idx] for idx in range(num_classes)],
            dtype=torch.float32,
            device=device,
        )

    elif isinstance(class_weight, dict):
        weights_by_idx = {
            class_to_idx[cls]: weight
            for cls, weight in class_weight.items()
            if cls in class_to_idx
        }

        criterion_weight = torch.tensor(
            [weights_by_idx.get(idx, 1.0) for idx in range(num_classes)],
            dtype=torch.float32,
            device=device,
        )

    else:
        raise ValueError("class_weight debe ser None, 'balanced' o dict")

    # =========================
    # 6. TENSORES EN CPU
    # =========================
    X_train_t = torch.tensor(X_train, dtype=torch.float32)
    y_train_t = torch.tensor(y_train_enc, dtype=torch.long)

    X_valid_t = torch.tensor(X_valid, dtype=torch.float32)
    y_valid_t = torch.tensor(y_valid_enc, dtype=torch.long)

    # =========================
    # 7. DATALOADERS
    # =========================
    train_ds = torch.utils.data.TensorDataset(X_train_t, y_train_t)
    valid_ds = torch.utils.data.TensorDataset(X_valid_t, y_valid_t)

    train_loader = torch.utils.data.DataLoader(
        train_ds,
        batch_size=batch_size,
        shuffle=True,
        drop_last=False,
        num_workers=num_workers,
        pin_memory=use_pin_memory,
    )

    valid_loader = torch.utils.data.DataLoader(
        valid_ds,
        batch_size=eval_batch_size,
        shuffle=False,
        drop_last=False,
        num_workers=num_workers,
        pin_memory=use_pin_memory,
    )

    # =========================
    # 8. MODELO
    # =========================
    model = GRUClassifier(
        n_features=n_features,
        hidden_size=hidden_size,
        num_layers=num_layers,
        dropout=dropout,
        num_classes=num_classes,
    ).to(device)

    criterion = nn.CrossEntropyLoss(weight=criterion_weight)

    # =========================
    # 9. OPTIMIZER
    # =========================
    optimizer_name_norm = optimizer_name.lower()

    if optimizer_name_norm == "adam":
        optimizer = torch.optim.Adam(
            model.parameters(),
            lr=learning_rate,
            weight_decay=weight_decay,
        )
    elif optimizer_name_norm == "adamw":
        optimizer = torch.optim.AdamW(
            model.parameters(),
            lr=learning_rate,
            weight_decay=weight_decay,
        )
    else:
        raise ValueError(f"optimizer_name no soportado: {optimizer_name}")

    # =========================
    # 10. HELPERS
    # =========================
    def _move_batch(x):
        if device == "cuda":
            return x.to(device, non_blocking=True)
        return x.to(device)

    def compute_valid_loss():
        model.eval()
        valid_loss_sum = 0.0
        valid_count = 0

        with torch.no_grad():
            for xb, yb in valid_loader:
                xb = _move_batch(xb)
                yb = _move_batch(yb)

                logits = model(xb)
                loss = criterion(logits, yb)

                batch_n = xb.size(0)
                valid_loss_sum += loss.item() * batch_n
                valid_count += batch_n

        return valid_loss_sum / max(valid_count, 1)

    def predict_loader(loader):
        logits_all = []

        model.eval()
        with torch.no_grad():
            for xb, *_ in loader:
                xb = _move_batch(xb)
                logits = model(xb)
                logits_all.append(logits.cpu())

        logits_all = torch.cat(logits_all, dim=0)
        return logits_all

    # =========================
    # 11. TRAIN + EARLY STOPPING
    # =========================
    best_state = copy.deepcopy(model.state_dict())
    best_valid_loss = np.inf
    best_epoch = 0
    wait = 0
    history = []

    try:
        for epoch in range(1, epochs + 1):
            model.train()
            train_loss_sum = 0.0
            train_count = 0

            for xb, yb in train_loader:
                xb = _move_batch(xb)
                yb = _move_batch(yb)

                optimizer.zero_grad(set_to_none=True)
                logits = model(xb)
                loss = criterion(logits, yb)

                loss.backward()

                if grad_clip_norm is not None:
                    torch.nn.utils.clip_grad_norm_(
                        model.parameters(),
                        grad_clip_norm,
                    )

                optimizer.step()

                batch_n = xb.size(0)
                train_loss_sum += loss.item() * batch_n
                train_count += batch_n

            train_loss = train_loss_sum / max(train_count, 1)
            valid_loss = compute_valid_loss()

            history.append(
                {
                    "epoch": epoch,
                    "train_loss": float(train_loss),
                    "valid_loss": float(valid_loss),
                }
            )

            if verbose:
                print(
                    f"[Epoch {epoch:03d}] "
                    f"train_loss={train_loss:.6f} | "
                    f"valid_loss={valid_loss:.6f}"
                )

            if valid_loss < best_valid_loss:
                best_valid_loss = valid_loss
                best_epoch = epoch
                best_state = copy.deepcopy(model.state_dict())
                wait = 0
            else:
                wait += 1
                if wait >= patience:
                    if verbose:
                        print(
                            f"[EARLY STOP] epoch={epoch} | "
                            f"best_epoch={best_epoch} | "
                            f"best_valid_loss={best_valid_loss:.6f}"
                        )
                    break

        model.load_state_dict(best_state)

        # =========================
        # 12. PREDICT (VALID)
        # =========================
        valid_logits = predict_loader(valid_loader)

        y_pred_valid_enc = valid_logits.argmax(dim=1).numpy()
        y_proba_valid = torch.softmax(valid_logits, dim=1).numpy()
        y_pred_valid = np.array([idx_to_class[int(y)] for y in y_pred_valid_enc])

        if verbose:
            print(
                f"[GRU] target={target} | horizon={horizon} | "
                f"window_size={window_size} | device={device} | "
                f"X_train={X_train.shape} | X_valid={X_valid.shape} | "
                f"best_epoch={best_epoch} | best_valid_loss={best_valid_loss:.6f}"
            )

        return {
            "model_name": "gru",
            "target": target,
            "horizon": horizon,
            "window_size": window_size,

            # hiperparámetros
            "hidden_size": hidden_size,
            "num_layers": num_layers,
            "dropout": dropout,
            "learning_rate": learning_rate,
            "weight_decay": weight_decay,
            "batch_size": batch_size,
            "eval_batch_size": eval_batch_size,
            "epochs": epochs,
            "patience": patience,
            "random_state": random_state,
            "deterministic": deterministic,
            "class_weight": str(class_weight),
            "num_workers": num_workers,
            "optimizer_name": optimizer_name_norm,
            "grad_clip_norm": grad_clip_norm,

            # estado / metadata
            "device": device,
            "model": model,
            "classes_": classes_.tolist(),
            "class_to_idx": class_to_idx,
            "idx_to_class": idx_to_class,
            "criterion_weight": (
                criterion_weight.detach().cpu().numpy().tolist()
                if criterion_weight is not None else None
            ),
            "weights_by_idx": weights_by_idx,
            "history": history,
            "best_valid_loss": float(best_valid_loss),
            "best_epoch": int(best_epoch),

            # outputs
            "y_valid": y_valid,
            "y_pred_valid": y_pred_valid,
            "y_proba_valid": y_proba_valid,
        }

    finally:
        if device == "cuda":
            torch.cuda.empty_cache()

## **10.2. Función de evaluación sobre uno o más bundles**

In [20]:
from typing import Any, Dict, List, Sequence, Union
import gc
import pandas as pd
import torch


def eval_gru_bundles(
    bundles: Union[Dict[str, Any], Sequence[Dict[str, Any]]],
    *,
    model_name: str = "gru",
    hidden_size: int = 64,
    num_layers: int = 1,
    dropout: float = 0.0,
    learning_rate: float = 1e-3,
    weight_decay: float = 0.0,
    batch_size: int = 64,
    eval_batch_size: int = 64,
    epochs: int = 20,
    patience: int = 5,
    random_state: int = 42,
    device: str | None = None,
    class_weight=None,
    num_workers: int = 0,
    optimizer_name: str = "adam",
    grad_clip_norm: float | None = None,
    prob_threshold_long: float = 0.40,
    prob_threshold_short: float = 0.40,
    verbose: bool = False,
) -> Dict[str, pd.DataFrame]:
    """
    Evalúa GRU para uno o varios bundles seq2one
    usando SOLO el split VALID.

    Retorna
    -------
    dict con:
    - "metrics": DataFrame de métricas de clasificación
    - "probabilities": DataFrame de métricas probabilísticas / decisión
    """

    # --------------------------------------------------
    # 1) Normalizar entrada
    # --------------------------------------------------
    if isinstance(bundles, dict):
        if "train" in bundles and "valid" in bundles:
            bundles_list: List[Dict[str, Any]] = [bundles]
        else:
            bundles_list = list(bundles.values())
    else:
        bundles_list = list(bundles)

    metrics_rows = []
    probabilities_rows = []

    optimizer_name_norm = optimizer_name.lower()

    # --------------------------------------------------
    # 2) Iterar por bundles
    # --------------------------------------------------
    for bundle in bundles_list:
        target = bundle.get("target", None)
        window_size = int(bundle["window_size"])
        horizon = int(bundle.get("horizon", -1))

        if verbose:
            print(
                f"  -> L{window_size} | "
                f"target={target} | "
                f"model={model_name} | "
                f"class_weight={class_weight}"
            )

        preds = None

        try:
            # ----------------------------------------------
            # 3) Entrenar + predecir SOLO VALID
            # ----------------------------------------------
            preds = run_gru_for_bundle_seq2one(
                bundle,
                hidden_size=hidden_size,
                num_layers=num_layers,
                dropout=dropout,
                learning_rate=learning_rate,
                weight_decay=weight_decay,
                batch_size=batch_size,
                eval_batch_size=eval_batch_size,
                epochs=epochs,
                patience=patience,
                random_state=random_state,
                device=device,
                class_weight=class_weight,
                num_workers=num_workers,
                optimizer_name=optimizer_name_norm,
                grad_clip_norm=grad_clip_norm,
                verbose=False,
            )

            y_true = preds["y_valid"]
            y_pred = preds["y_pred_valid"]
            y_proba = preds["y_proba_valid"]

            # ----------------------------------------------
            # 4) Métricas de clasificación
            # ----------------------------------------------
            metrics = compute_classification_metrics(
                y_true=y_true,
                y_pred=y_pred,
                model_name=model_name,
                split="valid",
                target=target,
                labels=[-1, 0, 1],
            )

            df_metrics_row = classification_metrics_to_df(
                metrics,
                model=model_name,
                split="valid",
                window_size=window_size,
                target=target,
                horizon=horizon,
            )

            if class_weight == "balanced":
                class_weight_mode = "balanced"
            elif class_weight is None:
                class_weight_mode = "none"
            else:
                class_weight_mode = "custom"

            df_metrics_row["class_weight_mode"] = class_weight_mode
            df_metrics_row["input_mode"] = "3d"
            df_metrics_row["hidden_size"] = hidden_size
            df_metrics_row["num_layers"] = num_layers
            df_metrics_row["dropout"] = dropout
            df_metrics_row["learning_rate"] = learning_rate
            df_metrics_row["weight_decay"] = weight_decay
            df_metrics_row["batch_size"] = batch_size
            df_metrics_row["eval_batch_size"] = eval_batch_size
            df_metrics_row["epochs"] = epochs
            df_metrics_row["patience"] = patience
            df_metrics_row["device"] = preds.get("device", device)
            df_metrics_row["best_epoch"] = preds.get("best_epoch")
            df_metrics_row["best_valid_loss"] = preds.get("best_valid_loss")
            df_metrics_row["optimizer_name"] = optimizer_name_norm
            df_metrics_row["grad_clip_norm"] = grad_clip_norm
            df_metrics_row["num_workers"] = num_workers
            df_metrics_row["random_state"] = random_state
            df_metrics_row["threshold_long"] = prob_threshold_long
            df_metrics_row["threshold_short"] = prob_threshold_short

            metrics_rows.append(df_metrics_row)

            # ----------------------------------------------
            # 5) Outputs probabilísticos
            # ----------------------------------------------
            class_labels = preds["classes_"]

            proba_df = compute_probabilistic_outputs(
                y_proba=y_proba,
                class_labels=class_labels,
                y_true=y_true,
            )

            decision_df = apply_decision_rule(
                proba_df,
                long_class=1,
                short_class=-1,
                long_threshold=prob_threshold_long,
                short_threshold=prob_threshold_short,
            )

            overlap_cols = [c for c in decision_df.columns if c in proba_df.columns]
            if overlap_cols:
                decision_df = decision_df.drop(columns=overlap_cols)

            df_prob = pd.concat(
                [proba_df.reset_index(drop=True), decision_df.reset_index(drop=True)],
                axis=1,
            )

            df_prob["model"] = model_name
            df_prob["split"] = "valid"
            df_prob["window_size"] = window_size
            df_prob["target"] = target
            df_prob["horizon"] = horizon
            df_prob["class_weight_mode"] = class_weight_mode
            df_prob["input_mode"] = "3d"
            df_prob["hidden_size"] = hidden_size
            df_prob["num_layers"] = num_layers
            df_prob["dropout"] = dropout
            df_prob["learning_rate"] = learning_rate
            df_prob["weight_decay"] = weight_decay
            df_prob["batch_size"] = batch_size
            df_prob["eval_batch_size"] = eval_batch_size
            df_prob["epochs"] = epochs
            df_prob["patience"] = patience
            df_prob["optimizer_name"] = optimizer_name_norm
            df_prob["grad_clip_norm"] = grad_clip_norm
            df_prob["num_workers"] = num_workers
            df_prob["device"] = preds.get("device", device)
            df_prob["best_epoch"] = preds.get("best_epoch")
            df_prob["best_valid_loss"] = preds.get("best_valid_loss")
            df_prob["random_state"] = random_state
            df_prob["threshold_long"] = prob_threshold_long
            df_prob["threshold_short"] = prob_threshold_short

            # sample_id para incremental
            df_prob = df_prob.reset_index(drop=True)
            df_prob["sample_id"] = df_prob.index.astype(int)

            probabilities_rows.append(df_prob)

        finally:
            # ----------------------------------------------
            # 6) Liberación explícita de memoria
            # ----------------------------------------------
            if preds is not None:
                del preds
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    # --------------------------------------------------
    # 7) Consolidar salida
    # --------------------------------------------------
    df_metrics_all = pd.concat(metrics_rows, ignore_index=True)
    df_probabilities_all = pd.concat(probabilities_rows, ignore_index=True)

    return {
        "metrics": df_metrics_all,
        "probabilities": df_probabilities_all,
    }

## **10.3. Función orquestadora por `window_size`**

In [24]:
import gc
import pandas as pd
import torch


def run_gru(
    window_size: int,
    *,
    targets: list[str] = TARGETS,
    verbose: bool = True,
    model_name: str = "gru",
    hidden_size: int = 32,
    num_layers: int = 1,
    dropout: float = 0.0,
    learning_rate: float = 1e-3,
    weight_decay: float = 0.0,
    batch_size: int = 32,
    eval_batch_size: int = 32,
    epochs: int = 20,
    patience: int = 5,
    random_state: int = 42,
    device: str | None = None,
    class_weight=None,
    num_workers: int = 0,
    optimizer_name: str = "adam",
    grad_clip_norm: float | None = None,
    prob_threshold_long: float = 0.40,
    prob_threshold_short: float = 0.40,
) -> dict[str, pd.DataFrame]:
    """
    Ejecuta GRU para una sola window_size sobre los targets T2 indicados.

    Evalúa SOLO sobre VALID.

    Retorna
    -------
    dict con:
    - "metrics": DataFrame consolidado de métricas de clasificación
    - "probabilities": DataFrame consolidado de métricas probabilísticas / decisión
    """

    size = int(window_size)

    bundles = None
    results = None

    optimizer_name_norm = optimizer_name.lower()
    model_name_effective = model_name

    try:
        # --------------------------------------------------
        # 1) Encabezado
        # --------------------------------------------------
        if verbose:
            print("\n" + "=" * 80)
            print(f"GRU | T2 SEQ2ONE | WINDOW_SIZE=L{size}")
            print("=" * 80)
            print(f"targets          = {targets}")
            print(f"class_weight     = {class_weight}")
            print(f"hidden_size      = {hidden_size}")
            print(f"num_layers       = {num_layers}")
            print(f"dropout          = {dropout}")
            print(f"learning_rate    = {learning_rate}")
            print(f"weight_decay     = {weight_decay}")
            print(f"batch_size       = {batch_size}")
            print(f"eval_batch_size  = {eval_batch_size}")
            print(f"epochs           = {epochs}")
            print(f"patience         = {patience}")
            print(f"optimizer_name   = {optimizer_name_norm}")
            print(f"grad_clip_norm   = {grad_clip_norm}")
            print(f"device           = {device}")
            print(f"thr_long         = {prob_threshold_long}")
            print(f"thr_short        = {prob_threshold_short}")

        # --------------------------------------------------
        # 2) Construcción de bundles
        # --------------------------------------------------
        if verbose:
            print(f"\n[BUILD] L{size} | n_targets={len(targets)}")

        bundles = create_bundles(
            window_size=size,
            targets=targets,
            windows_paths=WINDOWS_PATHS,
            scaler_path=SCALER_T2_PATH,
        )

        # --------------------------------------------------
        # 3) Evaluación SOLO VALID
        # --------------------------------------------------
        if verbose:
            print(
                f"\n[EVAL] L{size} | split=valid | "
                f"model={model_name_effective} | class_weight={class_weight}"
            )

        results = eval_gru_bundles(
            bundles=bundles,
            model_name=model_name_effective,
            hidden_size=hidden_size,
            num_layers=num_layers,
            dropout=dropout,
            learning_rate=learning_rate,
            weight_decay=weight_decay,
            batch_size=batch_size,
            eval_batch_size=eval_batch_size,
            epochs=epochs,
            patience=patience,
            random_state=random_state,
            device=device,
            class_weight=class_weight,
            num_workers=num_workers,
            optimizer_name=optimizer_name_norm,
            grad_clip_norm=grad_clip_norm,
            prob_threshold_long=prob_threshold_long,
            prob_threshold_short=prob_threshold_short,
            verbose=verbose,
        )

        df_metrics = (
            results["metrics"]
            .sort_values(["window_size", "target", "split", "horizon", "model"])
            .reset_index(drop=True)
        )

        df_probabilities = (
            results["probabilities"]
            .sort_values(["window_size", "target", "split", "horizon", "model"])
            .reset_index(drop=True)
        )

        # --------------------------------------------------
        # 4) Resumen final
        # --------------------------------------------------
        if verbose:
            print(
                f"\n[DONE] L{size} | "
                f"metrics_rows={len(df_metrics)} | "
                f"probabilities_rows={len(df_probabilities)}"
            )

            print("\n[METRICS]")
            cols_metrics = [
                c for c in [
                    "window_size",
                    "split",
                    "target",
                    "model",
                    "horizon",
                    "class_weight_mode",
                    "balanced_accuracy",
                    "f1_macro",
                    "best_epoch",
                    "best_valid_loss",
                ] if c in df_metrics.columns
            ]
            if cols_metrics:
                print(df_metrics[cols_metrics].to_string(index=False))

            print("\n[PROBABILITIES - unique rows]")
            cols_probs = [
                c for c in [
                    "window_size",
                    "split",
                    "target",
                    "model",
                    "horizon",
                    "class_weight_mode",
                    "threshold_long",
                    "threshold_short",
                ] if c in df_probabilities.columns
            ]
            if cols_probs:
                print(
                    df_probabilities[cols_probs]
                    .drop_duplicates()
                    .to_string(index=False)
                )

        return {
            "metrics": df_metrics,
            "probabilities": df_probabilities,
        }

    finally:
        # --------------------------------------------------
        # 5) Liberación de memoria
        # --------------------------------------------------
        del bundles, results
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

## **10.4. Función incremental de tuneo**

In [25]:
from itertools import product
import pandas as pd


def run_gru_grid_incremental(
    window_size: int,
    *,
    targets: list[str],
    hidden_size_values: list[int],
    num_layers_values: list[int],
    learning_rate_values: list[float],
    dropout_values: list[float],
    batch_size_values: list[int],
    grad_clip_norm_values: list[float | None],
    threshold_long_values: list[float],
    threshold_short_values: list[float],
    model_name: str = "gru",
    weight_decay: float = 0.0,
    eval_batch_size: int | None = None,
    epochs: int = 20,
    patience: int = 5,
    random_state: int = 42,
    device: str | None = None,
    class_weight=None,
    num_workers: int = 0,
    optimizer_name: str = "adam",
    split: str = "valid",
    verbose: bool = True,
) -> dict[str, pd.DataFrame]:

    # --------------------------------------------------
    # 0) Helpers
    # --------------------------------------------------
    def safe_eq(df, col, value):
        if col in df.columns:
            return df[col] == value
        return pd.Series(False, index=df.index)

    optimizer_name_norm = optimizer_name.lower()

    if eval_batch_size is None:
        # por consistencia, usar mismo batch_size que train
        # se redefine dentro del loop para cada combinación
        pass

    if class_weight == "balanced":
        class_weight_mode = "balanced"
    elif class_weight is None:
        class_weight_mode = "none"
    else:
        class_weight_mode = "custom"

    # --------------------------------------------------
    # 1) Cargar persistencia previa
    # --------------------------------------------------
    df_metrics_existing = load_classification_metrics_if_exists(
        model_name=model_name,
        split=split,
    )

    df_prob_existing = load_classification_probabilities_if_exists(
        model_name=model_name,
        split=split,
    )

    # --------------------------------------------------
    # 2) Asegurar columnas requeridas
    # --------------------------------------------------
    required_metric_cols = [
        "model", "split", "window_size", "target",
        "hidden_size", "num_layers", "dropout",
        "learning_rate", "weight_decay",
        "batch_size", "eval_batch_size",
        "epochs", "patience",
        "input_mode", "class_weight_mode",
        "optimizer_name", "grad_clip_norm",
        "num_workers", "random_state",
        "threshold_long", "threshold_short",
    ]

    required_prob_cols = required_metric_cols + ["sample_id"]

    for col in required_metric_cols:
        if col not in df_metrics_existing.columns:
            df_metrics_existing[col] = None

    for col in required_prob_cols:
        if col not in df_prob_existing.columns:
            df_prob_existing[col] = None

    # --------------------------------------------------
    # 3) Definir grilla
    # --------------------------------------------------
    grid = list(product(
        hidden_size_values,
        num_layers_values,
        learning_rate_values,
        dropout_values,
        batch_size_values,
        grad_clip_norm_values,
        threshold_long_values,
        threshold_short_values,
    ))

    if verbose:
        print("\n" + "=" * 100)
        print(f"GRU GRID INCREMENTAL | L={window_size}")
        print("=" * 100)
        print(f"targets                = {targets}")
        print(f"n_combinations         = {len(grid)}")
        print(f"hidden_size_values     = {hidden_size_values}")
        print(f"num_layers_values      = {num_layers_values}")
        print(f"learning_rate_values   = {learning_rate_values}")
        print(f"dropout_values         = {dropout_values}")
        print(f"batch_size_values      = {batch_size_values}")
        print(f"grad_clip_norm_values  = {grad_clip_norm_values}")
        print(f"threshold_long_values  = {threshold_long_values}")
        print(f"threshold_short_values = {threshold_short_values}")
        print(f"class_weight_mode      = {class_weight_mode}")
        print(f"optimizer_name         = {optimizer_name_norm}")

    # --------------------------------------------------
    # 4) Loop principal
    # --------------------------------------------------
    for i, (
        hidden_size,
        num_layers,
        learning_rate,
        dropout,
        batch_size,
        grad_clip_norm,
        thr_long,
        thr_short,
    ) in enumerate(grid, start=1):

        eval_bs_current = eval_batch_size if eval_batch_size is not None else batch_size

        if verbose:
            print("\n" + "-" * 100)
            print(
                f"[{i}/{len(grid)}] "
                f"hidden_size={hidden_size} | "
                f"num_layers={num_layers} | "
                f"learning_rate={learning_rate} | "
                f"dropout={dropout} | "
                f"batch_size={batch_size} | "
                f"eval_batch_size={eval_bs_current} | "
                f"grad_clip_norm={grad_clip_norm} | "
                f"thr_long={thr_long} | "
                f"thr_short={thr_short}"
            )

        # ----------------------------------------------
        # 4.1) Verificar si el experimento ya existe
        # ----------------------------------------------
        mask = (
            safe_eq(df_metrics_existing, "model", model_name) &
            safe_eq(df_metrics_existing, "split", split) &
            safe_eq(df_metrics_existing, "window_size", window_size) &
            safe_eq(df_metrics_existing, "hidden_size", hidden_size) &
            safe_eq(df_metrics_existing, "num_layers", num_layers) &
            safe_eq(df_metrics_existing, "dropout", dropout) &
            safe_eq(df_metrics_existing, "learning_rate", learning_rate) &
            safe_eq(df_metrics_existing, "weight_decay", weight_decay) &
            safe_eq(df_metrics_existing, "batch_size", batch_size) &
            safe_eq(df_metrics_existing, "eval_batch_size", eval_bs_current) &
            safe_eq(df_metrics_existing, "epochs", epochs) &
            safe_eq(df_metrics_existing, "patience", patience) &
            safe_eq(df_metrics_existing, "input_mode", "3d") &
            safe_eq(df_metrics_existing, "class_weight_mode", class_weight_mode) &
            safe_eq(df_metrics_existing, "optimizer_name", optimizer_name_norm) &
            safe_eq(df_metrics_existing, "grad_clip_norm", grad_clip_norm) &
            safe_eq(df_metrics_existing, "num_workers", num_workers) &
            safe_eq(df_metrics_existing, "random_state", random_state) &
            safe_eq(df_metrics_existing, "threshold_long", thr_long) &
            safe_eq(df_metrics_existing, "threshold_short", thr_short)
        )

        existing_targets = set(df_metrics_existing.loc[mask, "target"].dropna().unique())
        already_exists = set(targets).issubset(existing_targets)

        if already_exists:
            if verbose:
                print("✔ Ya existe -> skip")
            continue

        # ----------------------------------------------
        # 4.2) Ejecutar modelo
        # ----------------------------------------------
        results = run_gru(
            window_size=window_size,
            targets=targets,
            verbose=verbose,
            model_name=model_name,
            hidden_size=hidden_size,
            num_layers=num_layers,
            dropout=dropout,
            learning_rate=learning_rate,
            weight_decay=weight_decay,
            batch_size=batch_size,
            eval_batch_size=eval_bs_current,
            epochs=epochs,
            patience=patience,
            random_state=random_state,
            device=device,
            class_weight=class_weight,
            num_workers=num_workers,
            optimizer_name=optimizer_name_norm,
            grad_clip_norm=grad_clip_norm,
            prob_threshold_long=thr_long,
            prob_threshold_short=thr_short,
        )

        df_metrics_new = results["metrics"].copy()
        df_prob_new = results["probabilities"].copy()

        # ----------------------------------------------
        # 4.3) Completar metadata
        # ----------------------------------------------
        df_metrics_new["threshold_long"] = thr_long
        df_metrics_new["threshold_short"] = thr_short
        df_metrics_new["random_state"] = random_state

        df_prob_new["threshold_long"] = thr_long
        df_prob_new["threshold_short"] = thr_short
        df_prob_new["random_state"] = random_state

        df_prob_new = df_prob_new.reset_index(drop=True)
        if "sample_id" not in df_prob_new.columns:
            df_prob_new["sample_id"] = df_prob_new.index.astype(int)

        for col in required_metric_cols:
            if col not in df_metrics_new.columns:
                df_metrics_new[col] = None

        for col in required_prob_cols:
            if col not in df_prob_new.columns:
                df_prob_new[col] = None

        # ----------------------------------------------
        # 4.4) Append
        # ----------------------------------------------
        df_metrics_existing = pd.concat(
            [df_metrics_existing, df_metrics_new],
            ignore_index=True
        )

        df_prob_existing = pd.concat(
            [df_prob_existing, df_prob_new],
            ignore_index=True
        )

        # ----------------------------------------------
        # 4.5) Deduplicación correcta
        # ----------------------------------------------
        metric_key_cols = [
            "model", "split", "window_size", "target",
            "hidden_size", "num_layers", "dropout",
            "learning_rate", "weight_decay",
            "batch_size", "eval_batch_size",
            "epochs", "patience",
            "input_mode", "class_weight_mode",
            "optimizer_name", "grad_clip_norm",
            "num_workers", "random_state",
            "threshold_long", "threshold_short",
        ]

        prob_key_cols = metric_key_cols + ["sample_id"]

        df_metrics_existing = (
            df_metrics_existing
            .drop_duplicates(subset=metric_key_cols, keep="last")
            .reset_index(drop=True)
        )

        df_prob_existing = (
            df_prob_existing
            .drop_duplicates(subset=prob_key_cols, keep="last")
            .reset_index(drop=True)
        )

        # ----------------------------------------------
        # 4.6) Guardar
        # ----------------------------------------------
        save_classification_metrics(
            df_metrics_existing,
            model_name=model_name,
            split=split,
        )

        save_classification_probabilities(
            df_prob_existing,
            model_name=model_name,
            split=split,
        )

        if verbose:
            print(
                f"💾 Guardado OK | metrics={len(df_metrics_existing)} | "
                f"prob={len(df_prob_existing)}"
            )

    # --------------------------------------------------
    # 5) Retorno final
    # --------------------------------------------------
    return {
        "metrics": df_metrics_existing,
        "probabilities": df_prob_existing,
    }

# **11. Tuneo grueso**

In [26]:
results_gru_coarse = run_gru_grid_incremental(
    window_size=30,
    targets=["t2_p40_h30", "t2_p50_h30"],
    hidden_size_values=[64, 128, 256],
    num_layers_values=[1, 2],
    learning_rate_values=[1e-4, 5e-4, 1e-3],
    dropout_values=[0.0],
    batch_size_values=[2048],
    grad_clip_norm_values=[1.0],
    threshold_long_values=[0.40],
    threshold_short_values=[0.40],
    class_weight="balanced",
    epochs=20,
    patience=5,
    optimizer_name="adam",
    verbose=True,
)

2026-04-23 16:28:01,375 | INFO | No existen métricas previas para model=gru | split=valid
2026-04-23 16:28:01,377 | INFO | No existen probabilidades previas para model=gru | split=valid
2026-04-23 16:28:01,462 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:28:01,463 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:28:01,480 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:28:01,480 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:28:01,497 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:28:01,498 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:28:01,501 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:28:01,501 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:28:01,575 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:28:01,576 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

====================================================================================================
GRU GRID INCREMENTAL | L=30
====================================================================================================
targets                = ['t2_p40_h30', 't2_p50_h30']
n_combinations         = 18
hidden_size_values     = [64, 128, 256]
num_layers_values      = [1, 2]
learning_rate_values   = [0.0001, 0.0005, 0.001]
dropout_values         = [0.0]
batch_size_values      = [2048]
grad_clip_norm_values  = [1.0]
threshold_long_values  = [0.4]
threshold_short_values = [0.4]
class_weight_mode      = balanced
optimizer_name         = adam

----------------------------------------------------------------------------------------------------
[1/18] hidden_size=64 | num_layers=1 | learning_rate=0.0001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 64
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:28:01,593 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:28:01,594 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:28:01,611 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:28:01,612 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:28:01,615 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:28:01,615 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.408994  0.347568          10         1.087213
          30 valid t2_p50_h30   gru       30          balanced           0.408281  0.370536          10         1.087448

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:28:14,352 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:28:14,410 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:28:14,486 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:28:14,486 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:28:14,503 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:28:14,504 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:28:14,521 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:28:14,521 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:28:14,524 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:28:14,524 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:28:14,599 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:28:14,600 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=2 | prob=13764

----------------------------------------------------------------------------------------------------
[2/18] hidden_size=64 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 64
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:28:14,618 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:28:14,618 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:28:14,635 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:28:14,636 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:28:14,638 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:28:14,639 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.411686  0.371892           7         1.084561
          30 valid t2_p50_h30   gru       30          balanced           0.401612  0.381182           6         1.086538

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:28:24,493 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:28:24,578 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:28:24,658 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:28:24,658 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:28:24,676 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:28:24,676 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:28:24,693 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:28:24,694 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:28:24,697 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:28:24,697 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:28:24,769 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:28:24,770 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=4 | prob=27528

----------------------------------------------------------------------------------------------------
[3/18] hidden_size=64 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 64
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:28:24,788 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:28:24,789 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:28:24,806 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:28:24,807 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:28:24,809 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:28:24,810 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413897  0.383102           7         1.080837
          30 valid t2_p50_h30   gru       30          balanced           0.404258  0.392404           7         1.082373

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:28:35,212 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:28:35,347 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:28:35,424 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:28:35,425 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:28:35,442 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:28:35,443 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:28:35,459 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:28:35,459 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:28:35,462 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:28:35,463 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:28:35,534 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:28:35,534 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=6 | prob=41292

----------------------------------------------------------------------------------------------------
[4/18] hidden_size=64 | num_layers=2 | learning_rate=0.0001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 64
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:28:35,552 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:28:35,552 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:28:35,568 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:28:35,569 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:28:35,572 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:28:35,572 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412521  0.368715          18         1.084956
          30 valid t2_p50_h30   gru       30          balanced           0.407114  0.369257           5         1.087507

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:28:49,761 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:28:49,912 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:28:49,991 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:28:49,992 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:28:50,009 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:28:50,010 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:28:50,027 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:28:50,027 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:28:50,030 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:28:50,030 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:28:50,102 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:28:50,103 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=8 | prob=55056

----------------------------------------------------------------------------------------------------
[5/18] hidden_size=64 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 64
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:28:50,120 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:28:50,121 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:28:50,137 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:28:50,138 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:28:50,140 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:28:50,141 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.408135  0.377639          14         1.078176
          30 valid t2_p50_h30   gru       30          balanced           0.415447  0.394531           5         1.084573

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:29:03,857 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:29:04,041 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:29:04,117 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:29:04,117 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:29:04,134 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:29:04,135 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:29:04,153 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:29:04,153 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:29:04,156 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:29:04,157 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:29:04,228 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:29:04,229 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=10 | prob=68820

----------------------------------------------------------------------------------------------------
[6/18] hidden_size=64 | num_layers=2 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 64
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:29:04,246 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:29:04,247 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:29:04,263 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:29:04,264 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:29:04,267 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:29:04,267 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405991  0.354953           1         1.083359
          30 valid t2_p50_h30   gru       30          balanced           0.401349  0.378605           1         1.089626

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:29:10,624 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:29:10,846 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:29:10,922 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:29:10,923 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:29:10,940 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:29:10,941 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:29:10,958 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:29:10,959 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:29:10,962 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:29:10,963 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:29:11,035 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:29:11,035 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=12 | prob=82584

----------------------------------------------------------------------------------------------------
[7/18] hidden_size=128 | num_layers=1 | learning_rate=0.0001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:29:11,053 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:29:11,053 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:29:11,070 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:29:11,070 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:29:11,073 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:29:11,073 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413606  0.362557           5         1.085794
          30 valid t2_p50_h30   gru       30          balanced           0.413884  0.386290           5         1.085633

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:29:21,173 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:29:21,428 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:29:21,502 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:29:21,503 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:29:21,521 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:29:21,521 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:29:21,538 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:29:21,538 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:29:21,542 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:29:21,542 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:29:21,613 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:29:21,614 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:29:21,632 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:29:21,632 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=14 | prob=96348

----------------------------------------------------------------------------------------------------
[8/18] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:29:21,650 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:29:21,651 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:29:21,654 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:29:21,654 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414087  0.358966           1         1.083643
          30 valid t2_p50_h30   gru       30          balanced           0.415827  0.388544           1         1.083447

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:29:28,266 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:29:28,537 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:29:28,611 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:29:28,612 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:29:28,630 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:29:28,631 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:29:28,648 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:29:28,649 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:29:28,651 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:29:28,652 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:29:28,725 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:29:28,725 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=16 | prob=110112

----------------------------------------------------------------------------------------------------
[9/18] hidden_size=128 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:29:28,743 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:29:28,743 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:29:28,761 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:29:28,762 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:29:28,764 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:29:28,765 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416000  0.382470           4         1.081974
          30 valid t2_p50_h30   gru       30          balanced           0.401475  0.385026           3         1.083628

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:29:37,709 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:29:38,008 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:29:38,088 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:29:38,089 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:29:38,107 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:29:38,107 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:29:38,124 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:29:38,125 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:29:38,128 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:29:38,128 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:29:38,196 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:29:38,197 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=18 | prob=123876

----------------------------------------------------------------------------------------------------
[10/18] hidden_size=128 | num_layers=2 | learning_rate=0.0001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:29:38,214 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:29:38,214 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:29:38,231 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:29:38,232 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:29:38,234 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:29:38,235 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.407838  0.359453           3         1.086521
          30 valid t2_p50_h30   gru       30          balanced           0.405122  0.379310           3         1.086758

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:29:48,555 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:29:48,928 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:29:48,999 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:29:49,000 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:29:49,018 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:29:49,018 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:29:49,035 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:29:49,036 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:29:49,039 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:29:49,039 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:29:49,114 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:29:49,115 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:29:49,132 | INFO | Loaded: windows_t2_p50_h30_valid.npz

💾 Guardado OK | metrics=20 | prob=137640

----------------------------------------------------------------------------------------------------
[11/18] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:29:49,133 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:29:49,150 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:29:49,151 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:29:49,154 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:29:49,155 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420773  0.380090           5         1.083092
          30 valid t2_p50_h30   gru       30          balanced           0.413918  0.396479           5         1.083793

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:30:01,934 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:30:02,321 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:30:02,393 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:30:02,394 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:30:02,412 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:30:02,412 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:30:02,429 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:30:02,430 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:30:02,433 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:30:02,433 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:30:02,500 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:30:02,501 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:30:02,519 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:30:02,519 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=22 | prob=151404

----------------------------------------------------------------------------------------------------
[12/18] hidden_size=128 | num_layers=2 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:30:02,537 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:30:02,538 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:30:02,541 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:30:02,541 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.411974  0.378624           5         1.081095
          30 valid t2_p50_h30   gru       30          balanced           0.412597  0.402245           5         1.081388

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:30:15,258 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:30:15,684 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:30:15,758 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:30:15,758 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:30:15,776 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:30:15,776 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:30:15,793 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:30:15,794 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:30:15,797 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:30:15,797 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:30:15,869 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:30:15,870 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:30:15,887 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:30:15,888 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=24 | prob=165168

----------------------------------------------------------------------------------------------------
[13/18] hidden_size=256 | num_layers=1 | learning_rate=0.0001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:30:15,904 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:30:15,905 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:30:15,908 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:30:15,908 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.404813  0.344242           2         1.087023
          30 valid t2_p50_h30   gru       30          balanced           0.406260  0.372107           2         1.086373

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:30:24,389 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:30:24,834 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:30:24,906 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:30:24,907 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:30:24,927 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:30:24,928 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:30:24,945 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:30:24,946 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:30:24,949 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:30:24,949 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:30:25,022 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:30:25,022 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=26 | prob=178932

----------------------------------------------------------------------------------------------------
[14/18] hidden_size=256 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:30:25,041 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:30:25,041 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:30:25,059 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:30:25,059 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:30:25,063 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:30:25,063 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415522  0.384250           4         1.079870
          30 valid t2_p50_h30   gru       30          balanced           0.413029  0.396489           4         1.080906

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:30:35,641 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:30:36,112 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:30:36,182 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:30:36,183 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:30:36,200 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:30:36,201 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:30:36,218 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:30:36,219 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:30:36,222 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:30:36,222 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:30:36,295 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:30:36,295 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:30:36,312 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:30:36,313 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=28 | prob=192696

----------------------------------------------------------------------------------------------------
[15/18] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:30:36,330 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:30:36,331 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:30:36,334 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:30:36,334 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387677  0.340268           1         1.083371
          30 valid t2_p50_h30   gru       30          balanced           0.417474  0.407541           6         1.083879

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:30:46,804 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:30:47,301 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:30:47,370 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:30:47,370 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:30:47,388 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:30:47,388 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:30:47,407 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:30:47,407 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:30:47,410 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:30:47,411 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:30:47,478 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:30:47,479 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=30 | prob=206460

----------------------------------------------------------------------------------------------------
[16/18] hidden_size=256 | num_layers=2 | learning_rate=0.0001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:30:47,510 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:30:47,510 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:30:47,527 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:30:47,527 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:30:47,530 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:30:47,531 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414599  0.381658          12         1.082866
          30 valid t2_p50_h30   gru       30          balanced           0.403457  0.380892           6         1.086931

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:31:09,501 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:31:10,020 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:31:10,091 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:31:10,091 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:31:10,109 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:31:10,109 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:31:10,126 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:31:10,127 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:31:10,129 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:31:10,130 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:31:10,197 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:31:10,198 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:31:10,215 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:31:10,216 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=32 | prob=220224

----------------------------------------------------------------------------------------------------
[17/18] hidden_size=256 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:31:10,234 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:31:10,234 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:31:10,237 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:31:10,237 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.402960  0.366158           4         1.081130
          30 valid t2_p50_h30   gru       30          balanced           0.400909  0.385489           4         1.083932

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:31:24,941 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:31:25,487 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:31:25,558 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:31:25,559 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:31:25,576 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:31:25,577 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:31:25,593 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:31:25,594 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:31:25,596 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:31:25,597 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:31:25,666 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:31:25,667 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:31:25,684 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:31:25,685 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=34 | prob=233988

----------------------------------------------------------------------------------------------------
[18/18] hidden_size=256 | num_layers=2 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:31:25,703 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:31:25,704 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:31:25,707 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:31:25,707 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.398097  0.378543           3         1.078617
          30 valid t2_p50_h30   gru       30          balanced           0.384949  0.371254           3         1.085100

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:31:38,915 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:31:39,499 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet

💾 Guardado OK | metrics=36 | prob=247752

## **11.1. Análisis de tuneo grueso**

In [27]:
df_gru_coarse = results_gru_coarse["metrics"].copy()

# =========================================
# Resumen global por configuración
# =========================================
summary_gru = (
    df_gru_coarse
    .groupby(
        ["hidden_size", "num_layers", "learning_rate"],
        as_index=False
    )
    .agg(
        n_targets=("target", "nunique"),
        balanced_accuracy_mean=("balanced_accuracy", "mean"),
        balanced_accuracy_std=("balanced_accuracy", "std"),
        f1_macro_mean=("f1_macro", "mean"),
        f1_macro_std=("f1_macro", "std"),
        accuracy_mean=("accuracy", "mean"),
    )
    .sort_values(
        ["balanced_accuracy_mean", "f1_macro_mean"],
        ascending=False
    )
    .reset_index(drop=True)
)

# =========================================
# Mejor configuración por target
# =========================================
best_gru_by_target = (
    df_gru_coarse
    .sort_values(
        ["target", "balanced_accuracy", "f1_macro"],
        ascending=[True, False, False]
    )
    .groupby("target", as_index=False)
    .first()[[
        "target",
        "hidden_size",
        "num_layers",
        "learning_rate",
        "balanced_accuracy",
        "f1_macro",
    ]]
)

# =========================================
# Mejor configuración global
# =========================================
best_gru_global = summary_gru.iloc[0][
    ["hidden_size", "num_layers", "learning_rate"]
].to_dict()

print("Resumen global por configuración GRU")
display(summary_gru)

print("Mejor configuración por target")
display(best_gru_by_target)

print("Mejor configuración global:")
print(best_gru_global)

Resumen global por configuración GRU

,hidden_size,num_layers,learning_rate,n_targets,balanced_accuracy_mean,balanced_accuracy_std,f1_macro_mean,f1_macro_std,accuracy_mean
0,128,2,0.0005,2,0.417345,0.004847,0.388284,0.011589,0.405623
1,128,1,0.0005,2,0.414957,0.001230,0.373755,0.020915,0.401555
2,256,1,0.0005,2,0.414275,0.001763,0.390369,0.008654,0.404897
3,128,1,0.0001,2,0.413745,0.000197,0.374423,0.016782,0.401337
4,128,2,0.0010,2,0.412285,0.000440,0.390434,0.016703,0.403153
5,64,2,0.0005,2,0.411791,0.005170,0.386085,0.011945,0.403662
6,64,2,0.0001,2,0.409817,0.003823,0.368986,0.000383,0.398431
7,64,1,0.0010,2,0.409078,0.006816,0.387753,0.006577,0.400610
8,256,2,0.0001,2,0.409028,0.007879,0.381275,0.000542,0.401482
9,128,1,0.0010,2,0.408738,0.010271,0.383748,0.001808,0.400320
10,64,1,0.0001,2,0.408637,0.000504,0.359052,0.016241,0.393999
11,64,1,0.0005,2,0.406649,0.007123,0.376537,0.006569,0.397123
12,128,2,0.0001,2,0.406480,0.001920,0.369382,0.014041,0.395525
13,256,1,0.0001,2,0.405537,0.001023,0.358175,0.019703,0.390729
14,64,2,0.0010,2,0.403670,0.003282,0.366779,0.016724,0.392982
15,256,1,0.0010,2,0.402576,0.021070,0.373905,0.047570,0.395379
16,256,2,0.0005,2,0.401934,0.001450,0.375823,0.013669,0.393490
17,256,2,0.0010,2,0.391523,0.009297,0.374898,0.005154,0.390875

Mejor configuración por target

,target,hidden_size,num_layers,learning_rate,balanced_accuracy,f1_macro
0,t2_p40_h30,128,2,0.0005,0.420773,0.380090
1,t2_p50_h30,256,1,0.0010,0.417474,0.407541

Mejor configuración global:
{'hidden_size': 128, 'num_layers': 2, 'learning_rate': 0.0005}

Lectura principal

La mejor configuración global obtenida en el tuneo grueso es:

* hidden_size = 128
* num_layers = 2
* learning_rate = 0.0005

Con desempeño promedio:

* balanced_accuracy ≈ 0.417
* f1_macro ≈ 0.388

Esta configuración se posiciona como la mejor en términos agregados entre ambos targets.

---

Patrón dominante

Se observa un comportamiento bastante estable:

* hidden_size = 128 aparece sistemáticamente en las mejores configuraciones
* learning_rate = 0.0005 domina claramente
* modelos con 2 capas (num_layers = 2) tienden a mejorar levemente el desempeño

Interpretación:

* el modelo requiere una capacidad intermedia (no 64, no necesariamente 256)
* un learning_rate moderado permite mejor convergencia
* aumentar la profundidad ayuda, pero con impacto acotado

---

Relación entre capacidad y estabilidad

Comparando configuraciones:

* hidden_size = 128 muestra menor varianza y mayor estabilidad
* hidden_size = 256 no mejora consistentemente y en algunos casos degrada
* hidden_size = 64 queda por debajo en general

Esto indica que:

* el modelo no necesita alta capacidad
* aumentar demasiado la complejidad no aporta mejora

---

Análisis por target

Los mejores resultados por target son:

* t2_p40_h30:

  * 128, 2, 0.0005
* t2_p50_h30:

  * 256, 1, 0.001

Esto muestra una ligera diferencia entre targets, pero:

* la configuración global (128, 2, 0.0005) es más estable
* la alternativa (256, 1, 0.001) es más específica

---

Selección para tuneo fino

Se recomienda trabajar con al menos dos configuraciones:

Configuración principal:

* hidden_size = 128
* num_layers = 2
* learning_rate = 0.0005

Configuración alternativa:

* hidden_size = 256
* num_layers = 1
* learning_rate = 0.001

Opcional (más conservadora):

* hidden_size = 128
* num_layers = 1
* learning_rate = 0.0005

---

Conclusión operativa

El modelo GRU presenta mejor desempeño cuando:

* se utiliza una capacidad intermedia
* se emplea un learning_rate moderado
* se permite una ligera profundidad adicional

El espacio óptimo queda bien definido, permitiendo enfocar el tuneo fino en:

* regularización (dropout)
* estabilidad de entrenamiento (batch_size, grad_clip_norm)
* thresholds de decisión

No es necesario explorar configuraciones más grandes o learning rates más agresivos.

# **12. Tuneo fino**

In [ ]:
results_gru_fine_1 = run_gru_grid_incremental(
    window_size=30,
    targets=["t2_p40_h30", "t2_p50_h30"],
    hidden_size_values=[128],
    num_layers_values=[2],
    learning_rate_values=[5e-4],
    dropout_values=[0.0, 0.1, 0.2, 0.3],
    batch_size_values=[1024, 2048, 4096],
    grad_clip_norm_values=[0.5, 1.0, 2.0],
    threshold_long_values=[0.40, 0.45],
    threshold_short_values=[0.40, 0.45],
    class_weight="balanced",
    epochs=20,
    patience=5,
    optimizer_name="adam",
    verbose=True,
)

results_gru_fine_2 = run_gru_grid_incremental(
    window_size=30,
    targets=["t2_p40_h30", "t2_p50_h30"],
    hidden_size_values=[256],
    num_layers_values=[1],
    learning_rate_values=[1e-3],
    dropout_values=[0.0, 0.1, 0.2, 0.3],
    batch_size_values=[1024, 2048, 4096],
    grad_clip_norm_values=[0.5, 1.0, 2.0],
    threshold_long_values=[0.40, 0.45],
    threshold_short_values=[0.40, 0.45],
    class_weight="balanced",
    epochs=20,
    patience=5,
    optimizer_name="adam",
    verbose=True,
)

results_gru_fine_3 = run_gru_grid_incremental(
    window_size=30,
    targets=["t2_p40_h30", "t2_p50_h30"],
    hidden_size_values=[128],
    num_layers_values=[1],
    learning_rate_values=[5e-4],
    dropout_values=[0.0, 0.1, 0.2, 0.3],
    batch_size_values=[1024, 2048, 4096],
    grad_clip_norm_values=[0.5, 1.0, 2.0],
    threshold_long_values=[0.40, 0.45],
    threshold_short_values=[0.40, 0.45],
    class_weight="balanced",
    epochs=20,
    patience=5,
    optimizer_name="adam",
    verbose=True,
)

2026-04-23 16:36:13,719 | INFO | Cargando métricas desde: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:36:13,778 | INFO | Cargando probabilidades desde: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:36:13,907 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:36:13,907 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:36:13,925 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:36:13,925 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:36:13,942 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:36:13,942 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:36:13,945 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:36:13,946 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:36:14,011 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:36:14,012 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:36:14,029 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:36:14,030 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

====================================================================================================
GRU GRID INCREMENTAL | L=30
====================================================================================================
targets                = ['t2_p40_h30', 't2_p50_h30']
n_combinations         = 144
hidden_size_values     = [128]
num_layers_values      = [2]
learning_rate_values   = [0.0005]
dropout_values         = [0.0, 0.1, 0.2, 0.3]
batch_size_values      = [1024, 2048, 4096]
grad_clip_norm_values  = [0.5, 1.0, 2.0]
threshold_long_values  = [0.4, 0.45]
threshold_short_values = [0.4, 0.45]
class_weight_mode      = balanced
optimizer_name         = adam

----------------------------------------------------------------------------------------------------
[1/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:36:14,047 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:36:14,048 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:36:14,051 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:36:14,052 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412523  0.385360           7         1.081819
          30 valid t2_p50_h30   gru       30          balanced           0.412331  0.400635           7         1.086069

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:36:28,093 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:36:28,475 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:36:28,547 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:36:28,547 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:36:28,565 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:36:28,566 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:36:28,583 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:36:28,584 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:36:28,587 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:36:28,588 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:36:28,659 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:36:28,660 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:36:28,677 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:36:28,677 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=38 | prob=261516

----------------------------------------------------------------------------------------------------
[2/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:36:28,694 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:36:28,695 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:36:28,698 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:36:28,698 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412523  0.385360           7         1.081819
          30 valid t2_p50_h30   gru       30          balanced           0.412331  0.400635           7         1.086069

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:36:42,761 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:36:43,168 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:36:43,238 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:36:43,238 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:36:43,256 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:36:43,256 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:36:43,319 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:36:43,319 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:36:43,325 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:36:43,325 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=40 | prob=275280

----------------------------------------------------------------------------------------------------
[3/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:36:43,393 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:36:43,394 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:36:43,411 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:36:43,412 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:36:43,429 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:36:43,430 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:36:43,433 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:36:43,433 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412523  0.385360           7         1.081819
          30 valid t2_p50_h30   gru       30          balanced           0.412331  0.400635           7         1.086069

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:36:57,500 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:36:57,909 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:36:57,978 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:36:57,979 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:36:57,996 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:36:57,997 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:36:58,015 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:36:58,015 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:36:58,018 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:36:58,019 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:36:58,086 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:36:58,086 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:36:58,104 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:36:58,104 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=42 | prob=289044

----------------------------------------------------------------------------------------------------
[4/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:36:58,122 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:36:58,122 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:36:58,125 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:36:58,126 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412523  0.385360           7         1.081819
          30 valid t2_p50_h30   gru       30          balanced           0.412331  0.400635           7         1.086069

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:37:12,164 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:37:12,585 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:37:12,655 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:37:12,656 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:37:12,673 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:37:12,674 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:37:12,690 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:37:12,691 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:37:12,694 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:37:12,694 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:37:12,759 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:37:12,760 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:37:12,777 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:37:12,778 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=44 | prob=302808

----------------------------------------------------------------------------------------------------
[5/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:37:12,795 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:37:12,795 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:37:12,798 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:37:12,799 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412523  0.385360           7         1.081819
          30 valid t2_p50_h30   gru       30          balanced           0.412331  0.400635           7         1.086069

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:37:26,912 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:37:27,355 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:37:27,439 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:37:27,440 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:37:27,459 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:37:27,460 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:37:27,476 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:37:27,477 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:37:27,480 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:37:27,480 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:37:27,546 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:37:27,547 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=46 | prob=316572

----------------------------------------------------------------------------------------------------
[6/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:37:27,565 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:37:27,565 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:37:27,583 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:37:27,583 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:37:27,586 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:37:27,587 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412523  0.385360           7         1.081819
          30 valid t2_p50_h30   gru       30          balanced           0.412331  0.400635           7         1.086069

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:37:41,743 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:37:42,198 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:37:42,268 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:37:42,268 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:37:42,286 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:37:42,287 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:37:42,303 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:37:42,304 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:37:42,306 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:37:42,307 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:37:42,372 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:37:42,373 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:37:42,390 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:37:42,391 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=48 | prob=330336

----------------------------------------------------------------------------------------------------
[7/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:37:42,408 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:37:42,409 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:37:42,412 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:37:42,413 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412523  0.385360           7         1.081819
          30 valid t2_p50_h30   gru       30          balanced           0.412331  0.400635           7         1.086069

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:37:56,526 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:37:57,007 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:37:57,076 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:37:57,077 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:37:57,095 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:37:57,096 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:37:57,113 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:37:57,113 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:37:57,116 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:37:57,117 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:37:57,184 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:37:57,185 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:37:57,203 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:37:57,204 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=50 | prob=344100

----------------------------------------------------------------------------------------------------
[8/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:37:57,222 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:37:57,222 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:37:57,225 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:37:57,226 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412523  0.385360           7         1.081819
          30 valid t2_p50_h30   gru       30          balanced           0.412331  0.400635           7         1.086069

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:38:11,408 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:38:11,883 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:38:11,952 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:38:11,953 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:38:11,983 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:38:11,984 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:38:12,001 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:38:12,002 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:38:12,005 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:38:12,006 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:38:12,072 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:38:12,073 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=52 | prob=357864

----------------------------------------------------------------------------------------------------
[9/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:38:12,091 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:38:12,091 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:38:12,108 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:38:12,109 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:38:12,111 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:38:12,112 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412523  0.385360           7         1.081819
          30 valid t2_p50_h30   gru       30          balanced           0.412331  0.400635           7         1.086069

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:38:26,381 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:38:26,880 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:38:26,950 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:38:26,950 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:38:26,968 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:38:26,969 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:38:26,985 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:38:26,986 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:38:26,989 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:38:26,989 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:38:27,060 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:38:27,060 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:38:27,078 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:38:27,078 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=54 | prob=371628

----------------------------------------------------------------------------------------------------
[10/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:38:27,095 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:38:27,096 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:38:27,099 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:38:27,099 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412523  0.385360           7         1.081819
          30 valid t2_p50_h30   gru       30          balanced           0.412331  0.400635           7         1.086069

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:38:41,384 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:38:41,889 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:38:41,959 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:38:41,959 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:38:41,977 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:38:41,977 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:38:41,994 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:38:41,994 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:38:41,997 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:38:41,998 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:38:42,070 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:38:42,071 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:38:42,088 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:38:42,088 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=56 | prob=385392

----------------------------------------------------------------------------------------------------
[11/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:38:42,106 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:38:42,106 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:38:42,109 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:38:42,110 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412523  0.385360           7         1.081819
          30 valid t2_p50_h30   gru       30          balanced           0.412331  0.400635           7         1.086069

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:38:56,308 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:38:56,840 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:38:56,931 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:38:56,931 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:38:56,949 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:38:56,950 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:38:56,967 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:38:56,967 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:38:56,970 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:38:56,970 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:38:57,038 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:38:57,039 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=58 | prob=399156

----------------------------------------------------------------------------------------------------
[12/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:38:57,057 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:38:57,058 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:38:57,075 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:38:57,075 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:38:57,078 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:38:57,079 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412523  0.385360           7         1.081819
          30 valid t2_p50_h30   gru       30          balanced           0.412331  0.400635           7         1.086069

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:39:11,345 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:39:11,878 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:39:11,950 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:39:11,951 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:39:11,969 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:39:11,970 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:39:11,987 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:39:11,988 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:39:11,992 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:39:11,992 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:39:12,059 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:39:12,059 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:39:12,078 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:39:12,079 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=60 | prob=412920

----------------------------------------------------------------------------------------------------
[13/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:39:12,096 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:39:12,097 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:39:12,100 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:39:12,100 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420773  0.380090           5         1.083092
          30 valid t2_p50_h30   gru       30          balanced           0.413918  0.396479           5         1.083793

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:39:24,944 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:39:25,496 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:39:25,567 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:39:25,568 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:39:25,585 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:39:25,586 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:39:25,603 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:39:25,604 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:39:25,606 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:39:25,607 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:39:25,673 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:39:25,674 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:39:25,691 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:39:25,691 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=62 | prob=426684

----------------------------------------------------------------------------------------------------
[14/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:39:25,709 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:39:25,710 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:39:25,714 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:39:25,714 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420773  0.380090           5         1.083092
          30 valid t2_p50_h30   gru       30          balanced           0.413918  0.396479           5         1.083793

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:39:38,641 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:39:39,224 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:39:39,295 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:39:39,296 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:39:39,313 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:39:39,314 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:39:39,331 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:39:39,332 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:39:39,335 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:39:39,336 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:39:39,404 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:39:39,405 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:39:39,423 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:39:39,424 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=64 | prob=440448

----------------------------------------------------------------------------------------------------
[15/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:39:39,442 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:39:39,443 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:39:39,446 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:39:39,446 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420773  0.380090           5         1.083092
          30 valid t2_p50_h30   gru       30          balanced           0.413918  0.396479           5         1.083793

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:39:52,340 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:39:52,928 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:39:52,998 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:39:52,999 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:39:53,016 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:39:53,017 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:39:53,034 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:39:53,034 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:39:53,037 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:39:53,037 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:39:53,103 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:39:53,104 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:39:53,121 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:39:53,122 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=66 | prob=454212

----------------------------------------------------------------------------------------------------
[16/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:39:53,140 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:39:53,140 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:39:53,143 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:39:53,144 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420773  0.380090           5         1.083092
          30 valid t2_p50_h30   gru       30          balanced           0.413918  0.396479           5         1.083793

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:40:06,114 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:40:06,718 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:40:06,791 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:40:06,792 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:40:06,809 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:40:06,810 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:40:06,828 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:40:06,829 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:40:06,832 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:40:06,832 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:40:06,898 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:40:06,899 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:40:06,916 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:40:06,916 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=68 | prob=467976

----------------------------------------------------------------------------------------------------
[17/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4
✔ Ya existe -> skip

----------------------------------------------------------------------------------------------------
[18/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:40:06,934 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:40:06,934 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:40:06,937 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:40:06,938 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420773  0.380090           5         1.083092
          30 valid t2_p50_h30   gru       30          balanced           0.413918  0.396479           5         1.083793

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:40:19,841 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:40:20,450 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:40:20,520 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:40:20,521 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:40:20,538 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:40:20,538 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:40:20,555 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:40:20,555 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:40:20,558 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:40:20,558 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:40:20,624 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:40:20,625 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:40:20,643 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:40:20,643 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=70 | prob=481740

----------------------------------------------------------------------------------------------------
[19/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:40:20,661 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:40:20,662 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:40:20,665 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:40:20,665 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420773  0.380090           5         1.083092
          30 valid t2_p50_h30   gru       30          balanced           0.413918  0.396479           5         1.083793

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:40:33,644 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:40:34,265 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:40:34,334 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:40:34,335 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:40:34,352 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:40:34,352 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:40:34,369 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:40:34,369 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:40:34,373 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:40:34,373 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:40:34,439 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:40:34,440 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:40:34,458 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:40:34,458 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=72 | prob=495504

----------------------------------------------------------------------------------------------------
[20/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:40:34,476 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:40:34,476 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:40:34,479 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:40:34,480 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420773  0.380090           5         1.083092
          30 valid t2_p50_h30   gru       30          balanced           0.413918  0.396479           5         1.083793

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:40:47,532 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:40:48,164 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:40:48,236 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:40:48,236 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:40:48,254 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:40:48,254 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:40:48,271 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:40:48,272 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:40:48,275 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:40:48,275 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:40:48,341 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:40:48,342 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:40:48,359 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:40:48,360 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=74 | prob=509268

----------------------------------------------------------------------------------------------------
[21/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:40:48,377 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:40:48,378 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:40:48,381 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:40:48,381 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420773  0.380090           5         1.083092
          30 valid t2_p50_h30   gru       30          balanced           0.413918  0.396479           5         1.083793

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:41:01,452 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:41:02,118 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:41:02,188 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:41:02,189 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:41:02,206 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:41:02,207 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:41:02,224 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:41:02,224 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:41:02,227 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:41:02,228 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:41:02,295 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:41:02,296 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:41:02,313 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:41:02,314 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=76 | prob=523032

----------------------------------------------------------------------------------------------------
[22/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:41:02,333 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:41:02,333 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:41:02,336 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:41:02,337 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420773  0.380090           5         1.083092
          30 valid t2_p50_h30   gru       30          balanced           0.413918  0.396479           5         1.083793

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:41:15,347 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:41:16,035 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:41:16,108 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:41:16,109 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:41:16,126 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:41:16,126 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:41:16,144 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:41:16,145 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:41:16,147 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:41:16,148 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:41:16,214 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:41:16,215 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:41:16,232 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:41:16,233 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=78 | prob=536796

----------------------------------------------------------------------------------------------------
[23/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:41:16,251 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:41:16,252 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:41:16,255 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:41:16,256 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420773  0.380090           5         1.083092
          30 valid t2_p50_h30   gru       30          balanced           0.413918  0.396479           5         1.083793

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:41:29,379 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:41:30,067 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:41:30,138 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:41:30,138 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:41:30,156 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:41:30,156 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:41:30,173 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:41:30,174 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:41:30,177 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:41:30,178 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:41:30,243 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:41:30,244 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:41:30,262 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:41:30,262 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=80 | prob=550560

----------------------------------------------------------------------------------------------------
[24/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:41:30,280 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:41:30,281 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:41:30,284 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:41:30,285 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420773  0.380090           5         1.083092
          30 valid t2_p50_h30   gru       30          balanced           0.413918  0.396479           5         1.083793

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:41:43,440 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:41:44,169 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:41:44,239 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:41:44,240 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:41:44,257 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:41:44,258 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:41:44,276 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:41:44,277 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:41:44,280 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:41:44,281 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:41:44,354 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:41:44,355 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:41:44,373 | INFO | Loaded: windows_t2_p50_h30_valid.npz

💾 Guardado OK | metrics=82 | prob=564324

----------------------------------------------------------------------------------------------------
[25/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:41:44,374 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:41:44,391 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:41:44,392 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:41:44,395 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:41:44,396 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415875   0.37297           6         1.083254
          30 valid t2_p50_h30   gru       30          balanced           0.408774   0.39010           1         1.083818

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:41:56,733 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:41:57,498 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:41:57,570 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:41:57,571 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:41:57,589 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:41:57,589 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:41:57,607 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:41:57,608 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:41:57,611 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:41:57,611 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:41:57,678 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:41:57,678 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:41:57,696 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:41:57,697 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=84 | prob=578088

----------------------------------------------------------------------------------------------------
[26/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:41:57,714 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:41:57,715 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:41:57,719 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:41:57,719 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415875   0.37297           6         1.083254
          30 valid t2_p50_h30   gru       30          balanced           0.408774   0.39010           1         1.083818

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:42:09,981 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:42:10,728 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:42:10,799 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:42:10,800 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:42:10,818 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:42:10,819 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:42:10,837 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:42:10,837 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:42:10,841 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:42:10,842 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:42:10,910 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:42:10,911 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:42:10,929 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:42:10,929 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=86 | prob=591852

----------------------------------------------------------------------------------------------------
[27/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:42:10,947 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:42:10,948 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:42:10,950 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:42:10,951 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415875   0.37297           6         1.083254
          30 valid t2_p50_h30   gru       30          balanced           0.408774   0.39010           1         1.083818

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:42:23,315 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:42:24,082 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:42:24,153 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:42:24,153 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:42:24,171 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:42:24,172 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:42:24,189 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:42:24,190 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:42:24,192 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:42:24,193 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:42:24,260 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:42:24,261 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:42:24,279 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:42:24,280 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=88 | prob=605616

----------------------------------------------------------------------------------------------------
[28/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:42:24,298 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:42:24,298 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:42:24,302 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:42:24,303 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415875   0.37297           6         1.083254
          30 valid t2_p50_h30   gru       30          balanced           0.408774   0.39010           1         1.083818

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:42:36,761 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:42:37,538 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:42:37,608 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:42:37,609 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:42:37,627 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:42:37,628 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:42:37,645 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:42:37,646 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:42:37,649 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:42:37,650 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:42:37,718 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:42:37,719 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:42:37,736 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:42:37,737 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=90 | prob=619380

----------------------------------------------------------------------------------------------------
[29/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:42:37,755 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:42:37,756 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:42:37,759 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:42:37,759 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415875   0.37297           6         1.083254
          30 valid t2_p50_h30   gru       30          balanced           0.408774   0.39010           1         1.083818

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:42:50,206 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:42:50,988 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:42:51,066 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:42:51,066 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:42:51,084 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:42:51,085 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:42:51,102 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:42:51,103 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:42:51,107 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:42:51,108 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:42:51,174 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:42:51,175 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:42:51,193 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:42:51,193 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=92 | prob=633144

----------------------------------------------------------------------------------------------------
[30/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:42:51,211 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:42:51,212 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:42:51,215 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:42:51,216 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415875   0.37297           6         1.083254
          30 valid t2_p50_h30   gru       30          balanced           0.408774   0.39010           1         1.083818

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:43:03,712 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:43:04,515 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:43:04,586 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:43:04,586 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:43:04,607 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:43:04,607 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:43:04,625 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:43:04,625 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:43:04,628 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:43:04,629 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:43:04,695 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:43:04,696 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:43:04,713 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:43:04,713 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=94 | prob=646908

----------------------------------------------------------------------------------------------------
[31/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:43:04,732 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:43:04,732 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:43:04,735 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:43:04,736 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415875   0.37297           6         1.083254
          30 valid t2_p50_h30   gru       30          balanced           0.408774   0.39010           1         1.083818

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:43:17,151 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:43:17,983 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:43:18,057 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:43:18,057 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:43:18,075 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:43:18,076 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:43:18,093 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:43:18,093 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:43:18,096 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:43:18,097 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:43:18,163 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:43:18,163 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:43:18,182 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:43:18,182 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=96 | prob=660672

----------------------------------------------------------------------------------------------------
[32/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:43:18,201 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:43:18,201 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:43:18,204 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:43:18,205 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415875   0.37297           6         1.083254
          30 valid t2_p50_h30   gru       30          balanced           0.408774   0.39010           1         1.083818

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:43:30,616 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:43:31,438 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:43:31,512 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:43:31,512 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:43:31,529 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:43:31,530 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:43:31,547 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:43:31,548 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:43:31,551 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:43:31,551 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:43:31,619 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:43:31,620 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:43:31,638 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:43:31,638 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=98 | prob=674436

----------------------------------------------------------------------------------------------------
[33/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:43:31,656 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:43:31,657 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:43:31,660 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:43:31,661 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415875   0.37297           6         1.083254
          30 valid t2_p50_h30   gru       30          balanced           0.408774   0.39010           1         1.083818

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:43:44,113 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:43:44,960 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:43:45,030 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:43:45,031 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:43:45,049 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:43:45,049 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:43:45,066 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:43:45,067 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:43:45,070 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:43:45,071 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:43:45,136 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:43:45,136 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:43:45,154 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:43:45,155 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=100 | prob=688200

----------------------------------------------------------------------------------------------------
[34/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:43:45,172 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:43:45,173 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:43:45,175 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:43:45,176 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415875   0.37297           6         1.083254
          30 valid t2_p50_h30   gru       30          balanced           0.408774   0.39010           1         1.083818

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:43:57,669 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:43:58,527 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:43:58,598 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:43:58,599 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:43:58,616 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:43:58,617 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:43:58,634 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:43:58,634 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:43:58,637 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:43:58,638 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:43:58,704 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:43:58,705 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:43:58,723 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:43:58,723 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=102 | prob=701964

----------------------------------------------------------------------------------------------------
[35/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:43:58,742 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:43:58,743 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:43:58,746 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:43:58,746 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415875   0.37297           6         1.083254
          30 valid t2_p50_h30   gru       30          balanced           0.408774   0.39010           1         1.083818

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:44:11,224 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:44:12,090 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:44:12,160 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:44:12,160 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:44:12,177 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:44:12,178 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:44:12,195 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:44:12,195 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:44:12,198 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:44:12,199 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:44:12,265 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:44:12,266 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:44:12,283 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:44:12,283 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=104 | prob=715728

----------------------------------------------------------------------------------------------------
[36/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:44:12,301 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:44:12,302 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:44:12,304 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:44:12,305 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415875   0.37297           6         1.083254
          30 valid t2_p50_h30   gru       30          balanced           0.408774   0.39010           1         1.083818

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:44:24,831 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:44:25,714 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:44:25,784 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:44:25,784 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:44:25,802 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:44:25,803 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:44:25,821 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:44:25,822 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:44:25,825 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:44:25,825 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:44:25,893 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:44:25,894 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:44:25,911 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:44:25,912 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=106 | prob=729492

----------------------------------------------------------------------------------------------------
[37/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:44:25,930 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:44:25,931 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:44:25,934 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:44:25,934 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410090  0.381527           7         1.082837
          30 valid t2_p50_h30   gru       30          balanced           0.409984  0.395320           4         1.087172

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:44:39,396 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:44:40,294 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:44:40,364 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:44:40,365 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:44:40,382 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:44:40,383 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:44:40,400 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:44:40,401 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:44:40,404 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:44:40,405 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:44:40,472 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:44:40,473 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:44:40,490 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:44:40,490 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=108 | prob=743256

----------------------------------------------------------------------------------------------------
[38/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:44:40,510 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:44:40,511 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:44:40,514 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:44:40,515 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410090  0.381527           7         1.082837
          30 valid t2_p50_h30   gru       30          balanced           0.409984  0.395320           4         1.087172

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:44:53,987 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:44:54,939 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:44:55,014 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:44:55,015 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:44:55,033 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:44:55,034 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:44:55,052 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:44:55,053 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:44:55,056 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:44:55,056 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:44:55,124 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:44:55,124 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:44:55,141 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:44:55,142 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=110 | prob=757020

----------------------------------------------------------------------------------------------------
[39/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:44:55,159 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:44:55,160 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:44:55,163 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:44:55,163 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410090  0.381527           7         1.082837
          30 valid t2_p50_h30   gru       30          balanced           0.409984  0.395320           4         1.087172

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:45:08,676 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:45:09,600 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:45:09,673 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:45:09,674 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:45:09,691 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:45:09,692 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:45:09,709 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:45:09,709 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:45:09,712 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:45:09,713 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:45:09,779 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:45:09,780 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:45:09,797 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:45:09,798 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=112 | prob=770784

----------------------------------------------------------------------------------------------------
[40/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:45:09,815 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:45:09,815 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:45:09,818 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:45:09,819 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410090  0.381527           7         1.082837
          30 valid t2_p50_h30   gru       30          balanced           0.409984  0.395320           4         1.087172

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:45:23,317 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:45:24,270 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:45:24,346 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:45:24,347 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:45:24,365 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:45:24,365 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:45:24,383 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:45:24,383 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:45:24,386 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:45:24,386 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:45:24,453 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:45:24,454 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:45:24,472 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:45:24,472 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=114 | prob=784548

----------------------------------------------------------------------------------------------------
[41/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:45:24,490 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:45:24,490 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:45:24,493 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:45:24,494 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410090  0.381527           7         1.082837
          30 valid t2_p50_h30   gru       30          balanced           0.409984  0.395320           4         1.087172

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:45:38,020 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:45:38,977 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:45:39,048 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:45:39,049 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:45:39,066 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:45:39,067 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:45:39,084 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:45:39,084 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:45:39,087 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:45:39,088 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:45:39,154 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:45:39,155 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:45:39,172 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:45:39,172 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=116 | prob=798312

----------------------------------------------------------------------------------------------------
[42/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:45:39,189 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:45:39,190 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:45:39,193 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:45:39,193 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410090  0.381527           7         1.082837
          30 valid t2_p50_h30   gru       30          balanced           0.409984  0.395320           4         1.087172

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:45:52,778 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:45:53,752 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:45:53,823 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:45:53,824 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:45:53,841 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:45:53,842 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:45:53,859 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:45:53,860 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:45:53,863 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:45:53,863 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:45:53,930 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:45:53,931 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:45:53,949 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:45:53,950 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=118 | prob=812076

----------------------------------------------------------------------------------------------------
[43/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:45:53,968 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:45:53,968 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:45:53,972 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:45:53,972 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410090  0.381527           7         1.082837
          30 valid t2_p50_h30   gru       30          balanced           0.409984  0.395320           4         1.087172

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:46:07,491 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:46:08,478 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:46:08,553 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:46:08,554 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:46:08,572 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:46:08,573 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:46:08,590 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:46:08,590 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:46:08,593 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:46:08,594 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:46:08,661 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:46:08,662 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:46:08,678 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:46:08,679 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=120 | prob=825840

----------------------------------------------------------------------------------------------------
[44/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:46:08,696 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:46:08,697 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:46:08,700 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:46:08,700 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410090  0.381527           7         1.082837
          30 valid t2_p50_h30   gru       30          balanced           0.409984  0.395320           4         1.087172

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:46:22,289 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:46:23,309 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:46:23,385 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:46:23,386 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:46:23,404 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:46:23,405 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:46:23,423 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:46:23,423 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:46:23,426 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:46:23,427 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:46:23,495 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:46:23,496 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:46:23,514 | INFO | Loaded: windows_t2_p50_h30_valid.npz

💾 Guardado OK | metrics=122 | prob=839604

----------------------------------------------------------------------------------------------------
[45/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:46:23,514 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:46:23,534 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:46:23,534 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:46:23,537 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:46:23,537 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410090  0.381527           7         1.082837
          30 valid t2_p50_h30   gru       30          balanced           0.409984  0.395320           4         1.087172

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:46:37,145 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:46:38,169 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:46:38,243 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:46:38,244 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:46:38,261 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:46:38,262 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:46:38,279 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:46:38,280 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:46:38,283 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:46:38,283 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:46:38,351 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:46:38,351 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:46:38,369 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:46:38,370 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=124 | prob=853368

----------------------------------------------------------------------------------------------------
[46/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:46:38,388 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:46:38,389 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:46:38,392 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:46:38,392 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410090  0.381527           7         1.082837
          30 valid t2_p50_h30   gru       30          balanced           0.409984  0.395320           4         1.087172

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:46:52,034 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:46:53,053 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:46:53,128 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:46:53,128 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:46:53,146 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:46:53,147 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:46:53,164 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:46:53,164 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:46:53,167 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:46:53,168 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:46:53,236 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:46:53,236 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:46:53,254 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:46:53,255 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=126 | prob=867132

----------------------------------------------------------------------------------------------------
[47/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:46:53,272 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:46:53,272 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:46:53,275 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:46:53,275 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410090  0.381527           7         1.082837
          30 valid t2_p50_h30   gru       30          balanced           0.409984  0.395320           4         1.087172

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:47:06,962 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:47:08,019 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:47:08,095 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:47:08,096 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:47:08,113 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:47:08,114 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:47:08,131 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:47:08,132 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:47:08,134 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:47:08,134 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:47:08,200 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:47:08,200 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:47:08,218 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:47:08,219 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=128 | prob=880896

----------------------------------------------------------------------------------------------------
[48/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:47:08,237 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:47:08,237 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:47:08,241 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:47:08,241 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410090  0.381527           7         1.082837
          30 valid t2_p50_h30   gru       30          balanced           0.409984  0.395320           4         1.087172

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:47:21,865 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:47:22,922 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:47:22,992 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:47:22,993 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:47:23,010 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:47:23,011 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:47:23,029 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:47:23,029 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:47:23,032 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:47:23,032 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:47:23,098 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:47:23,099 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:47:23,117 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:47:23,117 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=130 | prob=894660

----------------------------------------------------------------------------------------------------
[49/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:47:23,135 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:47:23,136 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:47:23,139 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:47:23,139 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420364  0.380199           5         1.082874
          30 valid t2_p50_h30   gru       30          balanced           0.413400  0.395978           5         1.083665

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:47:37,095 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:47:38,160 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:47:38,235 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:47:38,236 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:47:38,254 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:47:38,254 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:47:38,271 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:47:38,272 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:47:38,275 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:47:38,275 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:47:38,342 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:47:38,342 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:47:38,360 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:47:38,361 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=132 | prob=908424

----------------------------------------------------------------------------------------------------
[50/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:47:38,378 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:47:38,378 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:47:38,381 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:47:38,382 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420364  0.380199           5         1.082874
          30 valid t2_p50_h30   gru       30          balanced           0.413400  0.395978           5         1.083665

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:47:52,386 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:47:53,463 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:47:53,535 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:47:53,536 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:47:53,553 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:47:53,554 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:47:53,572 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:47:53,573 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:47:53,576 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:47:53,576 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:47:53,642 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:47:53,642 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:47:53,660 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:47:53,660 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=134 | prob=922188

----------------------------------------------------------------------------------------------------
[51/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:47:53,677 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:47:53,678 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:47:53,681 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:47:53,682 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420364  0.380199           5         1.082874
          30 valid t2_p50_h30   gru       30          balanced           0.413400  0.395978           5         1.083665

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:48:07,705 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:48:08,819 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:48:08,889 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:48:08,890 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:48:08,907 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:48:08,908 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:48:08,925 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:48:08,925 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:48:08,928 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:48:08,929 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:48:08,995 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:48:08,995 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:48:09,013 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:48:09,014 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=136 | prob=935952

----------------------------------------------------------------------------------------------------
[52/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:48:09,031 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:48:09,031 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:48:09,034 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:48:09,035 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420364  0.380199           5         1.082874
          30 valid t2_p50_h30   gru       30          balanced           0.413400  0.395978           5         1.083665

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:48:23,059 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:48:24,196 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:48:24,273 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:48:24,274 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:48:24,292 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:48:24,293 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:48:24,310 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:48:24,311 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:48:24,314 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:48:24,314 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:48:24,381 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:48:24,381 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:48:24,399 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:48:24,400 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=138 | prob=949716

----------------------------------------------------------------------------------------------------
[53/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:48:24,419 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:48:24,420 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:48:24,423 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:48:24,423 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420364  0.380199           5         1.082874
          30 valid t2_p50_h30   gru       30          balanced           0.413400  0.395978           5         1.083665

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:48:38,450 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:48:39,567 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:48:39,644 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:48:39,645 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:48:39,662 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:48:39,663 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:48:39,679 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:48:39,680 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:48:39,683 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:48:39,683 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:48:39,751 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:48:39,752 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:48:39,771 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:48:39,771 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=140 | prob=963480

----------------------------------------------------------------------------------------------------
[54/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:48:39,791 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:48:39,792 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:48:39,795 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:48:39,796 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420364  0.380199           5         1.082874
          30 valid t2_p50_h30   gru       30          balanced           0.413400  0.395978           5         1.083665

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:48:53,878 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:48:55,029 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:48:55,105 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:48:55,106 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:48:55,123 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:48:55,123 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:48:55,140 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:48:55,141 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:48:55,144 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:48:55,144 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:48:55,210 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:48:55,211 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:48:55,228 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:48:55,229 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=142 | prob=977244

----------------------------------------------------------------------------------------------------
[55/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:48:55,247 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:48:55,247 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:48:55,250 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:48:55,250 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420364  0.380199           5         1.082874
          30 valid t2_p50_h30   gru       30          balanced           0.413400  0.395978           5         1.083665

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:49:09,354 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:49:10,518 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:49:10,594 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:49:10,595 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:49:10,612 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:49:10,613 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:49:10,631 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:49:10,632 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:49:10,635 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:49:10,636 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:49:10,702 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:49:10,703 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:49:10,720 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:49:10,721 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=144 | prob=991008

----------------------------------------------------------------------------------------------------
[56/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:49:10,738 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:49:10,739 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:49:10,742 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:49:10,742 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420364  0.380199           5         1.082874
          30 valid t2_p50_h30   gru       30          balanced           0.413400  0.395978           5         1.083665

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:49:24,877 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:49:26,038 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:49:26,115 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:49:26,116 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:49:26,133 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:49:26,134 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:49:26,151 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:49:26,151 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:49:26,155 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:49:26,155 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:49:26,223 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:49:26,223 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:49:26,241 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:49:26,242 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=146 | prob=1004772

----------------------------------------------------------------------------------------------------
[57/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:49:26,260 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:49:26,261 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:49:26,294 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:49:26,295 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420364  0.380199           5         1.082874
          30 valid t2_p50_h30   gru       30          balanced           0.413400  0.395978           5         1.083665

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:49:40,473 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:49:41,653 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:49:41,730 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:49:41,731 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:49:41,750 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:49:41,751 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:49:41,768 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:49:41,769 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:49:41,773 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:49:41,773 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:49:41,840 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:49:41,841 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:49:41,858 | INFO | Loaded: windows_t2_p50_h30_valid.npz

💾 Guardado OK | metrics=148 | prob=1018536

----------------------------------------------------------------------------------------------------
[58/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:49:41,859 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:49:41,877 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:49:41,878 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:49:41,881 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:49:41,881 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420364  0.380199           5         1.082874
          30 valid t2_p50_h30   gru       30          balanced           0.413400  0.395978           5         1.083665

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:49:56,150 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:49:57,360 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:49:57,439 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:49:57,440 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:49:57,458 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:49:57,459 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:49:57,477 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:49:57,478 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:49:57,481 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:49:57,482 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:49:57,550 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:49:57,551 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=150 | prob=1032300

----------------------------------------------------------------------------------------------------
[59/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:49:57,569 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:49:57,569 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:49:57,587 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:49:57,587 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:49:57,590 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:49:57,591 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420364  0.380199           5         1.082874
          30 valid t2_p50_h30   gru       30          balanced           0.413400  0.395978           5         1.083665

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:50:11,875 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:50:13,080 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:50:13,158 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:50:13,159 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:50:13,177 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:50:13,177 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:50:13,195 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:50:13,195 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:50:13,198 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:50:13,199 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=152 | prob=1046064

----------------------------------------------------------------------------------------------------
[60/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:50:13,294 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:50:13,295 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:50:13,314 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:50:13,315 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:50:13,332 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:50:13,332 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:50:13,335 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:50:13,335 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.420364  0.380199           5         1.082874
          30 valid t2_p50_h30   gru       30          balanced           0.413400  0.395978           5         1.083665

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:50:27,611 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:50:28,853 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:50:28,933 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:50:28,934 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:50:28,952 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:50:28,953 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:50:28,970 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:50:28,971 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:50:28,974 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:50:28,975 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:50:29,042 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:50:29,043 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=154 | prob=1059828

----------------------------------------------------------------------------------------------------
[61/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:50:29,061 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:50:29,061 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:50:29,079 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:50:29,079 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:50:29,082 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:50:29,083 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415811  0.372365           6         1.083217
          30 valid t2_p50_h30   gru       30          balanced           0.408776  0.389607           1         1.083993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:50:42,406 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:50:43,679 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:50:43,757 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:50:43,757 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:50:43,774 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:50:43,775 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:50:43,792 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:50:43,793 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:50:43,796 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:50:43,797 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:50:43,863 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:50:43,864 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:50:43,882 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:50:43,883 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=156 | prob=1073592

----------------------------------------------------------------------------------------------------
[62/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:50:43,900 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:50:43,901 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:50:43,904 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:50:43,904 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415811  0.372365           6         1.083217
          30 valid t2_p50_h30   gru       30          balanced           0.408776  0.389607           1         1.083993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:50:57,233 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:50:58,514 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:50:58,586 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:50:58,586 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:50:58,635 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:50:58,636 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:50:58,653 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:50:58,653 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:50:58,656 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:50:58,657 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=158 | prob=1087356

----------------------------------------------------------------------------------------------------
[63/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:50:58,723 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:50:58,723 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:50:58,741 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:50:58,741 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:50:58,759 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:50:58,760 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:50:58,763 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:50:58,763 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415811  0.372365           6         1.083217
          30 valid t2_p50_h30   gru       30          balanced           0.408776  0.389607           1         1.083993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:51:12,109 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:51:13,413 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:51:13,489 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:51:13,490 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:51:13,507 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:51:13,508 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:51:13,525 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:51:13,526 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:51:13,529 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:51:13,530 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:51:13,596 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:51:13,597 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:51:13,614 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:51:13,615 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=160 | prob=1101120

----------------------------------------------------------------------------------------------------
[64/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:51:13,632 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:51:13,633 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:51:13,636 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:51:13,636 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415811  0.372365           6         1.083217
          30 valid t2_p50_h30   gru       30          balanced           0.408776  0.389607           1         1.083993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:51:27,012 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:51:28,313 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:51:28,389 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:51:28,389 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:51:28,407 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:51:28,408 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:51:28,426 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:51:28,427 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:51:28,429 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:51:28,430 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:51:28,496 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:51:28,497 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:51:28,514 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:51:28,515 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=162 | prob=1114884

----------------------------------------------------------------------------------------------------
[65/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:51:28,532 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:51:28,533 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:51:28,537 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:51:28,537 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415811  0.372365           6         1.083217
          30 valid t2_p50_h30   gru       30          balanced           0.408776  0.389607           1         1.083993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:51:41,969 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:51:43,292 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:51:43,364 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:51:43,365 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:51:43,383 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:51:43,384 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:51:43,402 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:51:43,402 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:51:43,405 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:51:43,405 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:51:43,471 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:51:43,472 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:51:43,490 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:51:43,490 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=164 | prob=1128648

----------------------------------------------------------------------------------------------------
[66/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:51:43,509 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:51:43,509 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:51:43,512 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:51:43,513 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415811  0.372365           6         1.083217
          30 valid t2_p50_h30   gru       30          balanced           0.408776  0.389607           1         1.083993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:51:56,923 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:51:58,243 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:51:58,319 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:51:58,320 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:51:58,338 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:51:58,338 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:51:58,356 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:51:58,357 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:51:58,359 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:51:58,360 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:51:58,426 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:51:58,427 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:51:58,445 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:51:58,445 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=166 | prob=1142412

----------------------------------------------------------------------------------------------------
[67/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:51:58,462 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:51:58,463 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:51:58,465 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:51:58,465 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415811  0.372365           6         1.083217
          30 valid t2_p50_h30   gru       30          balanced           0.408776  0.389607           1         1.083993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:52:11,904 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:52:13,231 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:52:13,303 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:52:13,303 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:52:13,321 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:52:13,321 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:52:13,337 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:52:13,338 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:52:13,341 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:52:13,341 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:52:13,408 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:52:13,409 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:52:13,427 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:52:13,428 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=168 | prob=1156176

----------------------------------------------------------------------------------------------------
[68/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:52:13,447 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:52:13,447 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:52:13,450 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:52:13,451 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415811  0.372365           6         1.083217
          30 valid t2_p50_h30   gru       30          balanced           0.408776  0.389607           1         1.083993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:52:26,917 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:52:28,291 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:52:28,374 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:52:28,374 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:52:28,392 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:52:28,393 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:52:28,412 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:52:28,412 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:52:28,415 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:52:28,416 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:52:28,485 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:52:28,486 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=170 | prob=1169940

----------------------------------------------------------------------------------------------------
[69/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:52:28,504 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:52:28,504 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:52:28,524 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:52:28,524 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:52:28,527 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:52:28,528 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415811  0.372365           6         1.083217
          30 valid t2_p50_h30   gru       30          balanced           0.408776  0.389607           1         1.083993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:52:42,096 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:52:43,470 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:52:43,550 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:52:43,551 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:52:43,569 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:52:43,569 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:52:43,586 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:52:43,587 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:52:43,589 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:52:43,590 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:52:43,658 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:52:43,659 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=172 | prob=1183704

----------------------------------------------------------------------------------------------------
[70/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:52:43,679 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:52:43,680 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:52:43,697 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:52:43,698 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:52:43,701 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:52:43,701 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415811  0.372365           6         1.083217
          30 valid t2_p50_h30   gru       30          balanced           0.408776  0.389607           1         1.083993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:52:57,264 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:52:58,633 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:52:58,713 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:52:58,714 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:52:58,731 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:52:58,732 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:52:58,750 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:52:58,751 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:52:58,753 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:52:58,754 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:52:58,822 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:52:58,822 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=174 | prob=1197468

----------------------------------------------------------------------------------------------------
[71/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:52:58,841 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:52:58,841 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:52:58,859 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:52:58,860 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:52:58,863 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:52:58,864 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415811  0.372365           6         1.083217
          30 valid t2_p50_h30   gru       30          balanced           0.408776  0.389607           1         1.083993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:53:12,358 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:53:13,754 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:53:13,832 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:53:13,833 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:53:13,851 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:53:13,851 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:53:13,868 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:53:13,869 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:53:13,872 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:53:13,872 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:53:13,940 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:53:13,941 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:53:13,959 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:53:13,960 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=176 | prob=1211232

----------------------------------------------------------------------------------------------------
[72/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:53:13,977 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:53:13,977 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:53:13,981 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:53:13,981 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.415811  0.372365           6         1.083217
          30 valid t2_p50_h30   gru       30          balanced           0.408776  0.389607           1         1.083993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:53:27,475 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:53:28,878 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:53:28,954 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:53:28,955 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:53:28,973 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:53:28,974 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:53:28,992 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:53:28,992 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:53:28,996 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:53:28,997 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:53:29,064 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:53:29,064 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:53:29,082 | INFO | Loaded: windows_t2_p50_h30_valid.npz

💾 Guardado OK | metrics=178 | prob=1224996

----------------------------------------------------------------------------------------------------
[73/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:53:29,083 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:53:29,101 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:53:29,101 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:53:29,104 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:53:29,105 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412342  0.380135           7         1.082378
          30 valid t2_p50_h30   gru       30          balanced           0.411180  0.396433           7         1.087113

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:53:44,968 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:53:46,391 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:53:46,471 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:53:46,472 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:53:46,489 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:53:46,490 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:53:46,507 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:53:46,508 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:53:46,510 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:53:46,511 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:53:46,580 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:53:46,581 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=180 | prob=1238760

----------------------------------------------------------------------------------------------------
[74/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:53:46,599 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:53:46,599 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:53:46,616 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:53:46,616 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:53:46,619 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:53:46,620 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412342  0.380135           7         1.082378
          30 valid t2_p50_h30   gru       30          balanced           0.411180  0.396433           7         1.087113

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:54:02,467 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:54:03,956 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:54:04,034 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:54:04,035 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:54:04,053 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:54:04,054 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:54:04,071 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:54:04,071 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:54:04,074 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:54:04,075 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:54:04,141 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:54:04,142 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:54:04,159 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:54:04,160 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=182 | prob=1252524

----------------------------------------------------------------------------------------------------
[75/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:54:04,177 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:54:04,178 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:54:04,181 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:54:04,182 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412342  0.380135           7         1.082378
          30 valid t2_p50_h30   gru       30          balanced           0.411180  0.396433           7         1.087113

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:54:20,075 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:54:21,551 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:54:21,633 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:54:21,634 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:54:21,654 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:54:21,655 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:54:21,673 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:54:21,674 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:54:21,677 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:54:21,677 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:54:21,746 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:54:21,747 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=184 | prob=1266288

----------------------------------------------------------------------------------------------------
[76/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:54:21,765 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:54:21,765 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:54:21,785 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:54:21,785 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:54:21,788 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:54:21,789 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412342  0.380135           7         1.082378
          30 valid t2_p50_h30   gru       30          balanced           0.411180  0.396433           7         1.087113

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:54:37,695 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:54:39,160 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:54:39,240 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:54:39,241 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:54:39,259 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:54:39,259 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:54:39,276 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:54:39,277 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:54:39,279 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:54:39,280 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:54:39,347 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:54:39,348 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=186 | prob=1280052

----------------------------------------------------------------------------------------------------
[77/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:54:39,365 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:54:39,366 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:54:39,383 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:54:39,384 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:54:39,387 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:54:39,388 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412342  0.380135           7         1.082378
          30 valid t2_p50_h30   gru       30          balanced           0.411180  0.396433           7         1.087113

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:54:55,302 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:54:56,779 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:54:56,855 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:54:56,856 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:54:56,873 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:54:56,874 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:54:56,892 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:54:56,893 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:54:56,896 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:54:56,896 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:54:56,961 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:54:56,962 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:54:56,979 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:54:56,980 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=188 | prob=1293816

----------------------------------------------------------------------------------------------------
[78/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:54:57,001 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:54:57,001 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:54:57,004 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:54:57,005 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412342  0.380135           7         1.082378
          30 valid t2_p50_h30   gru       30          balanced           0.411180  0.396433           7         1.087113

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:55:13,001 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:55:14,496 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:55:14,575 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:55:14,576 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:55:14,593 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:55:14,594 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:55:14,611 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:55:14,611 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:55:14,614 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:55:14,615 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:55:14,685 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:55:14,686 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=190 | prob=1307580

----------------------------------------------------------------------------------------------------
[79/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:55:14,704 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:55:14,705 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:55:14,721 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:55:14,722 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:55:14,725 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:55:14,725 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412342  0.380135           7         1.082378
          30 valid t2_p50_h30   gru       30          balanced           0.411180  0.396433           7         1.087113

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:55:30,753 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:55:32,323 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:55:32,404 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:55:32,405 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:55:32,422 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:55:32,423 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:55:32,440 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:55:32,441 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:55:32,444 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:55:32,444 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:55:32,511 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:55:32,512 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=192 | prob=1321344

----------------------------------------------------------------------------------------------------
[80/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:55:32,530 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:55:32,531 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:55:32,548 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:55:32,549 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:55:32,552 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:55:32,552 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412342  0.380135           7         1.082378
          30 valid t2_p50_h30   gru       30          balanced           0.411180  0.396433           7         1.087113

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:55:48,552 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:55:50,115 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:55:50,195 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:55:50,196 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:55:50,213 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:55:50,214 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:55:50,231 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:55:50,232 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:55:50,235 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:55:50,235 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:55:50,302 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:55:50,302 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=194 | prob=1335108

----------------------------------------------------------------------------------------------------
[81/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:55:50,320 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:55:50,320 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:55:50,338 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:55:50,338 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:55:50,341 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:55:50,342 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412342  0.380135           7         1.082378
          30 valid t2_p50_h30   gru       30          balanced           0.411180  0.396433           7         1.087113

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:56:06,297 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:56:07,849 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:56:07,925 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:56:07,926 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:56:07,943 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:56:07,944 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:56:07,961 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:56:07,962 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:56:07,965 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:56:07,966 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:56:08,032 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:56:08,033 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:56:08,051 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:56:08,052 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=196 | prob=1348872

----------------------------------------------------------------------------------------------------
[82/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:56:08,069 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:56:08,069 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:56:08,072 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:56:08,073 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412342  0.380135           7         1.082378
          30 valid t2_p50_h30   gru       30          balanced           0.411180  0.396433           7         1.087113

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:56:24,085 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:56:25,652 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:56:25,731 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:56:25,732 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:56:25,750 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:56:25,751 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:56:25,772 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:56:25,772 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:56:25,775 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:56:25,775 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:56:25,842 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:56:25,843 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=198 | prob=1362636

----------------------------------------------------------------------------------------------------
[83/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:56:25,861 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:56:25,861 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:56:25,879 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:56:25,880 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:56:25,883 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:56:25,883 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412342  0.380135           7         1.082378
          30 valid t2_p50_h30   gru       30          balanced           0.411180  0.396433           7         1.087113

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:56:41,980 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:56:43,564 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:56:43,642 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:56:43,643 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:56:43,660 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:56:43,661 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:56:43,677 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:56:43,678 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:56:43,681 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:56:43,681 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:56:43,747 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:56:43,748 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:56:43,765 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:56:43,766 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=200 | prob=1376400

----------------------------------------------------------------------------------------------------
[84/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:56:43,783 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:56:43,784 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:56:43,786 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:56:43,787 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412342  0.380135           7         1.082378
          30 valid t2_p50_h30   gru       30          balanced           0.411180  0.396433           7         1.087113

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:56:59,849 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:57:01,426 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:57:01,505 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:57:01,505 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:57:01,523 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:57:01,524 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:57:01,543 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:57:01,544 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:57:01,547 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:57:01,547 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:57:01,614 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:57:01,615 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=202 | prob=1390164

----------------------------------------------------------------------------------------------------
[85/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:57:01,632 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:57:01,632 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:57:01,649 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:57:01,650 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:57:01,652 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:57:01,652 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.418866  0.377342           5         1.082922
          30 valid t2_p50_h30   gru       30          balanced           0.415489  0.396801           5         1.084048

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:57:16,310 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:57:17,930 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:57:18,009 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:57:18,010 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:57:18,031 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:57:18,031 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:57:18,049 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:57:18,049 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:57:18,052 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:57:18,053 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:57:18,119 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:57:18,120 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=204 | prob=1403928

----------------------------------------------------------------------------------------------------
[86/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:57:18,139 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:57:18,139 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:57:18,159 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:57:18,160 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:57:18,164 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:57:18,164 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.418866  0.377342           5         1.082922
          30 valid t2_p50_h30   gru       30          balanced           0.415489  0.396801           5         1.084048

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:57:32,863 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:57:34,476 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:57:34,554 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:57:34,554 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:57:34,572 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:57:34,572 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:57:34,590 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:57:34,591 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:57:34,594 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:57:34,594 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:57:34,663 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:57:34,664 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=206 | prob=1417692

----------------------------------------------------------------------------------------------------
[87/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:57:34,682 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:57:34,683 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:57:34,700 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:57:34,701 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:57:34,703 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:57:34,704 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.418866  0.377342           5         1.082922
          30 valid t2_p50_h30   gru       30          balanced           0.415489  0.396801           5         1.084048

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:57:49,399 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:57:51,012 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:57:51,085 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:57:51,086 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:57:51,103 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:57:51,104 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:57:51,121 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:57:51,122 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:57:51,125 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:57:51,125 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:57:51,191 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:57:51,192 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:57:51,209 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:57:51,210 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=208 | prob=1431456

----------------------------------------------------------------------------------------------------
[88/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:57:51,227 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:57:51,228 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:57:51,230 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:57:51,231 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.418866  0.377342           5         1.082922
          30 valid t2_p50_h30   gru       30          balanced           0.415489  0.396801           5         1.084048

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:58:05,923 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:58:07,584 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:58:07,663 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:58:07,664 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:58:07,687 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:58:07,687 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:58:07,705 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:58:07,706 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:58:07,709 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:58:07,710 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:58:07,776 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:58:07,777 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=210 | prob=1445220

----------------------------------------------------------------------------------------------------
[89/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:58:07,795 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:58:07,796 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:58:07,813 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:58:07,814 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:58:07,816 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:58:07,817 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.418866  0.377342           5         1.082922
          30 valid t2_p50_h30   gru       30          balanced           0.415489  0.396801           5         1.084048

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:58:22,524 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:58:24,189 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:58:24,267 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:58:24,268 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:58:24,285 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:58:24,286 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:58:24,303 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:58:24,303 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:58:24,306 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:58:24,306 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:58:24,372 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:58:24,373 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:58:24,391 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:58:24,392 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=212 | prob=1458984

----------------------------------------------------------------------------------------------------
[90/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:58:24,409 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:58:24,410 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:58:24,412 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:58:24,413 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.418866  0.377342           5         1.082922
          30 valid t2_p50_h30   gru       30          balanced           0.415489  0.396801           5         1.084048

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:58:39,145 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:58:40,806 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:58:40,883 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:58:40,884 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:58:40,901 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:58:40,902 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:58:40,918 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:58:40,919 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:58:40,922 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:58:40,922 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:58:40,989 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:58:40,989 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:58:41,006 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:58:41,007 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=214 | prob=1472748

----------------------------------------------------------------------------------------------------
[91/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:58:41,025 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:58:41,026 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:58:41,029 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:58:41,030 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.418866  0.377342           5         1.082922
          30 valid t2_p50_h30   gru       30          balanced           0.415489  0.396801           5         1.084048

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 16:58:55,743 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:58:57,471 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:58:57,549 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:58:57,550 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:58:57,567 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:58:57,568 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:58:57,586 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:58:57,586 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:58:57,590 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:58:57,590 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:58:57,657 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:58:57,658 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:58:57,675 | INFO | Loaded: windows_t2_p50_h30_valid.npz

💾 Guardado OK | metrics=216 | prob=1486512

----------------------------------------------------------------------------------------------------
[92/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:58:57,676 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:58:57,693 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:58:57,694 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:58:57,697 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:58:57,698 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.418866  0.377342           5         1.082922
          30 valid t2_p50_h30   gru       30          balanced           0.415489  0.396801           5         1.084048

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 16:59:12,424 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:59:14,122 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:59:14,203 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:59:14,203 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:59:14,221 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:59:14,221 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:59:14,238 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:59:14,239 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:59:14,243 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:59:14,244 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:59:14,310 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:59:14,311 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=218 | prob=1500276

----------------------------------------------------------------------------------------------------
[93/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:59:14,328 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:59:14,328 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:59:14,346 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:59:14,347 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:59:14,350 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:59:14,350 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.418866  0.377342           5         1.082922
          30 valid t2_p50_h30   gru       30          balanced           0.415489  0.396801           5         1.084048

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 16:59:29,100 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:59:30,853 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:59:30,932 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:59:30,933 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:59:30,951 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:59:30,951 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:59:30,968 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:59:30,969 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:59:30,972 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:59:30,972 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:59:31,038 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:59:31,039 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:59:31,056 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 16:59:31,057 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=220 | prob=1514040

----------------------------------------------------------------------------------------------------
[94/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 16:59:31,074 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:59:31,075 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:59:31,078 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:59:31,079 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.418866  0.377342           5         1.082922
          30 valid t2_p50_h30   gru       30          balanced           0.415489  0.396801           5         1.084048

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 16:59:45,826 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 16:59:47,570 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 16:59:47,649 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 16:59:47,650 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:59:47,667 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 16:59:47,668 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:59:47,685 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 16:59:47,686 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:59:47,689 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:59:47,690 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 16:59:47,758 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 16:59:47,759 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 16:59:47,777 | INFO | Loaded: windows_t2_p50_h30_valid.npz

💾 Guardado OK | metrics=222 | prob=1527804

----------------------------------------------------------------------------------------------------
[95/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 16:59:47,777 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 16:59:47,795 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 16:59:47,796 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 16:59:47,799 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 16:59:47,799 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.418866  0.377342           5         1.082922
          30 valid t2_p50_h30   gru       30          balanced           0.415489  0.396801           5         1.084048

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:00:02,681 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:00:04,479 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:00:04,551 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:00:04,552 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:00:04,569 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:00:04,569 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:00:04,586 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:00:04,587 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:00:04,589 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:00:04,590 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:00:04,656 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:00:04,656 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:00:04,673 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:00:04,674 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=224 | prob=1541568

----------------------------------------------------------------------------------------------------
[96/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:00:04,691 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:00:04,692 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:00:04,694 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:00:04,695 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.418866  0.377342           5         1.082922
          30 valid t2_p50_h30   gru       30          balanced           0.415489  0.396801           5         1.084048

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:00:19,573 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:00:21,345 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:00:21,425 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:00:21,426 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:00:21,444 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:00:21,445 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:00:21,462 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:00:21,462 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:00:21,465 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:00:21,466 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:00:21,534 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:00:21,535 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=226 | prob=1555332

----------------------------------------------------------------------------------------------------
[97/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:00:21,553 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:00:21,553 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:00:21,570 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:00:21,571 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:00:21,574 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:00:21,575 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414338  0.368868           6         1.083628
          30 valid t2_p50_h30   gru       30          balanced           0.409067  0.389682           1         1.084269

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:00:35,540 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:00:37,340 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:00:37,420 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:00:37,420 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:00:37,438 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:00:37,439 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:00:37,456 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:00:37,456 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:00:37,460 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:00:37,460 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:00:37,528 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:00:37,529 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=228 | prob=1569096

----------------------------------------------------------------------------------------------------
[98/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:00:37,547 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:00:37,548 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:00:37,565 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:00:37,566 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:00:37,569 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:00:37,569 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414338  0.368868           6         1.083628
          30 valid t2_p50_h30   gru       30          balanced           0.409067  0.389682           1         1.084269

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:00:51,547 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:00:53,361 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:00:53,443 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:00:53,444 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:00:53,461 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:00:53,462 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:00:53,479 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:00:53,479 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:00:53,482 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:00:53,483 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:00:53,548 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:00:53,549 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=230 | prob=1582860

----------------------------------------------------------------------------------------------------
[99/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:00:53,566 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:00:53,567 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:00:53,585 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:00:53,586 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:00:53,588 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:00:53,589 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414338  0.368868           6         1.083628
          30 valid t2_p50_h30   gru       30          balanced           0.409067  0.389682           1         1.084269

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:01:07,642 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:01:09,442 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:01:09,526 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:01:09,527 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:01:09,546 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:01:09,546 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:01:09,563 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:01:09,564 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:01:09,567 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:01:09,567 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:01:09,633 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:01:09,634 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=232 | prob=1596624

----------------------------------------------------------------------------------------------------
[100/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:01:09,651 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:01:09,652 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:01:09,669 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:01:09,669 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:01:09,672 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:01:09,672 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414338  0.368868           6         1.083628
          30 valid t2_p50_h30   gru       30          balanced           0.409067  0.389682           1         1.084269

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:01:23,751 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:01:25,594 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:01:25,678 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:01:25,679 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:01:25,696 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:01:25,696 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:01:25,715 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:01:25,716 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:01:25,718 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:01:25,719 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:01:25,785 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:01:25,786 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=234 | prob=1610388

----------------------------------------------------------------------------------------------------
[101/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:01:25,804 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:01:25,804 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:01:25,822 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:01:25,822 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:01:25,825 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:01:25,825 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414338  0.368868           6         1.083628
          30 valid t2_p50_h30   gru       30          balanced           0.409067  0.389682           1         1.084269

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:01:39,986 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:01:41,880 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:01:41,963 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:01:41,964 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:01:41,982 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:01:41,983 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:01:42,002 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:01:42,003 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:01:42,006 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:01:42,007 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:01:42,077 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:01:42,077 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=236 | prob=1624152

----------------------------------------------------------------------------------------------------
[102/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:01:42,096 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:01:42,096 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:01:42,115 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:01:42,116 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:01:42,119 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:01:42,119 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414338  0.368868           6         1.083628
          30 valid t2_p50_h30   gru       30          balanced           0.409067  0.389682           1         1.084269

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:01:56,269 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:01:58,144 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:01:58,225 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:01:58,226 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:01:58,243 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:01:58,243 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:01:58,262 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:01:58,262 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:01:58,265 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:01:58,265 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:01:58,332 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:01:58,333 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=238 | prob=1637916

----------------------------------------------------------------------------------------------------
[103/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:01:58,350 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:01:58,351 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:01:58,368 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:01:58,369 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:01:58,371 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:01:58,372 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414338  0.368868           6         1.083628
          30 valid t2_p50_h30   gru       30          balanced           0.409067  0.389682           1         1.084269

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:02:12,570 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:02:14,440 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:02:14,524 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:02:14,524 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:02:14,542 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:02:14,542 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:02:14,559 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:02:14,560 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:02:14,563 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:02:14,563 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:02:14,630 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:02:14,630 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=240 | prob=1651680

----------------------------------------------------------------------------------------------------
[104/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:02:14,649 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:02:14,649 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:02:14,666 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:02:14,667 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:02:14,670 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:02:14,670 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414338  0.368868           6         1.083628
          30 valid t2_p50_h30   gru       30          balanced           0.409067  0.389682           1         1.084269

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:02:28,903 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:02:30,799 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:02:30,880 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:02:30,881 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:02:30,898 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:02:30,899 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:02:30,919 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:02:30,920 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:02:30,922 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:02:30,923 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:02:30,989 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:02:30,990 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=242 | prob=1665444

----------------------------------------------------------------------------------------------------
[105/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:02:31,009 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:02:31,009 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:02:31,030 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:02:31,030 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:02:31,033 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:02:31,034 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414338  0.368868           6         1.083628
          30 valid t2_p50_h30   gru       30          balanced           0.409067  0.389682           1         1.084269

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:02:45,255 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:02:47,176 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:02:47,255 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:02:47,256 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:02:47,274 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:02:47,274 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:02:47,292 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:02:47,292 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:02:47,295 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:02:47,296 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:02:47,363 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:02:47,364 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=244 | prob=1679208

----------------------------------------------------------------------------------------------------
[106/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:02:47,381 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:02:47,382 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:02:47,399 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:02:47,400 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:02:47,403 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:02:47,403 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414338  0.368868           6         1.083628
          30 valid t2_p50_h30   gru       30          balanced           0.409067  0.389682           1         1.084269

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:03:01,636 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:03:03,576 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:03:03,655 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:03:03,655 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:03:03,673 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:03:03,673 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:03:03,690 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:03:03,690 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:03:03,693 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:03:03,694 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=246 | prob=1692972

----------------------------------------------------------------------------------------------------
[107/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:03:03,809 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:03:03,810 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:03:03,830 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:03:03,831 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:03:03,849 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:03:03,849 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:03:03,852 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:03:03,853 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414338  0.368868           6         1.083628
          30 valid t2_p50_h30   gru       30          balanced           0.409067  0.389682           1         1.084269

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:03:18,112 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:03:20,078 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:03:20,157 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:03:20,158 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:03:20,175 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:03:20,176 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:03:20,193 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:03:20,193 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:03:20,196 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:03:20,196 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:03:20,263 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:03:20,264 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:03:20,282 | INFO | Loaded: windows_t2_p50_h30_valid.npz

💾 Guardado OK | metrics=248 | prob=1706736

----------------------------------------------------------------------------------------------------
[108/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.2
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:03:20,283 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:03:20,301 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:03:20,302 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:03:20,305 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:03:20,305 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414338  0.368868           6         1.083628
          30 valid t2_p50_h30   gru       30          balanced           0.409067  0.389682           1         1.084269

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:03:34,550 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:03:36,534 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:03:36,604 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:03:36,605 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:03:36,622 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:03:36,623 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:03:36,640 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:03:36,640 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:03:36,643 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:03:36,644 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:03:36,710 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:03:36,711 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:03:36,728 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:03:36,728 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=250 | prob=1720500

----------------------------------------------------------------------------------------------------
[109/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:03:36,746 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:03:36,746 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:03:36,749 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:03:36,749 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414154  0.380019           7         1.081183
          30 valid t2_p50_h30   gru       30          balanced           0.413078  0.396895           7         1.085993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:03:53,306 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:03:55,265 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:03:55,401 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:03:55,402 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:03:55,420 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:03:55,421 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:03:55,439 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:03:55,440 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:03:55,443 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:03:55,443 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=252 | prob=1734264

----------------------------------------------------------------------------------------------------
[110/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:03:55,514 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:03:55,515 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:03:55,531 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:03:55,532 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:03:55,549 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:03:55,549 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:03:55,552 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:03:55,553 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414154  0.380019           7         1.081183
          30 valid t2_p50_h30   gru       30          balanced           0.413078  0.396895           7         1.085993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:04:12,107 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:04:14,132 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:04:14,213 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:04:14,214 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:04:14,231 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:04:14,232 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:04:14,249 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:04:14,249 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:04:14,252 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:04:14,253 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:04:14,318 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:04:14,319 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=254 | prob=1748028

----------------------------------------------------------------------------------------------------
[111/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:04:14,337 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:04:14,337 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:04:14,354 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:04:14,355 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:04:14,357 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:04:14,358 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414154  0.380019           7         1.081183
          30 valid t2_p50_h30   gru       30          balanced           0.413078  0.396895           7         1.085993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:04:30,926 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:04:32,915 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:04:32,994 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:04:32,995 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:04:33,012 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:04:33,012 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:04:33,029 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:04:33,030 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:04:33,033 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:04:33,033 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:04:33,099 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:04:33,100 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:04:33,117 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:04:33,117 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=256 | prob=1761792

----------------------------------------------------------------------------------------------------
[112/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:04:33,135 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:04:33,135 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:04:33,138 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:04:33,138 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414154  0.380019           7         1.081183
          30 valid t2_p50_h30   gru       30          balanced           0.413078  0.396895           7         1.085993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:04:49,702 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:04:51,743 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:04:51,876 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:04:51,877 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:04:51,894 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:04:51,895 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:04:51,916 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:04:51,916 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:04:51,919 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:04:51,920 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=258 | prob=1775556

----------------------------------------------------------------------------------------------------
[113/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:04:51,986 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:04:51,986 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:04:52,004 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:04:52,005 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:04:52,023 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:04:52,023 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:04:52,026 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:04:52,026 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414154  0.380019           7         1.081183
          30 valid t2_p50_h30   gru       30          balanced           0.413078  0.396895           7         1.085993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:05:08,620 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:05:10,611 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:05:10,692 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:05:10,693 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:05:10,710 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:05:10,710 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:05:10,728 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:05:10,728 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:05:10,731 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:05:10,732 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:05:10,798 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:05:10,799 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=260 | prob=1789320

----------------------------------------------------------------------------------------------------
[114/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:05:10,819 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:05:10,820 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:05:10,837 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:05:10,837 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:05:10,840 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:05:10,840 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414154  0.380019           7         1.081183
          30 valid t2_p50_h30   gru       30          balanced           0.413078  0.396895           7         1.085993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:05:27,463 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:05:29,606 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:05:29,687 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:05:29,688 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:05:29,705 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:05:29,706 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:05:29,723 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:05:29,723 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:05:29,726 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:05:29,726 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:05:29,792 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:05:29,793 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=262 | prob=1803084

----------------------------------------------------------------------------------------------------
[115/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:05:29,810 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:05:29,811 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:05:29,832 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:05:29,832 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:05:29,835 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:05:29,836 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414154  0.380019           7         1.081183
          30 valid t2_p50_h30   gru       30          balanced           0.413078  0.396895           7         1.085993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:05:46,474 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:05:48,568 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:05:48,647 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:05:48,647 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:05:48,666 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:05:48,667 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:05:48,684 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:05:48,685 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:05:48,688 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:05:48,688 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:05:48,755 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:05:48,756 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=264 | prob=1816848

----------------------------------------------------------------------------------------------------
[116/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:05:48,773 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:05:48,774 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:05:48,794 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:05:48,795 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:05:48,798 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:05:48,799 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414154  0.380019           7         1.081183
          30 valid t2_p50_h30   gru       30          balanced           0.413078  0.396895           7         1.085993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:06:05,416 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:06:07,540 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:06:07,620 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:06:07,621 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:06:07,638 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:06:07,639 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:06:07,656 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:06:07,657 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:06:07,660 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:06:07,660 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:06:07,732 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:06:07,733 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=266 | prob=1830612

----------------------------------------------------------------------------------------------------
[117/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:06:07,751 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:06:07,751 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:06:07,769 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:06:07,769 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:06:07,772 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:06:07,772 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414154  0.380019           7         1.081183
          30 valid t2_p50_h30   gru       30          balanced           0.413078  0.396895           7         1.085993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:06:24,351 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:06:26,447 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:06:26,525 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:06:26,525 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:06:26,543 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:06:26,544 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:06:26,560 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:06:26,561 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:06:26,564 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:06:26,565 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:06:26,630 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:06:26,631 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=268 | prob=1844376

----------------------------------------------------------------------------------------------------
[118/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:06:26,652 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:06:26,653 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:06:26,671 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:06:26,672 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:06:26,675 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:06:26,675 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414154  0.380019           7         1.081183
          30 valid t2_p50_h30   gru       30          balanced           0.413078  0.396895           7         1.085993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:06:43,347 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:06:45,504 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:06:45,580 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:06:45,581 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:06:45,598 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:06:45,599 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:06:45,615 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:06:45,616 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:06:45,619 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:06:45,619 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:06:45,686 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:06:45,687 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:06:45,704 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:06:45,705 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=270 | prob=1858140

----------------------------------------------------------------------------------------------------
[119/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:06:45,723 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:06:45,723 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:06:45,726 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:06:45,726 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414154  0.380019           7         1.081183
          30 valid t2_p50_h30   gru       30          balanced           0.413078  0.396895           7         1.085993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:07:02,387 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:07:04,510 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:07:04,591 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:07:04,592 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:07:04,609 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:07:04,610 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:07:04,628 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:07:04,628 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:07:04,631 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:07:04,631 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:07:04,698 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:07:04,698 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=272 | prob=1871904

----------------------------------------------------------------------------------------------------
[120/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:07:04,716 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:07:04,717 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:07:04,737 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:07:04,738 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:07:04,740 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:07:04,741 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414154  0.380019           7         1.081183
          30 valid t2_p50_h30   gru       30          balanced           0.413078  0.396895           7         1.085993

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:07:21,486 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:07:23,641 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:07:23,722 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:07:23,723 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:07:23,743 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:07:23,744 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:07:23,761 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:07:23,761 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:07:23,764 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:07:23,765 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:07:23,831 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:07:23,832 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=274 | prob=1885668

----------------------------------------------------------------------------------------------------
[121/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:07:23,850 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:07:23,851 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:07:23,868 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:07:23,869 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:07:23,871 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:07:23,872 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416501  0.377136           5         1.082290
          30 valid t2_p50_h30   gru       30          balanced           0.415349  0.396631           5         1.083946

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:07:39,139 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:07:41,297 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:07:41,378 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:07:41,379 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:07:41,398 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:07:41,399 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:07:41,417 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:07:41,417 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:07:41,420 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:07:41,420 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:07:41,486 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:07:41,487 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=276 | prob=1899432

----------------------------------------------------------------------------------------------------
[122/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:07:41,505 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:07:41,505 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:07:41,523 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:07:41,523 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:07:41,526 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:07:41,527 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416501  0.377136           5         1.082290
          30 valid t2_p50_h30   gru       30          balanced           0.415349  0.396631           5         1.083946

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:07:56,820 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:07:58,992 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:07:59,072 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:07:59,073 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:07:59,093 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:07:59,094 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:07:59,111 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:07:59,112 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:07:59,115 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:07:59,115 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:07:59,187 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:07:59,188 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=278 | prob=1913196

----------------------------------------------------------------------------------------------------
[123/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:07:59,206 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:07:59,207 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:07:59,224 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:07:59,224 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:07:59,227 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:07:59,228 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416501  0.377136           5         1.082290
          30 valid t2_p50_h30   gru       30          balanced           0.415349  0.396631           5         1.083946

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:08:14,537 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:08:16,744 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:08:16,826 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:08:16,827 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:08:16,844 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:08:16,845 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:08:16,862 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:08:16,863 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:08:16,867 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:08:16,867 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:08:16,939 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:08:16,940 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=280 | prob=1926960

----------------------------------------------------------------------------------------------------
[124/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:08:16,957 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:08:16,958 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:08:16,975 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:08:16,975 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:08:16,978 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:08:16,978 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416501  0.377136           5         1.082290
          30 valid t2_p50_h30   gru       30          balanced           0.415349  0.396631           5         1.083946

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:08:32,285 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:08:34,482 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:08:34,560 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:08:34,561 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:08:34,579 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:08:34,579 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:08:34,597 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:08:34,598 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:08:34,601 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:08:34,601 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:08:34,667 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:08:34,668 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:08:34,685 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:08:34,686 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=282 | prob=1940724

----------------------------------------------------------------------------------------------------
[125/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:08:34,705 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:08:34,705 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:08:34,708 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:08:34,709 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416501  0.377136           5         1.082290
          30 valid t2_p50_h30   gru       30          balanced           0.415349  0.396631           5         1.083946

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:08:50,099 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:08:52,354 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:08:52,436 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:08:52,437 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:08:52,454 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:08:52,455 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:08:52,472 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:08:52,473 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:08:52,475 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:08:52,476 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:08:52,543 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:08:52,544 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=284 | prob=1954488

----------------------------------------------------------------------------------------------------
[126/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:08:52,562 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:08:52,562 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:08:52,581 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:08:52,581 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:08:52,584 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:08:52,584 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416501  0.377136           5         1.082290
          30 valid t2_p50_h30   gru       30          balanced           0.415349  0.396631           5         1.083946

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:09:07,979 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:09:10,232 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:09:10,308 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:09:10,309 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:09:10,326 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:09:10,327 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:09:10,345 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:09:10,345 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:09:10,348 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:09:10,348 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:09:10,415 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:09:10,416 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:09:10,433 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:09:10,434 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=286 | prob=1968252

----------------------------------------------------------------------------------------------------
[127/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:09:10,452 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:09:10,452 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:09:10,455 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:09:10,455 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416501  0.377136           5         1.082290
          30 valid t2_p50_h30   gru       30          balanced           0.415349  0.396631           5         1.083946

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:09:25,815 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:09:28,085 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:09:28,165 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:09:28,165 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:09:28,183 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:09:28,184 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:09:28,201 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:09:28,202 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:09:28,205 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:09:28,206 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:09:28,273 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:09:28,273 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=288 | prob=1982016

----------------------------------------------------------------------------------------------------
[128/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:09:28,291 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:09:28,291 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:09:28,308 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:09:28,309 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:09:28,312 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:09:28,312 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416501  0.377136           5         1.082290
          30 valid t2_p50_h30   gru       30          balanced           0.415349  0.396631           5         1.083946

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:09:43,710 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:09:45,944 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:09:46,029 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:09:46,030 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:09:46,048 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:09:46,048 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:09:46,066 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:09:46,066 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:09:46,069 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:09:46,069 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:09:46,136 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:09:46,136 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=290 | prob=1995780

----------------------------------------------------------------------------------------------------
[129/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:09:46,154 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:09:46,154 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:09:46,171 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:09:46,172 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:09:46,175 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:09:46,175 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416501  0.377136           5         1.082290
          30 valid t2_p50_h30   gru       30          balanced           0.415349  0.396631           5         1.083946

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:10:01,599 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:10:03,851 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:10:03,930 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:10:03,931 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:10:03,951 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:10:03,952 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:10:03,969 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:10:03,969 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:10:03,972 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:10:03,972 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:10:04,039 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:10:04,039 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=292 | prob=2009544

----------------------------------------------------------------------------------------------------
[130/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:10:04,057 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:10:04,058 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:10:04,075 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:10:04,076 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:10:04,078 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:10:04,079 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416501  0.377136           5         1.082290
          30 valid t2_p50_h30   gru       30          balanced           0.415349  0.396631           5         1.083946

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:10:19,516 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:10:21,774 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:10:21,853 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:10:21,854 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:10:21,871 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:10:21,871 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:10:21,888 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:10:21,889 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:10:21,892 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:10:21,893 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:10:21,958 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:10:21,959 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:10:21,976 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:10:21,977 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=294 | prob=2023308

----------------------------------------------------------------------------------------------------
[131/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:10:21,997 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:10:21,998 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:10:22,001 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:10:22,001 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416501  0.377136           5         1.082290
          30 valid t2_p50_h30   gru       30          balanced           0.415349  0.396631           5         1.083946

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:10:37,444 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:10:39,780 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:10:39,861 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:10:39,862 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:10:39,879 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:10:39,880 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:10:39,898 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:10:39,898 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:10:39,901 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:10:39,902 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:10:39,969 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:10:39,970 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=296 | prob=2037072

----------------------------------------------------------------------------------------------------
[132/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:10:39,988 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:10:39,989 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:10:40,006 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:10:40,006 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:10:40,009 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:10:40,010 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416501  0.377136           5         1.082290
          30 valid t2_p50_h30   gru       30          balanced           0.415349  0.396631           5         1.083946

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:10:55,488 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:10:57,836 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:10:57,921 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:10:57,922 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:10:57,940 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:10:57,940 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:10:57,958 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:10:57,958 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:10:57,961 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:10:57,962 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:10:58,028 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:10:58,028 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=298 | prob=2050836

----------------------------------------------------------------------------------------------------
[133/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:10:58,046 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:10:58,047 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:10:58,064 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:10:58,064 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:10:58,067 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:10:58,068 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413410  0.369065           6         1.083844
          30 valid t2_p50_h30   gru       30          balanced           0.410023  0.389691           1         1.084478

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:11:12,714 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:11:15,047 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:11:15,131 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:11:15,132 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:11:15,149 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:11:15,150 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:11:15,167 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:11:15,168 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:11:15,170 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:11:15,171 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:11:15,236 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:11:15,237 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=300 | prob=2064600

----------------------------------------------------------------------------------------------------
[134/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:11:15,255 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:11:15,255 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:11:15,272 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:11:15,272 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:11:15,275 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:11:15,276 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413410  0.369065           6         1.083844
          30 valid t2_p50_h30   gru       30          balanced           0.410023  0.389691           1         1.084478

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:11:29,831 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:11:32,203 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:11:32,288 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:11:32,288 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:11:32,306 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:11:32,307 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:11:32,325 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:11:32,325 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:11:32,328 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:11:32,329 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:11:32,395 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:11:32,396 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=302 | prob=2078364

----------------------------------------------------------------------------------------------------
[135/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:11:32,413 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:11:32,414 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:11:32,431 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:11:32,432 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:11:32,435 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:11:32,435 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413410  0.369065           6         1.083844
          30 valid t2_p50_h30   gru       30          balanced           0.410023  0.389691           1         1.084478

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:11:47,094 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:11:49,426 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:11:49,509 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:11:49,509 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:11:49,527 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:11:49,527 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:11:49,544 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:11:49,545 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:11:49,548 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:11:49,549 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:11:49,617 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:11:49,618 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=304 | prob=2092128

----------------------------------------------------------------------------------------------------
[136/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:11:49,639 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:11:49,640 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:11:49,657 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:11:49,657 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:11:49,660 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:11:49,661 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413410  0.369065           6         1.083844
          30 valid t2_p50_h30   gru       30          balanced           0.410023  0.389691           1         1.084478

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:12:04,330 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:12:06,723 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:12:06,802 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:12:06,803 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:12:06,821 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:12:06,821 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:12:06,838 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:12:06,839 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:12:06,842 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:12:06,842 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:12:06,907 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:12:06,908 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:12:06,927 | INFO | Loaded: windows_t2_p50_h30_valid.npz

💾 Guardado OK | metrics=306 | prob=2105892

----------------------------------------------------------------------------------------------------
[137/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:12:06,928 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:12:06,947 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:12:06,948 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:12:06,951 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:12:06,951 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413410  0.369065           6         1.083844
          30 valid t2_p50_h30   gru       30          balanced           0.410023  0.389691           1         1.084478

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:12:21,587 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:12:24,010 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:12:24,093 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:12:24,093 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:12:24,111 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:12:24,112 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:12:24,129 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:12:24,130 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:12:24,133 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:12:24,133 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:12:24,202 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:12:24,202 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=308 | prob=2119656

----------------------------------------------------------------------------------------------------
[138/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:12:24,220 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:12:24,221 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:12:24,238 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:12:24,239 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:12:24,241 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:12:24,242 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413410  0.369065           6         1.083844
          30 valid t2_p50_h30   gru       30          balanced           0.410023  0.389691           1         1.084478

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:12:38,884 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:12:41,327 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:12:41,410 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:12:41,410 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:12:41,428 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:12:41,428 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:12:41,446 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:12:41,446 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:12:41,450 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:12:41,450 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:12:41,517 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:12:41,517 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=310 | prob=2133420

----------------------------------------------------------------------------------------------------
[139/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:12:41,538 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:12:41,539 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:12:41,556 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:12:41,556 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:12:41,559 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:12:41,560 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413410  0.369065           6         1.083844
          30 valid t2_p50_h30   gru       30          balanced           0.410023  0.389691           1         1.084478

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:12:56,236 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:12:58,694 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:12:58,776 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:12:58,776 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:12:58,794 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:12:58,794 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:12:58,811 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:12:58,812 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:12:58,815 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:12:58,816 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:12:58,884 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:12:58,884 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=312 | prob=2147184

----------------------------------------------------------------------------------------------------
[140/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:12:58,902 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:12:58,903 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:12:58,920 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:12:58,921 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:12:58,923 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:12:58,924 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413410  0.369065           6         1.083844
          30 valid t2_p50_h30   gru       30          balanced           0.410023  0.389691           1         1.084478

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:13:13,635 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:13:16,105 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:13:16,185 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:13:16,186 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:13:16,202 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:13:16,203 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:13:16,220 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:13:16,221 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:13:16,224 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:13:16,225 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:13:16,291 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:13:16,292 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:13:16,309 | INFO | Loaded: windows_t2_p50_h30_valid.npz

💾 Guardado OK | metrics=314 | prob=2160948

----------------------------------------------------------------------------------------------------
[141/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:13:16,310 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:13:16,326 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:13:16,327 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:13:16,330 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:13:16,330 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413410  0.369065           6         1.083844
          30 valid t2_p50_h30   gru       30          balanced           0.410023  0.389691           1         1.084478

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:13:31,057 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:13:33,508 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:13:33,590 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:13:33,590 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:13:33,608 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:13:33,608 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:13:33,625 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:13:33,625 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:13:33,628 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:13:33,629 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:13:33,695 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:13:33,695 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:13:33,713 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:13:33,714 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=316 | prob=2174712

----------------------------------------------------------------------------------------------------
[142/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:13:33,732 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:13:33,732 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:13:33,735 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:13:33,736 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413410  0.369065           6         1.083844
          30 valid t2_p50_h30   gru       30          balanced           0.410023  0.389691           1         1.084478

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:13:48,519 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:13:51,013 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:13:51,095 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:13:51,095 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:13:51,113 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:13:51,113 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:13:51,130 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:13:51,131 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:13:51,134 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:13:51,135 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:13:51,201 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:13:51,201 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=318 | prob=2188476

----------------------------------------------------------------------------------------------------
[143/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:13:51,219 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:13:51,220 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:13:51,238 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:13:51,239 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:13:51,242 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:13:51,243 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413410  0.369065           6         1.083844
          30 valid t2_p50_h30   gru       30          balanced           0.410023  0.389691           1         1.084478

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:14:06,027 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:14:08,506 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:14:08,586 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:14:08,586 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:14:08,605 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:14:08,605 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:14:08,625 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:14:08,626 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:14:08,629 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:14:08,630 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:14:08,696 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:14:08,696 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=320 | prob=2202240

----------------------------------------------------------------------------------------------------
[144/144] hidden_size=128 | num_layers=2 | learning_rate=0.0005 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 2
dropout          = 0.3
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:14:08,714 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:14:08,715 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:14:08,732 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:14:08,732 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:14:08,735 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:14:08,735 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413410  0.369065           6         1.083844
          30 valid t2_p50_h30   gru       30          balanced           0.410023  0.389691           1         1.084478

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:14:23,463 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:14:25,957 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:14:25,959 | INFO | Cargando métricas desde: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:14:25,984 | INFO | Cargando probabilidades desde: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet

💾 Guardado OK | metrics=322 | prob=2216004

2026-04-23 17:14:26,475 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:14:26,476 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:14:26,493 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:14:26,494 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:14:26,511 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:14:26,512 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:14:26,515 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:14:26,516 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:14:26,582 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:14:26,583 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:14:26,601 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:14:26,601 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

====================================================================================================
GRU GRID INCREMENTAL | L=30
====================================================================================================
targets                = ['t2_p40_h30', 't2_p50_h30']
n_combinations         = 144
hidden_size_values     = [256]
num_layers_values      = [1]
learning_rate_values   = [0.001]
dropout_values         = [0.0, 0.1, 0.2, 0.3]
batch_size_values      = [1024, 2048, 4096]
grad_clip_norm_values  = [0.5, 1.0, 2.0]
threshold_long_values  = [0.4, 0.45]
threshold_short_values = [0.4, 0.45]
class_weight_mode      = balanced
optimizer_name         = adam

----------------------------------------------------------------------------------------------------
[1/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:14:26,619 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:14:26,619 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:14:26,622 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:14:26,622 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410899  0.379913           2         1.082311
          30 valid t2_p50_h30   gru       30          balanced           0.409536  0.401325           4         1.083070

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:14:38,351 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:14:40,867 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:14:40,947 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:14:40,948 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:14:40,965 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:14:40,965 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:14:40,983 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:14:40,983 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:14:40,986 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:14:40,987 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:14:41,054 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:14:41,055 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=324 | prob=2229768

----------------------------------------------------------------------------------------------------
[2/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:14:41,072 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:14:41,073 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:14:41,090 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:14:41,091 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:14:41,094 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:14:41,095 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410899  0.379913           2         1.082311
          30 valid t2_p50_h30   gru       30          balanced           0.409536  0.401325           4         1.083070

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:14:52,796 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:14:55,411 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:14:55,494 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:14:55,494 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:14:55,512 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:14:55,512 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:14:55,532 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:14:55,533 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:14:55,536 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:14:55,536 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:14:55,604 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:14:55,605 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=326 | prob=2243532

----------------------------------------------------------------------------------------------------
[3/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:14:55,622 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:14:55,623 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:14:55,640 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:14:55,640 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:14:55,643 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:14:55,644 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410899  0.379913           2         1.082311
          30 valid t2_p50_h30   gru       30          balanced           0.409536  0.401325           4         1.083070

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:15:07,357 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:15:09,922 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:15:10,008 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:15:10,008 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:15:10,025 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:15:10,026 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:15:10,044 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:15:10,045 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:15:10,048 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:15:10,049 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:15:10,120 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:15:10,121 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=328 | prob=2257296

----------------------------------------------------------------------------------------------------
[4/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:15:10,139 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:15:10,139 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:15:10,157 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:15:10,157 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:15:10,161 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:15:10,161 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410899  0.379913           2         1.082311
          30 valid t2_p50_h30   gru       30          balanced           0.409536  0.401325           4         1.083070

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:15:21,914 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:15:24,506 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:15:24,588 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:15:24,589 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:15:24,609 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:15:24,609 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:15:24,626 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:15:24,626 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:15:24,629 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:15:24,629 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:15:24,695 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:15:24,696 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=330 | prob=2271060

----------------------------------------------------------------------------------------------------
[5/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:15:24,713 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:15:24,714 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:15:24,731 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:15:24,731 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:15:24,734 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:15:24,735 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410899  0.379913           2         1.082311
          30 valid t2_p50_h30   gru       30          balanced           0.409536  0.401325           4         1.083070

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:15:36,508 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:15:39,060 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:15:39,143 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:15:39,144 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:15:39,162 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:15:39,162 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:15:39,179 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:15:39,180 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:15:39,183 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:15:39,183 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:15:39,249 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:15:39,250 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=332 | prob=2284824

----------------------------------------------------------------------------------------------------
[6/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:15:39,267 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:15:39,268 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:15:39,285 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:15:39,285 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:15:39,288 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:15:39,288 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410899  0.379913           2         1.082311
          30 valid t2_p50_h30   gru       30          balanced           0.409536  0.401325           4         1.083070

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:15:51,114 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:15:53,714 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:15:53,795 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:15:53,796 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:15:53,813 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:15:53,814 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:15:53,830 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:15:53,830 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:15:53,833 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:15:53,833 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:15:53,905 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:15:53,906 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=334 | prob=2298588

----------------------------------------------------------------------------------------------------
[7/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:15:53,924 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:15:53,925 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:15:53,941 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:15:53,942 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:15:53,944 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:15:53,945 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410899  0.379913           2         1.082311
          30 valid t2_p50_h30   gru       30          balanced           0.409536  0.401325           4         1.083070

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:16:05,751 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:16:08,330 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:16:08,414 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:16:08,414 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:16:08,435 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:16:08,436 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:16:08,454 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:16:08,455 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:16:08,457 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:16:08,458 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:16:08,525 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:16:08,526 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=336 | prob=2312352

----------------------------------------------------------------------------------------------------
[8/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:16:08,544 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:16:08,545 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:16:08,562 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:16:08,563 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:16:08,566 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:16:08,566 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410899  0.379913           2         1.082311
          30 valid t2_p50_h30   gru       30          balanced           0.409536  0.401325           4         1.083070

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:16:20,427 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:16:23,109 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:16:23,179 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:16:23,180 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:16:23,198 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:16:23,198 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:16:23,216 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:16:23,217 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:16:23,221 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:16:23,222 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:16:23,289 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:16:23,290 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:16:23,308 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:16:23,309 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=338 | prob=2326116

----------------------------------------------------------------------------------------------------
[9/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:16:23,329 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:16:23,330 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:16:23,333 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:16:23,333 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410899  0.379913           2         1.082311
          30 valid t2_p50_h30   gru       30          balanced           0.409536  0.401325           4         1.083070

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:16:35,192 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:16:37,868 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:16:37,952 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:16:37,953 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:16:37,971 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:16:37,972 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:16:37,989 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:16:37,990 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:16:37,992 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:16:37,993 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:16:38,059 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:16:38,060 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=340 | prob=2339880

----------------------------------------------------------------------------------------------------
[10/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:16:38,078 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:16:38,078 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:16:38,164 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:16:38,165 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:16:38,169 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:16:38,169 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410899  0.379913           2         1.082311
          30 valid t2_p50_h30   gru       30          balanced           0.409536  0.401325           4         1.083070

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:16:50,035 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:16:52,696 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:16:52,778 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:16:52,779 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:16:52,800 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:16:52,801 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:16:52,818 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:16:52,818 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:16:52,821 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:16:52,821 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:16:52,887 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:16:52,887 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=342 | prob=2353644

----------------------------------------------------------------------------------------------------
[11/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:16:52,905 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:16:52,905 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:16:52,922 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:16:52,923 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:16:52,925 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:16:52,926 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410899  0.379913           2         1.082311
          30 valid t2_p50_h30   gru       30          balanced           0.409536  0.401325           4         1.083070

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:17:04,884 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:17:07,539 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:17:07,620 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:17:07,621 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:17:07,638 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:17:07,638 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:17:07,656 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:17:07,656 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:17:07,659 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:17:07,660 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:17:07,727 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:17:07,727 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=344 | prob=2367408

----------------------------------------------------------------------------------------------------
[12/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:17:07,745 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:17:07,746 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:17:07,762 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:17:07,763 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:17:07,766 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:17:07,766 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410899  0.379913           2         1.082311
          30 valid t2_p50_h30   gru       30          balanced           0.409536  0.401325           4         1.083070

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:17:19,715 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:17:22,402 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:17:22,484 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:17:22,484 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:17:22,501 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:17:22,502 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:17:22,519 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:17:22,520 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:17:22,523 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:17:22,524 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:17:22,589 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:17:22,590 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=346 | prob=2381172

----------------------------------------------------------------------------------------------------
[13/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:17:22,679 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:17:22,679 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:17:22,698 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:17:22,699 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:17:22,702 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:17:22,702 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387677  0.340268           1         1.083371
          30 valid t2_p50_h30   gru       30          balanced           0.417474  0.407541           6         1.083879

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:17:35,624 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:17:38,305 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:17:38,387 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:17:38,388 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:17:38,406 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:17:38,406 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:17:38,424 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:17:38,425 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:17:38,428 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:17:38,429 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:17:38,496 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:17:38,497 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=348 | prob=2394936

----------------------------------------------------------------------------------------------------
[14/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:17:38,515 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:17:38,516 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:17:38,534 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:17:38,534 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:17:38,537 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:17:38,538 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387677  0.340268           1         1.083371
          30 valid t2_p50_h30   gru       30          balanced           0.417474  0.407541           6         1.083879

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:17:51,389 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:17:54,118 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:17:54,199 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:17:54,200 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:17:54,218 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:17:54,218 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:17:54,235 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:17:54,236 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:17:54,239 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:17:54,239 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:17:54,306 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:17:54,307 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=350 | prob=2408700

----------------------------------------------------------------------------------------------------
[15/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:17:54,325 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:17:54,325 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:17:54,342 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:17:54,343 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:17:54,345 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:17:54,346 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387677  0.340268           1         1.083371
          30 valid t2_p50_h30   gru       30          balanced           0.417474  0.407541           6         1.083879

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:18:07,301 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:18:10,032 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:18:10,114 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:18:10,114 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:18:10,132 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:18:10,133 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:18:10,150 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:18:10,151 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:18:10,154 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:18:10,155 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:18:10,229 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:18:10,229 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=352 | prob=2422464

----------------------------------------------------------------------------------------------------
[16/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:18:10,247 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:18:10,248 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:18:10,265 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:18:10,266 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:18:10,269 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:18:10,270 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387677  0.340268           1         1.083371
          30 valid t2_p50_h30   gru       30          balanced           0.417474  0.407541           6         1.083879

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:18:23,253 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:18:26,001 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:18:26,083 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:18:26,084 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:18:26,101 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:18:26,102 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:18:26,119 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:18:26,120 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:18:26,123 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:18:26,123 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:18:26,190 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:18:26,191 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:18:26,209 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:18:26,209 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=354 | prob=2436228

----------------------------------------------------------------------------------------------------
[17/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4
✔ Ya existe -> skip

----------------------------------------------------------------------------------------------------
[18/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:18:26,226 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:18:26,227 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:18:26,230 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:18:26,230 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387677  0.340268           1         1.083371
          30 valid t2_p50_h30   gru       30          balanced           0.417474  0.407541           6         1.083879

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:18:39,337 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:18:42,144 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:18:42,224 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:18:42,225 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:18:42,243 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:18:42,243 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:18:42,261 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:18:42,262 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:18:42,265 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:18:42,265 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:18:42,333 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:18:42,334 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=356 | prob=2449992

----------------------------------------------------------------------------------------------------
[19/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:18:42,352 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:18:42,353 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:18:42,370 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:18:42,371 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:18:42,374 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:18:42,374 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387677  0.340268           1         1.083371
          30 valid t2_p50_h30   gru       30          balanced           0.417474  0.407541           6         1.083879

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:18:55,485 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:18:58,336 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:18:58,416 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:18:58,416 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:18:58,434 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:18:58,434 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:18:58,528 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:18:58,529 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:18:58,532 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:18:58,532 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=358 | prob=2463756

----------------------------------------------------------------------------------------------------
[20/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:18:58,599 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:18:58,600 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:18:58,618 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:18:58,618 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:18:58,636 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:18:58,636 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:18:58,639 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:18:58,639 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387677  0.340268           1         1.083371
          30 valid t2_p50_h30   gru       30          balanced           0.417474  0.407541           6         1.083879

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:19:11,708 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:19:14,498 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:19:14,581 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:19:14,582 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:19:14,599 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:19:14,599 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:19:14,616 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:19:14,617 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:19:14,620 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:19:14,620 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:19:14,686 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:19:14,686 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=360 | prob=2477520

----------------------------------------------------------------------------------------------------
[21/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:19:14,704 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:19:14,705 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:19:14,722 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:19:14,722 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:19:14,725 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:19:14,726 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387677  0.340268           1         1.083371
          30 valid t2_p50_h30   gru       30          balanced           0.417474  0.407541           6         1.083879

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:19:27,763 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:19:30,566 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:19:30,648 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:19:30,649 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:19:30,667 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:19:30,668 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:19:30,685 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:19:30,686 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:19:30,689 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:19:30,690 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:19:30,758 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:19:30,759 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=362 | prob=2491284

----------------------------------------------------------------------------------------------------
[22/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:19:30,777 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:19:30,778 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:19:30,795 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:19:30,795 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:19:30,799 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:19:30,799 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387677  0.340268           1         1.083371
          30 valid t2_p50_h30   gru       30          balanced           0.417474  0.407541           6         1.083879

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:19:43,888 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:19:46,757 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:19:46,919 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:19:46,920 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:19:46,940 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:19:46,940 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:19:46,958 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:19:46,959 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:19:46,961 | INFO | Scaler cargado: scaler_mnq_t2.pkl

💾 Guardado OK | metrics=364 | prob=2505048

----------------------------------------------------------------------------------------------------
[23/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:19:46,962 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:19:47,028 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:19:47,028 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:19:47,048 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:19:47,049 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:19:47,066 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:19:47,066 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:19:47,069 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:19:47,070 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387677  0.340268           1         1.083371
          30 valid t2_p50_h30   gru       30          balanced           0.417474  0.407541           6         1.083879

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:20:00,132 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:20:02,943 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:20:03,022 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:20:03,023 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:20:03,040 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:20:03,041 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:20:03,058 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:20:03,059 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:20:03,062 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:20:03,062 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:20:03,129 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:20:03,130 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:20:03,147 | INFO | Loaded: windows_t2_p50_h30_valid.npz

💾 Guardado OK | metrics=366 | prob=2518812

----------------------------------------------------------------------------------------------------
[24/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:20:03,148 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:20:03,165 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:20:03,166 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:20:03,169 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:20:03,169 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387677  0.340268           1         1.083371
          30 valid t2_p50_h30   gru       30          balanced           0.417474  0.407541           6         1.083879

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:20:16,231 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:20:19,090 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:20:19,173 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:20:19,173 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:20:19,191 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:20:19,191 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:20:19,211 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:20:19,212 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:20:19,215 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:20:19,215 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:20:19,280 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:20:19,281 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=368 | prob=2532576

----------------------------------------------------------------------------------------------------
[25/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:20:19,298 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:20:19,298 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:20:19,315 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:20:19,316 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:20:19,319 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:20:19,319 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413719  0.386351           9         1.079431
          30 valid t2_p50_h30   gru       30          balanced           0.411653  0.397610           4         1.081541

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:20:36,851 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:20:39,752 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:20:39,913 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:20:39,914 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:20:39,931 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:20:39,932 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:20:39,949 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:20:39,949 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:20:39,952 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:20:39,953 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=370 | prob=2546340

----------------------------------------------------------------------------------------------------
[26/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:20:40,019 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:20:40,020 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:20:40,037 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:20:40,038 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:20:40,055 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:20:40,056 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:20:40,058 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:20:40,059 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413719  0.386351           9         1.079431
          30 valid t2_p50_h30   gru       30          balanced           0.411653  0.397610           4         1.081541

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:20:57,544 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:21:00,463 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:21:00,534 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:21:00,534 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:21:00,552 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:21:00,552 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:21:00,570 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:21:00,570 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:21:00,573 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:21:00,574 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:21:00,640 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:21:00,641 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:21:00,658 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:21:00,659 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=372 | prob=2560104

----------------------------------------------------------------------------------------------------
[27/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:21:00,677 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:21:00,677 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:21:00,680 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:21:00,681 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413719  0.386351           9         1.079431
          30 valid t2_p50_h30   gru       30          balanced           0.411653  0.397610           4         1.081541

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:21:18,182 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:21:21,077 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:21:21,155 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:21:21,156 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:21:21,173 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:21:21,173 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:21:21,194 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:21:21,195 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:21:21,197 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:21:21,198 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:21:21,266 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:21:21,266 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=374 | prob=2573868

----------------------------------------------------------------------------------------------------
[28/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:21:21,284 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:21:21,284 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:21:21,302 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:21:21,302 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:21:21,305 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:21:21,306 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413719  0.386351           9         1.079431
          30 valid t2_p50_h30   gru       30          balanced           0.411653  0.397610           4         1.081541

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:21:38,825 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:21:41,717 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:21:41,792 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:21:41,792 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:21:41,810 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:21:41,811 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:21:41,828 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:21:41,829 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:21:41,832 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:21:41,833 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:21:41,899 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:21:41,900 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:21:41,917 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:21:41,918 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=376 | prob=2587632

----------------------------------------------------------------------------------------------------
[29/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:21:41,935 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:21:41,936 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:21:41,939 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:21:41,939 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413719  0.386351           9         1.079431
          30 valid t2_p50_h30   gru       30          balanced           0.411653  0.397610           4         1.081541

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:21:59,444 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:22:02,409 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:22:02,491 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:22:02,492 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:22:02,511 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:22:02,511 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:22:02,529 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:22:02,530 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:22:02,532 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:22:02,533 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:22:02,604 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:22:02,605 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=378 | prob=2601396

----------------------------------------------------------------------------------------------------
[30/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:22:02,624 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:22:02,624 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:22:02,642 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:22:02,643 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:22:02,647 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:22:02,647 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413719  0.386351           9         1.079431
          30 valid t2_p50_h30   gru       30          balanced           0.411653  0.397610           4         1.081541

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:22:20,249 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:22:23,163 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:22:23,244 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:22:23,245 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:22:23,262 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:22:23,263 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:22:23,280 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:22:23,281 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:22:23,283 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:22:23,284 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:22:23,349 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:22:23,350 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=380 | prob=2615160

----------------------------------------------------------------------------------------------------
[31/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:22:23,368 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:22:23,369 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:22:23,386 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:22:23,387 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:22:23,390 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:22:23,390 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413719  0.386351           9         1.079431
          30 valid t2_p50_h30   gru       30          balanced           0.411653  0.397610           4         1.081541

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:22:41,015 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:22:43,985 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:22:44,068 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:22:44,069 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:22:44,087 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:22:44,087 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:22:44,105 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:22:44,106 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:22:44,109 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:22:44,109 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:22:44,175 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:22:44,176 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=382 | prob=2628924

----------------------------------------------------------------------------------------------------
[32/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:22:44,193 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:22:44,194 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:22:44,211 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:22:44,211 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:22:44,214 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:22:44,214 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413719  0.386351           9         1.079431
          30 valid t2_p50_h30   gru       30          balanced           0.411653  0.397610           4         1.081541

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:23:01,629 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:23:04,561 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:23:04,645 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:23:04,646 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:23:04,663 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:23:04,663 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:23:04,679 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:23:04,680 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:23:04,682 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:23:04,683 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:23:04,749 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:23:04,750 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:23:04,768 | INFO | Loaded: windows_t2_p50_h30_valid.npz

💾 Guardado OK | metrics=384 | prob=2642688

----------------------------------------------------------------------------------------------------
[33/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:23:04,769 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:23:04,786 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:23:04,786 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:23:04,789 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:23:04,789 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413719  0.386351           9         1.079431
          30 valid t2_p50_h30   gru       30          balanced           0.411653  0.397610           4         1.081541

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:23:22,134 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:23:25,064 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:23:25,147 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:23:25,147 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:23:25,165 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:23:25,165 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:23:25,182 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:23:25,183 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:23:25,185 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:23:25,186 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:23:25,251 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:23:25,252 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:23:25,269 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:23:25,270 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=386 | prob=2656452

----------------------------------------------------------------------------------------------------
[34/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:23:25,287 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:23:25,287 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:23:25,290 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:23:25,291 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413719  0.386351           9         1.079431
          30 valid t2_p50_h30   gru       30          balanced           0.411653  0.397610           4         1.081541

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:23:42,742 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:23:45,756 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:23:45,837 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:23:45,837 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:23:45,855 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:23:45,855 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:23:45,872 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:23:45,873 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:23:45,876 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:23:45,876 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:23:45,949 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:23:45,950 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=388 | prob=2670216

----------------------------------------------------------------------------------------------------
[35/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:23:45,967 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:23:45,968 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:23:45,985 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:23:45,986 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:23:45,988 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:23:45,989 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413719  0.386351           9         1.079431
          30 valid t2_p50_h30   gru       30          balanced           0.411653  0.397610           4         1.081541

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:24:03,553 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:24:06,530 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:24:06,615 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:24:06,616 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:24:06,634 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:24:06,635 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:24:06,653 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:24:06,654 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:24:06,657 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:24:06,657 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:24:06,730 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:24:06,731 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=390 | prob=2683980

----------------------------------------------------------------------------------------------------
[36/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:24:06,750 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:24:06,750 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:24:06,768 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:24:06,768 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:24:06,771 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:24:06,771 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.413719  0.386351           9         1.079431
          30 valid t2_p50_h30   gru       30          balanced           0.411653  0.397610           4         1.081541

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:24:24,282 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:24:27,262 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:24:27,343 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:24:27,344 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:24:27,361 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:24:27,361 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:24:27,378 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:24:27,379 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:24:27,381 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:24:27,382 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:24:27,448 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:24:27,448 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=392 | prob=2697744

----------------------------------------------------------------------------------------------------
[37/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:24:27,469 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:24:27,470 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:24:27,488 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:24:27,488 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:24:27,491 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:24:27,491 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405262  0.386872           6         1.081952
          30 valid t2_p50_h30   gru       30          balanced           0.408325  0.400267           4         1.082458

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:24:41,793 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:24:44,822 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:24:44,905 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:24:44,906 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:24:44,923 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:24:44,923 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:24:44,940 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:24:44,941 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:24:44,944 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:24:44,944 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:24:45,012 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:24:45,012 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=394 | prob=2711508

----------------------------------------------------------------------------------------------------
[38/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:24:45,031 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:24:45,031 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:24:45,050 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:24:45,051 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:24:45,054 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:24:45,055 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405262  0.386872           6         1.081952
          30 valid t2_p50_h30   gru       30          balanced           0.408325  0.400267           4         1.082458

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:24:59,322 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:25:02,338 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:25:02,422 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:25:02,423 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:25:02,440 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:25:02,441 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:25:02,458 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:25:02,459 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:25:02,462 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:25:02,462 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:25:02,528 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:25:02,529 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=396 | prob=2725272

----------------------------------------------------------------------------------------------------
[39/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:25:02,546 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:25:02,547 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:25:02,564 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:25:02,564 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:25:02,567 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:25:02,568 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405262  0.386872           6         1.081952
          30 valid t2_p50_h30   gru       30          balanced           0.408325  0.400267           4         1.082458

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:25:16,781 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:25:19,816 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:25:19,899 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:25:19,900 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:25:19,917 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:25:19,917 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:25:19,934 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:25:19,935 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:25:19,937 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:25:19,938 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:25:20,003 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:25:20,004 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=398 | prob=2739036

----------------------------------------------------------------------------------------------------
[40/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:25:20,023 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:25:20,023 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:25:20,043 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:25:20,044 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:25:20,047 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:25:20,048 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405262  0.386872           6         1.081952
          30 valid t2_p50_h30   gru       30          balanced           0.408325  0.400267           4         1.082458

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:25:34,337 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:25:37,474 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:25:37,556 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:25:37,557 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:25:37,574 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:25:37,574 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:25:37,591 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:25:37,591 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:25:37,594 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:25:37,595 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:25:37,661 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:25:37,661 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=400 | prob=2752800

----------------------------------------------------------------------------------------------------
[41/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:25:37,679 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:25:37,680 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:25:37,697 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:25:37,698 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:25:37,700 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:25:37,701 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405262  0.386872           6         1.081952
          30 valid t2_p50_h30   gru       30          balanced           0.408325  0.400267           4         1.082458

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:25:51,904 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:25:54,972 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:25:55,054 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:25:55,055 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:25:55,073 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:25:55,073 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:25:55,090 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:25:55,091 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:25:55,094 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:25:55,094 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:25:55,166 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:25:55,167 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=402 | prob=2766564

----------------------------------------------------------------------------------------------------
[42/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:25:55,184 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:25:55,185 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:25:55,201 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:25:55,202 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:25:55,205 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:25:55,205 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405262  0.386872           6         1.081952
          30 valid t2_p50_h30   gru       30          balanced           0.408325  0.400267           4         1.082458

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:26:09,435 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:26:12,481 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:26:12,568 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:26:12,569 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:26:12,586 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:26:12,586 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:26:12,604 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:26:12,604 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:26:12,607 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:26:12,607 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:26:12,674 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:26:12,674 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=404 | prob=2780328

----------------------------------------------------------------------------------------------------
[43/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:26:12,693 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:26:12,693 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:26:12,711 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:26:12,712 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:26:12,715 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:26:12,715 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405262  0.386872           6         1.081952
          30 valid t2_p50_h30   gru       30          balanced           0.408325  0.400267           4         1.082458

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:26:27,089 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:26:30,250 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:26:30,332 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:26:30,333 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:26:30,350 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:26:30,350 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:26:30,367 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:26:30,368 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:26:30,371 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:26:30,371 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:26:30,444 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:26:30,445 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=406 | prob=2794092

----------------------------------------------------------------------------------------------------
[44/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:26:30,462 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:26:30,463 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:26:30,480 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:26:30,480 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:26:30,483 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:26:30,484 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405262  0.386872           6         1.081952
          30 valid t2_p50_h30   gru       30          balanced           0.408325  0.400267           4         1.082458

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:26:44,876 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:26:47,970 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:26:48,054 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:26:48,055 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:26:48,072 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:26:48,072 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:26:48,089 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:26:48,090 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:26:48,092 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:26:48,093 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:26:48,158 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:26:48,159 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:26:48,176 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:26:48,177 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=408 | prob=2807856

----------------------------------------------------------------------------------------------------
[45/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:26:48,194 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:26:48,194 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:26:48,197 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:26:48,197 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405262  0.386872           6         1.081952
          30 valid t2_p50_h30   gru       30          balanced           0.408325  0.400267           4         1.082458

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:27:02,550 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:27:05,692 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:27:05,778 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:27:05,779 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:27:05,796 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:27:05,797 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:27:05,814 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:27:05,814 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:27:05,817 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:27:05,818 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:27:05,883 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:27:05,884 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=410 | prob=2821620

----------------------------------------------------------------------------------------------------
[46/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:27:05,902 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:27:05,902 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:27:05,919 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:27:05,920 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:27:05,922 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:27:05,923 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405262  0.386872           6         1.081952
          30 valid t2_p50_h30   gru       30          balanced           0.408325  0.400267           4         1.082458

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:27:20,336 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:27:23,491 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:27:23,577 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:27:23,578 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:27:23,597 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:27:23,597 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:27:23,617 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:27:23,618 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:27:23,621 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:27:23,622 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:27:23,690 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:27:23,690 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=412 | prob=2835384

----------------------------------------------------------------------------------------------------
[47/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:27:23,708 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:27:23,708 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:27:23,726 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:27:23,726 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:27:23,729 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:27:23,730 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405262  0.386872           6         1.081952
          30 valid t2_p50_h30   gru       30          balanced           0.408325  0.400267           4         1.082458

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:27:38,151 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:27:41,307 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:27:41,391 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:27:41,392 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:27:41,409 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:27:41,410 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:27:41,426 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:27:41,426 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:27:41,429 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:27:41,430 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:27:41,498 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:27:41,499 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=414 | prob=2849148

----------------------------------------------------------------------------------------------------
[48/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:27:41,517 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:27:41,518 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:27:41,534 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:27:41,535 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:27:41,537 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:27:41,538 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405262  0.386872           6         1.081952
          30 valid t2_p50_h30   gru       30          balanced           0.408325  0.400267           4         1.082458

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:27:55,952 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:27:59,090 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:27:59,176 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:27:59,176 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:27:59,193 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:27:59,194 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:27:59,211 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:27:59,211 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:27:59,214 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:27:59,214 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:27:59,280 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:27:59,281 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=416 | prob=2862912

----------------------------------------------------------------------------------------------------
[49/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:27:59,299 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:27:59,300 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:27:59,316 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:27:59,317 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:27:59,320 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:27:59,320 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387322  0.339288           1         1.083475
          30 valid t2_p50_h30   gru       30          balanced           0.418621  0.409104           6         1.082911

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:28:12,759 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:28:15,927 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:28:16,008 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:28:16,009 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:28:16,026 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:28:16,027 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:28:16,044 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:28:16,045 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:28:16,048 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:28:16,049 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:28:16,116 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:28:16,117 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=418 | prob=2876676

----------------------------------------------------------------------------------------------------
[50/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:28:16,134 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:28:16,135 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:28:16,151 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:28:16,152 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:28:16,155 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:28:16,155 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387322  0.339288           1         1.083475
          30 valid t2_p50_h30   gru       30          balanced           0.418621  0.409104           6         1.082911

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:28:29,552 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:28:32,743 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:28:32,826 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:28:32,826 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:28:32,844 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:28:32,844 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:28:32,862 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:28:32,863 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:28:32,866 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:28:32,867 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:28:32,940 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:28:32,941 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=420 | prob=2890440

----------------------------------------------------------------------------------------------------
[51/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:28:32,959 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:28:32,959 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:28:32,976 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:28:32,977 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:28:32,980 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:28:32,981 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387322  0.339288           1         1.083475
          30 valid t2_p50_h30   gru       30          balanced           0.418621  0.409104           6         1.082911

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:28:46,417 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:28:49,659 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:28:49,741 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:28:49,742 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:28:49,759 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:28:49,760 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:28:49,777 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:28:49,778 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:28:49,781 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:28:49,781 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:28:49,849 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:28:49,849 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=422 | prob=2904204

----------------------------------------------------------------------------------------------------
[52/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:28:49,867 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:28:49,868 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:28:49,884 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:28:49,885 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:28:49,887 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:28:49,888 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387322  0.339288           1         1.083475
          30 valid t2_p50_h30   gru       30          balanced           0.418621  0.409104           6         1.082911

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:29:03,323 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:29:06,533 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:29:06,621 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:29:06,622 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:29:06,639 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:29:06,639 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:29:06,660 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:29:06,660 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:29:06,663 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:29:06,664 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:29:06,730 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:29:06,731 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=424 | prob=2917968

----------------------------------------------------------------------------------------------------
[53/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:29:06,748 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:29:06,749 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:29:06,768 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:29:06,768 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:29:06,771 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:29:06,772 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387322  0.339288           1         1.083475
          30 valid t2_p50_h30   gru       30          balanced           0.418621  0.409104           6         1.082911

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:29:20,223 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:29:23,458 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:29:23,545 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:29:23,546 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:29:23,563 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:29:23,564 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:29:23,582 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:29:23,582 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:29:23,585 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:29:23,586 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:29:23,652 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:29:23,652 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=426 | prob=2931732

----------------------------------------------------------------------------------------------------
[54/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:29:23,672 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:29:23,672 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:29:23,693 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:29:23,693 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:29:23,696 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:29:23,696 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387322  0.339288           1         1.083475
          30 valid t2_p50_h30   gru       30          balanced           0.418621  0.409104           6         1.082911

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:29:37,174 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:29:40,461 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:29:40,541 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:29:40,542 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:29:40,558 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:29:40,559 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:29:40,576 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:29:40,576 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:29:40,579 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:29:40,580 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:29:40,646 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:29:40,647 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:29:40,664 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:29:40,665 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=428 | prob=2945496

----------------------------------------------------------------------------------------------------
[55/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:29:40,683 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:29:40,683 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:29:40,687 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:29:40,687 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387322  0.339288           1         1.083475
          30 valid t2_p50_h30   gru       30          balanced           0.418621  0.409104           6         1.082911

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:29:54,304 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:29:57,588 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:29:57,673 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:29:57,674 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:29:57,691 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:29:57,691 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:29:57,708 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:29:57,709 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:29:57,712 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:29:57,712 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:29:57,778 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:29:57,779 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=430 | prob=2959260

----------------------------------------------------------------------------------------------------
[56/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:29:57,796 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:29:57,797 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:29:57,814 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:29:57,815 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:29:57,818 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:29:57,818 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387322  0.339288           1         1.083475
          30 valid t2_p50_h30   gru       30          balanced           0.418621  0.409104           6         1.082911

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:30:11,353 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:30:14,681 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:30:14,767 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:30:14,767 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:30:14,784 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:30:14,785 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:30:14,804 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:30:14,804 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:30:14,807 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:30:14,808 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:30:14,882 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:30:14,883 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=432 | prob=2973024

----------------------------------------------------------------------------------------------------
[57/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:30:14,900 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:30:14,900 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:30:14,918 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:30:14,918 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:30:14,920 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:30:14,921 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387322  0.339288           1         1.083475
          30 valid t2_p50_h30   gru       30          balanced           0.418621  0.409104           6         1.082911

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:30:28,420 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:30:31,702 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:30:31,784 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:30:31,785 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:30:31,802 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:30:31,803 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:30:31,820 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:30:31,821 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:30:31,823 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:30:31,824 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:30:31,897 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:30:31,898 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=434 | prob=2986788

----------------------------------------------------------------------------------------------------
[58/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:30:31,915 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:30:31,916 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:30:31,932 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:30:31,933 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:30:31,935 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:30:31,936 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387322  0.339288           1         1.083475
          30 valid t2_p50_h30   gru       30          balanced           0.418621  0.409104           6         1.082911

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:30:45,519 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:30:48,829 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:30:48,914 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:30:48,915 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:30:48,933 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:30:48,934 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:30:48,954 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:30:48,955 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:30:48,958 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:30:48,958 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:30:49,033 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:30:49,033 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=436 | prob=3000552

----------------------------------------------------------------------------------------------------
[59/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:30:49,051 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:30:49,052 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:30:49,071 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:30:49,071 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:30:49,075 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:30:49,075 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387322  0.339288           1         1.083475
          30 valid t2_p50_h30   gru       30          balanced           0.418621  0.409104           6         1.082911

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:31:02,634 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:31:05,986 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:31:06,070 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:31:06,071 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:31:06,088 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:31:06,089 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:31:06,105 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:31:06,105 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:31:06,108 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:31:06,108 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:31:06,174 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:31:06,175 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=438 | prob=3014316

----------------------------------------------------------------------------------------------------
[60/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:31:06,193 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:31:06,194 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:31:06,211 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:31:06,212 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:31:06,214 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:31:06,215 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.387322  0.339288           1         1.083475
          30 valid t2_p50_h30   gru       30          balanced           0.418621  0.409104           6         1.082911

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:31:19,717 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:31:23,052 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:31:23,136 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:31:23,137 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:31:23,154 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:31:23,155 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:31:23,171 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:31:23,172 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:31:23,174 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:31:23,175 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:31:23,250 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:31:23,251 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=440 | prob=3028080

----------------------------------------------------------------------------------------------------
[61/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:31:23,268 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:31:23,269 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:31:23,285 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:31:23,286 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:31:23,288 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:31:23,289 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.417348  0.385809           5         1.079693
          30 valid t2_p50_h30   gru       30          balanced           0.410978  0.396920           4         1.081655

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:31:38,902 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:31:42,302 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:31:42,386 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:31:42,387 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:31:42,404 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:31:42,405 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:31:42,422 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:31:42,423 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:31:42,426 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:31:42,427 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:31:42,493 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:31:42,494 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=442 | prob=3041844

----------------------------------------------------------------------------------------------------
[62/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:31:42,512 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:31:42,512 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:31:42,530 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:31:42,530 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:31:42,533 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:31:42,533 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.417348  0.385809           5         1.079693
          30 valid t2_p50_h30   gru       30          balanced           0.410978  0.396920           4         1.081655

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:31:58,152 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:32:01,497 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:32:01,581 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:32:01,582 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:32:01,599 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:32:01,600 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:32:01,616 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:32:01,617 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:32:01,620 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:32:01,620 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:32:01,686 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:32:01,687 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=444 | prob=3055608

----------------------------------------------------------------------------------------------------
[63/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:32:01,703 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:32:01,704 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:32:01,722 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:32:01,723 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:32:01,725 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:32:01,726 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.417348  0.385809           5         1.079693
          30 valid t2_p50_h30   gru       30          balanced           0.410978  0.396920           4         1.081655

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:32:17,332 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:32:20,761 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:32:20,847 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:32:20,847 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:32:20,865 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:32:20,865 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:32:20,882 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:32:20,883 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:32:20,885 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:32:20,886 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:32:20,952 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:32:20,952 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=446 | prob=3069372

----------------------------------------------------------------------------------------------------
[64/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:32:20,970 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:32:20,971 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:32:20,988 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:32:20,989 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:32:20,992 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:32:20,992 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.417348  0.385809           5         1.079693
          30 valid t2_p50_h30   gru       30          balanced           0.410978  0.396920           4         1.081655

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:32:36,685 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:32:40,093 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:32:40,176 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:32:40,176 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:32:40,193 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:32:40,194 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:32:40,211 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:32:40,211 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:32:40,214 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:32:40,214 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:32:40,280 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:32:40,281 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=448 | prob=3083136

----------------------------------------------------------------------------------------------------
[65/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:32:40,298 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:32:40,299 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:32:40,315 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:32:40,316 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:32:40,318 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:32:40,319 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.417348  0.385809           5         1.079693
          30 valid t2_p50_h30   gru       30          balanced           0.410978  0.396920           4         1.081655

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:32:55,932 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:32:59,377 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:32:59,463 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:32:59,463 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:32:59,482 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:32:59,482 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:32:59,500 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:32:59,501 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:32:59,503 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:32:59,504 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:32:59,571 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:32:59,571 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=450 | prob=3096900

----------------------------------------------------------------------------------------------------
[66/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:32:59,589 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:32:59,590 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:32:59,607 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:32:59,608 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:32:59,610 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:32:59,611 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.417348  0.385809           5         1.079693
          30 valid t2_p50_h30   gru       30          balanced           0.410978  0.396920           4         1.081655

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:33:15,245 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:33:18,661 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:33:18,746 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:33:18,747 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:33:18,764 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:33:18,765 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:33:18,783 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:33:18,783 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:33:18,787 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:33:18,787 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:33:18,856 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:33:18,856 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=452 | prob=3110664

----------------------------------------------------------------------------------------------------
[67/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:33:18,874 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:33:18,875 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:33:18,990 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:33:18,991 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:33:18,995 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:33:18,996 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.417348  0.385809           5         1.079693
          30 valid t2_p50_h30   gru       30          balanced           0.410978  0.396920           4         1.081655

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:33:34,681 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:33:38,123 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:33:38,208 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:33:38,208 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:33:38,226 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:33:38,226 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:33:38,244 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:33:38,244 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:33:38,247 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:33:38,248 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:33:38,314 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:33:38,315 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=454 | prob=3124428

----------------------------------------------------------------------------------------------------
[68/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:33:38,332 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:33:38,332 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:33:38,349 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:33:38,350 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:33:38,353 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:33:38,353 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.417348  0.385809           5         1.079693
          30 valid t2_p50_h30   gru       30          balanced           0.410978  0.396920           4         1.081655

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:33:53,981 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:33:57,405 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:33:57,489 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:33:57,490 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:33:57,507 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:33:57,508 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:33:57,525 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:33:57,526 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:33:57,529 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:33:57,529 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:33:57,600 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:33:57,601 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=456 | prob=3138192

----------------------------------------------------------------------------------------------------
[69/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:33:57,618 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:33:57,618 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:33:57,635 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:33:57,636 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:33:57,638 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:33:57,639 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.417348  0.385809           5         1.079693
          30 valid t2_p50_h30   gru       30          balanced           0.410978  0.396920           4         1.081655

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:34:13,358 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:34:16,853 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:34:16,935 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:34:16,936 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:34:16,953 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:34:16,954 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:34:16,970 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:34:16,971 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:34:16,974 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:34:16,974 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=458 | prob=3151956

----------------------------------------------------------------------------------------------------
[70/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:34:17,142 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:34:17,142 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:34:17,160 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:34:17,160 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:34:17,177 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:34:17,178 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:34:17,181 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:34:17,181 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.417348  0.385809           5         1.079693
          30 valid t2_p50_h30   gru       30          balanced           0.410978  0.396920           4         1.081655

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:34:32,847 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:34:36,357 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:34:36,441 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:34:36,441 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:34:36,459 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:34:36,459 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:34:36,477 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:34:36,478 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:34:36,481 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:34:36,482 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:34:36,550 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:34:36,551 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=460 | prob=3165720

----------------------------------------------------------------------------------------------------
[71/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:34:36,568 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:34:36,569 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:34:36,586 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:34:36,586 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:34:36,589 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:34:36,590 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.417348  0.385809           5         1.079693
          30 valid t2_p50_h30   gru       30          balanced           0.410978  0.396920           4         1.081655

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:34:52,320 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:34:55,834 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:34:55,918 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:34:55,919 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:34:55,937 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:34:55,937 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:34:55,955 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:34:55,955 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:34:55,959 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:34:55,959 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:34:56,027 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:34:56,028 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=462 | prob=3179484

----------------------------------------------------------------------------------------------------
[72/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:34:56,046 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:34:56,046 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:34:56,064 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:34:56,064 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:34:56,067 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:34:56,068 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.417348  0.385809           5         1.079693
          30 valid t2_p50_h30   gru       30          balanced           0.410978  0.396920           4         1.081655

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:35:11,894 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:35:15,488 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:35:15,570 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:35:15,571 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:35:15,688 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:35:15,688 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=464 | prob=3193248

----------------------------------------------------------------------------------------------------
[73/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:35:15,708 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:35:15,708 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:35:15,711 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:35:15,712 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:35:15,779 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:35:15,780 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:35:15,797 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:35:15,797 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:35:15,814 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:35:15,815 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:35:15,818 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:35:15,818 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405073  0.388088           6         1.080756
          30 valid t2_p50_h30   gru       30          balanced           0.408094  0.399890           4         1.082619

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:35:30,619 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:35:34,151 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:35:34,235 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:35:34,236 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:35:34,254 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:35:34,254 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:35:34,273 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:35:34,274 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:35:34,276 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:35:34,277 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:35:34,343 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:35:34,344 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=466 | prob=3207012

----------------------------------------------------------------------------------------------------
[74/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:35:34,361 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:35:34,362 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:35:34,379 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:35:34,379 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:35:34,382 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:35:34,382 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405073  0.388088           6         1.080756
          30 valid t2_p50_h30   gru       30          balanced           0.408094  0.399890           4         1.082619

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:35:49,176 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:35:52,722 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:35:52,807 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:35:52,808 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:35:52,826 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:35:52,826 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:35:52,843 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:35:52,844 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:35:52,846 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:35:52,847 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:35:52,913 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:35:52,913 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=468 | prob=3220776

----------------------------------------------------------------------------------------------------
[75/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:35:52,931 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:35:52,932 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:35:52,948 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:35:52,949 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:35:52,952 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:35:52,952 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405073  0.388088           6         1.080756
          30 valid t2_p50_h30   gru       30          balanced           0.408094  0.399890           4         1.082619

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:36:07,946 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:36:11,512 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:36:11,699 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:36:11,699 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=470 | prob=3234540

----------------------------------------------------------------------------------------------------
[76/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:36:11,717 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:36:11,718 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:36:11,735 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:36:11,735 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:36:11,738 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:36:11,739 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:36:11,807 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:36:11,807 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:36:11,824 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:36:11,825 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:36:11,842 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:36:11,843 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:36:11,846 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:36:11,847 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405073  0.388088           6         1.080756
          30 valid t2_p50_h30   gru       30          balanced           0.408094  0.399890           4         1.082619

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:36:26,899 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:36:30,486 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:36:30,570 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:36:30,571 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:36:30,589 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:36:30,589 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:36:30,606 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:36:30,607 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:36:30,609 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:36:30,610 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:36:30,682 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:36:30,683 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=472 | prob=3248304

----------------------------------------------------------------------------------------------------
[77/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:36:30,700 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:36:30,701 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:36:30,718 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:36:30,719 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:36:30,722 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:36:30,722 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405073  0.388088           6         1.080756
          30 valid t2_p50_h30   gru       30          balanced           0.408094  0.399890           4         1.082619

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:36:45,814 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:36:49,414 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:36:49,498 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:36:49,499 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:36:49,516 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:36:49,516 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:36:49,533 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:36:49,534 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:36:49,537 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:36:49,538 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:36:49,605 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:36:49,606 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=474 | prob=3262068

----------------------------------------------------------------------------------------------------
[78/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:36:49,626 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:36:49,627 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:36:49,647 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:36:49,647 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:36:49,650 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:36:49,650 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405073  0.388088           6         1.080756
          30 valid t2_p50_h30   gru       30          balanced           0.408094  0.399890           4         1.082619

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:37:04,717 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:37:08,383 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:37:08,470 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:37:08,470 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:37:08,488 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:37:08,489 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:37:08,505 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:37:08,506 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:37:08,509 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:37:08,509 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:37:08,583 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:37:08,584 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=476 | prob=3275832

----------------------------------------------------------------------------------------------------
[79/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:37:08,601 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:37:08,601 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:37:08,618 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:37:08,619 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:37:08,621 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:37:08,621 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405073  0.388088           6         1.080756
          30 valid t2_p50_h30   gru       30          balanced           0.408094  0.399890           4         1.082619

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:37:23,733 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:37:27,400 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:37:27,485 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:37:27,486 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:37:27,503 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:37:27,504 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:37:27,522 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:37:27,522 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:37:27,525 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:37:27,525 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:37:27,592 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:37:27,592 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=478 | prob=3289596

----------------------------------------------------------------------------------------------------
[80/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:37:27,610 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:37:27,611 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:37:27,628 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:37:27,629 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:37:27,632 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:37:27,633 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405073  0.388088           6         1.080756
          30 valid t2_p50_h30   gru       30          balanced           0.408094  0.399890           4         1.082619

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:37:42,809 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:37:46,517 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:37:46,600 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:37:46,600 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:37:46,618 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:37:46,618 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:37:46,638 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:37:46,639 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:37:46,642 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:37:46,642 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:37:46,709 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:37:46,710 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=480 | prob=3303360

----------------------------------------------------------------------------------------------------
[81/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:37:46,728 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:37:46,728 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:37:46,745 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:37:46,746 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:37:46,748 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:37:46,749 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405073  0.388088           6         1.080756
          30 valid t2_p50_h30   gru       30          balanced           0.408094  0.399890           4         1.082619

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:38:01,821 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:38:05,494 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:38:05,573 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:38:05,574 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:38:05,593 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:38:05,594 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:38:05,610 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:38:05,611 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:38:05,614 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:38:05,614 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:38:05,681 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:38:05,681 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=482 | prob=3317124

----------------------------------------------------------------------------------------------------
[82/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:38:05,699 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:38:05,700 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:38:05,717 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:38:05,718 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:38:05,720 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:38:05,721 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405073  0.388088           6         1.080756
          30 valid t2_p50_h30   gru       30          balanced           0.408094  0.399890           4         1.082619

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:38:20,838 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:38:24,510 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:38:24,595 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:38:24,596 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:38:24,613 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:38:24,613 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:38:24,630 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:38:24,631 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:38:24,634 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:38:24,634 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:38:24,701 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:38:24,702 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=484 | prob=3330888

----------------------------------------------------------------------------------------------------
[83/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:38:24,719 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:38:24,720 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:38:24,737 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:38:24,737 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:38:24,740 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:38:24,740 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405073  0.388088           6         1.080756
          30 valid t2_p50_h30   gru       30          balanced           0.408094  0.399890           4         1.082619

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:38:39,838 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:38:43,508 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:38:43,592 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:38:43,592 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:38:43,609 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:38:43,610 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:38:43,627 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:38:43,628 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:38:43,630 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:38:43,631 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:38:43,697 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:38:43,698 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=486 | prob=3344652

----------------------------------------------------------------------------------------------------
[84/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:38:43,715 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:38:43,716 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:38:43,733 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:38:43,734 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:38:43,736 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:38:43,737 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.405073  0.388088           6         1.080756
          30 valid t2_p50_h30   gru       30          balanced           0.408094  0.399890           4         1.082619

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:38:58,965 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:39:02,727 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:39:02,811 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:39:02,812 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:39:02,831 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:39:02,831 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:39:02,849 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:39:02,849 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:39:02,852 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:39:02,852 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:39:02,918 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:39:02,919 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=488 | prob=3358416

----------------------------------------------------------------------------------------------------
[85/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:39:02,936 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:39:02,936 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:39:02,953 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:39:02,954 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:39:02,956 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:39:02,957 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.388369  0.340991           1         1.083440
          30 valid t2_p50_h30   gru       30          balanced           0.418545  0.409143           6         1.082205

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:39:17,080 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:39:20,845 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:39:20,930 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:39:20,931 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:39:20,948 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:39:20,949 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:39:20,966 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:39:20,966 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:39:20,968 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:39:20,969 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:39:21,035 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:39:21,035 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=490 | prob=3372180

----------------------------------------------------------------------------------------------------
[86/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:39:21,053 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:39:21,053 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:39:21,070 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:39:21,071 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:39:21,073 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:39:21,073 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.388369  0.340991           1         1.083440
          30 valid t2_p50_h30   gru       30          balanced           0.418545  0.409143           6         1.082205

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:39:35,186 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:39:38,996 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:39:39,083 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:39:39,084 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:39:39,101 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:39:39,102 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:39:39,119 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:39:39,119 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:39:39,122 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:39:39,123 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:39:39,189 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:39:39,190 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=492 | prob=3385944

----------------------------------------------------------------------------------------------------
[87/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:39:39,208 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:39:39,209 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:39:39,229 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:39:39,230 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:39:39,234 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:39:39,234 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.388369  0.340991           1         1.083440
          30 valid t2_p50_h30   gru       30          balanced           0.418545  0.409143           6         1.082205

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:39:53,460 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:39:57,282 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:39:57,368 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:39:57,369 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:39:57,386 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:39:57,387 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:39:57,403 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:39:57,403 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:39:57,406 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:39:57,406 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:39:57,471 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:39:57,472 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=494 | prob=3399708

----------------------------------------------------------------------------------------------------
[88/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:39:57,489 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:39:57,490 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:39:57,507 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:39:57,507 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:39:57,510 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:39:57,511 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.388369  0.340991           1         1.083440
          30 valid t2_p50_h30   gru       30          balanced           0.418545  0.409143           6         1.082205

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:40:11,793 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:40:15,686 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:40:15,771 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:40:15,772 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:40:15,790 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:40:15,790 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:40:15,808 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:40:15,808 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:40:15,811 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:40:15,812 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:40:15,882 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:40:15,883 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=496 | prob=3413472

----------------------------------------------------------------------------------------------------
[89/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:40:15,900 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:40:15,901 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:40:15,918 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:40:15,919 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:40:15,922 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:40:15,922 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.388369  0.340991           1         1.083440
          30 valid t2_p50_h30   gru       30          balanced           0.418545  0.409143           6         1.082205

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:40:30,124 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:40:33,975 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:40:34,061 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:40:34,062 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:40:34,079 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:40:34,080 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:40:34,097 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:40:34,098 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:40:34,102 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:40:34,102 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:40:34,168 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:40:34,169 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=498 | prob=3427236

----------------------------------------------------------------------------------------------------
[90/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:40:34,186 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:40:34,187 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:40:34,203 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:40:34,204 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:40:34,206 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:40:34,207 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.388369  0.340991           1         1.083440
          30 valid t2_p50_h30   gru       30          balanced           0.418545  0.409143           6         1.082205

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:40:48,523 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:40:52,396 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:40:52,487 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:40:52,487 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:40:52,505 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:40:52,505 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:40:52,522 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:40:52,523 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:40:52,526 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:40:52,526 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:40:52,592 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:40:52,592 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=500 | prob=3441000

----------------------------------------------------------------------------------------------------
[91/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:40:52,610 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:40:52,610 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:40:52,627 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:40:52,628 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:40:52,631 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:40:52,631 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.388369  0.340991           1         1.083440
          30 valid t2_p50_h30   gru       30          balanced           0.418545  0.409143           6         1.082205

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:41:06,963 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:41:10,823 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:41:10,913 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:41:10,914 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:41:10,931 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:41:10,932 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:41:10,948 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:41:10,949 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:41:10,952 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:41:10,952 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:41:11,019 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:41:11,019 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=502 | prob=3454764

----------------------------------------------------------------------------------------------------
[92/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:41:11,037 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:41:11,038 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:41:11,054 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:41:11,055 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:41:11,058 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:41:11,058 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.388369  0.340991           1         1.083440
          30 valid t2_p50_h30   gru       30          balanced           0.418545  0.409143           6         1.082205

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:41:25,348 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:41:29,199 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:41:29,287 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:41:29,288 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:41:29,305 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:41:29,306 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:41:29,323 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:41:29,324 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:41:29,326 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:41:29,327 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:41:29,397 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:41:29,398 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=504 | prob=3468528

----------------------------------------------------------------------------------------------------
[93/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:41:29,417 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:41:29,417 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:41:29,435 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:41:29,436 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:41:29,439 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:41:29,440 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.388369  0.340991           1         1.083440
          30 valid t2_p50_h30   gru       30          balanced           0.418545  0.409143           6         1.082205

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:41:43,782 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:41:47,666 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:41:47,755 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:41:47,756 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:41:47,773 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:41:47,773 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:41:47,790 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:41:47,791 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:41:47,794 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:41:47,794 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:41:47,860 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:41:47,860 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=506 | prob=3482292

----------------------------------------------------------------------------------------------------
[94/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:41:47,878 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:41:47,878 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:41:47,895 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:41:47,895 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:41:47,898 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:41:47,899 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.388369  0.340991           1         1.083440
          30 valid t2_p50_h30   gru       30          balanced           0.418545  0.409143           6         1.082205

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:42:02,219 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:42:06,169 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:42:06,256 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:42:06,257 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:42:06,275 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:42:06,276 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:42:06,293 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:42:06,294 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:42:06,297 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:42:06,297 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:42:06,363 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:42:06,364 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=508 | prob=3496056

----------------------------------------------------------------------------------------------------
[95/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:42:06,381 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:42:06,382 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:42:06,398 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:42:06,399 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:42:06,401 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:42:06,402 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.388369  0.340991           1         1.083440
          30 valid t2_p50_h30   gru       30          balanced           0.418545  0.409143           6         1.082205

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:42:20,789 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:42:24,707 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:42:24,793 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:42:24,794 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:42:24,811 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:42:24,812 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:42:24,828 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:42:24,829 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:42:24,832 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:42:24,832 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:42:24,899 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:42:24,900 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=510 | prob=3509820

----------------------------------------------------------------------------------------------------
[96/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:42:24,917 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:42:24,918 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:42:24,936 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:42:24,937 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:42:24,939 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:42:24,940 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.388369  0.340991           1         1.083440
          30 valid t2_p50_h30   gru       30          balanced           0.418545  0.409143           6         1.082205

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:42:39,300 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:42:43,248 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:42:43,335 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:42:43,335 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:42:43,352 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:42:43,353 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:42:43,370 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:42:43,370 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:42:43,373 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:42:43,374 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:42:43,441 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:42:43,441 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=512 | prob=3523584

----------------------------------------------------------------------------------------------------
[97/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:42:43,459 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:42:43,460 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:42:43,476 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:42:43,477 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:42:43,480 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:42:43,481 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416374  0.384889           5         1.079829
          30 valid t2_p50_h30   gru       30          balanced           0.409704  0.395807           4         1.081681

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:42:59,918 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:43:03,854 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:43:03,940 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:43:03,941 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:43:03,959 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:43:03,959 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:43:03,976 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:43:03,977 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:43:03,980 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:43:03,981 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=514 | prob=3537348

----------------------------------------------------------------------------------------------------
[98/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:43:04,058 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:43:04,059 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:43:04,077 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:43:04,077 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:43:04,098 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:43:04,098 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:43:04,101 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:43:04,101 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416374  0.384889           5         1.079829
          30 valid t2_p50_h30   gru       30          balanced           0.409704  0.395807           4         1.081681

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:43:20,533 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:43:24,547 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:43:24,633 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:43:24,633 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:43:24,654 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:43:24,654 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:43:24,672 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:43:24,673 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:43:24,675 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:43:24,676 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:43:24,744 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:43:24,745 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=516 | prob=3551112

----------------------------------------------------------------------------------------------------
[99/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:43:24,762 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:43:24,763 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:43:24,782 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:43:24,783 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:43:24,786 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:43:24,787 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416374  0.384889           5         1.079829
          30 valid t2_p50_h30   gru       30          balanced           0.409704  0.395807           4         1.081681

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:43:41,167 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:43:45,122 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:43:45,206 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:43:45,207 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:43:45,224 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:43:45,224 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:43:45,241 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:43:45,242 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:43:45,244 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:43:45,245 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:43:45,311 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:43:45,311 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=518 | prob=3564876

----------------------------------------------------------------------------------------------------
[100/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:43:45,328 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:43:45,329 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:43:45,345 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:43:45,346 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:43:45,349 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:43:45,350 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416374  0.384889           5         1.079829
          30 valid t2_p50_h30   gru       30          balanced           0.409704  0.395807           4         1.081681

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:44:01,790 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:44:05,791 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:44:05,876 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:44:05,877 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:44:05,895 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:44:05,895 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:44:05,912 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:44:05,912 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:44:05,915 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:44:05,916 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:44:05,982 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:44:05,983 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=520 | prob=3578640

----------------------------------------------------------------------------------------------------
[101/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:44:06,001 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:44:06,001 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:44:06,019 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:44:06,020 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:44:06,023 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:44:06,023 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416374  0.384889           5         1.079829
          30 valid t2_p50_h30   gru       30          balanced           0.409704  0.395807           4         1.081681

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:44:22,422 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:44:26,391 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:44:26,478 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:44:26,478 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:44:26,496 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:44:26,497 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:44:26,517 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:44:26,517 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:44:26,520 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:44:26,521 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:44:26,590 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:44:26,591 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=522 | prob=3592404

----------------------------------------------------------------------------------------------------
[102/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:44:26,608 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:44:26,609 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:44:26,625 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:44:26,626 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:44:26,629 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:44:26,630 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416374  0.384889           5         1.079829
          30 valid t2_p50_h30   gru       30          balanced           0.409704  0.395807           4         1.081681

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:44:43,043 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:44:47,071 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:44:47,160 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:44:47,160 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:44:47,178 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:44:47,179 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:44:47,196 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:44:47,196 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:44:47,200 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:44:47,200 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:44:47,267 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:44:47,268 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=524 | prob=3606168

----------------------------------------------------------------------------------------------------
[103/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:44:47,285 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:44:47,286 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:44:47,303 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:44:47,304 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:44:47,307 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:44:47,308 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416374  0.384889           5         1.079829
          30 valid t2_p50_h30   gru       30          balanced           0.409704  0.395807           4         1.081681

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:45:03,801 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:45:07,827 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:45:07,921 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:45:07,922 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:45:07,939 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:45:07,940 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:45:07,960 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:45:07,961 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:45:07,964 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:45:07,964 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=526 | prob=3619932

----------------------------------------------------------------------------------------------------
[104/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:45:08,031 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:45:08,031 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:45:08,049 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:45:08,049 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:45:08,067 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:45:08,068 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:45:08,071 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:45:08,071 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416374  0.384889           5         1.079829
          30 valid t2_p50_h30   gru       30          balanced           0.409704  0.395807           4         1.081681

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:45:24,691 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:45:28,728 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:45:28,825 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:45:28,825 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:45:28,842 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:45:28,843 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:45:28,862 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:45:28,863 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:45:28,866 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:45:28,866 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=528 | prob=3633696

----------------------------------------------------------------------------------------------------
[105/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:45:28,941 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:45:28,942 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:45:28,959 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:45:28,960 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:45:28,977 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:45:28,978 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:45:28,980 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:45:28,981 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416374  0.384889           5         1.079829
          30 valid t2_p50_h30   gru       30          balanced           0.409704  0.395807           4         1.081681

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:45:45,485 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:45:49,506 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:45:49,590 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:45:49,590 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:45:49,607 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:45:49,608 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:45:49,625 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:45:49,625 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:45:49,628 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:45:49,628 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:45:49,694 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:45:49,695 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=530 | prob=3647460

----------------------------------------------------------------------------------------------------
[106/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:45:49,712 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:45:49,713 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:45:49,729 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:45:49,730 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:45:49,732 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:45:49,733 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416374  0.384889           5         1.079829
          30 valid t2_p50_h30   gru       30          balanced           0.409704  0.395807           4         1.081681

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:46:06,191 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:46:10,265 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:46:10,351 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:46:10,351 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:46:10,369 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:46:10,369 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:46:10,386 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:46:10,387 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:46:10,389 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:46:10,390 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:46:10,458 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:46:10,458 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=532 | prob=3661224

----------------------------------------------------------------------------------------------------
[107/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:46:10,479 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:46:10,479 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:46:10,496 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:46:10,497 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:46:10,500 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:46:10,500 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416374  0.384889           5         1.079829
          30 valid t2_p50_h30   gru       30          balanced           0.409704  0.395807           4         1.081681

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:46:27,034 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:46:31,108 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:46:31,198 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:46:31,198 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:46:31,217 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:46:31,217 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:46:31,234 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:46:31,235 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:46:31,237 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:46:31,238 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:46:31,304 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:46:31,305 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=534 | prob=3674988

----------------------------------------------------------------------------------------------------
[108/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.2 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.2
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:46:31,323 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:46:31,323 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:46:31,340 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:46:31,341 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:46:31,344 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:46:31,344 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416374  0.384889           5         1.079829
          30 valid t2_p50_h30   gru       30          balanced           0.409704  0.395807           4         1.081681

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:46:47,879 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:46:52,002 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:46:52,097 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:46:52,098 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:46:52,115 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:46:52,116 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:46:52,133 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:46:52,134 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:46:52,137 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:46:52,137 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:46:52,203 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:46:52,204 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=536 | prob=3688752

----------------------------------------------------------------------------------------------------
[109/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:46:52,225 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:46:52,226 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:46:52,243 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:46:52,244 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:46:52,247 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:46:52,247 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.406134  0.390125           6         1.080355
          30 valid t2_p50_h30   gru       30          balanced           0.404763  0.396119           4         1.083284

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:47:07,912 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:47:12,102 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:47:12,193 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:47:12,194 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:47:12,212 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:47:12,213 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:47:12,232 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:47:12,232 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:47:12,235 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:47:12,236 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:47:12,302 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:47:12,303 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=538 | prob=3702516

----------------------------------------------------------------------------------------------------
[110/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:47:12,321 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:47:12,321 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:47:12,342 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:47:12,342 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:47:12,345 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:47:12,346 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.406134  0.390125           6         1.080355
          30 valid t2_p50_h30   gru       30          balanced           0.404763  0.396119           4         1.083284

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:47:27,991 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:47:32,123 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:47:32,211 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:47:32,212 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:47:32,229 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:47:32,229 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:47:32,246 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:47:32,247 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:47:32,250 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:47:32,250 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:47:32,316 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:47:32,316 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=540 | prob=3716280

----------------------------------------------------------------------------------------------------
[111/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:47:32,334 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:47:32,334 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:47:32,352 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:47:32,352 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:47:32,355 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:47:32,355 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.406134  0.390125           6         1.080355
          30 valid t2_p50_h30   gru       30          balanced           0.404763  0.396119           4         1.083284

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:47:48,072 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:47:52,238 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:47:52,328 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:47:52,329 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:47:52,346 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:47:52,347 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:47:52,364 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:47:52,365 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:47:52,367 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:47:52,368 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:47:52,441 | INFO | Loaded: windows_t2_p50_h30_train.npz

💾 Guardado OK | metrics=542 | prob=3730044

----------------------------------------------------------------------------------------------------
[112/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:47:52,442 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:47:52,459 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:47:52,459 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:47:52,477 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:47:52,477 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:47:52,480 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:47:52,481 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.406134  0.390125           6         1.080355
          30 valid t2_p50_h30   gru       30          balanced           0.404763  0.396119           4         1.083284

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:48:08,220 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:48:12,439 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:48:12,527 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:48:12,528 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:48:12,545 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:48:12,546 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:48:12,563 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:48:12,564 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:48:12,566 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:48:12,567 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:48:12,633 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:48:12,634 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=544 | prob=3743808

----------------------------------------------------------------------------------------------------
[113/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:48:12,651 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:48:12,652 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:48:12,668 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:48:12,669 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:48:12,672 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:48:12,673 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.406134  0.390125           6         1.080355
          30 valid t2_p50_h30   gru       30          balanced           0.404763  0.396119           4         1.083284

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:48:28,518 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:48:32,696 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:48:32,784 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:48:32,785 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:48:32,803 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:48:32,804 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:48:32,821 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:48:32,821 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:48:32,824 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:48:32,824 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:48:32,890 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:48:32,891 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=546 | prob=3757572

----------------------------------------------------------------------------------------------------
[114/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:48:32,909 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:48:32,910 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:48:32,927 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:48:32,928 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:48:32,930 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:48:32,931 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.406134  0.390125           6         1.080355
          30 valid t2_p50_h30   gru       30          balanced           0.404763  0.396119           4         1.083284

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:48:48,741 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:48:52,928 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:48:53,018 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:48:53,019 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:48:53,036 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:48:53,037 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:48:53,054 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:48:53,055 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:48:53,058 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:48:53,058 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:48:53,125 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:48:53,125 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=548 | prob=3771336

----------------------------------------------------------------------------------------------------
[115/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:48:53,143 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:48:53,143 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:48:53,164 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:48:53,164 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:48:53,167 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:48:53,167 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.406134  0.390125           6         1.080355
          30 valid t2_p50_h30   gru       30          balanced           0.404763  0.396119           4         1.083284

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:49:08,987 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:49:13,164 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:49:13,250 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:49:13,251 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:49:13,271 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:49:13,271 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:49:13,291 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:49:13,292 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:49:13,294 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:49:13,295 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:49:13,362 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:49:13,363 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=550 | prob=3785100

----------------------------------------------------------------------------------------------------
[116/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:49:13,380 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:49:13,381 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:49:13,398 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:49:13,398 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:49:13,401 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:49:13,401 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.406134  0.390125           6         1.080355
          30 valid t2_p50_h30   gru       30          balanced           0.404763  0.396119           4         1.083284

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:49:29,165 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:49:33,388 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:49:33,473 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:49:33,473 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:49:33,491 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:49:33,492 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:49:33,509 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:49:33,509 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:49:33,512 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:49:33,512 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:49:33,579 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:49:33,580 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=552 | prob=3798864

----------------------------------------------------------------------------------------------------
[117/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:49:33,601 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:49:33,601 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:49:33,733 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:49:33,734 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:49:33,739 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:49:33,739 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.406134  0.390125           6         1.080355
          30 valid t2_p50_h30   gru       30          balanced           0.404763  0.396119           4         1.083284

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:49:49,630 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:49:53,921 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:49:54,009 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:49:54,010 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:49:54,028 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:49:54,029 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:49:54,046 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:49:54,047 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:49:54,050 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:49:54,051 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:49:54,119 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:49:54,120 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=554 | prob=3812628

----------------------------------------------------------------------------------------------------
[118/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:49:54,138 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:49:54,138 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:49:54,156 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:49:54,156 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:49:54,159 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:49:54,159 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.406134  0.390125           6         1.080355
          30 valid t2_p50_h30   gru       30          balanced           0.404763  0.396119           4         1.083284

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:50:09,963 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:50:14,222 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:50:14,311 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:50:14,311 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:50:14,329 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:50:14,329 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:50:14,347 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:50:14,347 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:50:14,350 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:50:14,350 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:50:14,417 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:50:14,417 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=556 | prob=3826392

----------------------------------------------------------------------------------------------------
[119/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:50:14,435 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:50:14,435 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:50:14,452 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:50:14,453 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:50:14,455 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:50:14,456 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.406134  0.390125           6         1.080355
          30 valid t2_p50_h30   gru       30          balanced           0.404763  0.396119           4         1.083284

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:50:30,272 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:50:34,552 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:50:34,638 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:50:34,638 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:50:34,656 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:50:34,656 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:50:34,673 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:50:34,674 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)

💾 Guardado OK | metrics=558 | prob=3840156

----------------------------------------------------------------------------------------------------
[120/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:50:34,797 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:50:34,798 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:50:34,867 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:50:34,867 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:50:34,885 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:50:34,885 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:50:34,902 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:50:34,903 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:50:34,906 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:50:34,906 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.406134  0.390125           6         1.080355
          30 valid t2_p50_h30   gru       30          balanced           0.404763  0.396119           4         1.083284

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:50:50,703 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:50:54,941 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:50:55,028 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:50:55,029 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:50:55,047 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:50:55,048 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:50:55,066 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:50:55,067 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:50:55,069 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:50:55,070 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:50:55,137 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:50:55,138 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=560 | prob=3853920

----------------------------------------------------------------------------------------------------
[121/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:50:55,155 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:50:55,156 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:50:55,173 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:50:55,173 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:50:55,176 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:50:55,176 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410292  0.386731           9         1.081438
          30 valid t2_p50_h30   gru       30          balanced           0.418771  0.409444           6         1.080930

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:51:13,965 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:51:18,200 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:51:18,276 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:51:18,277 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:51:18,294 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:51:18,295 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:51:18,312 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:51:18,312 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:51:18,315 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:51:18,316 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:51:18,381 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:51:18,382 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:51:18,399 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:51:18,400 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=562 | prob=3867684

----------------------------------------------------------------------------------------------------
[122/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:51:18,417 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:51:18,418 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:51:18,421 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:51:18,421 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410292  0.386731           9         1.081438
          30 valid t2_p50_h30   gru       30          balanced           0.418771  0.409444           6         1.080930

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:51:37,229 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:51:41,500 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:51:41,590 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:51:41,591 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=564 | prob=3881448

----------------------------------------------------------------------------------------------------
[123/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:51:41,733 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:51:41,734 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:51:41,751 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:51:41,751 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:51:41,754 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:51:41,754 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:51:41,824 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:51:41,825 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:51:41,845 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:51:41,845 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:51:41,864 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:51:41,865 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:51:41,868 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:51:41,868 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410292  0.386731           9         1.081438
          30 valid t2_p50_h30   gru       30          balanced           0.418771  0.409444           6         1.080930

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:52:00,634 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:52:04,953 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:52:05,054 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:52:05,055 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:52:05,075 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:52:05,075 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:52:05,092 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:52:05,093 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:52:05,095 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:52:05,096 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=566 | prob=3895212

----------------------------------------------------------------------------------------------------
[124/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:52:05,161 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:52:05,162 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:52:05,178 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:52:05,179 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:52:05,195 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:52:05,195 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:52:05,198 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:52:05,198 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410292  0.386731           9         1.081438
          30 valid t2_p50_h30   gru       30          balanced           0.418771  0.409444           6         1.080930

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:52:24,005 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:52:28,334 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:52:28,421 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:52:28,422 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:52:28,439 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:52:28,440 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:52:28,456 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:52:28,457 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:52:28,460 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:52:28,461 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:52:28,527 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:52:28,528 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=568 | prob=3908976

----------------------------------------------------------------------------------------------------
[125/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:52:28,546 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:52:28,546 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:52:28,563 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:52:28,564 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:52:28,569 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:52:28,569 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410292  0.386731           9         1.081438
          30 valid t2_p50_h30   gru       30          balanced           0.418771  0.409444           6         1.080930

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:52:47,303 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:52:51,673 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet

💾 Guardado OK | metrics=570 | prob=3922740

----------------------------------------------------------------------------------------------------
[126/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:52:51,886 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:52:51,886 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:52:51,903 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:52:51,904 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:52:51,921 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:52:51,921 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:52:51,924 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:52:51,924 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:52:51,990 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:52:51,991 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:52:52,008 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:52:52,008 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:52:52,026 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:52:52,026 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:52:52,029 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:52:52,030 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410292  0.386731           9         1.081438
          30 valid t2_p50_h30   gru       30          balanced           0.418771  0.409444           6         1.080930

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:53:10,789 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:53:15,133 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:53:15,221 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:53:15,221 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:53:15,240 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:53:15,241 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:53:15,258 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:53:15,258 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:53:15,261 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:53:15,262 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:53:15,329 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:53:15,330 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=572 | prob=3936504

----------------------------------------------------------------------------------------------------
[127/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:53:15,347 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:53:15,348 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:53:15,365 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:53:15,366 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:53:15,369 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:53:15,369 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410292  0.386731           9         1.081438
          30 valid t2_p50_h30   gru       30          balanced           0.418771  0.409444           6         1.080930

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:53:34,112 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:53:38,469 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:53:38,560 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:53:38,560 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:53:38,577 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:53:38,578 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:53:38,595 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:53:38,595 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:53:38,598 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:53:38,598 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=574 | prob=3950268

----------------------------------------------------------------------------------------------------
[128/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:53:38,677 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:53:38,678 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:53:38,698 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:53:38,699 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:53:38,717 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:53:38,717 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:53:38,720 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:53:38,720 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410292  0.386731           9         1.081438
          30 valid t2_p50_h30   gru       30          balanced           0.418771  0.409444           6         1.080930

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:53:57,623 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:54:01,971 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:54:02,053 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:54:02,054 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:54:02,074 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:54:02,075 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:54:02,095 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:54:02,096 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:54:02,098 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:54:02,099 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:54:02,165 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:54:02,166 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=576 | prob=3964032

----------------------------------------------------------------------------------------------------
[129/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:54:02,183 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:54:02,183 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:54:02,201 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:54:02,201 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:54:02,204 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:54:02,204 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410292  0.386731           9         1.081438
          30 valid t2_p50_h30   gru       30          balanced           0.418771  0.409444           6         1.080930

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:54:21,170 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:54:25,566 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:54:25,653 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:54:25,653 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:54:25,670 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:54:25,671 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:54:25,688 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:54:25,689 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:54:25,691 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:54:25,692 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:54:25,758 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:54:25,758 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=578 | prob=3977796

----------------------------------------------------------------------------------------------------
[130/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:54:25,776 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:54:25,776 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:54:25,793 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:54:25,794 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:54:25,796 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:54:25,797 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410292  0.386731           9         1.081438
          30 valid t2_p50_h30   gru       30          balanced           0.418771  0.409444           6         1.080930

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:54:44,750 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:54:49,174 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:54:49,259 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:54:49,260 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:54:49,277 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:54:49,278 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:54:49,295 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:54:49,296 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:54:49,299 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:54:49,299 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:54:49,366 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:54:49,366 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=580 | prob=3991560

----------------------------------------------------------------------------------------------------
[131/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:54:49,384 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:54:49,385 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:54:49,401 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:54:49,402 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:54:49,405 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:54:49,405 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410292  0.386731           9         1.081438
          30 valid t2_p50_h30   gru       30          balanced           0.418771  0.409444           6         1.080930

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:55:08,327 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:55:12,788 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:55:12,874 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:55:12,875 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:55:12,893 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:55:12,893 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:55:12,911 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:55:12,911 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:55:12,914 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:55:12,915 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:55:12,983 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:55:12,984 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=582 | prob=4005324

----------------------------------------------------------------------------------------------------
[132/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:55:13,002 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:55:13,002 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:55:13,019 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:55:13,020 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:55:13,023 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:55:13,024 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410292  0.386731           9         1.081438
          30 valid t2_p50_h30   gru       30          balanced           0.418771  0.409444           6         1.080930

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:55:31,989 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:55:36,527 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:55:36,618 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:55:36,619 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:55:36,636 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:55:36,637 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:55:36,655 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:55:36,656 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:55:36,659 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:55:36,660 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:55:36,728 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:55:36,728 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=584 | prob=4019088

----------------------------------------------------------------------------------------------------
[133/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:55:36,746 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:55:36,746 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:55:36,764 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:55:36,764 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:55:36,767 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:55:36,768 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416944  0.385262           5         1.080047
          30 valid t2_p50_h30   gru       30          balanced           0.410106  0.395793           4         1.082177

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:55:53,847 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:55:58,350 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:55:58,438 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:55:58,439 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:55:58,456 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:55:58,456 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:55:58,473 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:55:58,474 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:55:58,476 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:55:58,477 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:55:58,545 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:55:58,546 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=586 | prob=4032852

----------------------------------------------------------------------------------------------------
[134/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:55:58,564 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:55:58,565 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:55:58,582 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:55:58,583 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:55:58,585 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:55:58,586 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416944  0.385262           5         1.080047
          30 valid t2_p50_h30   gru       30          balanced           0.410106  0.395793           4         1.082177

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:56:15,729 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:56:20,146 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:56:20,223 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:56:20,224 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:56:20,241 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:56:20,241 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:56:20,259 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:56:20,259 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:56:20,262 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:56:20,262 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:56:20,328 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:56:20,328 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:56:20,345 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:56:20,346 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=588 | prob=4046616

----------------------------------------------------------------------------------------------------
[135/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:56:20,363 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:56:20,363 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:56:20,365 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:56:20,366 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416944  0.385262           5         1.080047
          30 valid t2_p50_h30   gru       30          balanced           0.410106  0.395793           4         1.082177

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:56:37,449 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:56:41,939 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:56:42,027 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:56:42,027 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:56:42,045 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:56:42,046 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:56:42,064 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:56:42,064 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:56:42,068 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:56:42,068 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:56:42,135 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:56:42,136 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=590 | prob=4060380

----------------------------------------------------------------------------------------------------
[136/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:56:42,154 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:56:42,154 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:56:42,171 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:56:42,171 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:56:42,174 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:56:42,174 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416944  0.385262           5         1.080047
          30 valid t2_p50_h30   gru       30          balanced           0.410106  0.395793           4         1.082177

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:56:59,268 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:57:03,746 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:57:03,833 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:57:03,834 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:57:03,851 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:57:03,851 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:57:03,868 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:57:03,869 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:57:03,872 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:57:03,872 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:57:03,938 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:57:03,939 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=592 | prob=4074144

----------------------------------------------------------------------------------------------------
[137/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:57:03,958 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:57:03,958 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:57:03,975 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:57:03,975 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:57:03,978 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:57:03,978 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416944  0.385262           5         1.080047
          30 valid t2_p50_h30   gru       30          balanced           0.410106  0.395793           4         1.082177

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:57:21,030 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:57:25,535 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:57:25,623 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:57:25,624 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:57:25,644 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:57:25,645 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:57:25,662 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:57:25,663 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:57:25,666 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:57:25,666 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:57:25,733 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:57:25,734 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=594 | prob=4087908

----------------------------------------------------------------------------------------------------
[138/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:57:25,752 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:57:25,752 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:57:25,770 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:57:25,771 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:57:25,774 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:57:25,774 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416944  0.385262           5         1.080047
          30 valid t2_p50_h30   gru       30          balanced           0.410106  0.395793           4         1.082177

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:57:42,907 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:57:47,411 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:57:47,499 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:57:47,499 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:57:47,517 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:57:47,518 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:57:47,535 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:57:47,536 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:57:47,538 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:57:47,539 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:57:47,604 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:57:47,605 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=596 | prob=4101672

----------------------------------------------------------------------------------------------------
[139/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:57:47,622 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:57:47,623 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:57:47,639 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:57:47,640 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:57:47,642 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:57:47,643 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416944  0.385262           5         1.080047
          30 valid t2_p50_h30   gru       30          balanced           0.410106  0.395793           4         1.082177

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:58:04,761 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:58:09,308 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:58:09,398 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:58:09,399 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:58:09,416 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:58:09,417 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:58:09,434 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:58:09,434 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:58:09,437 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:58:09,437 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:58:09,503 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:58:09,504 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=598 | prob=4115436

----------------------------------------------------------------------------------------------------
[140/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:58:09,521 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:58:09,522 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:58:09,539 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:58:09,539 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:58:09,542 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:58:09,542 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416944  0.385262           5         1.080047
          30 valid t2_p50_h30   gru       30          balanced           0.410106  0.395793           4         1.082177

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:58:26,736 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:58:31,330 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:58:31,419 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:58:31,420 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:58:31,438 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:58:31,439 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:58:31,458 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:58:31,459 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:58:31,461 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:58:31,462 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:58:31,528 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:58:31,529 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=600 | prob=4129200

----------------------------------------------------------------------------------------------------
[141/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:58:31,546 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:58:31,547 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:58:31,564 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:58:31,565 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:58:31,567 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:58:31,568 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416944  0.385262           5         1.080047
          30 valid t2_p50_h30   gru       30          balanced           0.410106  0.395793           4         1.082177

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 17:58:48,685 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:58:53,251 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:58:53,341 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:58:53,342 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:58:53,359 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:58:53,359 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:58:53,377 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:58:53,377 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:58:53,380 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:58:53,381 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:58:53,446 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:58:53,447 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=602 | prob=4142964

----------------------------------------------------------------------------------------------------
[142/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:58:53,465 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:58:53,465 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:58:53,482 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:58:53,483 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:58:53,485 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:58:53,486 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416944  0.385262           5         1.080047
          30 valid t2_p50_h30   gru       30          balanced           0.410106  0.395793           4         1.082177

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 17:59:10,656 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:59:15,183 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:59:15,270 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:59:15,271 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:59:15,288 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:59:15,288 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:59:15,305 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:59:15,306 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:59:15,309 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:59:15,309 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:59:15,375 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:59:15,376 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=604 | prob=4156728

----------------------------------------------------------------------------------------------------
[143/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 17:59:15,393 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:59:15,394 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:59:15,411 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:59:15,411 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:59:15,413 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:59:15,414 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416944  0.385262           5         1.080047
          30 valid t2_p50_h30   gru       30          balanced           0.410106  0.395793           4         1.082177

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 17:59:32,609 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:59:37,207 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:59:37,293 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 17:59:37,294 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 17:59:37,310 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 17:59:37,311 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:59:37,328 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 17:59:37,328 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:59:37,331 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:59:37,331 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 17:59:37,398 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 17:59:37,398 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=606 | prob=4170492

----------------------------------------------------------------------------------------------------
[144/144] hidden_size=256 | num_layers=1 | learning_rate=0.001 | dropout=0.3 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 256
num_layers       = 1
dropout          = 0.3
learning_rate    = 0.001
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 17:59:37,415 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 17:59:37,416 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 17:59:37,433 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 17:59:37,434 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 17:59:37,436 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 17:59:37,437 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416944  0.385262           5         1.080047
          30 valid t2_p50_h30   gru       30          balanced           0.410106  0.395793           4         1.082177

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 17:59:54,814 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:59:59,426 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 17:59:59,428 | INFO | Cargando métricas desde: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 17:59:59,460 | INFO | Cargando probabilidades desde: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet

💾 Guardado OK | metrics=608 | prob=4184256

2026-04-23 18:00:00,248 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:00:00,249 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:00:00,266 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:00:00,266 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:00:00,283 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:00:00,283 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:00:00,286 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:00:00,287 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:00:00,354 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:00:00,354 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:00:00,371 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:00:00,372 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

====================================================================================================
GRU GRID INCREMENTAL | L=30
====================================================================================================
targets                = ['t2_p40_h30', 't2_p50_h30']
n_combinations         = 144
hidden_size_values     = [128]
num_layers_values      = [1]
learning_rate_values   = [0.0005]
dropout_values         = [0.0, 0.1, 0.2, 0.3]
batch_size_values      = [1024, 2048, 4096]
grad_clip_norm_values  = [0.5, 1.0, 2.0]
threshold_long_values  = [0.4, 0.45]
threshold_short_values = [0.4, 0.45]
class_weight_mode      = balanced
optimizer_name         = adam

----------------------------------------------------------------------------------------------------
[1/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:00:00,388 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:00:00,389 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:00:00,392 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:00:00,392 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.408323  0.382491           3         1.080468
          30 valid t2_p50_h30   gru       30          balanced           0.406567  0.394225           3         1.082254

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:00:13,810 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:00:18,581 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:00:18,674 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:00:18,675 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:00:18,692 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:00:18,693 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:00:18,710 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:00:18,710 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:00:18,713 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:00:18,713 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:00:18,780 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:00:18,781 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=610 | prob=4198020

----------------------------------------------------------------------------------------------------
[2/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:00:18,799 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:00:18,799 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:00:18,816 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:00:18,817 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:00:18,820 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:00:18,821 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.408323  0.382491           3         1.080468
          30 valid t2_p50_h30   gru       30          balanced           0.406567  0.394225           3         1.082254

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:00:32,385 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:00:37,193 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:00:37,277 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:00:37,278 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:00:37,295 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:00:37,296 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:00:37,317 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:00:37,318 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:00:37,321 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:00:37,321 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:00:37,388 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:00:37,388 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=612 | prob=4211784

----------------------------------------------------------------------------------------------------
[3/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:00:37,406 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:00:37,406 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:00:37,423 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:00:37,423 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:00:37,426 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:00:37,427 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.408323  0.382491           3         1.080468
          30 valid t2_p50_h30   gru       30          balanced           0.406567  0.394225           3         1.082254

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:00:50,858 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:00:55,567 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:00:55,654 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:00:55,654 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:00:55,671 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:00:55,672 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:00:55,688 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:00:55,689 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:00:55,692 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:00:55,692 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:00:55,759 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:00:55,760 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=614 | prob=4225548

----------------------------------------------------------------------------------------------------
[4/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:00:55,777 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:00:55,778 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:00:55,795 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:00:55,795 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:00:55,798 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:00:55,799 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.408323  0.382491           3         1.080468
          30 valid t2_p50_h30   gru       30          balanced           0.406567  0.394225           3         1.082254

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:01:09,318 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:01:14,122 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:01:14,211 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:01:14,211 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:01:14,229 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:01:14,229 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:01:14,246 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:01:14,247 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:01:14,250 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:01:14,251 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:01:14,317 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:01:14,318 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=616 | prob=4239312

----------------------------------------------------------------------------------------------------
[5/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:01:14,335 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:01:14,335 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:01:14,352 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:01:14,352 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:01:14,355 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:01:14,355 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.408323  0.382491           3         1.080468
          30 valid t2_p50_h30   gru       30          balanced           0.406567  0.394225           3         1.082254

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:01:27,912 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:01:32,696 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:01:32,787 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:01:32,788 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:01:32,805 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:01:32,805 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:01:32,823 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:01:32,823 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:01:32,826 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:01:32,826 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:01:32,894 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:01:32,894 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=618 | prob=4253076

----------------------------------------------------------------------------------------------------
[6/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:01:32,912 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:01:32,913 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:01:32,930 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:01:32,930 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:01:32,933 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:01:32,934 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.408323  0.382491           3         1.080468
          30 valid t2_p50_h30   gru       30          balanced           0.406567  0.394225           3         1.082254

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:01:46,645 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:01:51,583 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:01:51,672 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:01:51,673 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:01:51,691 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:01:51,692 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:01:51,709 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:01:51,709 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:01:51,712 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:01:51,713 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:01:51,780 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:01:51,781 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=620 | prob=4266840

----------------------------------------------------------------------------------------------------
[7/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:01:51,798 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:01:51,798 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:01:51,815 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:01:51,816 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:01:51,818 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:01:51,818 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.408323  0.382491           3         1.080468
          30 valid t2_p50_h30   gru       30          balanced           0.406567  0.394225           3         1.082254

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:02:05,487 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:02:10,289 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:02:10,376 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:02:10,377 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:02:10,395 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:02:10,395 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:02:10,412 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:02:10,413 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:02:10,416 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:02:10,416 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:02:10,483 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:02:10,484 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=622 | prob=4280604

----------------------------------------------------------------------------------------------------
[8/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:02:10,501 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:02:10,501 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:02:10,519 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:02:10,519 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:02:10,522 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:02:10,522 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.408323  0.382491           3         1.080468
          30 valid t2_p50_h30   gru       30          balanced           0.406567  0.394225           3         1.082254

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:02:24,245 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:02:29,092 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:02:29,183 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:02:29,183 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:02:29,202 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:02:29,202 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:02:29,219 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:02:29,220 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:02:29,222 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:02:29,223 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=624 | prob=4294368

----------------------------------------------------------------------------------------------------
[9/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:02:29,297 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:02:29,297 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:02:29,315 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:02:29,315 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:02:29,332 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:02:29,333 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:02:29,336 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:02:29,336 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.408323  0.382491           3         1.080468
          30 valid t2_p50_h30   gru       30          balanced           0.406567  0.394225           3         1.082254

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:02:42,997 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:02:47,872 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:02:47,962 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:02:47,963 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:02:47,980 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:02:47,981 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:02:47,998 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:02:47,998 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:02:48,001 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:02:48,002 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:02:48,070 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:02:48,071 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=626 | prob=4308132

----------------------------------------------------------------------------------------------------
[10/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:02:48,088 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:02:48,089 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:02:48,105 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:02:48,106 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:02:48,109 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:02:48,109 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.408323  0.382491           3         1.080468
          30 valid t2_p50_h30   gru       30          balanced           0.406567  0.394225           3         1.082254

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:03:01,976 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:03:06,878 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:03:06,968 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:03:06,969 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:03:06,986 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:03:06,987 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:03:07,004 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:03:07,005 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:03:07,008 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:03:07,009 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:03:07,083 | INFO | Loaded: windows_t2_p50_h30_train.npz

💾 Guardado OK | metrics=628 | prob=4321896

----------------------------------------------------------------------------------------------------
[11/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:03:07,084 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:03:07,101 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:03:07,101 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:03:07,118 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:03:07,119 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:03:07,122 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:03:07,123 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.408323  0.382491           3         1.080468
          30 valid t2_p50_h30   gru       30          balanced           0.406567  0.394225           3         1.082254

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:03:20,849 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:03:25,814 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:03:25,909 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:03:25,910 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:03:25,928 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:03:25,929 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:03:25,948 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:03:25,949 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:03:25,952 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:03:25,952 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=630 | prob=4335660

----------------------------------------------------------------------------------------------------
[12/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:03:26,020 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:03:26,021 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:03:26,039 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:03:26,040 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:03:26,058 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:03:26,059 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:03:26,062 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:03:26,062 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.408323  0.382491           3         1.080468
          30 valid t2_p50_h30   gru       30          balanced           0.406567  0.394225           3         1.082254

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:03:39,921 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:03:44,898 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:03:44,987 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:03:44,988 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:03:45,008 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:03:45,008 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:03:45,025 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:03:45,026 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:03:45,029 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:03:45,030 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:03:45,095 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:03:45,096 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=632 | prob=4349424

----------------------------------------------------------------------------------------------------
[13/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:03:45,114 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:03:45,114 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:03:45,131 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:03:45,131 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:03:45,134 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:03:45,134 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414087  0.358966           1         1.083643
          30 valid t2_p50_h30   gru       30          balanced           0.415827  0.388544           1         1.083447

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:03:57,625 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:04:02,568 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:04:02,659 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:04:02,660 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:04:02,679 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:04:02,679 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:04:02,697 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:04:02,698 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:04:02,701 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:04:02,701 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:04:02,768 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:04:02,769 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=634 | prob=4363188

----------------------------------------------------------------------------------------------------
[14/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:04:02,786 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:04:02,787 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:04:02,804 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:04:02,805 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:04:02,944 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:04:02,945 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414087  0.358966           1         1.083643
          30 valid t2_p50_h30   gru       30          balanced           0.415827  0.388544           1         1.083447

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:04:15,442 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:04:20,342 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:04:20,430 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:04:20,430 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:04:20,451 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:04:20,451 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:04:20,469 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:04:20,469 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:04:20,472 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:04:20,473 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:04:20,539 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:04:20,540 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=636 | prob=4376952

----------------------------------------------------------------------------------------------------
[15/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:04:20,557 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:04:20,558 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:04:20,575 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:04:20,576 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:04:20,579 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:04:20,579 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414087  0.358966           1         1.083643
          30 valid t2_p50_h30   gru       30          balanced           0.415827  0.388544           1         1.083447

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:04:33,077 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:04:38,040 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:04:38,131 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:04:38,132 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:04:38,149 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:04:38,149 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:04:38,166 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:04:38,167 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:04:38,169 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:04:38,170 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:04:38,236 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:04:38,237 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=638 | prob=4390716

----------------------------------------------------------------------------------------------------
[16/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:04:38,254 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:04:38,255 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:04:38,272 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:04:38,273 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:04:38,275 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:04:38,276 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414087  0.358966           1         1.083643
          30 valid t2_p50_h30   gru       30          balanced           0.415827  0.388544           1         1.083447

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:04:50,762 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:04:55,728 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:04:55,819 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:04:55,820 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:04:55,837 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:04:55,838 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:04:55,855 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:04:55,855 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:04:55,858 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:04:55,859 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:04:55,924 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:04:55,925 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=640 | prob=4404480

----------------------------------------------------------------------------------------------------
[17/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4
✔ Ya existe -> skip

----------------------------------------------------------------------------------------------------
[18/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:04:55,942 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:04:55,943 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:04:55,960 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:04:55,961 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:04:55,964 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:04:55,964 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414087  0.358966           1         1.083643
          30 valid t2_p50_h30   gru       30          balanced           0.415827  0.388544           1         1.083447

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:05:08,501 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:05:13,483 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:05:13,572 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:05:13,573 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:05:13,591 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:05:13,592 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:05:13,612 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:05:13,613 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:05:13,616 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:05:13,616 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=642 | prob=4418244

----------------------------------------------------------------------------------------------------
[19/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:05:13,688 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:05:13,689 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:05:13,706 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:05:13,707 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:05:13,724 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:05:13,725 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:05:13,727 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:05:13,727 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414087  0.358966           1         1.083643
          30 valid t2_p50_h30   gru       30          balanced           0.415827  0.388544           1         1.083447

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:05:26,280 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:05:31,269 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:05:31,358 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:05:31,359 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:05:31,376 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:05:31,377 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:05:31,394 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:05:31,394 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:05:31,397 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:05:31,397 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:05:31,462 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:05:31,463 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=644 | prob=4432008

----------------------------------------------------------------------------------------------------
[20/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:05:31,480 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:05:31,481 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:05:31,498 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:05:31,498 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:05:31,501 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:05:31,501 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414087  0.358966           1         1.083643
          30 valid t2_p50_h30   gru       30          balanced           0.415827  0.388544           1         1.083447

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:05:44,038 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:05:49,056 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:05:49,149 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:05:49,150 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:05:49,170 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:05:49,171 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:05:49,191 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:05:49,192 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:05:49,195 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:05:49,196 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=646 | prob=4445772

----------------------------------------------------------------------------------------------------
[21/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:05:49,262 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:05:49,262 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:05:49,280 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:05:49,281 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:05:49,299 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:05:49,299 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:05:49,302 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:05:49,303 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414087  0.358966           1         1.083643
          30 valid t2_p50_h30   gru       30          balanced           0.415827  0.388544           1         1.083447

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:06:01,901 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:06:06,919 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:06:07,013 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:06:07,013 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:06:07,031 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:06:07,032 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:06:07,049 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:06:07,049 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:06:07,053 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:06:07,053 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:06:07,118 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:06:07,119 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=648 | prob=4459536

----------------------------------------------------------------------------------------------------
[22/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:06:07,137 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:06:07,137 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:06:07,155 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:06:07,155 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:06:07,158 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:06:07,158 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414087  0.358966           1         1.083643
          30 valid t2_p50_h30   gru       30          balanced           0.415827  0.388544           1         1.083447

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:06:19,811 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:06:24,765 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:06:24,839 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:06:24,839 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:06:24,857 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:06:24,858 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:06:24,875 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:06:24,876 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:06:24,879 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:06:24,879 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:06:24,947 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:06:24,947 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:06:24,964 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:06:24,965 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=650 | prob=4473300

----------------------------------------------------------------------------------------------------
[23/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:06:24,982 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:06:24,983 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:06:24,986 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:06:24,986 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414087  0.358966           1         1.083643
          30 valid t2_p50_h30   gru       30          balanced           0.415827  0.388544           1         1.083447

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:06:37,557 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:06:42,602 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:06:42,690 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:06:42,691 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:06:42,708 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:06:42,709 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:06:42,726 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:06:42,727 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:06:42,729 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:06:42,729 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:06:42,797 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:06:42,797 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=652 | prob=4487064

----------------------------------------------------------------------------------------------------
[24/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:06:42,815 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:06:42,816 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:06:42,832 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:06:42,833 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:06:42,835 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:06:42,836 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.414087  0.358966           1         1.083643
          30 valid t2_p50_h30   gru       30          balanced           0.415827  0.388544           1         1.083447

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:06:55,425 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:07:00,470 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:07:00,557 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:07:00,557 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:07:00,577 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:07:00,577 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:07:00,597 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:07:00,598 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:07:00,600 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:07:00,601 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:07:00,668 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:07:00,668 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=654 | prob=4500828

----------------------------------------------------------------------------------------------------
[25/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:07:00,685 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:07:00,686 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:07:00,703 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:07:00,704 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:07:00,706 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:07:00,707 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412624  0.353805           2         1.084446
          30 valid t2_p50_h30   gru       30          balanced           0.410555  0.374276           2         1.084742

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:07:14,865 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:07:19,972 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:07:20,062 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:07:20,063 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:07:20,080 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:07:20,081 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:07:20,099 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:07:20,100 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:07:20,103 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:07:20,103 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:07:20,171 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:07:20,172 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=656 | prob=4514592

----------------------------------------------------------------------------------------------------
[26/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:07:20,189 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:07:20,190 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:07:20,207 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:07:20,208 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:07:20,211 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:07:20,211 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412624  0.353805           2         1.084446
          30 valid t2_p50_h30   gru       30          balanced           0.410555  0.374276           2         1.084742

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:07:34,393 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:07:39,488 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:07:39,578 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:07:39,579 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:07:39,597 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:07:39,598 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:07:39,615 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:07:39,616 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:07:39,619 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:07:39,619 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:07:39,691 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:07:39,692 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=658 | prob=4528356

----------------------------------------------------------------------------------------------------
[27/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:07:39,709 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:07:39,710 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:07:39,727 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:07:39,728 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:07:39,730 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:07:39,731 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412624  0.353805           2         1.084446
          30 valid t2_p50_h30   gru       30          balanced           0.410555  0.374276           2         1.084742

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:07:53,919 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:07:59,050 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:07:59,140 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:07:59,141 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:07:59,158 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:07:59,159 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:07:59,179 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:07:59,180 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:07:59,183 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:07:59,183 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:07:59,249 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:07:59,250 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=660 | prob=4542120

----------------------------------------------------------------------------------------------------
[28/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:07:59,267 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:07:59,267 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:07:59,284 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:07:59,284 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:07:59,287 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:07:59,287 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412624  0.353805           2         1.084446
          30 valid t2_p50_h30   gru       30          balanced           0.410555  0.374276           2         1.084742

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:08:13,432 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:08:18,545 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:08:18,638 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:08:18,639 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:08:18,656 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:08:18,657 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:08:18,675 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:08:18,676 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:08:18,678 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:08:18,679 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:08:18,746 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:08:18,747 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=662 | prob=4555884

----------------------------------------------------------------------------------------------------
[29/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:08:18,767 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:08:18,768 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:08:18,788 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:08:18,788 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:08:18,791 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:08:18,792 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412624  0.353805           2         1.084446
          30 valid t2_p50_h30   gru       30          balanced           0.410555  0.374276           2         1.084742

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:08:33,185 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:08:38,347 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:08:38,440 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:08:38,441 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:08:38,458 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:08:38,459 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:08:38,476 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:08:38,477 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:08:38,479 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:08:38,480 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:08:38,547 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:08:38,547 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=664 | prob=4569648

----------------------------------------------------------------------------------------------------
[30/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:08:38,565 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:08:38,566 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:08:38,583 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:08:38,584 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:08:38,587 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:08:38,588 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412624  0.353805           2         1.084446
          30 valid t2_p50_h30   gru       30          balanced           0.410555  0.374276           2         1.084742

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:08:52,959 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:08:58,145 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:08:58,238 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:08:58,238 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:08:58,259 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:08:58,260 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:08:58,280 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:08:58,281 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:08:58,283 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:08:58,284 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=666 | prob=4583412

----------------------------------------------------------------------------------------------------
[31/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:08:58,351 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:08:58,351 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:08:58,368 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:08:58,369 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:08:58,386 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:08:58,387 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:08:58,390 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:08:58,390 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412624  0.353805           2         1.084446
          30 valid t2_p50_h30   gru       30          balanced           0.410555  0.374276           2         1.084742

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:09:12,727 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:09:17,920 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:09:18,009 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:09:18,009 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:09:18,027 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:09:18,028 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:09:18,045 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:09:18,046 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:09:18,049 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:09:18,049 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:09:18,116 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:09:18,116 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=668 | prob=4597176

----------------------------------------------------------------------------------------------------
[32/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:09:18,134 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:09:18,134 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:09:18,151 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:09:18,151 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:09:18,154 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:09:18,154 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412624  0.353805           2         1.084446
          30 valid t2_p50_h30   gru       30          balanced           0.410555  0.374276           2         1.084742

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:09:32,561 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:09:37,748 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:09:37,836 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:09:37,837 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:09:37,856 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:09:37,857 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:09:37,874 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:09:37,874 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:09:37,877 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:09:37,878 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:09:37,945 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:09:37,946 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=670 | prob=4610940

----------------------------------------------------------------------------------------------------
[33/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:09:37,963 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:09:37,964 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:09:37,981 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:09:37,982 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:09:37,984 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:09:37,985 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412624  0.353805           2         1.084446
          30 valid t2_p50_h30   gru       30          balanced           0.410555  0.374276           2         1.084742

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:09:52,398 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:09:57,603 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:09:57,691 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:09:57,692 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:09:57,710 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:09:57,710 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:09:57,728 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:09:57,728 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:09:57,731 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:09:57,731 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:09:57,797 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:09:57,798 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=672 | prob=4624704

----------------------------------------------------------------------------------------------------
[34/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:09:57,815 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:09:57,816 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:09:57,833 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:09:57,834 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:09:57,836 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:09:57,837 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412624  0.353805           2         1.084446
          30 valid t2_p50_h30   gru       30          balanced           0.410555  0.374276           2         1.084742

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:10:12,323 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:10:17,592 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:10:17,688 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:10:17,689 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:10:17,707 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:10:17,708 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:10:17,725 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:10:17,726 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:10:17,728 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:10:17,729 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:10:17,795 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:10:17,796 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=674 | prob=4638468

----------------------------------------------------------------------------------------------------
[35/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:10:17,817 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:10:17,817 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:10:17,835 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:10:17,836 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:10:17,839 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:10:17,839 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412624  0.353805           2         1.084446
          30 valid t2_p50_h30   gru       30          balanced           0.410555  0.374276           2         1.084742

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:10:32,287 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:10:37,514 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:10:37,611 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:10:37,612 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:10:37,629 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:10:37,630 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:10:37,647 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:10:37,648 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:10:37,651 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:10:37,652 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=676 | prob=4652232

----------------------------------------------------------------------------------------------------
[36/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.0 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.0
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:10:37,724 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:10:37,725 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:10:37,744 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:10:37,744 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:10:37,762 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:10:37,763 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:10:37,766 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:10:37,767 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412624  0.353805           2         1.084446
          30 valid t2_p50_h30   gru       30          balanced           0.410555  0.374276           2         1.084742

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:10:52,152 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:10:57,373 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:10:57,465 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:10:57,465 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:10:57,482 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:10:57,483 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:10:57,499 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:10:57,500 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:10:57,503 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:10:57,504 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:10:57,569 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:10:57,570 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=678 | prob=4665996

----------------------------------------------------------------------------------------------------
[37/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:10:57,587 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:10:57,588 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:10:57,605 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:10:57,606 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:10:57,608 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:10:57,609 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410301  0.384693           3         1.080654
          30 valid t2_p50_h30   gru       30          balanced           0.404815  0.392213           3         1.082237

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:11:11,835 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:11:17,127 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:11:17,226 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:11:17,226 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:11:17,247 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:11:17,248 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:11:17,265 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:11:17,265 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:11:17,268 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:11:17,269 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=680 | prob=4679760

----------------------------------------------------------------------------------------------------
[38/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:11:17,336 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:11:17,337 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:11:17,354 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:11:17,355 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:11:17,371 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:11:17,372 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:11:17,375 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:11:17,375 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410301  0.384693           3         1.080654
          30 valid t2_p50_h30   gru       30          balanced           0.404815  0.392213           3         1.082237

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:11:31,479 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:11:36,762 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:11:36,853 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:11:36,853 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:11:36,871 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:11:36,871 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:11:36,888 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:11:36,889 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:11:36,891 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:11:36,892 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:11:36,957 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:11:36,958 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=682 | prob=4693524

----------------------------------------------------------------------------------------------------
[39/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:11:36,975 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:11:36,976 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:11:36,993 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:11:36,993 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:11:36,996 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:11:36,996 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410301  0.384693           3         1.080654
          30 valid t2_p50_h30   gru       30          balanced           0.404815  0.392213           3         1.082237

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:11:51,279 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:11:56,539 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:11:56,630 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:11:56,631 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:11:56,651 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:11:56,652 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:11:56,670 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:11:56,670 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:11:56,673 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:11:56,674 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:11:56,740 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:11:56,741 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=684 | prob=4707288

----------------------------------------------------------------------------------------------------
[40/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:11:56,759 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:11:56,759 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:11:56,776 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:11:56,777 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:11:56,780 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:11:56,781 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410301  0.384693           3         1.080654
          30 valid t2_p50_h30   gru       30          balanced           0.404815  0.392213           3         1.082237

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:12:10,982 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:12:16,227 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:12:16,322 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:12:16,322 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:12:16,340 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:12:16,340 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:12:16,358 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:12:16,359 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:12:16,362 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:12:16,362 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:12:16,429 | INFO | Loaded: windows_t2_p50_h30_train.npz

💾 Guardado OK | metrics=686 | prob=4721052

----------------------------------------------------------------------------------------------------
[41/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:12:16,430 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:12:16,447 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:12:16,448 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:12:16,465 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:12:16,465 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:12:16,468 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:12:16,469 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410301  0.384693           3         1.080654
          30 valid t2_p50_h30   gru       30          balanced           0.404815  0.392213           3         1.082237

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:12:30,734 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:12:35,999 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:12:36,087 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:12:36,088 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:12:36,105 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:12:36,106 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:12:36,123 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:12:36,123 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:12:36,126 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:12:36,126 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:12:36,192 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:12:36,192 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=688 | prob=4734816

----------------------------------------------------------------------------------------------------
[42/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:12:36,210 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:12:36,210 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:12:36,228 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:12:36,228 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:12:36,231 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:12:36,232 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410301  0.384693           3         1.080654
          30 valid t2_p50_h30   gru       30          balanced           0.404815  0.392213           3         1.082237

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:12:50,518 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:12:55,797 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet

💾 Guardado OK | metrics=690 | prob=4748580

----------------------------------------------------------------------------------------------------
[43/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:12:56,036 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:12:56,037 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:12:56,054 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:12:56,055 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:12:56,073 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:12:56,074 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:12:56,077 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:12:56,078 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:12:56,146 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:12:56,146 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:12:56,164 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:12:56,165 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:12:56,183 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:12:56,183 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:12:56,187 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:12:56,187 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410301  0.384693           3         1.080654
          30 valid t2_p50_h30   gru       30          balanced           0.404815  0.392213           3         1.082237

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:13:10,363 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:13:15,656 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:13:15,727 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:13:15,728 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:13:15,747 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:13:15,747 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:13:15,765 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:13:15,766 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:13:15,768 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:13:15,769 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:13:15,840 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:13:15,841 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:13:15,858 | INFO | Loaded: windows_t2_p50_h30_valid.npz

💾 Guardado OK | metrics=692 | prob=4762344

----------------------------------------------------------------------------------------------------
[44/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:13:15,859 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:13:15,876 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:13:15,877 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:13:15,880 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:13:15,880 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410301  0.384693           3         1.080654
          30 valid t2_p50_h30   gru       30          balanced           0.404815  0.392213           3         1.082237

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:13:30,250 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:13:35,605 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:13:35,693 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:13:35,693 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:13:35,711 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:13:35,711 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:13:35,729 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:13:35,730 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:13:35,733 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:13:35,733 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:13:35,800 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:13:35,801 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=694 | prob=4776108

----------------------------------------------------------------------------------------------------
[45/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:13:35,818 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:13:35,819 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:13:35,836 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:13:35,836 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:13:35,839 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:13:35,839 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410301  0.384693           3         1.080654
          30 valid t2_p50_h30   gru       30          balanced           0.404815  0.392213           3         1.082237

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:13:50,100 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:13:55,431 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:13:55,522 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:13:55,523 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:13:55,540 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:13:55,541 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)

💾 Guardado OK | metrics=696 | prob=4789872

----------------------------------------------------------------------------------------------------
[46/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:13:55,707 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:13:55,707 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:13:55,711 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:13:55,711 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:13:55,780 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:13:55,780 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:13:55,798 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:13:55,798 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:13:55,815 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:13:55,816 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:13:55,819 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:13:55,820 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410301  0.384693           3         1.080654
          30 valid t2_p50_h30   gru       30          balanced           0.404815  0.392213           3         1.082237

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:14:10,138 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:14:15,563 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:14:15,651 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:14:15,651 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:14:15,668 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:14:15,669 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:14:15,685 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:14:15,686 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:14:15,689 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:14:15,689 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:14:15,755 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:14:15,756 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=698 | prob=4803636

----------------------------------------------------------------------------------------------------
[47/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:14:15,774 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:14:15,774 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:14:15,791 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:14:15,792 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:14:15,794 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:14:15,795 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410301  0.384693           3         1.080654
          30 valid t2_p50_h30   gru       30          balanced           0.404815  0.392213           3         1.082237

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:14:30,183 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:14:35,533 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:14:35,620 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:14:35,621 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:14:35,639 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:14:35,640 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:14:35,658 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:14:35,659 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:14:35,662 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:14:35,663 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:14:35,731 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:14:35,732 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=700 | prob=4817400

----------------------------------------------------------------------------------------------------
[48/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=1024 | eval_batch_size=1024 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 1024
eval_batch_size  = 1024
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:14:35,749 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:14:35,750 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:14:35,767 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:14:35,768 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:14:35,771 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:14:35,771 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.410301  0.384693           3         1.080654
          30 valid t2_p50_h30   gru       30          balanced           0.404815  0.392213           3         1.082237

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:14:50,143 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:14:55,500 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:14:55,585 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:14:55,586 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:14:55,603 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:14:55,603 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:14:55,620 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:14:55,621 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:14:55,624 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:14:55,624 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=702 | prob=4831164

----------------------------------------------------------------------------------------------------
[49/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:14:55,841 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:14:55,841 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:14:55,859 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:14:55,859 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:14:55,876 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:14:55,877 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:14:55,880 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:14:55,881 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416342  0.362536           1         1.083396
          30 valid t2_p50_h30   gru       30          balanced           0.414766  0.387990           1         1.083231

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:15:08,829 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:15:14,260 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:15:14,355 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:15:14,355 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:15:14,373 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:15:14,374 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:15:14,392 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:15:14,392 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:15:14,395 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:15:14,396 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:15:14,463 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:15:14,464 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=704 | prob=4844928

----------------------------------------------------------------------------------------------------
[50/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:15:14,481 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:15:14,482 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:15:14,499 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:15:14,500 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:15:14,503 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:15:14,503 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416342  0.362536           1         1.083396
          30 valid t2_p50_h30   gru       30          balanced           0.414766  0.387990           1         1.083231

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:15:27,805 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:15:33,224 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:15:33,313 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:15:33,314 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:15:33,331 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:15:33,332 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:15:33,349 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:15:33,350 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:15:33,352 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:15:33,353 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:15:33,423 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:15:33,424 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=706 | prob=4858692

----------------------------------------------------------------------------------------------------
[51/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:15:33,442 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:15:33,442 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:15:33,459 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:15:33,459 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:15:33,462 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:15:33,463 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416342  0.362536           1         1.083396
          30 valid t2_p50_h30   gru       30          balanced           0.414766  0.387990           1         1.083231

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:15:46,671 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:15:52,094 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:15:52,186 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:15:52,186 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:15:52,204 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:15:52,205 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:15:52,221 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:15:52,222 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:15:52,225 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:15:52,225 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:15:52,292 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:15:52,292 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=708 | prob=4872456

----------------------------------------------------------------------------------------------------
[52/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=0.5 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:15:52,310 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:15:52,311 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:15:52,485 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:15:52,486 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:15:52,489 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:15:52,490 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416342  0.362536           1         1.083396
          30 valid t2_p50_h30   gru       30          balanced           0.414766  0.387990           1         1.083231

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:16:05,515 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:16:11,023 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:16:11,111 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:16:11,111 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:16:11,129 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:16:11,129 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:16:11,146 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:16:11,147 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:16:11,149 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:16:11,150 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:16:11,216 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:16:11,217 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=710 | prob=4886220

----------------------------------------------------------------------------------------------------
[53/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:16:11,238 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:16:11,239 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:16:11,257 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:16:11,257 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:16:11,261 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:16:11,261 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416342  0.362536           1         1.083396
          30 valid t2_p50_h30   gru       30          balanced           0.414766  0.387990           1         1.083231

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:16:24,497 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:16:30,000 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:16:30,089 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:16:30,090 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:16:30,107 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:16:30,108 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:16:30,125 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:16:30,125 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:16:30,128 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:16:30,129 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:16:30,195 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:16:30,195 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=712 | prob=4899984

----------------------------------------------------------------------------------------------------
[54/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:16:30,213 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:16:30,213 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:16:30,230 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:16:30,230 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:16:30,233 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:16:30,234 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416342  0.362536           1         1.083396
          30 valid t2_p50_h30   gru       30          balanced           0.414766  0.387990           1         1.083231

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:16:43,407 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:16:48,871 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:16:48,958 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:16:48,959 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:16:48,977 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:16:48,977 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:16:48,994 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:16:48,995 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:16:48,997 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:16:48,998 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:16:49,064 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:16:49,065 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=714 | prob=4913748

----------------------------------------------------------------------------------------------------
[55/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:16:49,082 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:16:49,083 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:16:49,100 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:16:49,100 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:16:49,103 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:16:49,103 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416342  0.362536           1         1.083396
          30 valid t2_p50_h30   gru       30          balanced           0.414766  0.387990           1         1.083231

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:17:02,401 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:17:07,918 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:17:08,008 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:17:08,009 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:17:08,026 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:17:08,026 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:17:08,043 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:17:08,044 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:17:08,047 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:17:08,047 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:17:08,114 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:17:08,114 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=716 | prob=4927512

----------------------------------------------------------------------------------------------------
[56/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=1.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 1.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:17:08,132 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:17:08,132 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:17:08,149 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:17:08,150 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:17:08,153 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:17:08,154 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416342  0.362536           1         1.083396
          30 valid t2_p50_h30   gru       30          balanced           0.414766  0.387990           1         1.083231

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:17:21,332 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:17:26,856 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:17:26,944 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:17:26,945 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:17:26,962 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:17:26,963 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:17:26,981 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:17:26,981 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:17:26,985 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:17:26,985 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:17:27,051 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:17:27,052 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=718 | prob=4941276

----------------------------------------------------------------------------------------------------
[57/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:17:27,070 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:17:27,070 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:17:27,087 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:17:27,088 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:17:27,090 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:17:27,090 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416342  0.362536           1         1.083396
          30 valid t2_p50_h30   gru       30          balanced           0.414766  0.387990           1         1.083231

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:17:40,415 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:17:45,942 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:17:46,033 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:17:46,033 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:17:46,051 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:17:46,051 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:17:46,068 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:17:46,069 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:17:46,071 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:17:46,072 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:17:46,137 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:17:46,138 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=720 | prob=4955040

----------------------------------------------------------------------------------------------------
[58/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.4 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.4
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:17:46,156 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:17:46,157 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:17:46,174 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:17:46,174 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:17:46,177 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:17:46,178 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416342  0.362536           1         1.083396
          30 valid t2_p50_h30   gru       30          balanced           0.414766  0.387990           1         1.083231

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4             0.45
          30 valid t2_p50_h30   gru       30          balanced             0.4             0.45

2026-04-23 18:17:59,464 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:18:04,955 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:18:05,042 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:18:05,043 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:18:05,060 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:18:05,060 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:18:05,077 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:18:05,078 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:18:05,080 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:18:05,081 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:18:05,146 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:18:05,147 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=722 | prob=4968804

----------------------------------------------------------------------------------------------------
[59/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:18:05,165 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:18:05,166 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:18:05,183 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:18:05,184 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:18:05,186 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:18:05,187 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416342  0.362536           1         1.083396
          30 valid t2_p50_h30   gru       30          balanced           0.414766  0.387990           1         1.083231

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45              0.4
          30 valid t2_p50_h30   gru       30          balanced            0.45              0.4

2026-04-23 18:18:18,482 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:18:24,068 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:18:24,155 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:18:24,155 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:18:24,172 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:18:24,173 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:18:24,189 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:18:24,190 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:18:24,193 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:18:24,193 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)
2026-04-23 18:18:24,259 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:18:24,260 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)

💾 Guardado OK | metrics=724 | prob=4982568

----------------------------------------------------------------------------------------------------
[60/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=2048 | eval_batch_size=2048 | grad_clip_norm=2.0 | thr_long=0.45 | thr_short=0.45

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 2048
eval_batch_size  = 2048
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 2.0
device           = None
thr_long         = 0.45
thr_short        = 0.45

[BUILD] L30 | n_targets=2

2026-04-23 18:18:24,277 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:18:24,278 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:18:24,295 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:18:24,296 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:18:24,298 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:18:24,299 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.416342  0.362536           1         1.083396
          30 valid t2_p50_h30   gru       30          balanced           0.414766  0.387990           1         1.083231

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced            0.45             0.45
          30 valid t2_p50_h30   gru       30          balanced            0.45             0.45

2026-04-23 18:18:37,672 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet
2026-04-23 18:18:43,206 | INFO | Probabilidades guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_probabilities/classification_probabilities_gru_valid.parquet
2026-04-23 18:18:43,302 | INFO | Loaded: windows_t2_p40_h30_train.npz
2026-04-23 18:18:43,303 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:18:43,321 | INFO | Loaded: windows_t2_p40_h30_valid.npz
2026-04-23 18:18:43,321 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:18:43,338 | INFO | Loaded: windows_t2_p40_h30_test.npz
2026-04-23 18:18:43,339 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:18:43,342 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:18:43,342 | INFO | Bundle cargado | target=t2_p40_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

💾 Guardado OK | metrics=726 | prob=4996332

----------------------------------------------------------------------------------------------------
[61/144] hidden_size=128 | num_layers=1 | learning_rate=0.0005 | dropout=0.1 | batch_size=4096 | eval_batch_size=4096 | grad_clip_norm=0.5 | thr_long=0.4 | thr_short=0.4

================================================================================
GRU | T2 SEQ2ONE | WINDOW_SIZE=L30
================================================================================
targets          = ['t2_p40_h30', 't2_p50_h30']
class_weight     = balanced
hidden_size      = 128
num_layers       = 1
dropout          = 0.1
learning_rate    = 0.0005
weight_decay     = 0.0
batch_size       = 4096
eval_batch_size  = 4096
epochs           = 20
patience         = 5
optimizer_name   = adam
grad_clip_norm   = 0.5
device           = None
thr_long         = 0.4
thr_short        = 0.4

[BUILD] L30 | n_targets=2

2026-04-23 18:18:43,409 | INFO | Loaded: windows_t2_p50_h30_train.npz
2026-04-23 18:18:43,409 | INFO | X shape: (32147, 30, 7) | y shape: (32147,)
2026-04-23 18:18:43,426 | INFO | Loaded: windows_t2_p50_h30_valid.npz
2026-04-23 18:18:43,426 | INFO | X shape: (6882, 30, 7) | y shape: (6882,)
2026-04-23 18:18:43,444 | INFO | Loaded: windows_t2_p50_h30_test.npz
2026-04-23 18:18:43,444 | INFO | X shape: (6913, 30, 7) | y shape: (6913,)
2026-04-23 18:18:43,447 | INFO | Scaler cargado: scaler_mnq_t2.pkl
2026-04-23 18:18:43,447 | INFO | Bundle cargado | target=t2_p50_h30 | window_size=30 | train=(32147, 30, 7) | valid=(6882, 30, 7) | test=(6913, 30, 7)

======================================================================
WINDOW_SIZE: 30
======================================================================

TARGET: t2_p40_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

TARGET: t2_p50_h30
Train : (32147, 30, 7) (32147,)
Valid : (6882, 30, 7) (6882,)
Test  : (6913, 30, 7) (6913,)
Scaler: StandardScaler

[EVAL] L30 | split=valid | model=gru | class_weight=balanced
  -> L30 | target=t2_p40_h30 | model=gru | class_weight=balanced
  -> L30 | target=t2_p50_h30 | model=gru | class_weight=balanced

[DONE] L30 | metrics_rows=2 | probabilities_rows=13764

[METRICS]
 window_size split     target model  horizon class_weight_mode  balanced_accuracy  f1_macro  best_epoch  best_valid_loss
          30 valid t2_p40_h30   gru       30          balanced           0.412874  0.353989           2         1.084420
          30 valid t2_p50_h30   gru       30          balanced           0.409811  0.372893           2         1.084695

[PROBABILITIES - unique rows]
 window_size split     target model  horizon class_weight_mode  threshold_long  threshold_short
          30 valid t2_p40_h30   gru       30          balanced             0.4              0.4
          30 valid t2_p50_h30   gru       30          balanced             0.4              0.4

2026-04-23 18:18:58,312 | INFO | Métricas guardadas en: /content/drive/MyDrive/neural_profit/metrics_tuning/classification_metrics/classification_metrics_gru_valid.parquet

## **12.1. Análisis de tuneo fino**

In [ ]:
import pandas as pd
import numpy as np

# =========================================================
# 1) Cargar métricas y probabilities GRU
# =========================================================
df_gru = load_classification_metrics_if_exists(
    model_name="gru",
    split="valid",
).copy()

df_gru_prob = load_classification_probabilities_if_exists(
    model_name="gru",
    split="valid",
).copy()

# =========================================================
# 2) Filtrar SOLO zona óptima (tuneo fino)
#    Se restringe a las 3 bases elegidas
# =========================================================
fine_mask_metrics = (
    (
        ((df_gru["hidden_size"] == 128) & (df_gru["num_layers"] == 2) & (df_gru["learning_rate"] == 5e-4)) |
        ((df_gru["hidden_size"] == 256) & (df_gru["num_layers"] == 1) & (df_gru["learning_rate"] == 1e-3)) |
        ((df_gru["hidden_size"] == 128) & (df_gru["num_layers"] == 1) & (df_gru["learning_rate"] == 5e-4))
    )
)

fine_mask_prob = (
    (
        ((df_gru_prob["hidden_size"] == 128) & (df_gru_prob["num_layers"] == 2) & (df_gru_prob["learning_rate"] == 5e-4)) |
        ((df_gru_prob["hidden_size"] == 256) & (df_gru_prob["num_layers"] == 1) & (df_gru_prob["learning_rate"] == 1e-3)) |
        ((df_gru_prob["hidden_size"] == 128) & (df_gru_prob["num_layers"] == 1) & (df_gru_prob["learning_rate"] == 5e-4))
    )
)

df_gru_fine = df_gru.loc[fine_mask_metrics].copy()
df_gru_prob_fine = df_gru_prob.loc[fine_mask_prob].copy()

print("Shape fine metrics      :", df_gru_fine.shape)
print("Shape fine probabilities:", df_gru_prob_fine.shape)

# =========================================================
# 3) Resumen global por configuración completa (metrics)
# =========================================================
summary_gru_fine = (
    df_gru_fine
    .groupby(
        [
            "hidden_size",
            "num_layers",
            "learning_rate",
            "dropout",
            "batch_size",
            "grad_clip_norm",
            "threshold_long",
            "threshold_short",
        ],
        as_index=False
    )
    .agg(
        n_targets=("target", "nunique"),
        balanced_accuracy_mean=("balanced_accuracy", "mean"),
        balanced_accuracy_std=("balanced_accuracy", "std"),
        f1_macro_mean=("f1_macro", "mean"),
        f1_macro_std=("f1_macro", "std"),
        accuracy_mean=("accuracy", "mean"),
    )
    .sort_values(
        ["balanced_accuracy_mean", "f1_macro_mean"],
        ascending=False
    )
    .reset_index(drop=True)
)

# =========================================================
# 4) Mejor configuración por target (metrics)
# =========================================================
best_gru_fine_by_target = (
    df_gru_fine
    .sort_values(
        ["target", "balanced_accuracy", "f1_macro"],
        ascending=[True, False, False]
    )
    .groupby("target", as_index=False)
    .first()[[
        "target",
        "hidden_size",
        "num_layers",
        "learning_rate",
        "dropout",
        "batch_size",
        "grad_clip_norm",
        "threshold_long",
        "threshold_short",
        "balanced_accuracy",
        "f1_macro",
        "accuracy",
    ]]
    .reset_index(drop=True)
)

# =========================================================
# 5) Mejor configuración global (metrics)
# =========================================================
best_gru_fine_global = summary_gru_fine.iloc[0].copy()

# =========================================================
# 6) Análisis por base del modelo
# =========================================================
summary_gru_base = (
    df_gru_fine
    .groupby(
        ["hidden_size", "num_layers", "learning_rate"],
        as_index=False
    )
    .agg(
        balanced_accuracy_mean=("balanced_accuracy", "mean"),
        balanced_accuracy_std=("balanced_accuracy", "std"),
        f1_macro_mean=("f1_macro", "mean"),
        f1_macro_std=("f1_macro", "std"),
        accuracy_mean=("accuracy", "mean"),
    )
    .sort_values(
        ["balanced_accuracy_mean", "f1_macro_mean"],
        ascending=False
    )
    .reset_index(drop=True)
)

# =========================================================
# 7) Análisis por regularización / estabilidad
# =========================================================
summary_gru_regularization = (
    df_gru_fine
    .groupby(
        ["dropout", "batch_size", "grad_clip_norm"],
        as_index=False
    )
    .agg(
        balanced_accuracy_mean=("balanced_accuracy", "mean"),
        balanced_accuracy_std=("balanced_accuracy", "std"),
        f1_macro_mean=("f1_macro", "mean"),
        f1_macro_std=("f1_macro", "std"),
        accuracy_mean=("accuracy", "mean"),
    )
    .sort_values(
        ["balanced_accuracy_mean", "f1_macro_mean"],
        ascending=False
    )
    .reset_index(drop=True)
)

# =========================================================
# 8) Análisis individual por dropout / batch / clip
# =========================================================
summary_gru_dropout = (
    df_gru_fine
    .groupby("dropout", as_index=False)
    .agg(
        balanced_accuracy_mean=("balanced_accuracy", "mean"),
        balanced_accuracy_std=("balanced_accuracy", "std"),
        f1_macro_mean=("f1_macro", "mean"),
        f1_macro_std=("f1_macro", "std"),
        accuracy_mean=("accuracy", "mean"),
    )
    .sort_values(
        ["balanced_accuracy_mean", "f1_macro_mean"],
        ascending=False
    )
    .reset_index(drop=True)
)

summary_gru_batch = (
    df_gru_fine
    .groupby("batch_size", as_index=False)
    .agg(
        balanced_accuracy_mean=("balanced_accuracy", "mean"),
        balanced_accuracy_std=("balanced_accuracy", "std"),
        f1_macro_mean=("f1_macro", "mean"),
        f1_macro_std=("f1_macro", "std"),
        accuracy_mean=("accuracy", "mean"),
    )
    .sort_values(
        ["balanced_accuracy_mean", "f1_macro_mean"],
        ascending=False
    )
    .reset_index(drop=True)
)

summary_gru_clip = (
    df_gru_fine
    .groupby("grad_clip_norm", as_index=False)
    .agg(
        balanced_accuracy_mean=("balanced_accuracy", "mean"),
        balanced_accuracy_std=("balanced_accuracy", "std"),
        f1_macro_mean=("f1_macro", "mean"),
        f1_macro_std=("f1_macro", "std"),
        accuracy_mean=("accuracy", "mean"),
    )
    .sort_values(
        ["balanced_accuracy_mean", "f1_macro_mean"],
        ascending=False
    )
    .reset_index(drop=True)
)

# =========================================================
# 9) Análisis por thresholds (metrics)
# =========================================================
summary_gru_thresholds_metrics = (
    df_gru_fine
    .groupby(
        ["threshold_long", "threshold_short"],
        as_index=False
    )
    .agg(
        balanced_accuracy_mean=("balanced_accuracy", "mean"),
        balanced_accuracy_std=("balanced_accuracy", "std"),
        f1_macro_mean=("f1_macro", "mean"),
        f1_macro_std=("f1_macro", "std"),
        accuracy_mean=("accuracy", "mean"),
    )
    .sort_values(
        ["balanced_accuracy_mean", "f1_macro_mean"],
        ascending=False
    )
    .reset_index(drop=True)
)

# =========================================================
# 10) Construcción de variables operativas (probabilities)
# =========================================================
df_oper = df_gru_prob_fine.copy()

df_oper["decision"] = 0
df_oper.loc[df_oper["proba_1"] >= df_oper["threshold_long"], "decision"] = 1
df_oper.loc[df_oper["proba_-1"] >= df_oper["threshold_short"], "decision"] = -1

df_oper["is_trade"] = df_oper["decision"] != 0
df_oper["is_useful"] = df_oper["is_trade"] & (df_oper["decision"] == df_oper["y_true"])

# =========================================================
# 11) Resumen operativo completo
# =========================================================
summary_gru_prob_oper = (
    df_oper
    .groupby(
        [
            "hidden_size",
            "num_layers",
            "learning_rate",
            "dropout",
            "batch_size",
            "grad_clip_norm",
            "threshold_long",
            "threshold_short",
            "target",
        ],
        as_index=False
    )
    .agg(
        n_total=("y_true", "size"),
        n_trades=("is_trade", "sum"),
        n_useful=("is_useful", "sum"),
    )
)

summary_gru_prob_oper["trade_rate"] = (
    summary_gru_prob_oper["n_trades"] / summary_gru_prob_oper["n_total"]
)

summary_gru_prob_oper["useful_rate_total"] = (
    summary_gru_prob_oper["n_useful"] / summary_gru_prob_oper["n_total"]
)

summary_gru_prob_oper["precision_useful"] = np.where(
    summary_gru_prob_oper["n_trades"] > 0,
    summary_gru_prob_oper["n_useful"] / summary_gru_prob_oper["n_trades"],
    np.nan
)

# =========================================================
# 12) Resumen global operativo por configuración
# =========================================================
summary_gru_prob_global = (
    summary_gru_prob_oper
    .groupby(
        [
            "hidden_size",
            "num_layers",
            "learning_rate",
            "dropout",
            "batch_size",
            "grad_clip_norm",
            "threshold_long",
            "threshold_short",
        ],
        as_index=False
    )
    .agg(
        n_targets=("target", "nunique"),
        precision_useful_mean=("precision_useful", "mean"),
        precision_useful_std=("precision_useful", "std"),
        useful_rate_total_mean=("useful_rate_total", "mean"),
        useful_rate_total_std=("useful_rate_total", "std"),
        trade_rate_mean=("trade_rate", "mean"),
        trade_rate_std=("trade_rate", "std"),
    )
    .sort_values(
        ["precision_useful_mean", "useful_rate_total_mean", "trade_rate_mean"],
        ascending=False
    )
    .reset_index(drop=True)
)

# =========================================================
# 13) Mejor configuración operativa por target
# =========================================================
best_gru_prob_by_target = (
    summary_gru_prob_oper
    .sort_values(
        ["target", "precision_useful", "useful_rate_total", "trade_rate"],
        ascending=[True, False, False, False]
    )
    .groupby("target", as_index=False)
    .first()[[
        "target",
        "hidden_size",
        "num_layers",
        "learning_rate",
        "dropout",
        "batch_size",
        "grad_clip_norm",
        "threshold_long",
        "threshold_short",
        "precision_useful",
        "useful_rate_total",
        "trade_rate",
        "n_trades",
        "n_useful",
    ]]
    .reset_index(drop=True)
)

# =========================================================
# 14) Resumen operativo por thresholds
# =========================================================
summary_gru_thresholds_prob = (
    summary_gru_prob_oper
    .groupby(
        ["threshold_long", "threshold_short"],
        as_index=False
    )
    .agg(
        precision_useful_mean=("precision_useful", "mean"),
        precision_useful_std=("precision_useful", "std"),
        useful_rate_total_mean=("useful_rate_total", "mean"),
        useful_rate_total_std=("useful_rate_total", "std"),
        trade_rate_mean=("trade_rate", "mean"),
        trade_rate_std=("trade_rate", "std"),
    )
    .sort_values(
        ["precision_useful_mean", "useful_rate_total_mean", "trade_rate_mean"],
        ascending=False
    )
    .reset_index(drop=True)
)

# =========================================================
# 15) Formato para impresión
# =========================================================
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)
pd.set_option("display.max_rows", 200)

# =========================================================
# 16) Impresión ordenada
# =========================================================
print("=" * 100)
print("GRU FINE TUNING | RESUMEN GLOBAL TOP 20 (METRICS)")
print("=" * 100)
print(summary_gru_fine.head(20).to_string(index=False))

print("\n" + "=" * 100)
print("MEJOR CONFIGURACIÓN POR TARGET (METRICS)")
print("=" * 100)
print(best_gru_fine_by_target.to_string(index=False))

print("\n" + "=" * 100)
print("MEJOR CONFIGURACIÓN GLOBAL (METRICS)")
print("=" * 100)
print(best_gru_fine_global.to_string())

print("\n" + "=" * 100)
print("RESUMEN POR BASE DEL MODELO")
print("=" * 100)
print(summary_gru_base.to_string(index=False))

print("\n" + "=" * 100)
print("RESUMEN POR REGULARIZACIÓN / ESTABILIDAD")
print("=" * 100)
print(summary_gru_regularization.to_string(index=False))

print("\n" + "=" * 100)
print("RESUMEN POR DROPOUT")
print("=" * 100)
print(summary_gru_dropout.to_string(index=False))

print("\n" + "=" * 100)
print("RESUMEN POR BATCH SIZE")
print("=" * 100)
print(summary_gru_batch.to_string(index=False))

print("\n" + "=" * 100)
print("RESUMEN POR GRAD CLIP")
print("=" * 100)
print(summary_gru_clip.to_string(index=False))

print("\n" + "=" * 100)
print("RESUMEN POR THRESHOLDS (METRICS)")
print("=" * 100)
print(summary_gru_thresholds_metrics.to_string(index=False))

print("\n" + "=" * 100)
print("GRU FINE TUNING | RESUMEN GLOBAL TOP 20 (PROBABILITIES)")
print("=" * 100)
print(summary_gru_prob_global.head(20).to_string(index=False))

print("\n" + "=" * 100)
print("MEJOR CONFIGURACIÓN POR TARGET (PROBABILITIES)")
print("=" * 100)
print(best_gru_prob_by_target.to_string(index=False))

print("\n" + "=" * 100)
print("RESUMEN POR THRESHOLDS (PROBABILITIES)")
print("=" * 100)
print(summary_gru_thresholds_prob.to_string(index=False))

Lecturas clave

1. Trade-off entre calidad y actividad
   Se observa el comportamiento esperado: thresholds más altos reducen la cantidad de operaciones pero incrementan la precisión, mientras que thresholds más bajos aumentan la actividad a costa de mayor ruido. La relación es consistente y no presenta anomalías.

2. Mejor precisión
   La combinación (0.45, 0.45) presenta la mayor precision_useful, pero con un nivel de actividad bajo. Esto corresponde a un perfil conservador, donde se prioriza calidad sobre volumen de señales.

3. Zona eficiente
   Las combinaciones más relevantes en términos de balance son:

* (0.40, 0.45): alta precisión con una reducción moderada de actividad
* (0.45, 0.40): comportamiento similar, con mayor volumen de señales

Ambas superan al baseline (0.40, 0.40), logrando una mejor relación entre calidad y cantidad de operaciones.

4. Baseline
   La configuración (0.40, 0.40) presenta mayor actividad pero menor precisión. Funciona como referencia, pero no es óptima en términos de eficiencia operativa.

Conclusión operativa

Se identifican tres perfiles de comportamiento:

* Conservador: (0.45, 0.45), máxima precisión y baja frecuencia
* Balanceado: (0.40, 0.45), alto nivel de precisión con buena reducción de ruido
* Agresivo: (0.35, 0.40), mayor actividad con menor calidad de señal

Recomendación

Se selecciona la siguiente configuración:

```python
threshold_long  = 0.40
threshold_short = 0.45
```

Esta combinación mantiene una precisión cercana al máximo, mejora el baseline y reduce significativamente el ruido sin afectar excesivamente la actividad.

Observación estructural

Se observa un patrón consistente donde las mejores combinaciones presentan threshold_short mayor que threshold_long. Esto sugiere que el modelo es más confiable en señales largas que en cortas, lo cual constituye una característica estructural del modelo.

Análisis adicional recomendado

* Evaluar la distribución de señales long y short
* Analizar desempeño por régimen de mercado
* Verificar estabilidad de señales a lo largo del tiempo
* Construir curvas de precision vs trade_rate para identificar puntos óptimos

Conclusión

El modelo responde adecuadamente al proceso de tuning y el espacio de thresholds está bien definido. Se ha identificado una zona operativa estable, lo que permite avanzar hacia validación en test o implementación de backtesting.

# **13. Selección final de hiperparámetros**

A partir del proceso de tuneo grueso y fino, se determina como configuración óptima del modelo:

```python
C = 0.01
```

Este valor presenta el mejor desempeño consistente en términos de balanced_accuracy y f1_macro, indicando la necesidad de una regularización fuerte para este problema.

En cuanto a los umbrales de decisión, el análisis operativo muestra un trade-off claro entre precisión y frecuencia de señales. A partir del ranking global, se seleccionan dos configuraciones representativas:

Configuración principal (balanceada):

```python
threshold_long  = 0.40
threshold_short = 0.45
```

* precision_useful alta (~0.447)
* reducción significativa del ruido respecto al baseline
* nivel de actividad moderado
* mejor relación señal / ruido

Configuración alternativa (conservadora):

```python
threshold_long  = 0.45
threshold_short = 0.45
```

* máxima precision_useful (~0.448)
* menor frecuencia de operaciones
* adecuada para escenarios donde se prioriza calidad sobre volumen

El baseline original:

```python
threshold_long  = 0.40
threshold_short = 0.40
```

queda superado por ambas configuraciones en términos de eficiencia operativa.

Observación relevante

Se identifica un patrón consistente donde las mejores configuraciones presentan:

```python
threshold_short > threshold_long
```

Esto sugiere que el modelo muestra mayor confiabilidad en señales largas que en señales cortas, constituyendo una característica estructural del modelo.

Conclusión

El modelo Logistic Regression queda definido por:

* regularización óptima: C = 0.01
* thresholds seleccionados en zona eficiente del espacio de decisión

Con esto se completa la etapa de selección de hiperparámetros para LR, quedando listo para su comparación con otros modelos en etapas posteriores.